### ISSUE TITLE
Can't open the app on MacOS (preview7+)

### ISSUE THREAD

**Issue by Scorfox** [AvaloniaUI/Avalonia#11368] opened 2023-05-14 14:43 UTC
**Describe the bug**
When I try to launch the application with preview7/preview8 on MacOS (Big Sur 11.5.2) I get the error:

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Native.WindowImpl..ctor(IAvaloniaNativeFactory factory, AvaloniaNativePlatformOptions opts, AvaloniaNativeGlPlatformGraphics glFeature) in /_/src/Avalonia.Native/WindowImpl.cs:line 35
   at Avalonia.Native.AvaloniaNativePlatform.CreateWindow() in /_/src/Avalonia.Native/AvaloniaNativePlatform.cs:line 154
   at Avalonia.Controls.Platform.PlatformManager.CreateWindow() in /_/src/Avalonia.Controls/Platform/PlatformManager.cs:line 31
   at Avalonia.Controls.Window..ctor() in /_/src/Avalonia.Controls/Window.cs:line 214
   at Unlimotion.Views.MainWindow..ctor()
   at Unlimotion.App.OnFrameworkInitializationCompleted()
   at Avalonia.AppBuilder.Setup() in /_/src/Avalonia.Controls/AppBuilder.cs:line 302
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilder.cs:line 199
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214

**To Reproduce**

1. dotnet publish <...> -r osx-x64 -f net7.0
2. try to run the executable file on MacOS
3. get error

**Expected behavior**
The app started.

**Screenshots**
- 

**Desktop (please complete the following information):**

- OS:  Mac
- Version: Big Sur 11.5.2

**Additional context**
The app launched fine in previous versions, also the app with current version launched on Windows and Linux

**Comment by maxkatz6** [comment] 2023-05-18 02:14
Two possible problems come to mind:
1. It's a virtual machine, then see https://github.com/AvaloniaUI/Avalonia/issues/10770
2. You have mixed version dependencies or need to fully clean your solution to avoid wrong Avalonia.Native binaries used.

In general, it's not reproducible normally.

**Comment by maxkatz6** [comment] 2023-05-18 02:14
Seems to be duplicate of https://github.com/AvaloniaUI/Avalonia/issues/11259 with the same stacktrace

**Closed** 2023-05-20 22:24 UTC
Labels: bug, os-macos
