### ISSUE TITLE
MenuItem closes after click on macOS

### ISSUE THREAD

**Issue by josephmoresena** [AvaloniaUI/Avalonia#6888] opened 2021-11-09 02:14 UTC
**Describe the bug**
When clicking on any menu item, it opens but closes instantly, not allowing access to the options using the click.
However, if it is opened with the alt key, it does allow you to navigate over the open menus and select the options.

**Expected behavior**
When clicking on a menu item, it opens and stays open until you click outside of it.

**Screenshots**
https://youtu.be/gIY1uSeqxDY

**Desktop (please complete the following information):**

- OS: macOS Monterey Intel
- Version 0.10.10

**Comment by maxkatz6** [comment] 2021-11-09 06:41
https://github.com/AvaloniaUI/Avalonia/issues/6827

**Comment by grokys** [comment] 2021-11-12 11:06
Closing as duplicate of #6827.

**Closed by grokys** 2021-11-12 11:06 UTC
Labels: bug
