### ISSUE TITLE
macOS:Unable to create pixel format shim surface for conversion from Rgba8888 to Bgra8888

### ISSUE THREAD

**Issue by ghost** [AvaloniaUI/Avalonia#3808] opened 2020-04-22 11:23 UTC
Tested with Avalonia 0.9.6, 0.9.9
OS is running under VMware 15:
```
macOS Mojave 10.14.6
Darwin 18.7.0
```
Got the following error:
```
Unhandled exception. System.Exception: Unable to create pixel format shim surface for conversion from Rgba8888 to Bgra8888
   at Avalonia.Skia.FramebufferRenderTarget.PixelFormatConversionShim..ctor(SKImageInfo destinationInfo, IntPtr framebufferAddress)
   at Avalonia.Skia.FramebufferRenderTarget.CreateSurface(SKImageInfo desiredImageInfo, ILockedFramebuffer framebuffer)
   at Avalonia.Skia.FramebufferRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer)
   at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(IDrawingContextImpl& context)
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall)
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite)
   at Avalonia.Rendering.DeferredRenderer.Paint(Rect rect)
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
   at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.Paint()
   at Avalonia.Native.Interop.IAvnWindowBaseEventsShadow.IAvnWindowBaseEventsVtbl.Paint(IntPtr thisObject)
--- End of stack trace from previous location where exception was thrown ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at AvaloniaApp.Program.Main(String[] args) in /Users/osx/work/ceftest/cefnetmacos/AvaloniaApp/Program.cs:line 1
```
.
This is a test application for [CefNet](https://github.com/CefNet/CefNet). I load https://yandex.ru/ and move the mouse over the window. The application crashes within 1- 2 minutes.

**Comment by kekekeks** [comment] 2020-04-22 13:16
Have you tried running on actual Apple hardware?

**Comment by vmas** [comment] 2020-04-22 13:52
No, I have not tried.

**Comment by derekantrican** [comment] 2021-01-09 01:06
I just saw this issue on actual Mac hardware. Unfortunately, don't have a repo yet. Here are the details:

OSX 10.13.6
2012 MacBook Pro (13 inch)

I have a stack trace if you want it

**Comment by derekantrican** [comment] 2021-01-09 01:16
I seem to get it when tooltips are changing quickly. If you're interested, I could venture into creating a min repo

**Comment by derekantrican** [comment] 2021-01-23 04:14
Seems to be resolved with Avalonia 0.10.0 (at least for me)

**Comment by ltetak** [comment] 2021-11-15 12:11
This is easily reproducible on M1 macs when opening a context menu in 0.10.10.

**Comment by vmas** [comment] 2022-06-22 20:49
Still reproducible on Macbook Pro 14 M1 (2021), macOS 12.4, Avalonia 0.10.14 and
```
BuildAvaloniaApp()
.With(new AvaloniaNativePlatformOptions { UseGpu = !PlatformInfo.IsMacOS })
```

**Comment by DmitriyYukhanov** [comment] 2022-09-28 16:04
Still reproduces for me in Avalonia 0.10.18 in my Avalonia app which runs on Mac OS 12.6 VM when I try to show the context menu.

**Closed** 2023-11-18 05:40 UTC
Labels: os-macos
