### ISSUE TITLE
ListBox has extreme bugs in Avalonia preview5/6

### ISSUE THREAD

**Issue by onionware-github** [AvaloniaUI/Avalonia#10798] opened 2023-03-25 19:54 UTC
**Describe the bug**
Since I upgraded to Avalonia11-preview5 (and FluentAvalonia2-preview5), the ListBox control is heavily buggy. Items are "overlapping" information (text and images from other items), app crashes sometimes when I remove an item (ArgumentOutOfRangeException). I downgraded to preview4, where everything works fine. I don't know exactly if the bugs come from Avalonia itself, or from the FluentAvalonia library. The bugs also exist in preview6.
I recorded a video that shows these issues:
https://youtu.be/pcuidX6gVmE

**Expected behavior**
I should work like the preview4. Here is a video of OnionMedia X with (Fluent-)Avalonia-preview4 where everything works fine:
https://youtu.be/2qLzWo79cZ0

**Screenshots**
Completely wrong titles and thumbnails
![image](https://user-images.githubusercontent.com/91136545/227738570-2a7c4649-558d-43f6-805a-9489d3e1bef5.png)

**Desktop (please complete the following information):**

- OS: Bug appears on Windows and also on Linux, MacOS not tested
- Version 11.0.0-preview5/6

**Comment by robloo** [comment] 2023-03-26 14:16
Yea, I've seen some pretty strange things so far as well. Not all have been reported.

 * Container recycling doesn't seem to invalidate correctly in all cases and I see incorrect content in a row that doesn't match a view model. For example, a row may have an incorrect Bitmap Image.
 * When filtering a ListBox (bound to an ObservableCollection) I've seen the ListBox show one row at the top, a lot of empty space, and then another row at the bottom. I've never seen this happen before and it is quite strange to just have a big gap between rows.
 * I've seen the same rows overlap each other at the top (already reported in https://github.com/AvaloniaUI/Avalonia/issues/10769)
 * I've seen the selected row style applied to multiple rows (even though only one is actually selected in the model) as I scroll through -- again seems container relatated.

And these are just the ones that I can make sense of enough to make note of.

**Comment by timunie** [comment] 2023-03-27 08:43
@onionware-github can you try latest nightly? At lease one issue (#10788 inserting a new item at index 0) should be fixed there and probably your issue is also magically fixed.

**Comment by timunie** [comment] 2023-03-28 07:53
It was a huge step forward in Avalonia with all these changes done. It comes for a price of a few bugs when you do such huge changes, but going back in time is not a good solution. I think it's totally okay for previews to be not 100 % polished. Sorry for the inconvenience.

**Comment by grokys** [comment] 2023-04-04 08:07
Sorry for the problems @onionware-github but as others have said: there's a reason the release is marked "preview"!

I've been working on some more fixes over at https://github.com/AvaloniaUI/Avalonia/pull/10892 but without a repro it's hard to know what's going wrong here. If that PR doesn't fix the problems is there any chance of a simple repro?

**Comment by chenjing1294** [comment] 2023-04-08 11:21
version: preview5/6.
I also ran into some issues. ListBoxItem can't return to unselected state.
![listbox_bug](https://user-images.githubusercontent.com/21185657/230718383-a1261126-dd58-4742-a724-e5688b16e772.gif)

```xml
<ListBox>
    <ListBoxItem Height="30">a</ListBoxItem>
    <ListBoxItem Height="30">b</ListBoxItem>
    <ListBoxItem Height="30">c</ListBoxItem>
    <ListBoxItem Height="30">d</ListBoxItem>
    <ListBoxItem Height="30">e</ListBoxItem>
    <ListBoxItem Height="30">f</ListBoxItem>
    <ListBoxItem Height="30">g</ListBoxItem>
    <ListBoxItem Height="30">h</ListBoxItem>
    <ListBoxItem Height="30">i</ListBoxItem>
    ........
  </ListBox>
```

**Comment by timunie** [comment] 2023-04-08 11:47
Can you maybe try latest nightly build and check if the issue is gone?

**Comment by chenjing1294** [comment] 2023-04-08 13:44
version: 11.0.999-cibuild0033026-beta
Improved, but not completely resolved.
![listbox_bug2](https://user-images.githubusercontent.com/21185657/230724467-50394aef-df13-47ad-9421-62c2e692b992.gif)

**Comment by grokys** [comment] 2023-04-18 11:13
Sorry @chenjing1294 I couldn't reproduce that problem on `11.0.999-cibuild0033026-beta`. Could you provide a full repro?

**Closed** 2023-05-17 19:33 UTC
Labels: bug, needs-repro
