### ISSUE TITLE
Add a Visual Studio Code extension

### ISSUE THREAD

**Issue by emberian** [AvaloniaUI/Avalonia#999] opened 2017-05-29 21:46 UTC
Even something really basic would be nice for editing the XAML files (eg, autocompletion of tag names).

**Comment by kekekeks** [comment] 2017-05-31 16:14
https://github.com/kekekeks/Avalonia.Ide - our library for XAML completion

**Comment by ApiumJacob** [comment] 2021-06-19 17:07
I found this researching this topic...I haven't tried it yet.

https://marketplace.visualstudio.com/items?itemName=PrzemyslawOnak.pimp-my-avalonia

https://github.com/ShadowDancer/PimpMyAvalonia

**Comment by vleeuwenmenno** [comment] 2021-06-19 23:31
@ApiumJacob let me know how it goes once you tried.
Running Fedora 34 here and developing for Linux in .NET even when we only had mono

**Comment by ApiumJacob** [comment] 2021-06-20 17:39
@vleeuwenmenno at the moment I decided to go with Rider (30 day free trial).  I'm on Ubuntu 18.04.  Up until this point I've been using VScode and making console apps only.  But the app is getting big enough that its getting difficult to navigate text based menus and it sure would nice to have a file dialog selector so...

**Comment by trampster** [comment] 2021-12-13 08:15
I tried PimpMyAvalonia but it requires .net core 3, This doesn't work because I have .net 6 installed, and I'm using the ubuntu debian package so you can't do side by side installs.

Rider isn't an option for me because it isn't free. And I don't want my open source projects to require a payed product, because that will limit contributions.

I have also looked at using Uno platform because that does have vscode extension that does code completion for xaml. However it's not currently working on linux.

**Comment by trampster** [comment] 2021-12-13 23:52
My Uno platform issue was caused by an omnisharp bug, which is fixed in that latest release, So I can confirm that xaml code completion does work with Uno in vscode on linux. 

So for people wanting to develop on linux Uno might be a better choice, at least until Avalonia add vscode xaml code completion support.

**Comment by martin-braun** [comment] 2021-12-24 15:35
I'd love to not just have an extension for auto completion of XAML, but also a simple designer that allows me to preview my XAML and identify objects in the visual tree by clicking on them. 

If I understand correctly, this is already available for Windows users in Visual Studio, so Mac or Linux users are out of luck, although Avalonia targets all three platforms.

**Comment by iinuwa** [comment] 2022-01-28 14:58
> This doesn't work because I have .net 6 installed, and I'm using the ubuntu debian package so you can't do side by side installs.

@trampster Could you clarify this? I have .NET Core 3.1 and 6 installed at the same time on Ubuntu 20.04 with the `dotnet-sdk-3.1` and `dotnet-sdk-6.0` packages. I might not be thinking about the same thing that you are though.

**Comment by trampster** [comment] 2022-02-03 00:04
I think the extension requires dotnet to be on the path and dotnet --version to be 3.1

But there can be only one dotnet on the plath and it's 6.

**Comment by YoriMirus** [comment] 2022-02-12 21:39
> I think the extension requires dotnet to be on the path and dotnet --version to be 3.1
> 
> But there can be only one dotnet on the path and it's 6.

I have POP!_OS 21.10 and I have dotnet 6.0 and 3.1. dotnet --version lists only 6.0, dotnet --list-sdks shows both versions and the extension works properly to me, so it might be an issue somewhere else for you.

**Comment by Shayan-To** [comment] 2022-05-05 06:21
Any update on this? Any timeframe when this will be available?

**Comment by tizu69** [comment] 2022-10-07 19:33
While not a perfect solution, the "[Xml Complete](https://marketplace.visualstudio.com/items?itemName=rogalmic.vscode-xml-complete)" extension seemingly works flawlessly with axaml files (in the 5 minutes of testing that I did). Sure, it takes about 10 secs after vs code loads for me until the thing kicks in, but after that, it works!
This, obviously, does not include the designer or anything, but [Live.Avalonia](https://github.com/AvaloniaUI/Live.Avalonia) should do the trick for now.

**Comment by scriptBoris** [comment] 2023-05-22 08:39
Any updates?

**Comment by XanatosX** [comment] 2023-06-27 21:04
It's super difficult to develop ui's without either Rider or Visual Studio. It's possible but super time consuming with the current tools we have.
Would be nice to get a status at least.

**Comment by scriptBoris** [comment] 2023-06-27 22:39
> It's super difficult to develop ui's without either Rider or Visual Studio. It's possible but super time consuming with the current tools we have. Would be nice to get a status at least.

I've been using a HotReload all my life and I can say that it's possible!

**Comment by XanatosX** [comment] 2023-06-28 06:04
I will give this a try, you are talking about the "LIve.Avalonia" package which is mentioned some answers above?

**Comment by timunie** [comment] 2023-06-28 06:49
@XanatosX AvantGarde is maybe useful as a stand-alone previewer: https://github.com/kuiperzone/AvantGarde

**Comment by heartacker** [comment] 2023-10-09 14:18
https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.vscode-avalonia

there is

**Comment by tizu69** [comment] 2023-10-09 14:19
> https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.vscode-avalonia
> 
> there is

yup, but that wasn't a thing a few months ago.
kinda was the deal breaker for me, I fully switched to GTK now and love it :)

**Comment by timunie** [comment] 2023-10-09 14:30
CS Code extension is now GA. So we can close this issue imo

**Closed by timunie** 2023-10-09 14:30 UTC
Labels: enhancement
