### ISSUE TITLE
Avalonia.OpenGL.OpenGlException

### ISSUE THREAD

**Issue by HappyBullying** [AvaloniaUI/Avalonia#5025] opened 2020-11-11 08:01 UTC
This is my first issue. Don't judge me strictly if I did something wrong.
This exception sometimes occurs when I resize window and redraw picture in custom draw operation using SKCanvas.

Avalonia.OpenGL.OpenGlException
  HResult=0x80131500
  Сообщение = Unable to make the context current
  Источник = Avalonia.Win32
  Трассировка стека:
   at Avalonia.Win32.OpenGl.WglRestoreContext..ctor(IntPtr gc, IntPtr context, Object monitor, Boolean takeMonitor)
   at Avalonia.Win32.OpenGl.WglGlPlatformSurface.RenderTarget.BeginDraw()
   at Avalonia.Skia.GlRenderTarget.BeginRenderingSession()
   at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer)
   at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(IDrawingContextImpl& context)
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall)
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite)
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)

**Comment by maxkatz6** [comment] 2023-02-01 18:42
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/5562

**Closed by maxkatz6** 2023-02-01 18:42 UTC
