### ISSUE TITLE
Tmds.DBus.Protocol.DBusException

### ISSUE THREAD

**Issue by ChisterWu** [AvaloniaUI/Avalonia#12281] opened 2023-07-21 13:16 UTC
**Describe the bug**
Tmds DBus Error when use avalonia host the webkit webview in Ubuntu22.04.

**To Reproduce**

1.Clone my webview sample from github (https://github.com/MicroSugarDeveloperOrg/Avalonia.WebView.Sample)(use GtkSharp and webkitGtksharp)
2. Build and debug in Ubuntu22.04
3. You will see the avalonia window show and the gtk window also show.(I want to use avalonia host the webkit webview)
4. This is Ok in Debian.

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/28770378/d99d7dc0-09ba-4825-9fa4-140c9b83eb31)
![image](https://github.com/AvaloniaUI/Avalonia/assets/28770378/6c043e0f-24d4-46f2-98ea-b8b99c2a385a)

**Desktop (please complete the following information):**

- OS: [Linux]
- Version [Ubuntu 22.04]

**Additional context**
I don't know if it's due to a lack of system dependencies or a bug in Avalonia

**Comment by LuisThe0ne** [comment] 2024-01-04 22:19
@ChisterWu Could you please state which Version of Debian works?

**Comment by jp2masa** [comment] 2024-01-04 22:53
Duplicate of #13863?

**Comment by maxkatz6** [comment] 2024-01-05 02:16
I am going to close this issue now. If it's still reproducible on latest nightly builds - let me know.

**Closed by maxkatz6** 2024-01-05 02:16 UTC
Labels: bug, os-linux, area-x11

**Comment by erythana** [comment] 2024-03-06 09:22
@maxkatz6 
This issue is still happening for me on Fedora 39 Wayland with latest (yesterdays) Avalonia Release.

`[FreeDesktopPlatform] OnNameChange failed: System.ObjectDisposedException: Cannot access a disposed object.`

```
[IME] Error while destroying the context:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.Dispose() (IBusX11TextInputMethod #17490046)
```

This happens for me when i display a Tooltip on a DataGridRow. It is fine as long my cursor stays on the DataGridRow, but when i move away this error happens in the Debug Output.

**Comment by timunie** [comment] 2024-03-06 09:30
@erythana please try https://github.com/AvaloniaUI/Avalonia/pull/14548#issuecomment-1934755210

**Comment by erythana** [comment] 2024-03-06 09:36
@timunie Thank you, this seems to work!

**Comment by erythana** [comment] 2024-04-25 16:54
Hello @timunie 

With the latest which was released today i still get this error.

Is this going to be included in one of the next releases? I really would like to ship my program without needing to add the prerelease package source to my build.

**Comment by timunie** [comment] 2024-04-26 04:15
@erythana that fix should be in 11.1 beta. Double check your packages please. /Cc @maxkatz6

**Comment by maxkatz6** [comment] 2024-04-26 04:15
@erythana this PR was included in 11.1-beta1. Can you reproduce this issue on latest master?

**Comment by erythana** [comment] 2024-04-26 06:44
@timunie @maxkatz6 
Currently installed packages. I've cleaned the solution and rebuilt it.
![Bildschirmfoto vom 2024-04-26 08-40-10](https://github.com/AvaloniaUI/Avalonia/assets/42657063/333a10be-e96f-44d6-9028-b4142be2402d)

Still get these messages (when opening or closing a hover/popup window):
```
mds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.Dispose() (IBusX11TextInputMethod #19281542)
Started Thread 100832
[IME] Error while destroying the context:
Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   at Avalonia.FreeDesktop.DBusIme.DBusTextInputMethodBase.Dispose() (IBusX11TextInputMethod #54787541)
```

This problem, however, does NOT occur on the version that was posted here: https://github.com/AvaloniaUI/Avalonia/pull/14548#issuecomment-1934755210

In case you want to check on your own:
https://github.com/erythana/EveSquadron

(This version included the working (nightly) package, but i did not include it in my build pipelines)

**Comment by timunie** [comment] 2024-04-26 15:54
@erythana can you check with a minimal sample using 11.1 beta pls? It's not an option for us to scan large Apps.

**Comment by erythana** [comment] 2024-04-27 12:50
@timunie 
Sure, here it is: https://github.com/erythana/DBusExceptionMinimalSample/tree/master
(although i've left the Avalonia Template Code in there)

Hover over the Datagrid Items and as soon as you move away (popup in datagrid closes), to either another item or out of the grid, the messages appear in the debug log.
