### ISSUE TITLE
Blank/empty screen on elementary OS

### ISSUE THREAD

**Issue by SaitDev** [AvaloniaUI/Avalonia#1672] opened 2018-06-12 06:55 UTC
Avalonia: 0.6.1
Dotnet Core: 2.1.300
OS: Elementary OS 0.4.1 (base on Ubuntu 16.04.3)
GTK+ 3.18.9

App based on avalonia launches successfully but nothing appears on its window

**Comment by jkoritzinsky** [comment] 2018-06-13 04:29
I think this might be a duplicate of #1603. I'll leave it open for now.

**Comment by SaitDev** [comment] 2018-06-13 07:55
Agree, duplicated

**Comment by SaitDev** [comment] 2018-08-20 09:33
Reopen since #1603 is closed without solution

**Comment by jmacato** [comment] 2018-08-20 10:10
@SaitDev I'll close this in favor of #1603.

**Closed by jmacato** 2018-08-20 10:10 UTC
Labels: duplicate
