### ISSUE TITLE
[0.10.0-preview5] Potential regressions in ListBox SelectedItem

### ISSUE THREAD

**Issue by Moonlight-Angel** [AvaloniaUI/Avalonia#4864] opened 2020-10-14 09:43 UTC
After upgrading to `0.10.0-preview5`, I noticed some weird behavior and it looks like there are regressions on the ListBox `SelectedItem` property.
Given a ListBox with `SelectionMode` set to `AlwaysSelected,Single`, when a property is bound to the `SelectedItem` property, it doesn't get set when the ListBox auto-selects the first item, and once there are no more items in the list, it doesn't get set to `null`.
Maybe this issue also affects all other controls inheriting from `SelectingItemsControl` and/or other flags for `SelectionMode`.

Reproduction :
```XAML
<StackPanel>
    <ListBox Items="{Binding Items}" SelectionMode="AlwaysSelected,Single" SelectedItem="{Binding SelectedItem}" />
    <Button Command="{Binding RemoveItemCommand}">Remove item</Button>
</StackPanel>
```
```C#
private string _selectedItem;

ctor()
{
    RemoveItemCommand = ReactiveCommand.Create(() => Items.RemoveAt(0), this.WhenAnyValue(vm => vm.Items.Count, itemCount => itemCount > 0));
}

public ReactiveCommand<Unit, Unit> RemoveItemCommand { get; }

public ObservableCollection<string> Items { get; } = new ObservableCollection<string>() { "Item1", "Item2" };

public string SelectedItem
{
    get => _selectedItem;
    set {
        this.RaiseAndSetIfChanged(ref _selectedItem, value);
        Console.WriteLine($"Selected value : {value}");
    }
}
```

Expected output (actual `0.9.12` output) :
```
*Starting app*
Selected value : Item1
*Click on Remove item button*
Selected value : Item2
*Click on Remove item button*
Selected value : 
```

Actual output :
```
*Starting app*
*Click on Remove item button*
Selected value : Item2
*Click on Remove item button*
```

**Comment by grokys** [comment] 2020-10-15 09:51
Hi @Moonlight-Angel - I think this has already been fixed. Just tried in master with your code and I can't reproduce.

There have been a few fixes to selection since preview 5, could you try our latest CI release https://www.myget.org/feed/avalonia-ci/package/nuget/Avalonia/0.10.999-cibuild0011345-beta and see if that fixes it?

In the meantime will close this - please let me know if it's not fixed. Hopefully we'll have a new official 0.10 release out soon.

**Closed by grokys** 2020-10-15 09:51 UTC
Labels: bug

**Comment by Moonlight-Angel** [comment] 2020-10-17 05:29
Indeed @grokys, tried with `0.10.999-cibuild0011389-beta` and the issue is fixed.
Thanks for your response and sorry for the false positive ! 😀
