### ISSUE TITLE
Font rendering is different in version 11.1.0-beta1 on Windows

### ISSUE THREAD

**Issue by DavidZidar** [AvaloniaUI/Avalonia#15015] opened 2024-03-16 16:13 UTC
### Describe the bug

I tried updating my application to the beta and noticed that fonts are slightly smaller and blurrier than before.

As there is no mention of this change in the release notes so I wonder if it's intentional or a mistake?

Here's how a section of my app looks with v11.0.10 (nice and clear):
![image](https://github.com/AvaloniaUI/Avalonia/assets/381720/8adefd5a-9fde-4905-87a5-f4ecf5f80a8c)

And here's what it looks with v11.1.0-beta1 (blurry and too small):
![image](https://github.com/AvaloniaUI/Avalonia/assets/381720/24b7f7d8-37d2-453c-8d01-2d5d326edab0)

### To Reproduce

Update to v11.1.0-beta1.

### Expected behavior

The font rendering should be like before, or if it's intentional it should be in the release notes and there should be info on how to make adjustments if possible.

### Avalonia version

11.1.0-beta1

### OS

Windows

**Comment by timunie** [comment] 2024-03-17 09:21
Please file a minimum sample using your font to double-check on our side

**Comment by DavidZidar** [comment] 2024-03-17 10:01
@timunie It's the default font. But this also happens with a custom font I have so I assume it affects all fonts.

**Comment by DavidZidar** [comment] 2024-03-17 14:07
I reproduced it using `dotnet new avalonia.app` and then updating to 11.1.0-beta1

With 11.0.10:
![image](https://github.com/AvaloniaUI/Avalonia/assets/381720/8322adb0-1915-4213-990f-c4beecbde800)

With 11.1.0-beta1:
![image](https://github.com/AvaloniaUI/Avalonia/assets/381720/00c3b080-0637-4add-b06f-b64db38f127e)

**Comment by Gillibald** [comment] 2024-03-17 16:06
Second image has no ClearType enabled

**Comment by DavidZidar** [comment] 2024-03-17 16:18
Just to be clear, the only change I made was the version number of the Avalonia packages.

**Comment by rabbitism** [comment] 2024-03-17 17:21
similar
https://github.com/AvaloniaUI/Avalonia/issues/14711

**Comment by timunie** [comment] 2024-03-18 08:08
Yeah seems to be a duplicate of #14711 . 

@Gillibald I'll leave it to you if you want to close that issue in favor of the other one

**Comment by Gillibald** [comment] 2024-03-18 12:00
Such issue reports are not helping. I need a minimal repro I can run as is without building some full blown up application.

**Comment by rabbitism** [comment] 2024-03-18 12:28
https://github.com/rabbitism/FontDiffIssue 
Here is the repro, run both project and compare closely. 
![5164ccb1a8e8c70c407ba7ddac668a31](https://github.com/AvaloniaUI/Avalonia/assets/14807942/ccc16f22-befb-4ab6-a7f7-9875d1f62ded)

**Comment by DavidZidar** [comment] 2024-03-18 13:32
> Such issue reports are not helping. I need a minimal repro I can run as is without building some full blown up application.

Your own hello world template reproduces the issue, I don't see the problem.

**Comment by maxkatz6** [comment] 2024-03-18 23:20
Looks like ClearType doesn't work for some reason.

![image](https://github.com/AvaloniaUI/Avalonia/assets/3163374/bec28c26-649f-4e6f-8e36-47e28a33801e)

**Comment by BobbyCannon** [comment] 2024-04-26 13:33
Tested with 11.1.0-beta2 in the repo example. It's still fuzzy.

https://github.com/rabbitism/AvaloniaIssueRepro/tree/main/FontRenderIssue

**Closed** 2024-05-12 08:19 UTC
Labels: bug, regression, area-textprocessing
