### ISSUE TITLE
System.StackOverflowException in the ControlCatalog.Browser sample application

### ISSUE THREAD

**Issue by Numpsy** [AvaloniaUI/Avalonia#10675] opened 2023-03-15 14:48 UTC
**Describe the bug**
I was having a go at updating Avalonia.FuncUI with the latest Avalonia 11 changes (using the ```11.0.999-cibuild0031892-beta``` nightly build) and was getting a ```StackOverflowException``` in both Edge and Firefox whilst trying to run it.

I then tried running the ControlCatalog.Browser sample application using the latest ```master``` branch as of now, and I get the same error there as well.

**To Reproduce**
I was just doing ```dotnet run``` in the ```samples\ControlCatalog.Browser``` directory, and then navigating to the running web application.

**Expected behavior**
It should run without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/1178570/225345908-4629eb30-795c-45e7-b409-cd7983c609e1.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox (110.0.1) and Edge (111.0.1661.41)

**Comment by graealex** [comment] 2023-03-15 15:34
Issue seems to be caused by https://github.com/AvaloniaUI/Avalonia/pull/10620 where Skia has trouble matching the now-uppercased family names internally. I'd recommend to revert the PR as it's rather non-essential, until all the side-effects have been appreciated.

**Comment by timunie** [comment] 2023-03-15 16:31
@Gillibald @avaloniaui-team imo this should be done before next preview release

**Comment by Gillibald** [comment] 2023-03-15 17:50
It seems that the emscripten implementation is only able to load system fonts when the name exactly matches. So y we might want to revert the PR. It was meant to make font loading easier by normalizing family names.

**Comment by graealex** [comment] 2023-03-22 10:48
This [commit](https://github.com/AvaloniaUI/Avalonia/commit/46632741e4db1ea989744959b3ee69fce4805354) reverts the changes from the PR that introduced the StackOverflowException, so it is solved for now by updating to Preview 6

**Comment by timunie** [comment] 2023-03-22 11:00
@graealex thx for confirming the fix. I'll close the issue now. If a similar issue arises, a new bug report is needed

**Closed by timunie** 2023-03-22 11:00 UTC
Labels: bug

**Comment by Numpsy** [comment] 2023-03-22 11:07
I can confirm that the FuncUI web assembly samples work now when using Preview 6 as well, thanks. (for the record)
