### ISSUE TITLE
Closing Popup sets wrong focus.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#13325] opened 2023-10-20 09:32 UTC
## Describe the bug

Closing a popup can set focus to the wrong control. Reported by @jankrib .

## To Reproduce

```xml
  <Window.Styles>
    <Style Selector="Button:focus">
      <Setter Property="Background" Value="Green" />
    </Style>
  </Window.Styles>
  <StackPanel Margin="10">
    <ToggleButton Name="ShowToggle" Focusable="False">
      <TextBlock Text="Show" />
    </ToggleButton>
    <Button Name="Target" Content="?" HorizontalAlignment="Center"/>
    <Popup IsOpen="{Binding #ShowToggle.IsChecked}" PlacementTarget="{Binding #Target}" PlacementMode="Left">
      <Border Background="Red" Width="200" Height="100">
      </Border>
    </Popup>
    <StackPanel>
      <Button Content="Click me to delete to set focus to null" Click="Clicked"/>
      <Button Content="Click me to delete to set focus to null" Click="Clicked"/>
      <Button Content="Click me to delete to set focus to null" Click="Clicked"/>
    </StackPanel>
  </StackPanel>
```

```
public void Clicked(object sender, RoutedEventArgs args)
{
	if (sender is Button button)
	{
		button.FindLogicalAncestorOfType<StackPanel>()?.Children.Remove(button);
	}
}
```

1. Click "Show". You will see the red popup open
2. Click a button with the text "Click me to delete to set focus to null"
3. Click "Show" to hide the popup
4. The "?" button is focused, which was never user-focused

## Expected behaviour

Either:

- The "Show" button should be focused as that's what was focused when the popup was shown; or
- There should be no focus as after the popup was shown, a button was focused which was then removed (setting focus to null)

## Environment 

- OS: Windows/all
- Avalonia-Version: 11.0.5

## Additional context

This behaviour was added in #4809 which said:

> Alternatively, we could store the current focus on open and restore it on close (this should be the `PlacementTarget` anyway)

This may be a better solution. An even better solution might be to let our focus scope code handle this.

**Comment by jankrib** [comment] 2023-10-20 10:03
For expected behavior, I would argue it should be:
The "Show" button should be focused because closing a popup that does not have keyboard focus inside should not affect focused element.

Additional context:
In my view the main problem here is the subtle difference between KeyboardFocus and Focus that exists because of different focus scopes. This was a problem in WPF too just because of naming. IsFocused property on a control doesn't really tell you. You just have to know that if it is not called something with Keyboard it means scoped.

Take this code in InputElement:
```
protected override void OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e)
        {
            base.OnDetachedFromVisualTreeCore(e);

            if (IsFocused)
            {
                FocusManager.GetFocusManager(this)?.ClearFocus();
            }
        }
```

What it does here is to say if this control is focused in it's scope clear focus for the app.

The introduction of `FocusManager.GetFocusManager(this)` leads to additional confusion because it applies that there is an additional level in the focus tree where you can have multiple managers per app. As far as I know there is not.

**Comment by grokys** [comment] 2023-10-20 10:06
> The "Show" button should be focused because closing a popup that does not have keyboard focus inside should not affect focused element.

But by clicking the "Click me to delete to set focus to null" button, the "Show" button is no longer focused. So if this were to be refocused on close, then we might have unwanted behavior again.

> In my view the main problem here is the subtle difference between KeyboardFocus and Focus that exists because of different focus scopes.

There are no focus scopes in play here. The only focus scope is the `Window` in this example.

**Comment by jankrib** [comment] 2023-10-20 10:40
PopupRoot is a focus scope. It doesn't matter in this version of the example since we use the delete buttons to make focus null. The focus scope issue is probably best defined as a separate issue.

The reason why I argued the "Show" should have focus is not because it had focus before you click the delete button. I should have probably made a separate "Hide" button for the example. When you click the "Show" button to hide the popup you expect the button to get focus because you click it. In the example above the "Show" button has Focusable set to false, though. So I guess expected focus should be that it remains null.

**Comment by grokys** [comment] 2023-10-20 11:02
> PopupRoot is a focus scope

Are you sure? It doesn't implement `IFocusScope`, and I can't see any other focus scopes being registered in the focus manager

> When you click the "Show" button to hide the popup you expect the button to get focus because you click it.

But the "Show" button is explicitly marked as non-focusable?

**Comment by jankrib** [comment] 2023-10-20 11:17
PopupRoot implements IPopupHost which implements IFocusScope.

Yes. So in this example it shouldn't.

**Comment by grokys** [comment] 2023-10-20 11:18
> `PopupRoot` implements `IPopupHost` which implements `IFocusScope`.

Ah ok sorry, I missed that transitive reference. Ok, there's definitely something wrong with focus scopes in this case then. Investigating further.

**Comment by grokys** [comment] 2023-10-20 12:35
My suggestion is to remove the hackfix in #4809 and modify our focus scopes to restore focus to any outermost focus scope when `FocusManager.ClearFocus` is called.

**Closed** 2023-11-12 02:26 UTC
Labels: bug
