### ISSUE TITLE
Custom fonts do not work

### ISSUE THREAD

**Issue by MakcStudio** [AvaloniaUI/Avalonia#3222] opened 2019-11-06 10:01 UTC
[test.zip](https://github.com/AvaloniaUI/Avalonia/files/3813783/test.zip)

I put together a small project to show that nothing happens when you change. Maybe I'm doing something wrong, but I tried every option I could find.

**Comment by Gillibald** [comment] 2019-11-06 10:12
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2194

What version of Avalonia are you using?

**Comment by MakcStudio** [comment] 2019-11-06 10:13
> Дубликат [№2194](https://github.com/AvaloniaUI/Avalonia/issues/2194)
> 
> Какую версию Avalonia вы используете?

0.9.0-preview-4

**Comment by Gillibald** [comment] 2019-11-06 10:15
Will have a look

**Comment by MakcStudio** [comment] 2019-11-06 10:18
> Will have a look

I have this not causes exceptions, as in those Yishui, that I read, simply not is changing the fine print, remains default

**Comment by Gillibald** [comment] 2019-11-06 10:20
Your workaround shows that this is caused by a non present context when a style is parsed. Will verify this. If it is the case XamlIl is causing this.

**Comment by MakcStudio** [comment] 2019-11-06 12:38
resm:AvaloniaApplication1.Fonts.Banty_Bold.ttf?assembly=AvaloniaApplication1#Banty

its work!
Banty_Bold.ttf set EmbeddedResource in .cproj

**Closed** 2019-11-06 13:58 UTC
