### ISSUE TITLE
Focus NumericUpDown via code is not possible

### ISSUE THREAD

**Issue by tisis2** [AvaloniaUI/Avalonia#13362] opened 2023-10-24 08:07 UTC
## Describe the bug
controls can be focused through the Focus() method during runtime. this works with controls like textbox and button but not with a NumericUpDown

## To Reproduce
i created an example to showcase the issue

1. Clone https://github.com/tisis2/Examples/tree/main/Issues/Avalonia/FocusNumericUpDown
2. build and run
3. click the buttons

## Expected behavior
the NumericUpDown should be able to be focused like other controls

## Screenshots
![gif_69](https://github.com/AvaloniaUI/Avalonia/assets/18416393/bbbbe4a3-ff81-496e-a3bb-a366f26ed465)

## Environment 

- Windows 10
- Avalonia-Version: 11.0.5

**Comment by timunie** [comment] 2023-10-24 14:24
duplicate of https://github.com/AvaloniaUI/Avalonia/issues/8069 and probably https://github.com/AvaloniaUI/Avalonia/issues/13339

A focus of the TextBox-Part would be a solution imo. But only if the focus is not on the button spinner. One might want to file a PR as the original issue is tagged with Help-wanted

**Closed by timunie** 2023-10-24 14:24 UTC
Labels: bug

**Comment by tisis2** [comment] 2023-10-25 05:11
#13376
