### ISSUE TITLE
PointerPressed event didn't work

### ISSUE THREAD

**Issue by Piripe** [AvaloniaUI/Avalonia#11758] opened 2023-06-12 18:35 UTC
**Describe the bug**
I just tried using the `PointerPressed` event as described in the discussion #10673 but it didn't work at all.

**Expected behavior**
I would like to use the `PointerPressed` event.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0.0-rc1.1

**Additional context**

Example project that use `PointerPressed`:
[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/11726805/AvaloniaApplication1.zip)

**Comment by timunie** [comment] 2023-06-12 19:11
Added a valid answer after trying out for 11.0 again. See: https://github.com/AvaloniaUI/Avalonia/discussions/10673#discussioncomment-6155908 

I hope it helps. 

Note: I'm closing this issue for now as I think it's by design. If someone disagrees, please let me know.

**Comment by timunie** [comment] 2023-06-12 19:11
thanks for the sample btw. This was useful ;-)

**Closed by timunie** 2023-06-12 19:11 UTC
Labels: bug

**Comment by rabbitism** [comment] 2023-08-30 10:53
> Added a valid answer after trying out for 11.0 again. See: [#10673 (reply in thread)](https://github.com/AvaloniaUI/Avalonia/discussions/10673#discussioncomment-6155908)
> 
> I hope it helps.
> 
> Note: I'm closing this issue for now as I think it's by design. If someone disagrees, please let me know.

I can confirm it behaves the same in WPF, `MouseLeftButtonDown` event will not be triggered, only `PreviewMouseLeftButtonDown` can be triggered.
