### ISSUE TITLE
Ambiguous match found: *.xaml 

### ISSUE THREAD

**Issue by Wyvernius** [AvaloniaUI/Avalonia#3408] opened 2020-01-06 11:43 UTC
For the last 2 days i'v been trying to tackle this issue.
Basically rewriting my code to see where the error came from.
Problem:
I got a Ambiguous match found on an PdfController.xaml file.
No further info was given.

What i found was the problem:
In the csproj file there is this:
```
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
```
As it happened there was also:

 ```
   <Compile Update="PdfViewer\PdfController.xaml.cs">
      <DependentUpon>"PdfViewer\PdfController.xaml"</DependentUpon>
    </Compile>
```
At the bottom of the page.
After deleting the last definition the error went away and the designer could show me the layout.

Hope this helps someone who stumbles on the exact same problem.

**Comment by MikeCodesDotNET** [comment] 2023-07-03 09:33
This might have been caused by Visual Studio making assumptions about xaml files. We since changed to using the axaml extension to avoid VS getting confused and doing strange things. 

Closing as I don't think we can do much about VS oddities at the moment.

**Closed by MikeCodesDotNET** 2023-07-03 09:33 UTC
