### ISSUE TITLE
Error in CompileAvaloniaXamlTask prevents compiling Avalonia apps in Visual Studio for Mac

### ISSUE THREAD

**Issue by ylatuya** [AvaloniaUI/Avalonia#8149] opened 2022-05-17 07:36 UTC
**Describe the bug**
When compiling an Avalonia app with Visual Studio for Mac there is an error in the CompileAvaloniaXamlTask that halts the build midway. It appears randomly and I was able to fix it by deleting the file `Avalonia/original.pdb` before the build and building again. Right now it fails even deleting that file before build.

```
/Users/andoni/.nuget/packages/avalonia/0.10.13/buildTransitive/AvaloniaBuildTasks.targets(5,5): Error MSB4018: The "CompileAvaloniaXamlTask" task failed unexpectedly.
System.IO.IOException: Sharing violation on path /Users/****/LongoMatch/obj/netframework/Debug/Avalonia/original.pdb
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x00259] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:274 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:106 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
  at System.IO.FileSystem.CopyFile (System.String sourceFullPath, System.String destFullPath, System.Boolean overwrite) [0x00035] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:55 
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00056] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:74 
  at Avalonia.Build.Tasks.CompileAvaloniaXamlTask.Execute () [0x00083] in <a9f18681689043ab889adba9e4427dbb>:0 
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:578 
  at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002b9] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:807  (MSB4018)
```

**To Reproduce**

1. Start the build of an Avalonia app
2. Build fails in CompileAvaloniaXamlTask

**Expected behavior**
The build is completed successfully

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac
- Version 12.3.1
- VS for Mac 8.10.17 (build 2)

**Additional context**

**Comment by maxkatz6** [comment] 2022-05-24 07:21
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/5294

**Closed by maxkatz6** 2022-05-24 07:21 UTC
Labels: bug
