### ISSUE TITLE
Host Avalonia controls in WPF

### ISSUE THREAD

**Issue by Yslelf** [AvaloniaUI/Avalonia#17410] opened 2024-11-02 06:05 UTC
### Is your feature request related to a problem? Please describe.

Host Avalonia controls in  WPF

### Describe the solution you'd like

Host Avalonia controls in  WPF

**Comment by maxkatz6** [comment] 2024-11-02 07:22
It's already possible in two ways.

1. Windows specific, using HwndHost. Sample is here https://github.com/maxkatz6/AvaloniaHwndHostSample/tree/main
This issue is a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/11611

2. Using [XPF Hybrid](https://avaloniaui.net/blog/introducing-hybrid-xpf-bridging-avalonia-and-wpf-controls). Where WPF runs crossplatform, and can embed Avalonia content directly, without HwndHost.

**Closed by maxkatz6** 2024-11-02 07:22 UTC
Labels: enhancement
