### ISSUE TITLE
vscode axaml code completion doesn't work

### ISSUE THREAD

**Issue by trampster** [AvaloniaUI/Avalonia#14336] opened 2024-01-24 03:32 UTC
## Describe the bug
The axaml code completion doesn't work it always says: "Build the project to enable code completion". It doesn't matter how many times you build the project.

## To Reproduce

1. Install Avalonia for VSCode extension
2. Open an Avalonia project
3. Go to a axaml file
4. Try to use code completion

## Expected behavior
axaml Code completion works

## Screenshots
says "Build the project to enable code completion".

![Screenshot from 2024-01-24 16-29-54](https://github.com/AvaloniaUI/Avalonia/assets/2063633/72bf2860-3156-4375-a50c-dc2c9c95657c)

## Environment 

- OS: linux ubuntu 20.04
- Avalonia-Version: 11.0.6
- Avalonia for VSCode: v0.0.28

**Comment by timunie** [comment] 2024-01-24 07:14
Build needs to be done for debug mode iirc. Also worth to check 11.0.7 here. If that not helps, I'll forward the issue to the extension.

**Comment by timunie** [comment] 2024-01-24 10:11
Duplicate of https://github.com/AvaloniaUI/AvaloniaVSCode/issues/88 I believe.

**Closed by timunie** 2024-01-24 10:11 UTC
Labels: bug
