### ISSUE TITLE
How to implement input fields similar to weChat?

### ISSUE THREAD

**Issue by 239573049** [AvaloniaUI/Avalonia#12495] opened 2023-08-10 02:24 UTC
I want to implement an input box similar to weChat, when I paste the input box, if the data is a picture, it will be displayed in the input box. In html, I changed the div attribute to be editable, but I couldn't find a way to implement it in avalonia.

**Comment by rabbitism** [comment] 2023-08-10 04:09
You need rich text editor.

**Comment by timunie** [comment] 2023-08-10 06:10
closing as duplicate of #4625

**Closed by timunie** 2023-08-10 06:10 UTC
Labels: enhancement
