### ISSUE TITLE
NumericUpDown crashes when deleting the content

### ISSUE THREAD

**Issue by Developer-Alexander** [AvaloniaUI/Avalonia#11943] opened 2023-06-28 13:14 UTC
**Describe the bug**
When the content of a `NumericUpDown` is selected and deleted it crashes the app.

**To Reproduce**
Minimal app for reproduction: 
[NumericUpDownBug.zip](https://github.com/AvaloniaUI/Avalonia/files/11895047/NumericUpDownBug.zip)

**Expected behavior**
It should not crash. Instead it should return to a default value or minimum value.

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.0-rc1.1

**Comment by maxkatz6** [comment] 2023-06-28 18:45
duplicate of https://github.com/AvaloniaUI/Avalonia/issues/10793

**Closed by maxkatz6** 2023-06-28 18:45 UTC
Labels: bug
