### ISSUE TITLE
window flickers on mac

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#4500] opened 2020-08-17 19:35 UTC
My app has bursts of the app window flickering on mac. It looks like the whole window is not drawn for just a frame as you can very briefly see what ever is behind. It gets worse as the app works harder.  I see it on a late 2008 macbook pro and a user has reported it on a late 2012 macbook pro on Catalina 10.15.3

**Comment by wuzlai** [comment] 2020-08-18 07:58
> My app has bursts of the app window flickering on mac. It looks like the whole window is not drawn for just a frame as you can very briefly see what ever is behind. It gets worse as the app works harder. I see it on a late 2008 macbook pro and a user has reported it on a late 2012 macbook pro on Catalina 10.15.3

Hi, I have a similar problem with you.
window flickers,also on window,But not every time, and I'm curious as to why

**Comment by ahopper** [comment] 2020-08-19 17:58
Just checked on the current master. The flickering gets worse as you make the window larger, everything other than the top bar of the window flickers.  cpu use appears much higher on osx than other platforms and that appears to be connected to refreshing the screen rather than the rest of the app, I wonder if that is connected.

**Comment by grokys** [comment] 2020-08-19 19:56
This is often caused by the render thread throwing exceptions. If you're on Visual Studio, you can see if this is happening by disabling "Just My Code". Is this happening for either of you? If so, exception details/stacktrace should help us diagnose it.

**Comment by ahopper** [comment] 2020-08-19 21:32
I managed to set "JustMyCode" to false in launch.json in vscode on my mac and got no exceptions whilst flickering. On windows I get no exceptions and no flickering.

**Comment by ahopper** [comment] 2020-08-20 18:57
would a repro help or is there an idea what the problem is?

**Comment by wuzlai** [comment] 2020-09-04 03:50
> This is often caused by the render thread throwing exceptions. If you were on windows/Visual Studio, you can see if this is happening by disabling "Just My Code" - not sure how to do it on a mac?
> 
> Is this happening for either of you? If so, exception details/stacktrace should help us diagnose it.

Hi,I have do it,but  i use event.when i close the winfow,.
 protected override void OnClosing(CancelEventArgs e)
        {
            this.Hide();
            base.OnClosing(e);
        }

**Comment by danwalmsley** [comment] 2020-09-06 11:41
@kekekeks this repros in many OS X apps. Resizing etc. Is it possible to present ui when render hasn't yet completed? Btw it's worse with box shadows, but still happens without.

**Comment by ahopper** [comment] 2020-09-12 06:25
In my app the flickering gets worse the larger the window is. Below a certain size the flickering stops. It does feel like something is running out of time or resources during a frame.

**Comment by kekekeks** [comment] 2020-09-12 07:15
@danwalmsley can we drop Metal-incapable systems? Metal itself is available from  OSX 10.11 and is strictly required starting from 10.14.

**Comment by ahopper** [comment] 2020-09-12 08:25
I think that limits it to 2012 macs and later, it would write of my freebe 2008 test machine but that is not strictly supported by 10.13 (minimum for netcore3) so I can't complain. It would mean dropping support for the some 2009 and all 2010 and 2011 machines. I don't know how may of these are still in use but they are still very useable. I don't recall any of my users mentioning anything pre 2012.

**Comment by danwalmsley** [comment] 2020-09-12 12:15
Wasabi and .net core only support officially 10.13+ so let's do it.

**Comment by ahopper** [comment] 2020-09-14 15:52
I'm looking for a quick tempory fix for this, I have a feeling/hunch that the problem may have appeared when the real fps went from 30 to 60 fps, I'll try a 30 fps render timer on osx but would welcome any suggestions/advice/guesses on any other work arounds as my app is currently not useable on mac

**Comment by ahopper** [comment] 2020-09-15 11:17
running with a 30fps render timer reduces this from almost continuous flicker when full screen to an occasional flicker. At 10fps I saw no flicker.

**Comment by jenswet** [comment] 2020-11-08 17:19
I can reproduce the same. Is there any workaround available already?

**Comment by ahopper** [comment] 2020-11-08 18:41
I use this in BuildAvaloniaApp() to reduce fps to 30 which helps, I tried turning gpu off but cpu was too high for my use.

```
if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                var wp = builder.WindowingSubsystemInitializer;
                return builder.UseWindowingSubsystem(() =>
                {
                    wp();
                    AvaloniaLocator.CurrentMutable.Bind<IRenderTimer>().ToConstant(new DefaultRenderTimer(30));
                });
            }

            return builder;
```

**Comment by wuzlai** [comment] 2020-11-10 10:35
> I use this in BuildAvaloniaApp() to reduce fps to 30 which helps, I tried turning gpu off but cpu was too high for my use.
> 
> ```
> if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
>             {
>                 var wp = builder.WindowingSubsystemInitializer;
>                 return builder.UseWindowingSubsystem(() =>
>                 {
>                     wp();
>                     AvaloniaLocator.CurrentMutable.Bind<IRenderTimer>().ToConstant(new DefaultRenderTimer(30));
>                 });
>             }
> 
>             return builder;
> ```

Hi man,.i use your code,On Debian, the feel is ok.
 But still flicker occasionally, appear black back figure
This is a serious problem. I want to keep following up.

**Comment by jenswet** [comment] 2020-11-10 19:18
Hi @danwalmsley @kekekeks @grokys I tried recording some error log, but I didn't succeed.

When debugging with Rider and enabling debugging external code (https://www.jetbrains.com/help/rider/Debugging_External_Code.html) no exception or log output occurs.

When using Visual Studio for Mac with enabled exception tracking in external code I can't see any error either. But the app crashes very often after a few seconds with the flickering. macOS reports the following reason:
```
abort() called
dotnet(94980,0x70000f89f000) malloc: *** error for object 0x7fa06a098ca0: pointer being freed was not allocated
```

Can I enable any further logging to help debugging this issue? It would be great to fix this with the 0.10 release if possible.

Thank you!

**Comment by danwalmsley** [comment] 2020-11-10 19:22
@jenswet thanks for that useful information. Firstly be reassured, we will not be releasing without resolving this issue.

We have a strategy on how we are going to do it... but probably will prob take a few more weeks before we have something ready.

Not sure how to get more debugging... perhaps using either XCode or Intruments?

**Comment by jenswet** [comment] 2020-11-10 21:50
@danwalmsley Is there any option to enable logging for the render thread?

Thank you for including this issue in the plan for the next release!

**Comment by danwalmsley** [comment] 2020-11-10 22:13
Its a synchronisation issue... we are moving to use MTKView (https://developer.apple.com/documentation/metalkit/mtkview) to fix the issue.

**Comment by danwalmsley** [comment] 2020-11-21 23:28
Fixed!

**Closed** 2020-11-21 23:28 UTC
