### ISSUE TITLE
Cannot add binding inside DataTemplate to a property outside of it

### ISSUE THREAD

**Issue by JakubK** [AvaloniaUI/Avalonia#2780] opened 2019-07-27 14:38 UTC
Hello.
I'm having a problem with binding to my ViewModel's property inside DataTemplate in the View.

Consider the following example:
I have a View and a ViewModel. In the View I have a button and an ItemsControl with defined DataTemplate.
I assigned a Name to a View to make it possible to reach it's DataContext from the DataTemplate.
Here's the code for binding outside of the DataTemplate
` <Button Command="{Binding ElementName=Root,Path=DataContext.DeleteCommand}">Delete</Button>` where the Root is name of my View.

It works when placed outside of the DataTemplate, inside it won't work.

**Comment by FoggyFinder** [comment] 2019-07-27 14:42
Version of Avalonia? Can you provide full example?

**Comment by JakubK** [comment] 2019-07-27 15:35
@FoggyFinder  I'm using recent Version of Avalonia.
Here here full example in App that I'm working on
https://github.com/JakubK/LinCon/blob/feature/%2310_implement_basic_case_explorer_view/LinCon.Avalonia/Views/CaseExplorerView.xaml

**Comment by FoggyFinder** [comment] 2019-07-27 15:47
Seems like a bug. Workaround:

```xml
 Command="{Binding $parent[ItemsControl].DataContext.DeleteCommand}"
```

0.8.0 isn't a recent though.

**Comment by JakubK** [comment] 2019-07-27 15:59
@FoggyFinder  Yeah the bugs exists on 0.8.1 anyway so there's no difference.
Thanks, your workaround helped, but I will still keep this issue open because I think it's important to fix this.

**Comment by FoggyFinder** [comment] 2019-07-27 16:10
Sure, I can test it on nightly build later today to check if bug currently exists.

**Comment by FoggyFinder** [comment] 2019-07-27 20:30
I wasn't able to reproduce the behaviour on nightly build.

**Comment by grokys** [comment] 2019-10-28 14:19
Duplicate of #1572, should have been fixed by #2705.

**Closed by grokys** 2019-10-28 14:19 UTC

**Comment by balthild** [comment] 2019-11-04 12:12
Is this issue has beed fixed in the curernt release? I've upgraded Avalonia to v0.8.3 but `{Binding #ElementName.DataContext.XYZ}` inside ItemsControl still doesn't work.

**Comment by Gillibald** [comment] 2019-11-04 12:15
@balthild you need to use the current preview

**Comment by derekantrican** [comment] 2020-10-16 00:48
What is the proper way to do this in 0.9.12? I've been trying a bunch of variations on this (binding DataContext to window's DataContext, binding to the `DataContext.Command` with the element name of the parent, and the special `#` and `$` usages mentioned here) with no luck. Here's the section of my code where I'm trying to bind the inner Button's command to a command on the same DataContext as the outer ContextMenu. Any suggestions?

```xml
<Button Margin="5">
  <Button.ContextMenu>
    <ContextMenu Items="{Binding MenuItems}" SelectedItem="{Binding SelectedMenuItem}">
      <ContextMenu.ItemTemplate>
        <DataTemplate>
          <Button Padding="0" BorderThickness="0" Background="Transparent" Command="{Binding $parent[ContextMenu].DataContext.AddItemToToolTips}">
            <TextBlock Text="{Binding .}"/>
          </Button>
        </DataTemplate>
      </ContextMenu.ItemTemplate>
    </ContextMenu>
  </Button.ContextMenu>
</Button>
```
