### ISSUE TITLE
Set full screen, but cannot hide the taskbar of windows

### ISSUE THREAD

**Issue by hccoo** [AvaloniaUI/Avalonia#2791] opened 2019-07-30 09:48 UTC
Set full screen, but cannot hide the taskbar of windows, and the Topmost can not work on max sized mode. How to solve it?

**Comment by grokys** [comment] 2019-07-30 11:44
@danwalmsley @kekekeks

**Comment by kekekeks** [comment] 2019-07-30 16:09
Probably duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2759

**Closed** 2024-01-17 23:16 UTC
Labels: question
