### ISSUE TITLE
Style.Resrouces works out of style scope

### ISSUE THREAD

**Issue by Flithor** [AvaloniaUI/Avalonia#10945] opened 2023-04-07 10:11 UTC
**Describe the bug**
Resource in Style will work on global, not only style scope.

**To Reproduce**
The belows Style contant `ButtonBackground` resource will work for all button background....
```
<Style Selector="Button.NoBoundButton">
	<Style.Resources>
		<SolidColorBrush x:Key="ButtonBackground" Color="Transparent" />
	</Style.Resources>
</Style>
```

**Expected behavior**
It should only work for style selector matched scope

**Screenshots**
Nope

**Desktop (please complete the following information):**

- OS: Window 11
- Version 0.10.19

**Additional context**
Uhhhhhhhhhhhhhh.....

**Comment by maxkatz6** [comment] 2023-04-07 17:32
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/4801
Long story short: it's by design. But might feel unexpected for developers.

**Closed by maxkatz6** 2023-04-07 17:32 UTC
Labels: bug
