### ISSUE TITLE
Style Precedence is not considered when manually setting an overwriting class

### ISSUE THREAD

**Issue by HaSa1002** [AvaloniaUI/Avalonia#7401] opened 2022-01-20 12:29 UTC
**Describe the bug**

I am exceptionally bad at explaining this in words. So here is a MRP and an image:

```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaStyleIssue.MainWindow"
        Title="AvaloniaStyleIssue">
  <Window.Styles>
    <Style Selector="TextBlock.fg-orange, .fgd-orange TextBlock">
      <Setter Property="Foreground" Value="Orange" />
    </Style>
    <Style Selector="TextBlock.fg-blue, .fgd-blue TextBlock">
      <Setter Property="Foreground" Value="Blue" />
    </Style>

    <!-- Uncomment line below to "fix" -->
    
    <!--<Style Selector="TextBlock.fg-orange, .fgd-orange TextBlock">
      <Setter Property="Foreground" Value="Orange" />
    </Style>-->
  
  </Window.Styles>
  <Border Padding="20">
    <StackPanel Spacing="20">
      <TextBlock Classes="fg-orange">I am orange.</TextBlock>
    <StackPanel Classes="fgd-blue">
      <TextBlock>This is blue.</TextBlock>
      <TextBlock Classes="fg-orange">This should be orange.</TextBlock>
      <TextBlock Foreground="Orange">This is orange.</TextBlock>
    </StackPanel>
    </StackPanel>
  </Border>
</Window>
```

![grafik](https://user-images.githubusercontent.com/14185889/150336451-3acbe150-231b-40f7-bb9c-3c8981e06551.png)

The line `This should be orange.` should be coloured orange.

If the styles definition order is changed, it behaves correct. (This is not an option in the real project):
```xaml
  <Window.Styles>
    <Style Selector="TextBlock.fg-blue, .fgd-blue TextBlock">
      <Setter Property="Foreground" Value="Blue" />
    </Style>
    
    <Style Selector="TextBlock.fg-orange, .fgd-orange TextBlock">
      <Setter Property="Foreground" Value="Orange" />
    </Style>
  </Window.Styles>
```

![grafik](https://user-images.githubusercontent.com/14185889/150337131-da26735d-b185-4a5d-ae12-d424ac970b4b.png)

**To Reproduce**

1. Open the [MRP](https://github.com/AvaloniaUI/Avalonia/files/7905065/AvaloniaStyleIssue.zip).
2. Compile and Run.
3. Change the style definiton order like shown above and rerun.

**Expected behavior**
![grafik](https://user-images.githubusercontent.com/14185889/150337131-da26735d-b185-4a5d-ae12-d424ac970b4b.png)
The definition order shouldn't matter, because the styles are not the same like described here: https://docs.avaloniaui.net/docs/styling/troubleshooting#target-property-is-overridden-by-another-style and the local set class is nearest to the control like described there: https://docs.avaloniaui.net/docs/styling/styles#style-precedence (Okay actually reading again this is intended, but it does feel like a bug, because I set the desired class manually to overwrite the style that is already in place.)

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.10

**Comment by maxkatz6** [comment] 2022-01-20 12:51
> The definition order shouldn't matter

It matters. And it's the reason of current behavior. Blue style is defined after orange. 
As for me it makes sense if you define container(StackPanel)-related styles first, and then duplicate for specific textblock styles. It will be more flexible in this way.

> because the styles are not the same like described here

Not sure if I understand what exactly wrong.

> class is nearest to the control like described there

By "nearest" we meant nearest styles collection by going from child to parent direction. Which essentially has the same declaration order. You can simplify it by telling newer or nearer setter overrides the older one.

> I set the desired class manually

Existence of the class doesn't change the priority of styles, it doesn't make sense. But you can arrange your styles in a way so it will work - see my first answer here above.

**Comment by HaSa1002** [comment] 2022-01-20 13:29
> It matters. And it's the reason of current behavior. Blue style is defined after orange.
As for me it makes sense if you define container(StackPanel)-related styles first, and then duplicate for specific textblock styles. It will be more flexible in this way.

Ok. That is practically the answered I feared to get. Let me try to explain why. First of all we use Avalonia in our game. Thus we have a huge number of windows. To ease the production, we want to keep styles separated from the layout/structure. That's why we are making a theme and many classes to give our designer the possibility to customise the style but in a unified way.

> By "nearest" we meant nearest styles collection by going from child to parent direction. Which essentially has the same declaration order. You can simplify it by telling newer or nearer setter overrides the older one.

Yeah this makes total sense, but...

> Existence of the class doesn't change the priority of styles, it doesn't make sense. But you can arrange your styles in a way so it will work - see my first answer here above.

...here is our issue. We cannot rearrange the styles to work in a order so the overwriting works in the way you described. That would defeat the whole point of separating both to ease maintainability. For this purpose it would be benefical if styles that are applied through a class on parents, get overwritten by styles that are applied to a children using a class. Similar to setting local properties on that child control overwrite the style that is set on the parent.

**Comment by maxkatz6** [comment] 2022-05-24 07:31
Closing as "by design". Same as it works in HTML+CSS.
With https://github.com/AvaloniaUI/Avalonia/discussions/7120 done it will be possible to define control theme and use it on specific control. Similarly, how it is in WPF. But with combining with old styles.

**Closed by maxkatz6** 2022-05-24 07:31 UTC
Labels: by-design
