### ISSUE TITLE
Implicit ItemsSource assignment does not work

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#11403] opened 2023-05-16 15:34 UTC
**Describe the bug**
following xaml does not produce the expected result

```xaml
            <ComboBox x:Name="StretchSelector" HorizontalAlignment="Stretch" SelectedIndex="0" Margin="0,0,0,2">
              <collections:ArrayList>
                <Stretch>Uniform</Stretch>
                <Stretch>UniformToFill</Stretch>
                <Stretch>Fill</Stretch>
                <Stretch>None</Stretch>
              </collections:ArrayList>
            </ComboBox>
```

**To Reproduce**

1. Run CommonCatalog
2. Go ViewBox page
3. See error

**Expected behavior**
Items are correctly displayed

**Screenshots**

**Desktop (please complete the following information):**

- OS: any
- Version 11.0.0-preview8 and ef55b065c3119d233acd44e833bbd1c0b7bc9911

**workaround**

```xaml
            <ComboBox x:Name="StretchSelector" HorizontalAlignment="Stretch" SelectedIndex="0" Margin="0,0,0,2">
              <ComboBox.ItemsSource>
                <collections:ArrayList>
                  <Stretch>Uniform</Stretch>
                  <Stretch>UniformToFill</Stretch>
                  <Stretch>Fill</Stretch>
                  <Stretch>None</Stretch>
                </collections:ArrayList>
              </ComboBox.ItemsSource>
            </ComboBox>
```

**Comment by maxkatz6** [comment] 2023-05-16 20:29
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/10937

**Closed by maxkatz6** 2023-05-16 20:29 UTC
Labels: bug
