### ISSUE TITLE
NumericUpDown ValueChanged

### ISSUE THREAD

**Issue by highstars-gxx** [AvaloniaUI/Avalonia#17435] opened 2024-11-05 09:02 UTC
### Describe the bug

 axaml:
NumericUpDown ValueChanged="NumericUpDown_ValueChanged" Value="{Binding SetPointNumber, Mode=TwoWay}"  

"NumericUpDown_ValueChanged" is excuted before SetPointNumber set  when SetPointNumber value changes

### To Reproduce

Bind a property, register an event, change the value

### Expected behavior

"NumericUpDown_ValueChanged" is excuted after SetPointNumber set  when SetPointNumber value changes

### Avalonia version

11.10

### OS

Windows

**Comment by IanRawley** [comment] 2024-11-05 19:51
The ValueChanged event is the Value stored in the control, and no assumptions can be made about the existence of a binding to Value at all.  I don't think there's a practical way to defer the event firing until after Bindings have updated given that in practice the Control is completely unaware they exist, and that quite possibly the Bindings themselves are using the event to do their work.

**Comment by highstars-gxx** [comment] 2024-11-06 05:35
Why can the TextChanged event of Textbox be used? Can you refer to it and make some adjustments? I would appreciate any help.

**Comment by timunie** [comment] 2024-11-06 20:53
@highstars-gxx can you please explain what exactly you want to achieve? It's hard for me to understand where the bug should be tbh

**Comment by highstars-gxx** [comment] 2024-11-07 01:48
I want to implement a function to divide numbers evenly, and divide them evenly automatically as the number of points changes.So I bind a denominator(SetPointNumber) and an average function("NumericUpDown_ValueChanged") to automatically average when the denominator changes.But the average result each time is the value of the previous time.

**Comment by timunie** [comment] 2024-11-07 06:52
This is imo a task for your ViewModel. This can calculate and update the value as needed.

**Comment by highstars-gxx** [comment] 2024-11-07 07:20
It's ValueChanged, not ValueChanging or before changed.So I think it would be better if the value is updated before the event is triggered.

**Comment by timunie** [comment] 2024-11-07 18:55
I still don't get it tbh. Please file a very minimal sample for me to understand what the issue is.

**Comment by IanRawley** [comment] 2024-11-07 19:45
> It's ValueChanged, not ValueChanging or before changed.So I think it would be better if the value is updated before the event is triggered.

The Value has changed.  The Value property on the NumericUpDown.  SetPointNumber hasn't been updated yet because it responds to the same event you do, ValueChanged.

**Comment by timunie** [comment] 2024-11-09 14:49
@highstars-gxx I really think you want to handle new numbers either only in your ViewModel or in the ValueChanged event but then by using the event args. 

I also honestly don't see a bug here, so will close this as by design until we get a minimum sample to reproduce.

**Closed** 2024-11-09 14:49 UTC
Labels: question, by-design
