### ISSUE TITLE
Window with ExtendClientAreaToDecorationsHint="True" cannot be moved in 0.10.5

### ISSUE THREAD

**Issue by Outreaver** [AvaloniaUI/Avalonia#5977] opened 2021-05-25 20:03 UTC
**Describe the bug**
In version 0.10.3 moving window with flag ExtendClientAreaToDecorationsHint = "True" worked fine. I also checked version 0.10.4 and there it works too. After upgrading package to version 0.10.5 window is stuck in place and cannot be moved. 

**To Reproduce**
1. Create avalonia project (mine is creating in vesrion 0.10.3 by default and im and creating MVVM template).
2. Upgrade Avalonia packages to version 0.10.5 (Avalonia, Avalonia.Desktop, Avalonia.Diagnostics, Avalonia.ReactiveUI).
3. In MainWindow.axaml add flag `ExtendClientAreaToDecorationsHint="True"` in Window tag.
Xaml is looking like this
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:AvaloniaMoveTest.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaMoveTest.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="AvaloniaMoveTest"
	ExtendClientAreaToDecorationsHint="True">

    <Design.DataContext>
        <vm:MainWindowViewModel/>
    </Design.DataContext>

    <TextBlock Text="{Binding Greeting}" HorizontalAlignment="Center" VerticalAlignment="Center"/>

</Window>
```
4. Build project and run.
5. Window cannot be moved.

**Expected behavior**
Should be possible to move window with mouse.

**Desktop (please complete the following information):**
- OS: Window
- Version: 20H2 (19042.985)

**Comment by MiguelGuthridge** [comment] 2021-05-26 10:20
This issue is actually to do with using `ExtendClientAreaToDecorationsHint="True"` and `CanResize="False"` in the same window.

**Comment by piksel** [comment] 2021-05-26 13:07
@MiguelGuthridge that's not in the repro above, and adding `CanResize="True"` does not change anything when I test locally. But if it works for you when you remove it perhaps that is some insight into what is going on...

**Comment by piksel** [comment] 2021-05-26 14:05
#5923 seems to be the cause. Reverted it locally and built against and it successfully restored window movement.
There are comments made after the merge, so maybe they already figured out the problem... I am not familiar enough with the internals to say exactly how it should be fixed.

**Comment by maxkatz6** [comment] 2021-05-26 14:10
Most likely fixed by https://github.com/AvaloniaUI/Avalonia/pull/5968

**Comment by piksel** [comment] 2021-06-06 15:24
Confirmed as fixed in 0.10.6, closeable?

**Comment by aggieben** [comment] 2022-05-01 23:26
I have this problem in 0.10.13, following the music store tutorial.

**Comment by sergevm** [comment] 2022-06-12 13:47
Similar problem in 0.10.14. In some areas of the window top, I can grab the window and move it, in other areas I cannot.

**Comment by maxkatz6** [comment] 2022-06-12 16:35
Please open a new issue with details

**Comment by KillyMXI** [comment] 2022-09-02 20:24
I was also affected by the issue in 0.10.18.
Adding margin to the root control helped to restore the draggable header.

Is it so by design now?
Documentation should probably be updated to explain this caveat.
How should I go about adding non-interactive elements to the header area without affecting the window draggability?

**Comment by lazzy07** [comment] 2022-09-11 07:46
I have a dropdown menu on top of the screen (menubar), so I did it like this. The idea is that the menu items will still be visible at the hit test. and the area next to the menubar isn't, the same way the Visual Studio menubar works.

```xml
<Grid>
    <Grid.RowDefinitions>
      <RowDefinition Height="Auto"></RowDefinition>
      <RowDefinition Height="*"></RowDefinition>
    </Grid.RowDefinitions>
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="Auto"></ColumnDefinition>
      <ColumnDefinition Width="*"></ColumnDefinition>
    </Grid.ColumnDefinitions>

    <Menu Grid.Row="0" Grid.Column="0" Margin="0 8" IsHitTestVisible="True">
      <common:MatMenuItem>
      </common:MatMenuItem>
    </Menu>

    <Grid Grid.Row="0" Grid.Column="1" IsHitTestVisible="False">
    </Grid>
  </Grid>
```

**Comment by CHMarvin** [comment] 2022-09-20 14:34
Still not working

**Comment by timunie** [comment] 2022-09-22 07:51
@CHMarvin maybe you may want to take a look into FluentAvalonia's Core window.

**Comment by xleon** [comment] 2022-11-16 00:56
I can move it by manually adding a view with `IsHitTestVisible="False"` at the top. Is this by design or a bug?

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:views="clr-namespace:PlayAvalonia.Views"
        mc:Ignorable="d" 
        d:DesignWidth="500" 
        d:DesignHeight="750"
        Width="900"
        Height="750"
        x:Class="PlayAvalonia.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="PlayAvalonia"
        TransparencyLevelHint="AcrylicBlur"
        Background="Transparent"
        ExtendClientAreaToDecorationsHint="True">
    
    <Panel>
        <ExperimentalAcrylicBorder IsHitTestVisible="False">
            <ExperimentalAcrylicBorder.Material>
                <ExperimentalAcrylicMaterial
                    BackgroundSource="Digger"
                    TintColor="Black"
                    TintOpacity="1"
                    MaterialOpacity="0.7" />
            </ExperimentalAcrylicBorder.Material>
        </ExperimentalAcrylicBorder>
        
        <Grid RowDefinitions="Auto,*">
            <Border Height="30" IsHitTestVisible="False"/>
            <views:MainView Grid.Row="1"/>
        </Grid>
    </Panel>
</Window>
```

**Comment by maxkatz6** [comment] 2023-01-25 06:22
I am closing this issue, assuming previous reports weren't setting IsHitTestVisible to false.
Let me know if there is another bug.

**Closed by maxkatz6** 2023-01-25 06:22 UTC
Labels: bug, help-wanted

**Comment by RayKoopa** [comment] 2023-04-02 18:43
I'm still a little confused, IsHitTestVisible works different than in the WPF window chrome component.
- To whom is "the hit test visible"? To Avalonia to get control events, or to the DWM to control the window chrome?
- From which "direction" does the pointer stop checking for IsHitTestVisible? From the root control or from the top most control it clicked at?

I have a DockPanel as a title bar container whose last child is a Border with a non-transparent brush and IsHitTestVisible="False" and nothing above it, yet I can't move the window through it.

**Comment by phillip-haydon** [comment] 2023-04-21 10:11
I can't get this to work at all :(

**Comment by nameofSEOKWONHONG** [comment] 2023-07-05 13:33
It still doesn't work on v11. 
However, it works with a bit of tricks.

```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        TransparencyLevelHint="AcrylicBlur"
        Background="Transparent"
        ExtendClientAreaToDecorationsHint="True"
        ExtendClientAreaTitleBarHeightHint="40"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication2.MainWindow"
        Title="AvaloniaApplication2">
    <Panel>
        <ExperimentalAcrylicBorder IsHitTestVisible="False">
            <ExperimentalAcrylicBorder.Material>
                <ExperimentalAcrylicMaterial
                    BackgroundSource="Digger"
                    TintColor="Black"
                    TintOpacity="1"
                    MaterialOpacity="0.65" />
            </ExperimentalAcrylicBorder.Material>
        </ExperimentalAcrylicBorder>
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="20"/>
                <RowDefinition Height="30"/>
                <RowDefinition Height="*"/>
                <RowDefinition Height="*"/>
            </Grid.RowDefinitions>
            <DockPanel Grid.Row="1">
                <Menu DockPanel.Dock="Top">
                    <MenuItem Header="_File">
                        <MenuItem Header="_Open..."/>
                        <Separator/>
                        <MenuItem Header="_Exit"/>
                    </MenuItem>
                    <MenuItem Header="_Edit">
                        <MenuItem Header="Copy"/>
                        <MenuItem Header="Paste"/>
                    </MenuItem>
                </Menu>
                <TextBlock/>
            </DockPanel>
            <StackPanel Grid.Row="2" Margin="40">
                <Button>Press Me!</Button>
                <TextBlock Margin="0 10">Ready...</TextBlock>
            </StackPanel>
            <StackPanel Grid.Row="3" Margin="40">
                <Button>Press Me!</Button>
                <TextBlock Margin="0 10">Ready...</TextBlock>
            </StackPanel>            
        </Grid>
    </Panel>
</Window>
```

**Comment by Eskeminha** [comment] 2024-01-19 22:17
Easiest workaround: on the top Container of the view, like the <Panel> of the example above, just add Margin. 

Example:
`<Panel Margin="10">`

That will give you space to drag around.

**Comment by andrey-kondratov** [comment] 2024-11-03 15:49
Just make sure your top component (a Menu) does not occupy the entire width by putting it into an auto-sized column.

Example for a 2x2 grid:
```xaml
<Window xmlns="https://github.com/avaloniaui"
        ExtendClientAreaToDecorationsHint="True">

  <Grid RowDefinitions="Auto, *" ColumnDefinitions="Auto, *">
    <!-- the menu in row=0, column=0, and the rest of the row (column 1) is empty -->
    <Menu>
      <MenuItem Header="_File">
        <MenuItem Header="_Exit" />
      </MenuItem>
    </Menu>

    <!-- all the rows below have columnspan=2 -->
    <views:MainView Grid.Row="1" Grid.ColumnSpan="2" />
  </Grid>
</Window>
```
