### ISSUE TITLE
Ramdom Exception COM Iterop

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#10057] opened 2023-01-23 11:27 UTC
**Describe the bug**
While testing I got in the VS output console following errors but I didn't understand the source they depended on.

```cmd
[Visual]Exception when rendering: 'System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Avalonia.Win32.WinRT.Impl.__MicroComICompositionSurfaceBrushProxy'.
   at MicroCom.Runtime.MicroComProxyBase.get_NativePointer()
   at MicroCom.Runtime.MicroComProxyBase.get_PPV()
   at Avalonia.Win32.WinRT.Impl.__MicroComICompositionSurfaceBrushProxy.SetSurface(ICompositionSurface value) in C:\GitHub\Avalonia\src\Windows\Avalonia.Win32\WinRT\WinRT.Generated.cs:line 6864
   at Avalonia.Win32.WinRT.Composition.WinUiCompositedWindow.SetSurface(ICompositionSurface surface) in C:\GitHub\Avalonia\src\Windows\Avalonia.Win32\WinRT\Composition\WinUiCompositedWindow.cs:line 77
   at Avalonia.Win32.WinRT.Composition.WinUiCompositedWindowRenderTarget.BeginDraw() in C:\GitHub\Avalonia\src\Windows\Avalonia.Win32\WinRT\Composition\WinUiCompositedWindowSurface.cs:line 120
   at Avalonia.Win32.OpenGl.Angle.AngleD3DTextureFeature.RenderTargetWrapper.BeginDrawCore() in C:\GitHub\Avalonia\src\Windows\Avalonia.Win32\OpenGl\Angle\AngleD3DTextureFeature.cs:line 40
   at Avalonia.OpenGL.Egl.EglPlatformSurfaceRenderTargetBase.BeginDraw() in C:\GitHub\Avalonia\src\Avalonia.OpenGL\Egl\EglGlPlatformSurfaceBase.cs:line 30
   at Avalonia.Skia.GlRenderTarget.BeginRenderingSession() in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\Gpu\OpenGl\GlRenderTarget.cs:line 64
   at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer) in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\Gpu\SkiaGpuRenderTarget.cs:line 27
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render() in C:\GitHub\Avalonia\src\Avalonia.Base\Rendering\Composition\Server\ServerCompositionTarget.cs:line 108
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore() in C:\GitHub\Avalonia\src\Avalonia.Base\Rendering\Composition\Server\ServerCompositor.cs:line 169'(ServerCompositor #37472519)

[Visual]Exception when rendering: 'System.Runtime.InteropServices.COMException (0x80070057): CreateDesktopWindowTarget failed
   at Avalonia.Win32.WinRT.Impl.__MicroComICompositorDesktopInteropProxy.CreateDesktopWindowTarget(IntPtr hwndTarget, Int32 isTopmost) in C:\GitHub\Avalonia\src\Windows\Avalonia.Win32\WinRT\WinRT.Generated.cs:line 5946
   at Avalonia.Win32.WinRT.Composition.WinUiCompositedWindow..ctor(IEglWindowGlPlatformSurfaceInfo info, WinUiCompositionShared shared, Nullable`1 backdropCornerRadius) in C:\GitHub\Avalonia\src\Windows\Avalonia.Win32\WinRT\Composition\WinUiCompositedWindow.cs:line 41
   at Avalonia.Win32.WinRT.Composition.WinUiCompositedWindowSurface.CreateRenderTarget(IPlatformGraphicsContext context, IntPtr d3dDevice) in C:\GitHub\Avalonia\src\Windows\Avalonia.Win32\WinRT\Composition\WinUiCompositedWindowSurface.cs:line 34
   at Avalonia.Win32.OpenGl.Angle.AngleD3DTextureFeature.CreateRenderTarget(IGlContext context, Object surface) in C:\GitHub\Avalonia\src\Windows\Avalonia.Win32\OpenGl\Angle\AngleD3DTextureFeature.cs:line 93
   at Avalonia.Skia.GlSkiaGpu.SurfaceWrapper.CreateGlRenderTarget(IGlContext context) in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\Gpu\OpenGl\GlSkiaGpu.cs:line 56
   at Avalonia.Skia.GlRenderTarget..ctor(GRContext grContext, IGlContext glContext, IGlPlatformSurface glSurface) in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\Gpu\OpenGl\GlRenderTarget.cs:line 21
   at Avalonia.Skia.GlSkiaGpu.TryCreateRenderTarget(IEnumerable`1 surfaces) in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\Gpu\OpenGl\GlSkiaGpu.cs:line 67
   at Avalonia.Skia.SkiaContext.CreateRenderTarget(IEnumerable`1 surfaces) in C:\GitHub\Avalonia\src\Skia\Avalonia.Skia\SkiaBackendContext.cs:line 30
   at Avalonia.Rendering.PlatformRenderInterfaceContextManager.CreateRenderTarget(IEnumerable`1 surfaces) in C:\GitHub\Avalonia\src\Avalonia.Base\Rendering\PlatformRenderInterfaceContextManager.cs:line 66
   at Avalonia.Rendering.Composition.Server.ServerCompositor.CreateRenderTarget(IEnumerable`1 surfaces) in C:\GitHub\Avalonia\src\Avalonia.Base\Rendering\Composition\Server\ServerCompositor.cs:line 196
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render() in C:\GitHub\Avalonia\src\Avalonia.Base\Rendering\Composition\Server\ServerCompositionTarget.cs:line 89
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore() in C:\GitHub\Avalonia\src\Avalonia.Base\Rendering\Composition\Server\ServerCompositor.cs:line 169'(ServerCompositor #30474330)
```

**To Reproduce**

I haven't been able to recognize the schema that throws the exceptions.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 OS: Windows 10 x64 21H2
- Version b7b9a763263e9172f88a91f1e8c364a7040f639a

**Additional context**

**Comment by kekekeks** [comment] 2023-01-23 18:33
Most likely caused by closing a window while something is still being rendered. For some reason we dispose the window and its GPU surfaces before stopping the renderer.

**Comment by MrJul** [comment] 2023-01-23 23:03
Easy repro: open the control catalog systray icon's menu, then click on any option menu item.

**Comment by danipen** [comment] 2023-02-23 12:29
I'm also able to reproduce displaying a modal dialog and just closing it:
```(csharp)
var result = await dialog.ShowDialog<DialogResult>(parentWindow);
```

**Comment by maxkatz6** [comment] 2023-02-24 03:33
Renderer Thread:
```
	WinUiCompositedWindow.SetSurface() at C:\Work\Projects\Avalonia\src\Windows\Avalonia.Win32\WinRT\Composition\WinUiCompositedWindow.cs:line 81
	WinUiCompositedWindowRenderTarget.BeginDraw() at C:\Work\Projects\Avalonia\src\Windows\Avalonia.Win32\WinRT\Composition\WinUiCompositedWindowSurface.cs:line 121
	AngleD3DTextureFeature.RenderTargetWrapper.BeginDrawCore()
	EglPlatformSurfaceRenderTargetBase.BeginDraw()
	GlRenderTarget.BeginRenderingSession()
	SkiaGpuRenderTarget.CreateDrawingContext()
	ServerCompositionTarget.Render()
	ServerCompositor.RenderCore()
	ServerCompositor.Render()
	RenderLoop.TimerTick()
	WinUiCompositorConnection.RunLoopHandler.Invoke()
	__MicroComIAsyncActionCompletedHandlerVTable.Invoke()
	[Managed to Native Transition]
	WinUiCompositorConnection.RunLoop()
	WinUiCompositorConnection.<>c__DisplayClass7_0.<TryCreateAndRegisterCore>b__0()
	Thread.StartCallback()
	[Native to Managed Transition]
```

Main Thread
```
	Dictionary<RoutedEvent, List<Interactive.EventSubscription>>.FindValue()
	Dictionary<__Canon, __Canon>.TryGetValue()
	Interactive.AddToEventRoute()
	Interactive.BuildEventRoute()
	Interactive.RaiseEvent() [2]
	PointerOverPreProcessor.ClearPointerOver()
	PointerOverPreProcessor.ClearPointerOver()
	PointerOverPreProcessor.OnCompleted()
	TopLevel.HandleClosed()
	WindowBase.HandleClosed()
	WindowImpl.AppWndProc() [2]
	WindowImpl.WndProc() [2]
	PopupImpl.WndProc() [2]
	[Managed to Native Transition]
	WindowImpl.Dispose()
	Window.CloseInternal()
	Window.CloseCore()
	Window.Close()
	TrayIconImpl.TrayIconMenuFlyoutPresenter.Close()
	DefaultMenuInteractionHandler.CloseMenu()
	DefaultMenuInteractionHandler.Click()
	DefaultMenuInteractionHandler.PointerReleased()
	Interactive.<AddHandler>g__InvokeAdapter|4_0<Avalonia.Input.PointerReleasedEventArgs>()
	Interactive.<>c__4<PointerReleasedEventArgs>.<AddHandler>b__4_1()
	EventRoute.RaiseEventImpl()
	EventRoute.RaiseEvent()
	Interactive.RaiseEvent() [1]
	MouseDevice.MouseUp()
	MouseDevice.ProcessRawEvent()
	MouseDevice.ProcessRawEvent()
	InputManager.ProcessInput()
	TopLevel.HandleInput()
	WindowImpl.AppWndProc() [1]
	WindowImpl.WndProc() [1]
	PopupImpl.WndProc() [1]
	[Managed to Native Transition]
	Win32Platform.RunLoop()
	Dispatcher.MainLoop()
	ClassicDesktopStyleApplicationLifetime.Start()
	ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime()
	Program.Main()
```

> For some reason we dispose the window and its GPU surfaces before stopping the renderer.

`TopLevel.HandleClosed()` properly calls `Renderer.Dispose()`. Which disposes internal CompositionTarget, so everything should work good.
Unless there is a missing lock somewhere, but I am missing to find out where it even supposed to be.

**Comment by batzen** [comment] 2023-03-11 14:45
In my case it's enough to have the following inside a window.
```
    <StackPanel ToolTip.Tip="asödlfkjasdölfkjasöldkfjölkasjdf"
                ToolTip.Placement="Top"
                Margin="10">
        <Button>
            Welcome to Avalonia!
        </Button>
    </StackPanel>
```

It seems to be related to the placement und the control being at the top of the window.
Maybe the attached project helps to repro.
[AvaloniaTests.zip](https://github.com/AvaloniaUI/Avalonia/files/10948729/AvaloniaTests.zip)

**Closed** 2023-04-09 02:01 UTC
Labels: bug, os-windows

**Comment by tkefauver** [comment] 2024-01-02 14:20
@kekekeks I still get this exception randomly. Is it only a debug issue?

**Comment by timunie** [comment] 2024-01-02 20:26
@tkefauver if you can reproduce using 11.0 please try to create a minimal sample and open a new issue.

**Comment by tkefauver** [comment] 2024-01-04 14:27
@timunie I wish I could reproduce it but I don't know what causes it, its 'random'. I see [14089](that https://github.com/AvaloniaUI/Avalonia/pull/14089) was closed yesterday hopefully that fixes it. Will have see...

**Comment by timunie** [comment] 2024-01-04 14:29
you can also test nightly in that case and observe if it breaks again.

**Comment by tkefauver** [comment] 2024-01-13 13:59
@timunie I tested a nightly (11.1.999-cibuild0043318-beta) all week and it didn't hang at all from this exception so that's good :)
