### ISSUE TITLE
Incorrect visibility in listboxitem

### ISSUE THREAD

**Issue by MonkAlex** [AvaloniaUI/Avalonia#2237] opened 2019-01-10 14:34 UTC
Has this code from 0.6.1 (in this version work fine)
```
  <ListBox>
    <ListBox.Items>
      <Button Background="Red" Width="20" Height="20"/>
      <Button Background="Red" Width="20" Height="20"/>
      <Button Background="Red" Width="20" Height="20" IsVisible="False"/>
    </ListBox.Items>
    <ListBox.ItemsPanel>
      <ItemsPanelTemplate>
        <WrapPanel/>
      </ItemsPanelTemplate>
    </ListBox.ItemsPanel>
  </ListBox>
```

In 0.7 last button collapsed, but has gray color on mouseover (or keyboard left-right selection):
![default](https://user-images.githubusercontent.com/6784764/50974968-d8ede580-1505-11e9-87d9-1e75371877bc.png)
And this collapsed control can be selected:
![default](https://user-images.githubusercontent.com/6784764/50974994-e5723e00-1505-11e9-8d3b-1899b24a6490.png)

In wpf mouseover work fine, but selection fail too:
![default](https://user-images.githubusercontent.com/6784764/50975060-0fc3fb80-1506-11e9-8bb8-bdaddd3a29ff.png)

UPD: without overriding `itemspaneltemplate` selection smaller, but has too.

**Comment by grokys** [comment] 2019-01-16 12:03
Hi @MonkAlex,

I think the problem here is that items in a `ListBox` are wrapped in a `ListBoxItem`, so even if you're making the `Button` invisible the containing `ListBoxItem` is still visible.

You could use a style to hide the `ListBoxItem`, but this might have strange interactions with virtualization. I would recommend just filtering out the invisible items at the view model layer.

As you've seen, this is also the same in WPF (and UWP) so I think this behavior is by design. Because of this I'm going to close this issue - if you think there really is a bug let me know and I can reopen.

**Closed by grokys** 2019-01-16 12:03 UTC

**Comment by grokys** [comment] 2019-01-16 21:50
If you want to hide a `ListBoxItem` based on a binding you need to apply the binding in a style, like this:

```csharp
      <ListBox Items="{Binding Items}">
          <ListBox.Styles>
              <Style Selector="ListBoxItem">
                  <Setter Property="IsVisible" Value="{Binding IsVisible}"/>
              </Style>
          </ListBox.Styles>
      </ListBox>
```
