### ISSUE TITLE
Using DataGrid.SelectedItems results in an System.ArgumentException: The item is not contained in the ItemsSource. (Parameter 'dataItem')

### ISSUE THREAD

**Issue by Oleg-Olegovich** [AvaloniaUI/Avalonia#10940] opened 2023-04-07 00:32 UTC
I'm trying to use multiple selection in a DataGrid. When trying to bind the SelectedItems property to a collection, an exception is thrown in line 73 of the DataGridSelectedItemsCollection class. For some reason, the Add method is called with Binding as an argument. I have tried different binding modes, different types of collection, etc.
Is this a bug?

` <DataGrid SelectionMode="Extended"
                    Items="{Binding Items}"
                    SelectedItems="{Binding SelectedItems"/>`

**Comment by maxkatz6** [comment] 2023-04-07 00:46
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2890

**Closed by maxkatz6** 2023-04-07 00:46 UTC
Labels: bug
