### ISSUE TITLE
Using ContentAlignment style in Application.Styles changes text formatting for NumericUpDown

### ISSUE THREAD

**Issue by tobyfirth** [AvaloniaUI/Avalonia#12810] opened 2023-09-07 08:46 UTC
**Describe the bug**
Styling one of the ContentAlignment properties for a NumericUpDown in App.xml causes the displayed number formatting to not use the format for the current culture. This means that instead of showing '1,0' with the current culture set to fr-FR, the number is shown as '1.0' which matches the culture of the machine.

**To Reproduce**
1. Start a new project.
2. In App.axml add this style:
```xaml
<Style Selector="NumericUpDown">
    <Setter Property="HorizontalContentAlignment" Value="Center"/>
</Style>
```
3. In MainView.axml replace the TextBlock with:
```xaml
<NumericUpDown Value="1.0"  HorizontalAlignment="Center" VerticalAlignment="Center"/>
```
4. In App.axml.cs put this line in the OnFrameworkInitializationCompleted function. Possibly just needs to be a culture that uses a different number format to the  default culture.
```csharp
CultureInfo.CurrentCulture = new CultureInfo("fr-FR");
```

**Expected behavior**
When using 'fr-FR' as the culture the number '1.0' would be displayed as '1,0'.

**Desktop (please complete the following information):**
- OS: Windows
- Version: 11.0.4

**Additional context**
 If the style is moved to MainWindow.axml or MainView.axml, the number is shown with the expected formatting.

**Comment by maxkatz6** [comment] 2023-09-07 13:21
If it's really a bug, it's one of the weirdest so far.

**Comment by timunie** [comment] 2023-09-07 13:44
@tobyfirth please upload a minimal sample to reproduce. In Germany we use same number format and I cannot observe it in my usecase.

**Comment by tobyfirth** [comment] 2023-09-09 11:30
Here is a [minimal sample](https://github.com/tobyfirth/NumericUpDownContentAlignment).

@timunie so even when you change the culture to something like 'en-GB' or 'en-US' the formatting is correctly handled?

**Comment by timunie** [comment] 2023-09-10 15:14
https://github.com/tobyfirth/NumericUpDownContentAlignment/blob/master/NumericUpDownContentAlignment/App.axaml.cs#L20

Can you try CurrentUiCulture? Iirc there's a difference in behavior for both of them.

**Comment by tobyfirth** [comment] 2023-09-11 07:29
CurrentUICulture does not seem to do anything. The number is still formatted as a '1.0'.

In fact, when removing the styling the format does not change when using CurrentUICulture  but it does with CurrentCulture.

**Comment by timunie** [comment] 2023-09-11 07:58
If I set it before any XAMl is loaded, it still works for me: 

```diff
public override void Initialize()
{
+   CultureInfo.CurrentCulture = new CultureInfo("en-US");
    AvaloniaXamlLoader.Load(this);
}
```

if you need to change it dynamically, set `NumberFormat` explicitly. You can even bind that. 
```xml
<NumericUpDown NumberFormat="{Binding NumberFormat}" Value="1.0"  HorizontalAlignment="Center" VerticalAlignment="Center"/>
```

**Comment by tobyfirth** [comment] 2023-09-11 08:42
If I have either of the ContentAlignment styled from App.axml it does not seem to matter where I set the CurrentCulture it always seems to use '1.0'.

If I put the styling anywhere else then the number formatting changes just fine.

I worked around this issue in the application where I discovered this by just moving the styling to MainWindow.axml which allowed me to just change CurrentCulture.

**Comment by timunie** [comment] 2023-09-11 09:04
What happens here is that once you set a style for the control, the property will be evaluated. If that happens in App.axaml before culture changed, you see the result. If that happens after culture changed, it works well. Does it make any sense to you? 

Note: I'll close this as by design. You now have at least two options to make it work as you need it to work. If you disagree, let me know the reasons.

**Closed** 2023-09-11 09:04 UTC
Labels: by-design

**Comment by tobyfirth** [comment] 2023-09-11 09:35
Ok. That makes sense. I just tried with culture being set in Main and the formatting worked as expected.

Thank you for your time.
