### ISSUE TITLE
When maximized, the left most menu item will open on the left monitor when using a dual monitor setup

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#7342] opened 2022-01-11 12:37 UTC
**Describe the bug**
When the window is maximized, the left most menu item will open on the left monitor when using a dual monitor setup.
The second menu item have the correct behaviour.
If not maximized it works as expected

**To Reproduce**
1. Place the window on second screen and maximize the window
2. Click on first item

**Expected behavior**
The menu to open on same screen

**Screenshots**
![image](https://user-images.githubusercontent.com/113281/148943614-74a529aa-5a7e-41c1-87f0-bd9de658446d.png)
![image](https://user-images.githubusercontent.com/113281/148943643-c76805db-c0b8-4b8e-b486-8ff02f079825.png)

**Desktop (please complete the following information):**

- Operative system: Microsoft Windows 11 X64
- Runtime: win10-x64
- Framework: .NET 5.0.13
- AvaloniaUI: 0.10.11

**Additional context**
Resolution seens to doesn't matter, i tried multiple which produce same problem

**Comment by Sorien** [comment] 2022-01-11 14:16
i looks like same problem as https://github.com/AvaloniaUI/Avalonia/issues/7164

**Comment by grokys** [comment] 2022-01-11 16:03
Yep, closing as a duplicate of #7164 - there's a PR which should fix this in the queue as well - #7165 - just need to get time to review it.

**Closed by grokys** 2022-01-11 16:03 UTC
Labels: bug
