### ISSUE TITLE
Reveal Password Button - Visual Bug

### ISSUE THREAD

**Issue by eXmatrx** [AvaloniaUI/Avalonia#9302] opened 2022-10-28 11:38 UTC
**Describe the bug**
So basically the background of the reveal button doesn't not fit the radius property of the textbox when clicked.

**To Reproduce**

1. Create a basic avalonia project
2. Add a textbox
3. Set the corner radius to like 13, and set the password char to like '*'
4. Run the program
5. Click on the reveal password button
6. Notice the issue

**Expected behavior**
The reveal button background should be rounded as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/114802572/198577987-abd59134-9412-495c-97c5-cfe0b27d425d.png)

**Desktop (please complete the following information):**
- OS: Windows 11
- Version: 0.10.18

**Comment by timunie** [comment] 2022-10-28 12:53
I think this `ToggleButton` is missing `ClipToBounds`: 

https://github.com/AvaloniaUI/Avalonia/blob/7278dce4e24c7fb40f143faaec2d9db8c00c774b/src/Avalonia.Themes.Fluent/Controls/TextBox.xaml#L236-L246

https://github.com/AvaloniaUI/Avalonia/blob/7278dce4e24c7fb40f143faaec2d9db8c00c774b/src/Avalonia.Themes.Simple/Controls/TextBox.xaml#L212-L215

If you want to fix this, feel free to provide a PR to do so. 

Please note, clipping for corner radius does not work in v11.0 atm. So don't worry if the issue is not fixed immediately.

**Comment by eXmatrx** [comment] 2022-10-29 11:39
> I think this `ToggleButton` is missing `ClipToBounds`:
> 
> https://github.com/AvaloniaUI/Avalonia/blob/7278dce4e24c7fb40f143faaec2d9db8c00c774b/src/Avalonia.Themes.Fluent/Controls/TextBox.xaml#L236-L246
> 
> https://github.com/AvaloniaUI/Avalonia/blob/7278dce4e24c7fb40f143faaec2d9db8c00c774b/src/Avalonia.Themes.Simple/Controls/TextBox.xaml#L212-L215
> 
> If you want to fix this, feel free to provide a PR to do so.
> 
> Please note, clipping for corner radius does not work in v11.0 atm. So don't worry if the issue is not fixed immediately.

Alright thanks man for answering! I will just reduce the corner radius, it's not a big deal!

**Comment by timunie** [comment] 2022-10-29 11:44
I still consider it a bug which should be fixed. If you want to support us, your contribution is welcome but I fully understand if you have no time to do. Anyway I will reopen the issue.

**Closed** 2022-11-09 18:01 UTC
Labels: bug
