### ISSUE TITLE
OSX Popup Positioning not working

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#2962] opened 2019-09-10 16:52 UTC
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/4672627/64633911-fb693300-d3f3-11e9-9cb7-d6277c8358ee.png">

**Comment by x2bool** [comment] 2019-09-10 17:11
Related: https://github.com/AvaloniaUI/Avalonia/issues/2923

**Comment by grokys** [comment] 2019-09-11 09:07
Closing as duplicate of #2923

**Closed by grokys** 2019-09-11 09:07 UTC
