### ISSUE TITLE
Coded UI Tests

### ISSUE THREAD

**Issue by stef25761** [AvaloniaUI/Avalonia#4712] opened 2020-09-22 08:30 UTC
Hey folk. I have question about coded ui test. Is it possible with current frameworks like Selenium and WinAppDriver to test the UI of Avalonia via Pipeline? I look up my application with snoop and uiverify from win10 and cant find anything about my application.

**Comment by maxkatz6** [comment] 2022-05-26 00:10
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2157

**Closed by maxkatz6** 2022-05-26 00:10 UTC
