### ISSUE TITLE
Gtk errors and warnings

### ISSUE THREAD

**Issue by lontivero** [AvaloniaUI/Avalonia#1800] opened 2018-08-06 17:53 UTC
Our application writes some error messages in the console when it starts. This is not a blocker given that the application works properly anyway, however it seems that something wrong happens.

```
(dotnet:16553): Gtk-CRITICAL **: 21:04:19.624: gtk_application_new: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed
(dotnet:16553): GLib-GObject-CRITICAL **: 21:05:29.866: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed

(dotnet:16553): GLib-GObject-WARNING **: 21:05:29.866: instance with invalid (NULL) class pointer

(dotnet:16553): GLib-GObject-CRITICAL **: 21:05:29.866: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(dotnet:16553): GLib-GObject-WARNING **: 21:05:29.866: instance with invalid (NULL) class pointer

(dotnet:16553): GLib-GObject-CRITICAL **: 21:05:29.867: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

This happens in my machine:

### Ubuntu Version
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

### Gtk Version
```
$ apt-cache policy libgtk2.0-0 libgtk-3-0 | grep Installed
Installed: 2.24.32-1ubuntu1
Installed: 3.22.30-1ubuntu1
```

### Avalonia Version
```
Avalonia Version 0.6.2-build5800-beta
```

### How to reproduce it
1. git clone https://github.com/zkSNACKs/WalletWasabi --recursive
2. cd WalletWasabi/WalletWasabi.Gui
3. dotnet run

**Comment by nopara73** [comment] 2018-08-06 18:33
@lontivero Can you create a small Avalonia project that reproduces it, so that'd be more convenient for the maintainers?

**Comment by danwalmsley** [comment] 2018-08-20 16:57
Application id is that avalonia uses guid tostring and - are not allowed.

**Comment by qcmiao1998** [comment] 2018-08-29 09:38
I meet the same problem on Ubuntu18.04

**Comment by worldbeater** [comment] 2018-10-21 16:40
+1 but this is really not critical, the app works fine :)

**Comment by nopara73** [comment] 2018-10-23 14:41
I'd like to note a few things. First, this issue can be divided into two issues: warnings at start and warnings at shutdown. This warning comes when we start our app:

```sh
(dotnet:5402): GLib-GObject-CRITICAL **: 10:38:21.356: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
```

And these warnings come when we shut it down:
```sh
(dotnet:5402): GLib-GObject-WARNING **: 10:38:21.356: instance with invalid (NULL) class pointer

(dotnet:5402): GLib-GObject-CRITICAL **: 10:38:21.356: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(dotnet:5402): GLib-GObject-WARNING **: 10:38:21.356: instance with invalid (NULL) class pointer

(dotnet:5402): GLib-GObject-CRITICAL **: 10:38:21.356: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

About the startup issue. It should be something easy to resolve, unfortunately I wasn't able to play around with it.

> (dotnet:5402): Gtk-CRITICAL **: 10:37:30.124: gtk_application_new: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed

I think this fails here:

https://github.com/AvaloniaUI/Avalonia/blob/a184e27062101df3a4142a74c90f499eb419b86a/src/Gtk/Avalonia.Gtk3/Gtk3Platform.cs#L69-L70

This results in an id, like this: `avalonia.app.663e85f6-efe1-4552-ab1f-de9c8de0933f`.  
However I find it strange, because according to the [gtk reference](https://developer.gnome.org/gio//2.44/GApplication.html#g-application-id-is-valid) it should be a valid id. Unless I'm missing something.

Further reading: https://stackoverflow.com/a/16894116/2061103

**Comment by danwalmsley** [comment] 2018-10-23 15:05
its not a valid id because each part after the - must begin with a letter.

**Comment by danwalmsley** [comment] 2018-10-23 15:05
@kekekeks lets try and get a fix for this into 0.7

**Comment by nopara73** [comment] 2018-10-23 15:51
@kekekeks @danwalmsley Hold on. Application id should get a null, instead of being fixed.  

> Another feature that GApplication (optionally) provides is process uniqueness. Applications can make use of this functionality by providing a unique application ID. If given, only one application with this ID can be running at a time per session.

https://developer.gnome.org/gio/stable/GApplication.html

So, being it fixed would ultimately result in not being able to run multiple Avalonia apps the same time:)

**Comment by kekekeks** [comment] 2018-10-24 07:18
We should probably pass NULL there, but removing dashes also works.

We are planning to remove GTK backend in 0.8 anyway, so the rest of the warnings will go away.

**Comment by kekekeks** [comment] 2020-02-09 11:11
GTK backend is discontinued

**Closed by kekekeks** 2020-02-09 11:11 UTC
Labels: bug, gtk3
