### ISSUE TITLE
Preview crashes when using behaviors

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#7180] opened 2021-12-17 01:27 UTC
**Describe the bug**
Preview window crashes when using behaviors. Tested in both JetBrains Rider and Visual Studio 2022 and got the same crash.

> Unable to resolve type Interaction from namespace https://github.com/avaloniaui

**To Reproduce**
The Preview stops working when I add a behavior such as this. The application runs fine though.

    <TextBlock Text="{Binding Name}">
        <Interaction.Behaviors>
            <EventTriggerBehavior EventName="DoubleTapped">
                <InvokeCommandAction
                    Command="{Binding ViewModel.PlayListCommand, RelativeSource={RelativeSource AncestorType={x:Type Window}}}" />
            </EventTriggerBehavior>
        </Interaction.Behaviors>
    </TextBlock>

**Expected behavior**
The preview should work.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 0.10.10

**Comment by maxkatz6** [comment] 2021-12-17 01:51
because EventTriggerBehavior is not part of avalonia namespace.
Go to AvaloniaBehaviors repository and check what exact namespaces you should to include in your file.

**Comment by maxkatz6** [comment] 2021-12-17 01:56
Although AvaloniaBehaviors tries to fit into the same avalonia namespace: https://github.com/wieslawsoltes/AvaloniaBehaviors/blob/master/src/Avalonia.Xaml.Interactions/Properties/AssemblyInfo.cs
That's why it compiles, but doesn't work in previewer.
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/6481

**Closed by maxkatz6** 2021-12-17 01:56 UTC

**Comment by mysteryx93** [comment] 2021-12-17 04:53
Alright if I do it according to this syntax, then it works
https://github.com/wieslawsoltes/AvaloniaBehaviors/wiki
