### ISSUE TITLE
Avalonia不支持Net9吗？

### ISSUE THREAD

**Issue by Ultramund1** [AvaloniaUI/Avalonia#17503] opened 2024-11-14 03:00 UTC
### Describe the bug

前天，Net9正式版发布了，我将我的项目升级到Net9，发现browser不能运行。于是我用官方模板新建一个跨平台项目，一句代码也没写，运行browser，出现一样的错误如下：
CompileError: WebAssembly.compileStreaming(): Compiling function #18478:"mono_ppdb_load_file" failed: expected 0 elements on the stack for fallthru, found 4 @+7128821

Stack错误
>	reject [_framework/https:/raw.githubusercontent.com/dotnet/runtime/9d5a6a9aa463d6d10b0b0ba6d5982cc82f363dc3/src/mono/browser/runtime/loader/promise-controller.ts] Line 30	TypeScript
 	<anonymous> [_framework/https:/raw.githubusercontent.com/dotnet/runtime/9d5a6a9aa463d6d10b0b0ba6d5982cc82f363dc3/src/mono/browser/runtime/loader/exit.ts] Line 238	TypeScript
 	Object.at [_framework/https:/raw.githubusercontent.com/dotnet/runtime/9d5a6a9aa463d6d10b0b0ba6d5982cc82f363dc3/src/mono/browser/runtime/loader/exit.ts] Line 123	TypeScript
 	<anonymous> [_framework/https:/raw.githubusercontent.com/dotnet/runtime/9d5a6a9aa463d6d10b0b0ba6d5982cc82f363dc3/src/mono/browser/runtime/startup.ts] Line 509	TypeScript

### To Reproduce

每次必现，新建一个项目，Browser直接就不能运行

### Avalonia version

11.2

### OS

Windows

**Comment by maxkatz6** [comment] 2024-11-14 04:57
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/17416

**Closed by maxkatz6** 2024-11-14 04:57 UTC
Labels: bug

**Comment by Ultramund1** [comment] 2024-11-14 05:12
跟#17416不是一样的啊，我新建一个项目，选net8，Browser运行没任何问题！！！，但选net9，Browser就运行出错，Avalonia 11.1，11.2都是一样的错误

**Comment by Ultramund1** [comment] 2024-11-14 05:26
仅仅新建一个项目，运行

**Comment by Ultramund1** [comment] 2024-11-14 05:29
![1](https://github.com/user-attachments/assets/28f2c2b8-6953-4803-872e-4fae25f45e06)
