### ISSUE TITLE
Memory leak when resizing windows

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#3983] opened 2020-05-24 17:05 UTC

**Comment by FrankenApps** [comment] 2020-08-11 18:30
Hi, is there any update on this? 
My simple window with no logic at all went from ~150 MB in idle (which is still more 3x what a comparable Electron project uses), to ~ 450 MB after resizing.
A simple window in 0.9.x used ~ 16MB on my system for comparison, which I think is great. However the memory usage in the previews is clearly unacceptable...

I am on Win10 btw.

**Comment by grokys** [comment] 2020-08-11 21:06
@kekekeks @MarchingCube I believe you did some investigation into what's happening here? What were the findings?

@FrankenApps are you on Windows with Visual Studio? Can use use the VS diagnostic tools to tell us how much of that memory is managed memory?

**Comment by MarchingCube** [comment] 2020-08-12 08:15
@grokys My finding was that it was mostly GPU memory that was committed but not used. I couldn't find anything in regular RAM that was causing this. Might need a debug build of Skia to investigate further as D2D does not have this issue.

**Comment by worldbeater** [comment] 2020-08-12 09:14
Not sure if this is related, but we are experiencing performance degradation as well after switching from 0.9.* to 0.10.0-preview* on Ubuntu KDE machines, as stated in https://github.com/AvaloniaUI/AvaloniaEdit/issues/104#issue-665809196 and https://github.com/AvaloniaUI/AvaloniaEdit/issues/104#issuecomment-665136938

**Comment by FrankenApps** [comment] 2020-08-12 10:12
@grokys I am not sure if that is what you meant, but I collected these snapshots before and after resizing. But there is a weird spike in memory usage shortly before the Window is displayed, too.
![memory_profile](https://user-images.githubusercontent.com/17967303/90003719-c49b3d00-dc94-11ea-90a0-33b51a2fde95.png)
So according to the profiler native heap size only increased by 2.6 MB when resizing...

**Comment by grokys** [comment] 2020-08-12 10:18
Oh interesting, so this looks like a different problem to the one we investigated as it seems to be managed memory. That's a lot easier to diagnose.

Could you take a snapshot before and after the spike occurs and do a diff of the objects?

**Comment by FrankenApps** [comment] 2020-08-12 10:29
Well, I do honestly not understand how the numbers should add up...
It seems to me as if the graph shows much higher values, than what I get when taking a snapshot.
Here is the diff:
![managed_heap_diff](https://user-images.githubusercontent.com/17967303/90005442-85222000-dc97-11ea-99e1-606572381d89.PNG)

**Comment by HendrikMennen** [comment] 2020-08-15 18:24
Since 0.1 even scrolling through a file with AvaloniaEdit causes a memory leak. Or moving a GridSplitter.
My app goes from 250mb to 4GB ram usage very fast with normal use.

**Comment by grokys** [comment] 2020-09-02 10:18
@HendrikMennen I'm looking into this and while some of us are able to repro, others (including myself) aren't. What graphics card do you have on the machine where you're seeing this?

**Comment by FrankenApps** [comment] 2020-09-02 11:31
I use a Nvidia GeForce GTX 1060. I am still seeing it with 0.10-preview4, but it is improved, as I do not get above ~350 mb now and the garbage collector is much more active.

**Comment by grokys** [comment] 2020-09-02 13:51
The number shown in the VS diagnostic tools and Task Manager are different. Confirmed this with @FrankenApps in Gitter: when VS diagnostics reports the process using ~500MB, Task Manager reports around 35MB.

This is because VS diagnostics reports private bytes and VS diagnostics reports working set: https://stackoverflow.com/questions/42432101/why-do-visual-studio-and-task-manager-report-different-memory-usages

**Comment by grokys** [comment] 2020-09-02 14:13
The https://github.com/AvaloniaUI/Avalonia/tree/gl-texture-mem-intercept branch adds some diagnostics around what GL textures are being created by Skia. When run, and the window is resized it generates the following output:

```
glGenTexture: 1 - (0)
glGenTexture: 2 - (1)
glGenTexture: 3 - (2)
glGenTexture: 4 - (3)
glGenTexture: 5 - (4)
glGenTexture: 6 - (5)
glGenTexture: 7 - (6)
glGenTexture: 8 - (7)
glGenTexture: 9 - (8)
glGenTexture: 10 - (9)
glGenTexture: 11 - (10)
glGenTexture: 12 - (11)
glGenTexture: 13 - (12)
glGenTexture: 14 - (13)
glDeleteTexture: 14 - (13)
glGenTexture: 14 - (13)
glDeleteTexture: 14 - (13)
glGenTexture: 14 - (13)
glDeleteTexture: 14 - (13)
glGenTexture: 14 - (13)
glDeleteTexture: 14 - (13)
glGenTexture: 14 - (13)
glDeleteTexture: 14 - (13)
```

The value in parenthesis is the number of active textures. You can see that Skia is generating new textures as the window is resized, up to a certain point (13). After this point subsequent resizes cause the last texture to be deleted and a new texture recreated each time, but the first 13 textures are not reclaimed.

Inserting a call to `GrContext.PurgeResources();` as was done in https://github.com/AvaloniaUI/Avalonia/pull/4554/files fixes this, but causes rendering to slow down.

**Comment by grokys** [comment] 2020-09-02 14:28
Calling `GrContext.DumpMemoryStatistics` after resizing for a while reveals the following:

```
skia/gpu_resources/resource_11/texture: size - 4194304 (bytes
skia/gpu_resources/resource_11/texture: type - Texture
skia/gpu_resources/resource_11/texture: category - Scratch
skia/gpu_resources/resource_10: size - 49152 (bytes
skia/gpu_resources/resource_10: type - Buffer Object
skia/gpu_resources/resource_10: category - Scratch
skia/gpu_resources/resource_383/texture: size - 3017500 (bytes
skia/gpu_resources/resource_383/texture: type - Texture
skia/gpu_resources/resource_383/texture: category - Scratch
skia/gpu_resources/resource_19/texture: size - 7616160 (bytes
skia/gpu_resources/resource_19/texture: type - Texture
skia/gpu_resources/resource_19/texture: category - Scratch
skia/gpu_resources/resource_19/texture: purgeable_size - 7616160 (bytes
skia/gpu_resources/resource_23/texture: size - 8036392 (bytes
skia/gpu_resources/resource_23/texture: type - Texture
skia/gpu_resources/resource_23/texture: category - Scratch
skia/gpu_resources/resource_23/texture: purgeable_size - 8036392 (bytes
skia/gpu_resources/resource_31/texture: size - 9254700 (bytes
skia/gpu_resources/resource_31/texture: type - Texture
skia/gpu_resources/resource_31/texture: category - Scratch
skia/gpu_resources/resource_31/texture: purgeable_size - 9254700 (bytes
skia/gpu_resources/resource_39/texture: size - 9362688 (bytes
skia/gpu_resources/resource_39/texture: type - Texture
skia/gpu_resources/resource_39/texture: category - Scratch
skia/gpu_resources/resource_39/texture: purgeable_size - 9362688 (bytes
skia/gpu_resources/resource_27/texture: size - 8682240 (bytes
skia/gpu_resources/resource_27/texture: type - Texture
skia/gpu_resources/resource_27/texture: category - Scratch
skia/gpu_resources/resource_27/texture: purgeable_size - 8682240 (bytes
skia/gpu_resources/resource_55/texture: size - 4355712 (bytes
skia/gpu_resources/resource_55/texture: type - Texture
skia/gpu_resources/resource_55/texture: category - Scratch
skia/gpu_resources/resource_55/texture: purgeable_size - 4355712 (bytes
skia/gpu_resources/resource_35/texture: size - 9535560 (bytes
skia/gpu_resources/resource_35/texture: type - Texture
skia/gpu_resources/resource_35/texture: category - Scratch
skia/gpu_resources/resource_35/texture: purgeable_size - 9535560 (bytes
skia/gpu_resources/resource_107/texture: size - 4063860 (bytes
skia/gpu_resources/resource_107/texture: type - Texture
skia/gpu_resources/resource_107/texture: category - Scratch
skia/gpu_resources/resource_107/texture: purgeable_size - 4063860 (bytes
skia/gpu_resources/resource_43/texture: size - 8343816 (bytes
skia/gpu_resources/resource_43/texture: type - Texture
skia/gpu_resources/resource_43/texture: category - Scratch
skia/gpu_resources/resource_43/texture: purgeable_size - 8343816 (bytes
skia/gpu_resources/resource_47/texture: size - 6720224 (bytes
skia/gpu_resources/resource_47/texture: type - Texture
skia/gpu_resources/resource_47/texture: category - Scratch
skia/gpu_resources/resource_47/texture: purgeable_size - 6720224 (bytes
skia/gpu_resources/resource_51/texture: size - 5450504 (bytes
skia/gpu_resources/resource_51/texture: type - Texture
skia/gpu_resources/resource_51/texture: category - Scratch
skia/gpu_resources/resource_51/texture: purgeable_size - 5450504 (bytes
skia/gpu_resources/resource_143/texture: size - 3587200 (bytes
skia/gpu_resources/resource_143/texture: type - Texture
skia/gpu_resources/resource_143/texture: category - Scratch
skia/gpu_resources/resource_143/texture: purgeable_size - 3587200 (bytes
skia/gpu_resources/resource_95/texture: size - 2930928 (bytes
skia/gpu_resources/resource_95/texture: type - Texture
skia/gpu_resources/resource_95/texture: category - Scratch
skia/gpu_resources/resource_95/texture: purgeable_size - 2930928 (bytes
skia/gpu_resources/resource_135/texture: size - 3630168 (bytes
skia/gpu_resources/resource_135/texture: type - Texture
skia/gpu_resources/resource_135/texture: category - Scratch
skia/gpu_resources/resource_135/texture: purgeable_size - 3630168 (bytes
skia/gpu_resources/resource_171/texture: size - 3193840 (bytes
skia/gpu_resources/resource_171/texture: type - Texture
skia/gpu_resources/resource_171/texture: category - Scratch
skia/gpu_resources/resource_171/texture: purgeable_size - 3193840 (bytes
skia/gpu_resources/resource_5: size - 32768 (bytes
skia/gpu_resources/resource_5: type - Buffer Object
skia/gpu_resources/resource_5: category - Scratch
skia/gpu_resources/resource_5: purgeable_size - 32768 (bytes
skia/gr_text_blob_cache: size - 53200 (bytes
```

Seems that a number of scratch textures are being kept around.

**Comment by grokys** [comment] 2020-09-02 14:52
> The number shown in the VS diagnostic tools and Task Manager are different. Confirmed this with @FrankenApps in Gitter: when VS diagnostics reports the process using ~500MB, Task Manager reports around 35MB.

This is only the case on machines with dedicated graphics memory. On machines with integrated graphics (i.e. Intel graphics) these two numbers are equal.

**Comment by grokys** [comment] 2020-09-02 15:01
After running and resizing full ControlCatalog for a while, I get

```
35 textures, total 103.1962MB
```

At this point VS diagnostics reports 232.6MB total memory of which 10.8MB is the managed heap.

232.6 - 103.2 - 10.8 = 118.6 MB still unaccounted for.

**Comment by grokys** [comment] 2020-09-02 15:18
Setting

```
.With(new SkiaOptions
{
    MaxGpuResourceSizeBytes = 0,
})
```

in the app builder options causes less scratch textures to be allocated (approx 10mb instead of 100mb).

**Comment by danwalmsley** [comment] 2020-09-03 19:47
ok the several gib leak on OSX was caused by something seperate from this...

OSX now behaves well...

https://github.com/AvaloniaUI/Avalonia/pull/4612

**Comment by danwalmsley** [comment] 2020-09-03 22:45
On OSX... 100mb is used for the cache... setting this down to about 8 / 16 or 32mb... seems to work better... and you get about 78mb for an empty window.

**Comment by HendrikMennen** [comment] 2020-09-07 22:16
> @HendrikMennen @FrankenApps I'm looking into this and while some of us are able to repro, others (including myself) aren't. What graphics card do you have on the machine where you're seeing this?

Sorry for the late response. In my case the memory leak was caused by AvaloniaEdit bug which got already fixed. On my machine (GTX 1070) all (noticable) memory leaks are currently gone

**Closed** 2020-09-08 21:25 UTC
