### ISSUE TITLE
ItemsRepeater to search DataTemplates when no ItemTemplate defined

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#5362] opened 2021-01-26 09:15 UTC
The ItemsRepeater is inconsistent with the other Avalonia controls in that it doesn't appear to search the DataTemplates collections of its parent controls for a matching DataTemplate for it's items. Instead it reverts to using ToString() when no ItemTemplate is defined; e.g.
```<ItemsRepeater Items="{Binding Items}"/>```

The similar ItemsControl works as expected using the DataTemplates of its parent controls.
```<ItemsControl Items="{Binding Items}"/>```

I think it would make sense for ItemsRepeater to default to searching the Avalonia DataTemplates collections for a matching template.

**Comment by grokys** [comment] 2021-01-27 05:06
This is the behavior from the upstream `ItemsRepeater` and I'd be hesitant to diverge from the behavior there for a few reasons:

- It would make future porting of features/fixes from upstream more difficult
- It would disable element recycling, because we we need to wrap the `ItemTemplate` in an `ElementFactory` in order to implement recycling. If we have to search `DataTemplates` then there can be a different data template for each element

If you want your `ItemsRepeater` to search `DataTemplates` then the simplest way is to put a `ContentPresenter` or `ContentControl`-derived control in the `ItemsRepeater.ItemTemplate` property, Note that you may see decreased performance however because only the `ContentPresenter` can be recycled in this case, and not the content itself.

I'm going to close this issue as `by design` but please feel free to continue discussion.

**Closed by grokys** 2021-01-27 05:06 UTC
Labels: by-design

**Comment by aguahombre** [comment] 2021-01-27 09:54
Looks like UWP uses the ```DataTemplateSelector``` to implement different ```DataTemplates``` dependent on the item type or it's properties.
If Avalonia had a ```DataTemplateSelector``` equivalent that searches ```DataTemplates``` then it would work like UWP.
I assume ```DataTemplateSelector``` in UWP supports element recycling.

**Comment by grokys** [comment] 2021-01-27 10:22
`DataTemplateSelector` is needed in UWP because UWP has no concept of implicit data templates like Avalonia and WPF: https://blog.magnusmontin.net/2017/03/25/uwp-implicit-data-template/

However you don't need `DataTemplateSelector` to select different templates, we've ported `RecyclingElementFactory` from WinUI which has this feature. See the sample at https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/ItemsRepeaterPage.xaml#L4-L26

Unfortunately this is completely undocumented in both Avalonia and WinUI/UWP currently, sorry about that.

**Comment by nrenzoni** [comment] 2023-05-08 21:17
> This is the behavior from the upstream `ItemsRepeater` and I'd be hesitant to diverge from the behavior there for a few reasons:
> 
> * It would make future porting of features/fixes from upstream more difficult
> * It would disable element recycling, because we we need to wrap the `ItemTemplate` in an `ElementFactory` in order to implement recycling. If we have to search `DataTemplates` then there can be a different data template for each element
> 
> If you want your `ItemsRepeater` to search `DataTemplates` then the simplest way is to put a `ContentPresenter` or `ContentControl`-derived control in the `ItemsRepeater.ItemTemplate` property, Note that you may see decreased performance however because only the `ContentPresenter` can be recycled in this case, and not the content itself.
> 
> I'm going to close this issue as `by design` but please feel free to continue discussion.

Can you share code for how to do this? I have the use case where my ItemsRepeater.Items is a collection of an abstract class type, and I'd like to have different DataTemplates per each concrete class type. I thought I could define the Data Templates in ItemsRepeater.DataTemplates, but it's not being referenced, similar to this github issue.

**Comment by maxkatz6** [comment] 2023-05-09 01:38
@nrenzoni you need to use recycle pool for items repeater https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/ItemsRepeaterPage.xaml#L25-L43
