### ISSUE TITLE
Avalonia MVVM Application crashes after window resize

### ISSUE THREAD

**Issue by DmitryZhelnin** [AvaloniaUI/Avalonia#1411] opened 2018-03-01 09:16 UTC
Windows 7. Visual Studio Community 2017.
1. Build and run standard Avalonia MVVM Application from template.
2. Resize window to minimum size. 
![default](https://user-images.githubusercontent.com/4993430/36836247-e6f1ec1c-1d49-11e8-838f-647e3bfe7e2b.png)
3. Resize back.
4. Application crashes with:
```
Unhandled Exception: System.ArgumentOutOfRangeException: Positive number required.
Parameter name: bytesAllocated
   at System.GC.RemoveMemoryPressure(Int64 bytesAllocated)
   at Avalonia.Shared.PlatformSupport.StandardRuntimePlatform.UnmanagedBlob.DoDispose()
   at Avalonia.Shared.PlatformSupport.StandardRuntimePlatform.UnmanagedBlob.Finalize()
```

**Comment by grokys** [comment] 2019-03-02 13:30
Duplicate of #1023.

**Closed by grokys** 2019-03-02 13:30 UTC
Labels: bug, rendering

**Comment by xiangzhai** [comment] 2020-08-11 12:22
:mips-interest
