### ISSUE TITLE
ItemsPresenter not show all items with ReactUI and linuxfb

### ISSUE THREAD

**Issue by Giacomo-Gozzi** [AvaloniaUI/Avalonia#8349] opened 2022-06-15 21:16 UTC
**Describe the bug**
The same application on windows shows all items while on raspberry linux does not, sometimes it shows the first sometimes none

**To Reproduce**
Create an ItemsPresenter with datatemplate binded on list and run it on raspberry pi with linuxfb 

**Expected behavior**
Show all items like like on windows

**Desktop (please complete the following information):**

- OS: Raspbian 9 on raspberry pi 3
- Version: 0.10.15

**Comment by maxkatz6** [comment] 2022-06-15 23:19
Possibly duplicate of https://github.com/AvaloniaUI/Avalonia/issues/8181 and not platform specific (reactiveui specific instead?)

**Comment by Giacomo-Gozzi** [comment] 2022-06-16 05:33
On windows i haven't any kind of problem only on linuxfb with raspberry pi, in my case the list never was changed only on constructor of model.
I guess ReactUI is not a problem. 
How can i check it?

**Comment by kekekeks** [comment] 2023-07-03 08:55
1) no repro is provided
2) check with 11.0

Closing since there is no repro

**Closed by kekekeks** 2023-07-03 08:55 UTC
Labels: bug
