### ISSUE TITLE
Window setting transparency issues

### ISSUE THREAD

**Issue by Coolkeke** [AvaloniaUI/Avalonia#10780] opened 2023-03-24 11:52 UTC
Why is Window still clickable after being set to transparent in Avalonia? My current settings for attributes are SystemDecorations="None" and Background="{x: Null}", but setting them seems meaningless
The current version is 0.10.18

**Comment by timunie** [comment] 2023-03-24 12:16
1. which OS?
2. Can you try using latest nightly or latest 11.0 preview6?

**Comment by timunie** [comment] 2023-03-27 12:27
Okay looks like there is no "easy" solution for this. If you are on windows, you can try to implement a click through like described here: 
- https://stackoverflow.com/questions/13069717/letting-the-mouse-pass-through-windows-c

Another hint: 
> You need to create a mask bitmap and set it to the window with the win32 api directly iirc

**Comment by timunie** [comment] 2023-03-27 12:28
Okay looks like there is no "easy" solution for this. If you are on windows, you can try to implement a click through like described here: 
- https://stackoverflow.com/questions/13069717/letting-the-mouse-pass-through-windows-c

Another hint: 
> You need to create a mask bitmap and set it to the window with the win32 api directly iirc

**Comment by Coolkeke** [comment] 2023-03-28 02:26
> 好的，看起来没有“简单”的解决方案。如果你在 Windows 上，你可以尝试像这里描述的那样实现点击：
> 
> * https://stackoverflow.com/questions/13069717/letting-the-mouse-pass-through-windows-c
> 
> 另一个提示：
> 
> > 您需要创建一个掩码位图并直接将其设置为带有win32 api的窗口iirc

Does Avalonia have the ability to implement the above mentioned function, which does exist in real development scenarios. The completion of this function will be helpful for Avalonia to develop clients, such as turning Avalonia developed programs into desktop widgets, notification reminders, calendar widgets, and other functions

**Comment by Coolkeke** [comment] 2023-03-28 02:26
Does Avalonia have the ability to implement the above mentioned function, which does exist in real development scenarios. The completion of this function will be helpful for Avalonia to develop clients, such as turning Avalonia developed programs into desktop widgets, notification reminders, calendar widgets, and other functions

**Comment by timunie** [comment] 2023-03-28 07:01
> Does Avalonia have the ability to implement the above mentioned function, which does exist in real development scenarios. The completion of this function will be helpful for Avalonia to develop clients, such as turning Avalonia developed programs into desktop widgets, notification reminders, calendar widgets, and other functions

probably some day after 11.0 was released, but I can't promise as I don't know how hard it is on Mac and Linux.

**Comment by Coolkeke** [comment] 2023-03-28 07:08
> > Does Avalonia have the ability to implement the above mentioned function, which does exist in real development scenarios. The completion of this function will be helpful for Avalonia to develop clients, such as turning Avalonia developed programs into desktop widgets, notification reminders, calendar widgets, and other functions
> 
> probably some day after 11.0 was released, but I can't promise as I don't know how hard it is on Mac and Linux.

Looking forward to the day when this feature is added, I am also developing an open source project around the Avalonia project, providing a little assistance for this project. I hope the Avalonia team can do better and better

**Comment by maxkatz6** [comment] 2023-10-25 07:28
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/4956

**Closed by maxkatz6** 2023-10-25 07:28 UTC
Labels: enhancement, os-windows
