### ISSUE TITLE
OSK On Windows 

### ISSUE THREAD

**Issue by nlogozzo** [AvaloniaUI/Avalonia#7732] opened 2022-03-01 15:30 UTC
On Windows, if a TextBox, or whatever text input control, is selected with the finger the OSK appears and if it is clicked with a pen, the OSK appears in pen mode. This happens in all applications I've used (UWP, Win32, etc...) except for Avalonia built applications.

**Comment by robloo** [comment] 2022-03-02 02:45
OSK = On Screen Keyboard. I'm not sure everyone knows that abbreviation.

This isn't implemented yet as far as I know. It's clearly needed (and was planned for mobile) but the team hasn't had the time. Touch-based pointer support and use in Desktop were also later additions to the code base and it isn't fully polished.

Bottom line, this isn't a bug, it's a feature that needs to be implemented.

**Comment by maxkatz6** [comment] 2022-03-02 20:31
We don't really need our own on screen keyboard for most backends, including mobile. We need proper IME implementations for these backends instead. 
On Windows and Linux we have IME implementations. On OSX, Android and Web it's functional, but not complete. iOS has the poorest text input so far from these backends. 

Problem with this issue that on Windows we don't know about input type right now (remember that Pen PR wasn't yet merged). So we can't tell windows IME about expected OSK type. At least that's how I see this problem without going too deep.

**Comment by robloo** [comment] 2022-03-02 23:45
> We don't really need our own on screen keyboard for most backends, including mobile.

Yes, I think we are all only talking about popping up the platform-native keyboard when a textbox is selected by touch. 

> We need proper IME implementations for these backends instead.

I'm not sure IME is needed for this. It is only loosely related afaik.

**Comment by ohin** [comment] 2024-03-05 10:52
This became an issue for me too. I am running an Avalonia 11 app on Dell Latitude Rugged Tablet and the native On Screen Keyboard does not show when touching/focusing TextBox.

Is there any chance to get this fixed? Are there any workarounds to get the keyboard appear?

**Comment by andrenoel84** [comment] 2024-04-25 12:19
Hi, I'm facing the same issue. Any news on this topic ?
Regards

**Comment by timunie** [comment] 2024-04-25 12:53
Priorites are as customers require them, otherwise it is done when it's done or a community member add a PR. If you need an urgent feature, consider to request paid support.

**Comment by Hackmodford** [comment] 2024-05-14 01:48
We decided not to use Avalonia for a client's project because of this.

**Comment by flier268** [comment] 2024-06-18 06:15
```C#
public static class ScreenKeyboardHelper
{
    /// <summary>
    /// 靜態構造函數，設置定時器來監控螢幕鍵盤的開啟狀態
    /// </summary>
    static ScreenKeyboardHelper()
    {
        Observable.Interval(TimeSpan.FromMilliseconds(300)).Subscribe(x =>
        {
            bool isOpen = OnScreenKeyboard.IsOpened();
            if (isOpen && IsKeyboardOpen == false)
                OnKeyboardStatusChanged?.Invoke(null, true);
            else if (isOpen == false && IsKeyboardOpen)
                OnKeyboardStatusChanged?.Invoke(null, false);
            IsKeyboardOpen = isOpen;
        });
    }

    /// <summary>
    /// 獲取當前螢幕鍵盤是否打開的狀態
    /// </summary>
    public static bool IsKeyboardOpen { get; private set; }

    /// <summary>
    /// 是否需要鍵盤但不使用插件
    /// </summary>
    public static bool RequireKeyboardNotPlugin { get; set; } = false;

    /// <summary>
    /// 螢幕鍵盤狀態改變時觸發的事件
    /// </summary>
    /// <remarks>事件參數表示螢幕鍵盤的打開狀態，true 表示打開，false 表示關閉</remarks>
    public static event EventHandler<bool>? OnKeyboardStatusChanged;

    /// <summary>
    /// 顯示螢幕鍵盤
    /// </summary>
    /// <exception cref="NotImplementedException">當操作系統不是 Windows 時拋出異常</exception>
    public static void ShowKeyboard()
    {
        if (OperatingSystem.IsWindows())
        {
            if (RequireKeyboardNotPlugin == false || WMIHelper.GetKeyboardPresent() == false || Debugger.IsAttached)
            {
                Version version = Environment.OSVersion.Version;
                if (version.Major == 10)
                {
                    if (version.Build > 16299)
                    {
                        if (OnScreenKeyboard.IsOpened() == false)
                        {
                            ProcessStartInfo psi = new(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), "cmd.exe"))
                            {
                                UseShellExecute = false,
                                Arguments = "/c \"C:\\Program Files\\Common Files\\microsoft shared\\ink\\TabTip.exe\"",
                                CreateNoWindow = true
                            };
                            Process.Start(psi);
                        }
                    }
                    else
                    {
                    }
                }
                IsKeyboardOpen = true;
                OnKeyboardStatusChanged?.Invoke(null, true);
            }
        }
        else
        {
            throw new NotImplementedException();
        }
    }

    /// <summary>
    /// 關閉螢幕鍵盤
    /// </summary>
    public static void CloseKeyboard()
    {
        OnScreenKeyboard.Close();
        IsKeyboardOpen = false;
        OnKeyboardStatusChanged?.Invoke(null, false);
    }
}
```
View.cs
```C#

public partial class LoginView : UserControl
{
    public LoginView()
    {
        InitializeComponent();
        foreach (var textBox in this.GetLogicalDescendants().OfType<TextBox>())
        {
            textBox.AddHandler(PointerCaptureLostEvent, ShowKeyboard);
            textBox.AddHandler(GotFocusEvent, ShowKeyboard);
        }
    }

    private static async void ShowKeyboard(object? sender, EventArgs args)
    {
        Disable((sender as TextBox)!);
        ScreenKeyboardHelper.ShowKeyboard();
        await Task.Delay(TimeSpan.FromMilliseconds(350));
        Enable((sender as TextBox)!);
    }

    private static void Disable(TextBox textBox)
    {
        textBox.AddHandler(TextInputEvent, IgnoreInputText, RoutingStrategies.Tunnel);
    }

    private static void Enable(TextBox textBox)
    {
        textBox.RemoveHandler(TextInputEvent, IgnoreInputText);
    }

    private static void IgnoreInputText(object? sender, TextInputEventArgs eventArgs)
    {
        eventArgs.Handled = true;
    }
}
```

**Comment by maxkatz6** [comment] 2024-06-18 18:43
I am going to close this issue as a duplicate of #10136, to keep it in one place.
@flier268 thank you for a workaround.

**Closed by maxkatz6** 2024-06-18 18:43 UTC
Labels: bug, os-windows, area-textprocessing
