### ISSUE TITLE
Leftmost MenuItem popup appears on the adjacent screen next to the window

### ISSUE THREAD

**Issue by SparkyTD** [AvaloniaUI/Avalonia#7697] opened 2022-02-24 17:26 UTC
**Describe the bug**
When the first `<MenuItem/>` is clicked on a maximized Avalonia window on a multi-monitor setup, the menu popup appears on the monitor that is to the left of the main monitor.

**To Reproduce**

1. Have at least two monitors
2. Create a project with a basic menu strip on the main window 
3. Maximize the window a the right monitor
4. Click on the first menu item to open it

**Expected behavior**
The menu popup should appear on the same screen that the MainWindow is on. Instead, it appears on the screen to the left.

**Screenshots**
(Taken between two of my monitors)
![image](https://user-images.githubusercontent.com/45818400/155540041-bc79eb75-5baa-4d76-a489-200afd497eef.png)

**Desktop (please complete the following information):**

- OS: Windows 11 10.0.22000.493
- Version 0.10.11 - 0.10.999-cibuild0018899-beta

**Additional context**
The same behavior can be observed when the window isn't maximized, but is touching (not crossing) the left edge of the main screen.

Example MainWindow.axaml:
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="HexEditor.Views.MainWindow">
    <DockPanel>
        <Menu DockPanel.Dock="Top">
            <MenuItem Header="File">
                <MenuItem Header="New" />
                <MenuItem Header="Open File..." />
            </MenuItem>
            <MenuItem Header="Edit" />
            <MenuItem Header="Search" />
            <MenuItem Header="View" />
        </Menu>
        <Grid />
    </DockPanel>
</Window>
```

**Comment by grokys** [comment] 2022-04-09 18:04
I think this is a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/7164 which should be fixed in `master` and can hopefully be backported to the stable branch for the next release.

**Closed by grokys** 2022-04-09 18:04 UTC
Labels: bug
