### ISSUE TITLE
Controls in RoutedViewHost.DefaultContent loose styling after navigate and navigateback

### ISSUE THREAD

**Issue by sergevm** [AvaloniaUI/Avalonia#12249] opened 2023-07-18 21:06 UTC
**Describe the bug**
 Controls in the DefaultContent of a RoutedViewHost lose styling after a navigation was executed to a view, followed by a navigateback, which displays the DefaultContent again.

**To Reproduce**
1. I have a view (window) with a RoutedViewHost. The RoutedViewHost has DefaultContent with a button in it, with a particular styling on the button. When the application starts up, the default content is shown, with the styled button correctly displayed.
2. The button has a command that uses the router to display other content. When the button is clicked, that content is displayed correctly.
3. When navigating back on the router, the DefaultContent is displayed again. However, the button is styled incorrectly.

**Expected behavior**
The button keeps the correct styling
.
**Screenshots**
No screenshot, I created a small demo project that is included in the issue

**Desktop (please complete the following information):**

- OS: Macbook Air M1, Ventura 13.4.1

**Additional context**
- The styling was kept correctly in v0.10.x. The demo project was created with the template that initializes the solution with this version of Avalonia. Upgraded manually to 11.0, and then the issue occurs.
[RoutedViewHostDefaultContentIssue.zip](https://github.com/AvaloniaUI/Avalonia/files/12089012/RoutedViewHostDefaultContentIssue.zip)

**Comment by danielmayost** [comment] 2023-07-20 04:08
probably variation of #12158 and mostly fixes by #12173

**Comment by timunie** [comment] 2023-07-20 06:38
tested with https://github.com/AvaloniaUI/Avalonia/pull/12173#issuecomment-1634047287 and looks like you are right, @danielmayost. Thx for figuring this out. 

@sergevm can you also try the above linked PR build on your end to confirm? If it fixes your issue, it can be closed as a duplicate.

**Comment by timunie** [comment] 2023-07-20 11:24
closing as duplicate of #12158

**Closed by timunie** 2023-07-20 11:24 UTC
Labels: bug
