### ISSUE TITLE
Three Possible Solutions for the Pseudo Class Style Selector Problem

### ISSUE THREAD

**Issue by Elbon-Eastmage** [AvaloniaUI/Avalonia#14631] opened 2024-02-17 00:07 UTC
## The Problem
I didn't want the border for a specific text box to show when the cursor was over it. I found this in the documentation ([Styles - Nested Styles](https://docs.avaloniaui.net/docs/basics/user-interface/styling/styles#nested-styles)) and it looked like a perfect solution for my problem. So, I set this up:
```
<Style Selector="TextBox.buttonSpinnerBox">
	<Setter Property="Background" Value="Transparent" />
	<Setter Property="BorderBrush" Value="Transparent" />

	<Style Selector="^:pointerover">
		<Setter Property="BorderBrush" Value="Transparent" />
	</Style>
</Style>
```
However, it didn't work. After some digging around, I found out that I could add /template/ Border next to ^:pointerover. Thankfully, that solution proved successful.

I will admit, this wasn't easy for me to figure out. It also seems I'm not the only one; see [#2662](https://github.com/AvaloniaUI/Avalonia/pull/2662#issuecomment-652707731).
What's more, while the documentation does [mention this problem and a workaround](https://docs.avaloniaui.net/docs/guides/styles-and-resources/troubleshooting#selector-with-a-pseudoclass-doesnt-override-the-default), it suggests using ContentPresenter instead of Border, which doesn't work for the TextBox. This means that source code knowledge can be required to use pseudo class style selectors.

Now, I am definitely aware that this issue has been brought up multiple times (issue #9976, issue #9657, and issue #5406 for example), and based on what I read, the main problem with implementing this is that setting the local value of a control would prevent the pseudo class value from applying, as the local value has higher priority. Thus, I have three suggestions for getting around that problem.

## The (Possible) Solutions
1. Add properties to controls that could send new values to styled properties when a pseudo class is active. When no properties are associated with a pseudo class, the original value could be restored (possibly by a default property).
2. When an axaml style file is compiled, if there is a pseudo class selector, the /template/ ContentPresenter (or what applies to that control), could be added to it automatically.
3. If the local value doesn't have a pseudo class selector, the one in the style file could be added below the local value automatically at compile time.

## The Conclusion
I do hope this can get resolved. It may not seem like a huge problem right now, but it strikes me as something that could get out of control in the future. I certainly wouldn't want that to happen!

**Comment by robloo** [comment] 2024-02-17 03:29
This is a style priority problem that I agree is pretty unintuitive. It's been discussed a few other places and this might be considered a duplicate:

 * https://github.com/AvaloniaUI/Avalonia/issues/2789
 * https://github.com/AvaloniaUI/Avalonia/pull/7679
 * https://github.com/AvaloniaUI/Avalonia/issues/13601

It probably won't be addressed for some time. I think the solution is known though -- it just requires updating existing themes to work with the priority changes. It's breaking for apps too.

We probably should have just kept the fix in and updated fluent theme for v11...

**Comment by timunie** [comment] 2024-02-18 08:38
Closing this as a duplicate of #13601

Thanks for the suggestions anyway 👍

**Closed by timunie** 2024-02-18 08:38 UTC
Labels: enhancement
