### ISSUE TITLE
ContentPresenter null Content and DataContext when using binding for Context

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaUI/Avalonia#6422] opened 2021-08-14 20:10 UTC
**Describe the bug**
If we have `ContentPresenter` with string `Content` defined in XAML all works fine (text displayed via `TextBlock`):
```xaml
<ContentPresenter Content="My text"/>
```
![image](https://user-images.githubusercontent.com/29896317/129458756-f34e7e6a-2140-47c5-9f87-3318e8b523e8.png)

But if we use bindings for `Content` and bind to a string, but we will not see anything:
```xaml
<ContentPresenter Name="Presenter" Content="{Binding Greeting}"/>
```
VM:
```cs
public string Greeting => "Welcome to Avalonia!";
```
![image](https://user-images.githubusercontent.com/29896317/129458792-4192425d-2f48-43c2-80d3-b9dd09b5ff56.png)

A similar situation arises when we try to set Content from code:
```cs
this.FindControl<ContentPresenter>("Presenter").Content = "1234";
```

**To Reproduce**

1. Create Avalonia app
2. Add string property to VM
3. Create `ContentPresenter` and bind `Content` to this property

**Expected behavior**
If i set string to Content via binding or from code i should see TextBlock as i see TextBlock when set string to Content in xaml.

**Desktop (please complete the following information):**

- OS: Any
- Version 0.10.6

**Additional context**
I debugged the code and figured out the cause of this problem.
There are 3 DataContext changes:
1. Assignment of "normal" DC (ViewModel)
Changing the DataContext triggers the Content change, which is updated and eventually the ContentPresenter.UpdateChild method is called
In which if the content != Control (and we have a string) then the Content (string) is assigned in the DataContext
![image](https://user-images.githubusercontent.com/29896317/129458912-205a3491-f5c3-4cc8-99b1-0bd762d9c68c.png)
2. Assigning a string (which was Content)
So DataContext is now not a VM, but a string, the Content binding not resolved, and Content is now null
Further in ContentPresenter.UpdateChild null is assigned to DataContext
3. Now DataContext is null and Content is null

**Comment by SKProCH** [comment] 2021-08-14 20:11
I wrote about this in the avalonia ru chat, I was told to open an issue and ping @grokys

**Comment by grokys** [comment] 2021-08-14 20:34
I'm on vacation right now but have you tried using `ContentControl` instead?

**Comment by SKProCH** [comment] 2021-08-15 10:32
@grokys, yes, strange, but `ContentControl` works. 
in fact, I always thought that ContentControl is used as a base class for custom controls, and in my case (displaying arbitrary content), you need to use a ContentPresenter.

So, it's a bug or it's by design?

**Comment by jmkinzer** [comment] 2023-12-10 20:11
Old issue but just to note I was bitten by this as well (i.e. binding the Content property of ContentPresenter). Oddly this worked in the 11.0.x previews but when I upgraded to 11.0.5 I had to go with the previously noted work-around of using ContentControl.

**Comment by timunie** [comment] 2023-12-10 20:25
@jmkinzer ContentPresenter is only to be used inside ControlTemplates. It will not work as normal control. In that case ContentControl is the right choice.

@SKProCH btw do you face the issue if you use it only inside controlTemplates?

**Comment by SKProCH** [comment] 2023-12-10 22:16
@timunie actually i don't remember something like that.

**Comment by timunie** [comment] 2023-12-11 04:45
Closing this as by design

**Closed** 2023-12-11 04:46 UTC
Labels: by-design

**Comment by martin-holy** [comment] 2025-01-10 12:16
This also work:
`<ContentPresenter DataContext="{Binding MyProperty}" Content="{Binding}"/>`
