### ISSUE TITLE
NativeControlHost can't work on x11

### ISSUE THREAD

**Issue by sandsc** [AvaloniaUI/Avalonia#15284] opened 2024-04-09 10:13 UTC
### Describe the bug

I created a opengl render window from NativeControlHost platform handle by SDL3.
 Every thing works fine on platform Windows, but on linux I got a black window, I found that on linux underlying x11 window's size is always width = 1, height = 38 on my computer, regardless of the size of the main window, and when the main window is resized, the underlying window does not receive the size changed event.

### To Reproduce

Create a sdl_windows by a handle created by CreateNativeControlCore
` 
            SDL_SetBooleanProperty(sdlPid, SDL_PROP_WINDOW_CREATE_OPENGL_BOOLEAN, true);
#if SDL_PLATFORM_WIN32
            SDL_SetHint(SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP, "0");
            SDL_SetProperty(sdlPid, SDL_PROP_WINDOW_CREATE_WIN32_HWND_POINTER, handle);
#elif SDL_PLATFORM_LINUX
            SDL_SetProperty(sdlPid, SDL_PROP_WINDOW_CREATE_X11_WINDOW_NUMBER, handle);
            logger::debug_f("Platform linux: external handle: %p", handle);
#endif
SDL_Window* window = SDL_CreateWindowWithProperties(sdlPid);
`
then pull sdl events in game loop.
`
 SDL_Event event;
 while (SDL_PollEvent(&event))
 {
     process(&event);
 }
`
On windows platform, every thing works fine, every window and input events reported correctly, however on linux, no matter how you move or resize the window, you won't receive any events. 
 Following are some log outputs when SDL3 is turned on DEBUG_XEVENTS:

> window 0x5611e9891d60: ConfigureNotify! (position: 959,577, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 959,577, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 959,577, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 959,577, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 959,577, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 959,539, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 959,539, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 959,539, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 959,539, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 959,539, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 408,86, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 408,86, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 408,86, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 408,86, size: 1x38)
window 0x5611e9891d60: ConfigureNotify! (position: 408,86, size: 1x38)

those events are only received when window first created, when I resized main window, no events received any more.

### Avalonia version

11.0.10

### OS

Linux

### Additional context

Render window on platform window, but a black window on linux.
![image](https://github.com/AvaloniaUI/Avalonia/assets/1673854/a8028c84-81a6-4c81-bce1-6b47a1ba9430)

**Comment by sandsc** [comment] 2024-04-10 03:16
I try to resize underlying SDL window when main window pixel size changed, now rendering window is shown and rendering correctly, however, underlying SDL window don't embed into the Avalonia main window, it's detached from main window!  snapshot from Linux x11 platform:
![snapshot](https://github.com/AvaloniaUI/Avalonia/assets/1673854/40eb1b5c-9620-4180-a4d6-5a7aa3b6b8ef)

**Comment by maxkatz6** [comment] 2024-04-10 05:04
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/12556

**Comment by maxkatz6** [comment] 2024-04-10 05:05
Potentially https://github.com/AvaloniaUI/Avalonia/issues/10354 too

**Closed by maxkatz6** 2024-04-10 05:04 UTC
Labels: bug

**Comment by sandsc** [comment] 2024-04-10 05:58
So is this an avalonia bug or an SDL bug？

**Comment by niuzhaosen** [comment] 2025-01-09 10:16
Hello, have you solved this problem
