### ISSUE TITLE
VS Code extension ?

### ISSUE THREAD

**Issue by SeleDreams** [AvaloniaUI/Avalonia#1587] opened 2018-05-14 01:52 UTC
Hello, i'm wondering if there's any plans for a VS Code extension since VS Code is one of the best IDE for the cross platform C# development

**Comment by circler3** [comment] 2018-05-21 07:09
Do you mean a *xaml* extension?

**Comment by pikachuk** [comment] 2018-05-22 10:20
I'm mostly talking about an equivalent to the visual studio extension https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaforVisualStudio

**Comment by j4nbob** [comment] 2019-06-19 16:43
yes, for truly cross platform, avalonia is barking up with wrong tree with the visual extension. the correct tree would be Visual Studio Code.

**Comment by tuan-tu-tran** [comment] 2020-05-15 22:54
So is this a duplicate of #999 ?

**Comment by vleeuwenmenno** [comment] 2021-06-19 23:29
Sadly they are still Windows and not cross-platform by only supporting Visual Studio and not Visual Studio Code.

**Comment by maxkatz6** [comment] 2021-06-20 00:15
@vleeuwenmenno Rider is recommended IDE to work with Avalonia and it works on Windows, Linux and macOS.
Also I want to mention, that Rider XAML editor works better with Avalonia, than Visual Studio does.

**Comment by vleeuwenmenno** [comment] 2021-06-20 00:56
Cool, I will give Rider a try but I don't like the fact it costs 139 euro per year ... VSCode is free and works very well but I will give Rider a try and see if it's worth the 139 euro per year. (Still doesn't quite solve this issue however it points out a hopefully good alternative)

**Comment by maxkatz6** [comment] 2021-08-30 00:02
Closing as duplicate of https://github.com/AvaloniaUI/Avalonia/issues/999 to simplify issue tracking

**Closed by maxkatz6** 2021-08-30 00:02 UTC
Labels: question, designer
