### ISSUE TITLE
Exceptions when window width or height is 0

### ISSUE THREAD

**Issue by zii-dmg** [AvaloniaUI/Avalonia#1584] opened 2018-05-13 10:42 UTC
Windows 7 SP1 x64, master 44f3358

* ControlCatalog, MainWindow.xaml - remove `MinWidth` and `MinHeight`
* ControlCatalog.Desktop, UseSkia()
* Launch ControlCatalog.Desktop, resize main window to minimum height.

Windows allows to resize window client height to 0, this leads to:
```
System.ArgumentException: 'Positive number required
Parameter name: size'
```
Stack trace:
```
Avalonia.DotNetFrameworkRuntime.dll!Avalonia.Shared.PlatformSupport.StandardRuntimePlatform.UnmanagedBlob.UnmanagedBlob(Avalonia.Shared.PlatformSupport.StandardRuntimePlatform plat, int size) Line 61
Avalonia.DotNetFrameworkRuntime.dll!Avalonia.Shared.PlatformSupport.StandardRuntimePlatform.AllocBlob(int size) Line 26
Avalonia.Skia.dll!Avalonia.Skia.BitmapImpl.BitmapImpl(int width, int height, Avalonia.Vector dpi, Avalonia.Platform.PixelFormat? fmt) Line 46
Avalonia.Skia.dll!Avalonia.Skia.DrawingContextImpl.CreateLayer(Avalonia.Size size) Line 361
Avalonia.Visuals.dll!Avalonia.Rendering.RenderLayer.ResizeBitmap(Avalonia.Size size, double scaling) Line 35
Avalonia.Visuals.dll!Avalonia.Rendering.RenderLayers.Update(Avalonia.Rendering.SceneGraph.Scene scene, Avalonia.Platform.IDrawingContextImpl context) Line 37
Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.Render(Avalonia.Rendering.SceneGraph.Scene scene) Line 209
Avalonia.Visuals.dll!Avalonia.Rendering.DeferredRenderer.OnRenderLoopTick(object sender, System.EventArgs e) Line 432
Avalonia.Visuals.dll!Avalonia.Rendering.DefaultRenderLoop.InternalTick() Line 100
Avalonia.Win32.dll!Avalonia.Win32.RenderLoop.StartCore.AnonymousMethod__0(uint id, uint uMsg, System.UIntPtr user, System.UIntPtr dw1, System.UIntPtr dw2) Line 19
```

I have to enable breaking on ArgumentException in Visual Studio or exceptions just spamming output window.

Checks for 0 is needed in some places.

**Comment by Gillibald** [comment] 2018-05-13 12:17
I wonder how you reach a size of zero. If there are grips to resize there should be a border with a Thickness > 0.

**Comment by MarchingCube** [comment] 2018-05-13 12:53
Resize grips are not a part of a client area, so you can have 0x0 client size and window frame around it (with resize grips, etc.). I guess the renderer simply shouldn’t create a layer in this case.

**Comment by grokys** [comment] 2019-03-02 13:18
Duplicate of #1411.

**Closed by grokys** 2019-03-02 13:18 UTC
Labels: bug, rendering
