### ISSUE TITLE
ListBox slow rendering

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#12188] opened 2023-07-14 01:44 UTC
In v11.0.0

With the Preview releases, scrolling ListBoxes was fast. Instant without lag.

In the final v11.0.0, scolling a standard ListBox with text content (using FluentAvalonia) has some lag. It it noticeably slower to render.

OS: Garuda Linux

I'll note that scrolling through a long list of media players renders instantly. Only the ListBox is slow.

**Comment by mysteryx93** [comment] 2023-07-15 21:35
After publishing the app, the performance problem is gone.

Maybe it's just when debug is enabled?

**Comment by danielmayost** [comment] 2023-07-16 07:11
You may look in the debug console if you see a large amount of errors, in the debug mode it slows down the application, and also implies that you probably did something wrong.

**Comment by mysteryx93** [comment] 2023-07-16 07:25
> [Binding]Error in binding to 'Avalonia.Xaml.Interactions.Core.InvokeCommandAction'.'Command': 'Null value in expression '{empty}' at ''.'(InvokeCommandAction #57281770)

```xaml
<ListBox ItemsSource="{Binding Files.Source}" x:CompileBindings="False"
         SelectedItem="{Binding Files.CurrentItem, Mode=TwoWay}" TabIndex="8" Background="{x:Null}">
    <ListBox.Styles>
        <Style Selector="ListBoxItem">
            <Setter Property="TabIndex" Value="5" />
        </Style>
    </ListBox.Styles>
    <ListBox.ItemTemplate>
        <DataTemplate>
            <TextBlock Text="{Binding Display}">
                <Interaction.Behaviors>
                    <RoutedEventTriggerBehavior RoutedEvent="{x:Static InputElement.DoubleTappedEvent}">
                        <InvokeCommandAction
                            Command="{Binding ViewModel.Play, RelativeSource={RelativeSource AncestorType=views:MainView}}"
                            CommandParameter="{x:Null}" />
                    </RoutedEventTriggerBehavior>
                </Interaction.Behaviors>
            </TextBlock>
        </DataTemplate>
    </ListBox.ItemTemplate>
</ListBox>
```

Double-click works though.

**Comment by danielmayost** [comment] 2023-07-16 07:45
I had the same problem with `ItemsRepeater`, apparently a bug, it seems that the first moment the element is loaded, it's not yet connected to the `DataContext` and throws an error, and then the `DataContext` connects.

At least it's not a blocking bug.

**Comment by maxkatz6** [comment] 2023-07-16 21:54
Yeah, closing as a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/5762

**Closed by maxkatz6** 2023-07-16 21:54 UTC
Labels: bug
