### ISSUE TITLE
HotKey doesn't work on MenuItem until it is opened

### ISSUE THREAD

**Issue by izaksuilov** [AvaloniaUI/Avalonia#14367] opened 2024-01-26 20:24 UTC
## Describe the bug
The hotkey on the MenuItem is not working until you open it at least once.

## To Reproduce
[Example here](https://github.com/izaksuilov/AvaloniaHotKeyBug)

1. Create menu
2. Add into it Menu Item
3. Add into Menu Item one more Menu Item with command and hotkey

```
<Menu>
  <MenuItem Header="Open me and after that the hotkey will work">
    <MenuItem Header="Test Command"
              Command="{Binding TestCommand}"
              HotKey="Ctrl+O" InputGesture="Ctrl+O"/>
  </MenuItem>
</Menu>
```

## Expected behavior
The hotkey should work without opening the MenuItem

## Environment 

- OS: Windows 11
- Avalonia-Version: 11.0.7

**Comment by jp2masa** [comment] 2024-01-27 01:18
Duplicate of #2441?

**Comment by izaksuilov** [comment] 2024-01-27 01:38
> Duplicate of #2441?
I think yes, but it worked in avalonia 10 and after upgrading to avalonia 11 it stopped working

**Comment by timunie** [comment] 2024-01-29 08:47
Maybe chaning the ItemsPanel to StackPanel helps here to cancel virtualization. Anyways, I'm closing this as duplicate. We will track it further in the original issue.

**Closed by timunie** 2024-01-29 08:47 UTC
Labels: bug
