### ISSUE TITLE
Tooltip background color doesn`t change when changing theme

### ISSUE THREAD

**Issue by trofimchik** [AvaloniaUI/Avalonia#14596] opened 2024-02-12 11:14 UTC
After hovering over a tooltip and changing the theme, the background color of this tooltip does not change

1. Hover over the tooltip
2. Change theme
3. Hover over the tooltip again

![image](https://github.com/AvaloniaUI/Avalonia/assets/49271052/5d1680e9-4323-407b-aa6f-413b546abc27)
![image](https://github.com/AvaloniaUI/Avalonia/assets/49271052/ae05f9e8-c01d-4f02-9f19-7c158ef1dcd8)
![image](https://github.com/AvaloniaUI/Avalonia/assets/49271052/95bf7c0b-7077-447f-b3db-dac4aa987740)
![image](https://github.com/AvaloniaUI/Avalonia/assets/49271052/8ec1744b-e414-43c8-ab78-a25661c3cc3f)

- OS: Windows
- Avalonia-Version: 11.0.9/11.1.999-cibuild0044824-beta

**Comment by timunie** [comment] 2024-02-12 11:51
which Theme is this?

**Comment by trofimchik** [comment] 2024-02-12 11:56
SimpleTheme

**Comment by timunie** [comment] 2024-02-13 07:34
Okay tested with SimpleTheme and FluentTheme. Both suffer from it. Might be a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/14145

**Comment by KyrietS** [comment] 2024-08-20 22:49
I have the same problem. If you only use `ToolTip` with `String` here is my workaround:

```csharp
    public MainWindow()
    {
        InitializeComponent();
        
        // Subscribe to ActualThemeVariantChanged event
        Application.Current!.ActualThemeVariantChanged += (_, _) =>
        {
            // Iterate over all logical descendants of the window
            foreach (var child in this.GetLogicalDescendants())
            {
                // Only a Control can have a ToolTip
                if (child is Control control)
                {
                    var toolTip = ToolTip.GetTip(control);
                    if (toolTip is string toolTipString)
                    {
                        // Set a new Tip with the same value to force the ToolTip to update
                        // Note: you cannot use ToolTip.SetTip(control, toolTipString) because it will not work
                        ToolTip.SetTip(control, new String(toolTipString));
                    }
                }
            }
        };
    }
```

I've added this to my MainWindow. Every time there is a theme change I iterate over all GUI elements (😱) and manually update each ToolTip to force a refresh.

![light](https://github.com/user-attachments/assets/59a8a73b-f58e-4ab1-88ce-fcc59d6cd19c)
![dark](https://github.com/user-attachments/assets/92eed0e1-dbb4-4602-99b1-8ac4588edfd1)

If it's stupid but it works, it's not stupid 😄
I hope the Avalonia Team (or some other kind soul) will fix it some day 🙏

**Comment by timunie** [comment] 2024-08-21 06:21
@KyrietS If you wanted to try to fix it, you are welcome to give it a try 🚀

**Comment by maxkatz6** [comment] 2024-08-21 06:33
It might be already fixed in 11.2, since ToolTip use Popup internally now, which supports that already.

**Comment by timunie** [comment] 2024-08-21 06:50
In that case @KyrietS would be nice if you could test 11.2.0-beta1 with your sample to verify this.

**Comment by KyrietS** [comment] 2024-08-21 07:53
Thank you for the encouragement @timunie 🤗 But you can see my workaround above. If I submitted something like this I would be crushed in review 😅 I don't even understand what attached property is... yet (I'll get there). That's why my fix is so silly. I hope some day I'll be confident enough to submit PRs under my name 🦔.

@maxkatz6 Thanks. Today I'll check the version you pointed out and I'll let you guys know.

**Comment by timunie** [comment] 2024-08-22 05:58
@trofimchik after feedback I'll close this issue. If you have still an issue with 11.2.0-beta1 please ping me and we can reopen this one

**Closed by timunie** 2024-08-22 05:58 UTC
Labels: bug
