### ISSUE TITLE
Unable to Bind to IsFocused Property in XAML

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1658] opened 2018-06-06 09:56 UTC
Event with Binding Mode=OneWay.

Portable.Xaml tries to set the property.

**Comment by jkoritzinsky** [comment] 2018-06-07 02:08
The `IsFocusedProperty` is defined as a read-only DirectProperty:

https://github.com/AvaloniaUI/Avalonia/blob/e7df62ab2c086af816ecf8d3bb789ca73641c9e6/src/Avalonia.Input/InputElement.cs#L45-46

**Comment by danwalmsley** [comment] 2018-06-07 07:50
I should be able to bind to it though right?  As long as my binding doesn't try to write to it

**Comment by danwalmsley** [comment] 2018-06-07 13:40
OneWayToSource doesn't work either!

**Comment by jkoritzinsky** [comment] 2018-06-07 13:41
OK that's definitely a bug. I'll investigate!

**Comment by danwalmsley** [comment] 2018-06-07 13:52
https://github.com/AvaloniaUI/Avalonia/commit/8300d3a6c11606b6c6cd30d9403b875e464f9ccf here is a repro for control catalog.

Iv added binding to TextBoxPage and used TextBoxPage.xaml.cs as data context.

**Comment by jkoritzinsky** [comment] 2018-06-07 17:06
Ok. There were two issues in here. One was a broken `IsReadOnly` check when the `skipReadOnlyCheck` parameter was true. That was easy to fix. The other problem is more annoying. Since the property is read-only, Portable.Xaml wasn't assigning it a value, which makes sense but stops Bindings from being assigned. I can easily change that by lying to the XAML layer that all `AvaloniaProperty`s are not read-onlyand just avoiding setting read-only ones when setting the value. However, this causes bindings with `Mode=OneWay/TwoWay/etc` to crash when applied. Since we apply our bindings in a delayed manner in XAML, this causes a crash not when the XAML is parsed, but when the element is added to the visual tree.

So, how do we want to fix this? Do we want to enable a later crash if the wrong binding mode is set, or just disallow bindings on read-only AvaloniaProperties? For reference, WPF doesn't allow OneWayToSource bindings on read-only properties either. And we would still allow them in code, just not in XAML.

**Comment by grokys** [comment] 2019-03-04 13:05
I think we're going to have to close this as `wontfix`: this is a problem with XAML in that it doesn't allow bindings to read-only properties by design as @jkoritzinsky described.

**Comment by kekekeks** [comment] 2019-03-04 13:50
I think we can allow to do that with compiler at some point, so I'll reopen this one

**Comment by MihaMarkic** [comment] 2019-04-12 11:51
I'd like to see this working as well. Just tried to bind Bounds property...

**Comment by delaney31** [comment] 2019-06-13 21:15
Is this still true ..."XAML doesn't allow bindings to read-only properties by design as @jkoritzinsky described" ??

**Comment by jkoritzinsky** [comment] 2019-06-13 21:24
With the change to using XamlIL I am not sure if my statement is still true. I’d need to check again. I suspect it has changed.

**Comment by alexander-miglis** [comment] 2020-09-26 10:05
> OneWayToSource

I have the same issue

**Comment by alexander-miglis** [comment] 2020-09-26 10:06
> OneWayToSource doesn't work either!

I have the same issue

**Comment by maxkatz6** [comment] 2022-11-22 03:20
We migrated to a new compiler, OneWayToSource seems to work

**Closed by maxkatz6** 2022-11-22 03:20 UTC
Labels: bug, area-xaml
