### ISSUE TITLE
PlatformImpl.BeginResizeDrag() does not work on Mac 

### ISSUE THREAD

**Issue by npolyak** [AvaloniaUI/Avalonia#7140] opened 2021-12-13 01:49 UTC
The full code for the sample is located under https://github.com/npolyak/NP.Avalonia.Demos/tree/main/NP.Demos.VisualSamples/NP.Demos.CustomWindowResizeBug.
I created a very simple window without Chrome (I set SystemDecorations property to "None"). 
Create a red border on the right hand side for resizing. 

    <Window xmlns="https://github.com/avaloniaui"
            xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	        xmlns:np="https://np.com/visuals"
            x:Class="NP.Demos.CustomWindowResizeBug.MainWindow"
            SystemDecorations="None"
            Background="LightGray"
            Width="400"
            Height="300">
	    <VisualLayerManager>
		    <Grid>
			    <Border Name="Right" 
			            Background="Red"  
			            Width="20"
			            Cursor="SizeWestEast"
			            HorizontalAlignment="Right"
			            VerticalAlignment="Stretch"/>
		    </Grid>
	    </VisualLayerManager>
    </Window>

Then, following "Decorated Window" example from the Catalogue, I found the border in the code behind and 
added a handler to its PointerPressedEvent:

    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            ...

            Border b = this.FindControl<Border>("Right");

            b.PointerPressed += B_PointerPressed;
        }

        private void B_PointerPressed(object? sender, PointerPressedEventArgs e)
        {
            PlatformImpl?.BeginResizeDrag(WindowEdge.East, e);
        }

       ...
    }

Window resize after pressing on the red border and dragging works fine on Windows 10 and linux, but does not work on Mac (at least it does not work on Mac Catalina)

**Comment by kekekeks** [comment] 2021-12-13 07:50
@danwalmsley we've used to have ManagedDragHelper as a polyfill for macOS. What happened to it?

**Comment by kekekeks** [comment] 2021-12-13 07:52
https://github.com/AvaloniaUI/Avalonia/blob/0.10.10/src/Shared/WindowResizeDragHelper.cs - still there but not used in macOS backend code.

**Comment by npolyak** [comment] 2021-12-13 14:06
Can it be fixed? Thanks

**Comment by maxkatz6** [comment] 2022-03-26 03:36
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/3834

**Closed by maxkatz6** 2022-03-26 03:36 UTC
Labels: bug
