### ISSUE TITLE
Binding commands for submenu items makes whole submenu grayed out

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/Avalonia#3100] opened 2019-10-11 16:27 UTC
```xml
<ContextMenu>
                
    <MenuItem
        Header="Activate"
        Command="{Binding ActivateCommand}">
        
        <MenuItem.Icon>
            <Image
                Classes="Icon"
                Source="Activate.png" />
        </MenuItem.Icon>
        
    </MenuItem>
    
    <MenuItem
        Header="Commands"
        Items="{Binding MenuItems}">
        
        <MenuItem.Icon>
            <Image
                Classes="Icon"
                Source="resm:Command.png" />
        </MenuItem.Icon>
        
        <MenuItem.Styles>
            <Style Selector="MenuItem">
                <Setter Property="Icon">
                    <Template>
                        <Image
                            Classes="Icon"
                            Source="resm:Command.png" />
                    </Template>
                </Setter>
                <Setter Property="Header" Value="{Binding Name}" />
                <!-- <Setter Property="Command" Value="{Binding SelectCommand}" /> -->
                <!-- <Setter Property="CommandParameter" Value="{Binding}" /> -->
            </Style>
        </MenuItem.Styles>
        
    </MenuItem>
    
</ContextMenu>
```

When SelectCommand is uncommented it makes whole "Commands" submenu disabled. Doesn't matter what value the SelectCommand has, even simple stub or null value grays out the submenu.

0.8.999 - binding disables the submenu

0.8 - binding works as expected and does not result in disabled menu

<img width="255" alt="image" src="https://user-images.githubusercontent.com/892945/66668475-0535be80-ec5e-11e9-9f23-fa6d1dd78605.png">

**Comment by grokys** [comment] 2019-10-11 18:29
It sounds to me like `SelectCommand` can't be found, is this correct?

**Comment by x2bool** [comment] 2019-10-11 18:59
Sorry if the description is not clear. SelectCommand is bound to the items under "Commands" menu.

It is supposed to look like this:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/892945/66676501-4fc03680-ec70-11e9-8f6a-5fd1d3563b7a.png">

Those submenu items have bindings to this model:

```csharp
public class MenuItemModel
    {
        public string Name { get; set; }
        
        public ReactiveCommand<MenuItemModel, Unit> SelectCommand { get; set; }
            = ReactiveCommand.Create<MenuItemModel, Unit>(_ => Unit.Default);
    }
```

As you can observe on the screenshot it has Name and SelectCommand properties, where Name is the name of the command. In my example names are: "SCAN, SCAN MATCH, KEYS", and bindings to this property do work as they worked before. But when the binding to the SelectCommand appears whole menu is disabled for some reason, and submenu items are not accessible ar all

**Comment by x2bool** [comment] 2019-10-11 19:04
BTW can this be related to CommandProperty becoming direct property recently? It was StyledProperty not too long ago.

```csharp
public static readonly DirectProperty<MenuItem, ICommand> CommandProperty =
            Button.CommandProperty.AddOwner<MenuItem>(
                menuItem => menuItem.Command, 
                (menuItem, command) => menuItem.Command = command, 
                enableDataValidation: true);
```

**Comment by chhadidg** [comment] 2020-07-31 15:45
Question: Is this issue solved? Running Avalonia 0.9.11. MenuItem is grayed out and command is not working on a ContextMenu.
`<MenuItem
                    Header="{Binding ContextMenuAddSpecNode, FallbackValue=Add}"
                    Command="{Binding ProjectContextMenuAddSpecNode}"
                    CommandParameter="{Binding ElementName=MainWindow}"></MenuItem>`

**Comment by maxkatz6** [comment] 2020-07-31 15:50
@chhadidg issue is not closed, so it probably is not solved.
But you can check it with 0.10.0-preview2 nuget version just to be sure.

**Comment by chhadidg** [comment] 2020-07-31 16:01
Thanks. Is there any other way to execute a command from a contextmenu menuitem?

**Comment by Kermel** [comment] 2020-12-04 00:06
Hi, any news on this topic ?

**Comment by lordzomat** [comment] 2020-12-23 16:41
I have the same issue with the latest stable version and the following context menu. I cannot get it to work, is there a known workaround?

```
<ContextMenu IsVisible="{Binding IsRootNode}">
	<MenuItem Header="resx:ContextMenuRemoveRootNode" Command="{Binding RemoveRootNodeCommand}"></MenuItem>
</ContextMenu>
```

Testing with 0.10.0-rc1 is not possible at the moment because it crashes with a StackOverflowException which i could not fix

**Comment by lordzomat** [comment] 2020-12-23 17:46
I created a small test application using the latest `0.10.0-rc1` and the error is still there. Not able to get the context menu to work.

**Comment by Kermel** [comment] 2020-12-23 21:02
For now, I am using this solution (hereby an example from my menu with the option to switch between languages):

`<Menu>
    <MenuItem Header="Some menu item"/>
    <MenuItem Header="Options">      
        <MenuItem Header="Languages" Items="{Binding LanguageMenuItems}">
          <MenuItem.Styles>
            <Style Selector="MenuItem">
              <Setter Property="Icon" Value="{Binding Icon}"/>
              <Setter Property="Header" Value="{Binding LanguageCode}"/>
              <Setter Property="Command" Value="{Binding $parent[UserControl].DataContext.SwitchLanguageCommand}"/>
              <Setter Property="CommandParameter" Value="{Binding LanguageCode}"/>
            </Style>
          </MenuItem.Styles>          
        </MenuItem>  
    </MenuItem>
  </Menu>`

notes: 
- the whole menu is placed in my "TopMenu.axaml" user control and is using a TopMenuViewModel. This view model contains the collection of LanguageMenuItems (my instances of a simple "LanguageMenuItemModel"s with properties used in the Setters (Icon, LanguageCode))
- The working trick here is the command "SwitchLanguageCommand" I am using to bind on the menu item is also declared in the TopMenuViewModel

**Comment by maxkatz6** [comment] 2021-01-02 09:41
@Kermel @x2bool 
I took a look on this issue with your examples and found, that there is no any actual bug, but only unclear behavior.
When you set Style to the parent <MenuItem> element (Commands or Languages in your examples), style is also applied on this item itself. And it can't find command in the parent DataContext, so it shows disabled menu.

It can be fixed with more specific Selector, that will not match parent item, but only its children. In my example "SubItems" class will filter items:
```xaml
       <MenuItem Header="Languages" Items="{Binding LanguageMenuItems}" Classes="SubItems">
         <MenuItem.Styles>
           <Style Selector="MenuItem.SubItems MenuItem">
             <Setter Property="Icon" Value="{Binding Icon}"/>
             <Setter Property="Header" Value="{Binding LanguageCode}"/>
             <Setter Property="Command" Value="{Binding SwitchLanguageCommand}"/>
             <Setter Property="CommandParameter" Value="{Binding LanguageCode}"/>
           </Style>
         </MenuItem.Styles>          
       </MenuItem>  
```

**Comment by maxkatz6** [comment] 2021-01-02 09:44
@lordzomat I am not sure if you have same issue. But I already see, you have created another one - https://github.com/AvaloniaUI/Avalonia/issues/5212

**Comment by maxkatz6** [comment] 2021-01-02 09:45
I am not sure if this issue can be closed as "by design" or can we do something with this to make behavior more clear.
@grokys FYI

**Comment by lordzomat** [comment] 2021-01-02 12:20
@maxkatz6 i can reproduce the issue using the latest version with the test application mentioned in issue #5212 
i have no style defined on that so it must be caused by another thing? If you want i can provide you the application.

**Comment by mstumpf585** [comment] 2021-01-21 22:44
Is it possible to add @maxkatz6  example to https://avaloniaui.net/docs/controls/menu ?

**Comment by Kermel** [comment] 2021-02-11 00:00
> 
> 
> @Kermel @x2bool
> I took a look on this issue with your examples and found, that there is no any actual bug, but only unclear behavior.
> When you set Style to the parent `<MenuItem>` element (Commands or Languages in your examples), style is also applied on this item itself. And it can't find command in the parent DataContext, so it shows disabled menu.
> 
> It can be fixed with more specific Selector, that will not match parent item, but only its children. In my example "SubItems" class will filter items:
> 
> ```
>        <MenuItem Header="Languages" Items="{Binding LanguageMenuItems}" Classes="SubItems">
>          <MenuItem.Styles>
>            <Style Selector="MenuItem.SubItems MenuItem">
>              <Setter Property="Icon" Value="{Binding Icon}"/>
>              <Setter Property="Header" Value="{Binding LanguageCode}"/>
>              <Setter Property="Command" Value="{Binding SwitchLanguageCommand}"/>
>              <Setter Property="CommandParameter" Value="{Binding LanguageCode}"/>
>            </Style>
>          </MenuItem.Styles>          
>        </MenuItem>  
> ```

Thank you, this helped solving my problem !
It would be good to add this to the available examples... :)

**Closed** 2022-12-09 02:08 UTC
Labels: by-design

**Comment by Unforsakennn** [comment] 2024-09-16 05:19
Good day to everyone!
I carefully studied this issue. But I don't find the solution for next menu level binding.
For example if "SCAN" command also has next menu level commands (SCAN1, SCAN2). How could I bind this collection to already binded menu item from previous menu level?
