### ISSUE TITLE
Pointer Position Jumps to 0,0 on Fast Movement

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#8796] opened 2022-08-21 03:36 UTC
**Describe the bug**

This was first noticed with the ColorPicker but I expect is applies to every control.. Pressing and holding on the spectrum then dragging outside the window bounds will cause the pointer position to report 0,0 (relative) before it is usually fixed. This shouldn't happen and causes jumps in the selected color.

**To Reproduce**

1. Go to the ColorPicker page of the ControlCatalog
2. On the far-right color spectrum Press/Hold/Drag to change color
3. While continuing to hold the left mouse button, drag the pointer outside the app window
4. Notice that the reported pointer position to the control is sometimes (0,0) instead of the last position before the pointer exited the app.

**Expected behavior**

Pointer position should never be reported as 0,0. Instead, either the last pointer position should be used -- or more accurately -- the pointer position clipped to the bounds of the focused control.

**Screenshots**

https://user-images.githubusercontent.com/17993847/185774278-b5d84be0-772a-4aba-a919-216167c8e82c.mp4

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

**Comment by robloo** [comment] 2022-08-26 00:35
This actually occurs for fast movement in general. If the mouse is moved quickly over the control it will happen even if the pointer doesn't leave the app window.

I do not think this is an issue with the ColorPicker and think it was working before some of the later PRs for composition or pointer events.

**Comment by danipen** [comment] 2022-08-26 07:07
@robloo do you think this issue is related to this behavior? 

When resizing a column in the `TreeDataGrid`, or dragging the `ScrollBar` I get some flicker in some controls and sometimes in the mouse pointer. 

It seems that the `Control` is getting called to `PointerExited `and `PointerEntered `very fast.

![flicker](https://user-images.githubusercontent.com/501613/186843316-07bde051-f0d4-481a-8175-3215f9e28f32.gif)
![flicker2](https://user-images.githubusercontent.com/501613/186843323-fc0be9b1-1f75-4092-89e4-9738aefc8464.gif)

**Comment by kekekeks** [comment] 2022-08-26 09:39
@danipen Please, file a separate issue since it seems to be a different bug

**Comment by robloo** [comment] 2022-08-26 09:43
@danipen It looks like your issue may be related to #8795. I also noticed some fast blinking in some  mouse over situations. You might just want to move your comment there.

**Comment by maxkatz6** [comment] 2022-09-13 18:32
Not a regression, as this bug existed before 11.0. Unlikely other pointer blinking related issues.

**Comment by robloo** [comment] 2022-11-13 21:08
@maxkatz6 I haven't seen this issue since #8918. Is there any reason to keep this open? #8957 seems to be something else.

**Comment by maxkatz6** [comment] 2022-11-14 06:55
@robloo dragndrop and blinking were unrelated, yes. But 0,0 jumping was supposed to be fixed by that PR. Not sure why it's not reproducible now, need to check.

**Comment by maxkatz6** [comment] 2022-12-21 23:15
Apparently, yes, even on older branch I can't reproduce it anymore after https://github.com/AvaloniaUI/Avalonia/pull/8918

**Closed by maxkatz6** 2022-12-21 23:15 UTC
Labels: bug
