### ISSUE TITLE
Space handling bug inside TextBox

### ISSUE THREAD

**Issue by a-tk-by** [AvaloniaUI/Avalonia#11692] opened 2023-06-07 14:03 UTC
If TextBox is placed inside ListBox, it ignores input of space character. If TextBox is inside ItemsControl, everything works as expected.

Here is the link of minimal repro project: https://github.com/a-tk-by/Avalonia-BugInList

There are two regions on Window: with ListBox (left one) and ItemsControl (on the right). Both have ItemsSource that is binded to the same property of very simple view model.
Data template of list item consists of a single TextBox that binds its Text to Value property of ViewModelItem.

**Desktop :**

- OS: Windows 10
- Version: 11.0.0-rc1.1

**Comment by rabbitism** [comment] 2023-06-07 14:06
maybe duplicate of https://github.com/AvaloniaUI/Avalonia/issues/9623

**Comment by tkefauver** [comment] 2023-06-14 19:27
Having this same issue in a `ListBoxItem` with an embedded WebView so I don't think its specific to `TextBox`.

If its any help, there's also a `TextBox` in my `ListBoxItem` and I made this as temporary workaround (using a tunneled `KeyDown` handler):

```
private void HandleKeyDown(object sender, KeyEventArgs e) {
            var tb = e.Source as TextBox;
            if (e.Key == Key.Space) {
                string pre_str = tb.Text.Substring(0, tb.SelectionStart);
                string post_str = tb.Text.Substring(tb.SelectionEnd);
                string new_text = pre_str + " " + post_str;
                int new_sel_start = tb.SelectionStart + 1;
                tb.Text = new_text;
                tb.SelectionStart = new_sel_start;
                tb.SelectionEnd = new_sel_start;
                e.Handled = true;
            }
}
```

**Comment by tkefauver** [comment] 2023-06-14 19:38
I fixed this problem in a `TextBox` subclass using a workaround I'll show below. But now as of `11.0.0-rc1.1` I'm also having this issue in an embedded WebView (that also has the `TextBox` subclass in the same `ListBoxItem`) so I don't think this problem is just for `TextBox`. 

Here's the workaround (uses a tunneled `KeyDown` handler):

```
private void HandleKeyDown(object sender, KeyEventArgs e) {
    var tb = e.Source as TextBox;
    if (e.Key == Key.Space) {
        string pre_str = tb.Text.Substring(0, tb.SelectionStart);
        string post_str = tb.Text.Substring(tb.SelectionEnd);
        string new_text = pre_str + " " + post_str;
        int new_sel_start = tb.SelectionStart + 1;
        tb.Text = new_text;
        tb.SelectionStart = new_sel_start;
        tb.SelectionEnd = new_sel_start;
        e.Handled = true;
    }
}
```

**Closed** 2023-06-17 01:03 UTC
Labels: bug
