### ISSUE TITLE
Window: Allow closing Owner/Parent of a child window without closing the child

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#5346] opened 2021-01-23 18:30 UTC
Since https://github.com/AvaloniaUI/Avalonia/pull/3943 it is impossible to show a child window with an Owner (using `Show(Window parent)`) and then close the Owner window afterwards. A workaround is to use `Show()` so it doesn't get added to the Owner's `_children`, but then it's impossible to do some things with the Owner such as use `WindowStartupLocation.CenterOwner` to set the initial positioning of the child window.

`0.10.999-cibuild0012650-beta`

**Comment by grokys** [comment] 2021-01-27 07:59
Do you mean that closing the parent window now also closes the child? Looking at the linked issue in apollo-studio this appears to be what you're seeing.

I'm no expert on this but the new behavior would appear to be correct to me? I'd instinctively expect that closing a parent window would close child windows. Looking at [WPF docs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.owner?view=net-5.0) that's what appears to happen there too:

> Once this relationship is established, the following behaviors are exhibited:
> - If an owner window is minimized, all its owned windows are minimized as well.
> - If an owned window is minimized, its owner is not minimized.
> - If an owner window is maximized, both the owner window and its owned windows are restored.
> - An owner window can never cover an owned window.
> - Owned windows that were not opened using ShowDialog are not modal. The user can still interact with the owner window.
> - **If you close an owner window, its owned windows are also closed.**
> - If an owned window was opened by its owner window using Show, and the owner window is closed, the owned window's Closing event is not raised.

**Comment by grokys** [comment] 2021-01-27 08:03
Labeling this as by design for now. @MarchingCube might have some input as he implemented child windows.

**Comment by mat1jaczyyy** [comment] 2021-01-27 08:57
@grokys Yes, this is what I mean. Sure, in most apps we would expect this kind of hierarchy.

My app is specific in that it should be used (in an always of top state, if the user prefers it) at the same time as another which is usually maximized on the screen (my app handles visual effect rendering/editing, while the other handles live audio), so my windows are intentionally a smaller size and some functionalities are separated into multiple windows for easier reorganization.

In this case it's convenient for the user to be able to close any window on the screen, so long as there is at least one window left, the app considers the user is working on the currently open file. Only when the last window is closed will my app ask the user if they intended to quit in case they had unsaved changes.

I don't know if my app could be designed better, but considering the concurrent use I think it's suitable in this case, and my users have never complained of it being a confusing interface in the 1.5 years of my app being publicly released. Of course, I would definitely avoid this kind of design when it comes to a standalone app, and I can understand why this seems out of place to ask for.

Honestly, if you could agree on an API for detaching owners from children, this is something that I can likely PR into Avalonia myself.

**Comment by workgroupengineering** [comment] 2021-01-27 11:17
Hi @mat1jaczyyy ,
You could try making a 1px transparent window with no decorations that run the other windows.

**Comment by MarchingCube** [comment] 2021-01-31 21:21
@grokys This might be the reason why WPF has a separate owner/parent setup. Since at least on win32 parent windows will just close child windows anyway. While it is a bit confusing perhaps it allows for better control. 
I have no problem with matching WPF API here just so we can cover all use cases.

**Closed** 2023-01-25 06:25 UTC
Labels: by-design
