### ISSUE TITLE
11.0.6 breaks text box editing

### ISSUE THREAD

**Issue by rmcrackan** [AvaloniaUI/Avalonia#14110] opened 2024-01-04 14:57 UTC
* [My axaml](https://github.com/rmcrackan/Libation/blob/master/Source/LibationAvalonia/Dialogs/AccountsDialog.axaml)
* [My C#](https://github.com/rmcrackan/Libation/blob/master/Source/LibationAvalonia/Dialogs/AccountsDialog.axaml.cs)

In this grid's 'Audible/email login' column, in the bottom 'new' cell: the user should be able to double click the cell and type. This functions correctly in 11.0.5. In 11.0.6, typing isn't allowed.

I'm personally testing in Windows. Users have also reported it in Mac and Linux.

**Comment by maxkatz6** [comment] 2024-01-04 18:45
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/13928
Was already fixed in the nightly

**Closed by maxkatz6** 2024-01-04 18:45 UTC
Labels: bug

**Comment by rmcrackan** [comment] 2024-01-04 20:42
@maxkatz6 Much thanks! What does this mean in terms of when the fix will be live? Approx date?

**Comment by timunie** [comment] 2024-01-04 21:13
@rmcrackan you can already consume it using nightly builds or wait for 11.1 latest. No due date yet.
