### ISSUE TITLE
Distorted text rendering on a custom RenderTargetBitmap with transparent background

### ISSUE THREAD

**Issue by DrunkyBard** [AvaloniaUI/Avalonia#12441] opened 2023-08-04 15:15 UTC
**Describe the bug**
Text is being distorted after rendering on a custom instance of RenderTargetBitmap with transparent background

**To Reproduce**
Invoke the next code to render text:

```
var rt = new RenderTargetBitmap(new PixelSize(500, 500), new Vector(96d, 96d));
using (var ctx = rt.CreateDrawingContext())
{
    ctx.FillRectangle(Brushes.Transparent, new Rect(0d, 0d, 500d, 500d));
    ctx.DrawText(new FormattedText(
                     "Text on transparent background",
                     CultureInfo.CurrentUICulture, 
                     FlowDirection.LeftToRight,
                     new Typeface("Segoe UI"),
                     12d,
                     Brushes.Black), new Point(50d, 50d));
}

rt.Save("TransparentBackground.png");

using (var ctx = rt.CreateDrawingContext())
{
    ctx.FillRectangle(Brushes.Green, new Rect(0d, 0d, 500d, 500d));
    ctx.DrawText(new FormattedText(
                     "Text on colored background",
                     CultureInfo.CurrentUICulture, 
                     FlowDirection.LeftToRight,
                     new Typeface("Segoe UI"),
                     12d,
                     Brushes.Black), new Point(50d, 50d));
}

rt.Save("ColoredBackground.png");
```

This is the text that is being rendered on transparent background:
![TransparentBackground](https://github.com/AvaloniaUI/Avalonia/assets/1831879/25b5b2ec-d3ca-40e3-b905-94b77b412483)

and this is it's representation on colored background:
![ColoredBackground](https://github.com/AvaloniaUI/Avalonia/assets/1831879/7a6134c4-6c53-44b8-86b0-4accafc72190)

**Desktop (please complete the following information):**

- OS: tested on Windows 10
- Version: latest master

**Comment by Coloryr** [comment] 2024-03-25 12:39
I have same issue in Transparent Window
![image](https://github.com/AvaloniaUI/Avalonia/assets/26276037/2424fd1a-0308-4667-93de-968beb21d482)
The rendering result is different from Windows, how should I implement it.

**Comment by Gillibald** [comment] 2024-03-25 13:33
`RenderOptions.TextRenderingMode="Antialias"`

**Comment by maxkatz6** [comment] 2024-03-25 22:09
@Gillibald should this issue be closed as by design now? And since it can be configured.

**Comment by Gillibald** [comment] 2024-03-26 04:57
Y it is a limitation of ClearType and the results are expected

**Closed by Gillibald** 2024-03-26 04:57 UTC
Labels: bug, area-rendering, area-textprocessing

**Comment by Coloryr** [comment] 2024-03-26 05:51
> `RenderOptions.TextRenderingMode="Antialias"`

Thanks.
