### ISSUE TITLE
Rendering quality of images noticably lower than other solutions

### ISSUE THREAD

**Issue by NaamloosDT** [AvaloniaUI/Avalonia#1752] opened 2018-07-13 23:58 UTC
Rendering quality of images seems rather low. This issue is quite noticable when comparing side-by-side, and readability of small text is rather bad.

Image (left is windows image viewer, right is avalonia (rendering a bitmap on an image control)
![](https://saiko.is-a-good-waifu.com/aa11f6.png)

If there are any other solutions that will improve image quality, I'd love to hear. Thank you in advance!

**Comment by danwalmsley** [comment] 2018-07-14 13:23
Also check things like if Stretch is on

**Comment by danwalmsley** [comment] 2018-07-14 13:23
But I agree we need to improve this.

**Comment by jmacato** [comment] 2018-07-14 14:37
Duplicate of #1592

**Comment by jmacato** [comment] 2018-07-14 14:38
We'll need to fix the image interpolation on all backends and implement a `RenderOptions` API for users.

**Comment by NaamloosDT** [comment] 2018-07-14 15:18
@gillibald tried every back end thay didn't crash on my windows machine, little to no difference

**Closed** 2018-07-26 08:54 UTC
