### ISSUE TITLE
Avalonia DevTools crash app on Windows on corporate laptops

### ISSUE THREAD

**Issue by drweb86** [AvaloniaUI/Avalonia#15708] opened 2024-05-13 16:33 UTC
### Describe the bug

Avalonia.Diagnostics.Conventions crashes on corporate notebooks. I don't understand the reason. It tries to create folder that is already there `C:\Users\SiarheiKuchuk\Pictures\Screenshots` and fails.

```The type initializer for 'Avalonia.Diagnostics.Conventions' threw an exception.
   at Avalonia.Diagnostics.Conventions.get_DefaultScreenshotHandler()
   at Avalonia.Diagnostics.DevToolsOptions..ctor()
   at Avalonia.DevToolsExtensions.AttachDevTools(TopLevel root)
   at butil_ui.Views.MainWindow.InitializeComponent(Boolean loadXaml, Boolean attachDevTools) in D:\Personal\sources\butil\sources\butil-ui\obj\Debug\net8.0\Avalonia.Generators\Avalonia.Generators.NameGenerator.AvaloniaNameSourceGenerator\butil_ui.Views.MainWindow.g.cs:line 29
   at butil_ui.Views.MainWindow..ctor() in D:\Personal\sources\butil\sources\butil-ui\Views\MainWindow.axaml.cs:line 9
   at butil_ui.App.OnFrameworkInitializationCompleted() in D:\Personal\sources\butil\sources\butil-ui\App.axaml.cs:line 38
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at butil_ui.Desktop.Program.Main(String[] args) in D:\Personal\sources\butil\sources\butil-ui.Desktop\Program.cs:line 22
Avalonia.Diagnostics
Could not find file 'C:\Users\SiarheiKuchuk\Pictures\Screenshots'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Avalonia.Diagnostics.Conventions.get_DefaultScreenshotsRoot()
   at Avalonia.Diagnostics.Screenshots.FilePickerHandler..ctor(String title, String screenshotRoot)
   at Avalonia.Diagnostics.Screenshots.FilePickerHandler..ctor()
   at Avalonia.Diagnostics.Conventions..cctor()
System.Private.CoreLib
```

### To Reproduce

That's the first time i see it. It is not reproduced at home and at my own laptop.

### Expected behavior

No error obviously, but also showing real error would be nice.

### Avalonia version

11.0.10

### OS

Windows

### Additional context

NA

**Comment by drweb86** [comment] 2024-05-13 16:57
When i launch app via Ctrl+F5 - it works fine.

**Comment by drweb86** [comment] 2024-05-13 16:58
Basically idea is to add support for corporate environments?

**Comment by jp2masa** [comment] 2024-05-13 19:05
For reference: #14069.

**Comment by stevemonaco** [comment] 2024-05-13 22:19
`Conventions.DefaultScreenshotsRoot` should probably return `null` on exception and/or we need fallbacks. It is always accessed on startup regardless of config, so if it fails, then it's fine if `SuggestedStartLocation` gets set to `null`. Better than always crashing with no mitigation. I'm not a fan of I/O in a property getter either.

I'm still unsure what the system configuration issue is though since the directory is supposed to exist on @drweb86's system.

**Comment by thevortexcloud** [comment] 2024-05-14 07:52
I am guessing OneDrive is involved somehow and there is some weird folder redirection happening.

**Comment by drweb86** [comment] 2024-05-16 08:19
Directory is indeed exists. And yes, OneDrive create symbolic links to other directories.

**Comment by workgroupengineering** [comment] 2024-05-16 08:38
As the [docs](https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.createdirectory?view=net-8.0) explain, `Directory.CreateDirectory` ensure that the folder exists (eg: Linux does not have Screenshots folder) and creates it if it is not found.

Create a simple console app with this code and check if it works

```c#
                var dir = System.IO.Path.Combine(
                    Environment.GetFolderPath(Environment.SpecialFolder.MyPictures), "Screenshots");
                Directory.CreateDirectory(dir);
```

**Comment by drweb86** [comment] 2024-05-16 09:05
Hi. Bug stopped to reproduce since today. I don't know why. Probably Microsoft Defender was blocking it. I tried to delete screenshots folder and it still works. Also I tried to rename folder. First time - name remains the same, from second time - it gets changed. And anyway in this case it also works fine.

Console app also works good.

**Comment by timunie** [comment] 2024-05-17 06:25
closing as not reproducible anymore.

**Closed by timunie** 2024-05-17 06:25 UTC
Labels: bug, help-wanted, area-dev-tools
