### ISSUE TITLE
Add Alerts

### ISSUE THREAD

**Issue by fanoI** [AvaloniaUI/Avalonia#1283] opened 2017-11-19 15:11 UTC
I think an Alert class will need to be part of Avalonia, my first tough was on the Win32 MessageBox but it was Windows centric and so somewhat limiting so now I think Xamarin Alerts[1] are a better solution.

The only thing that I don't like is that there is not the possibility to not set an icon to make clear to the user the type of Alert; Xaramin has done this probably because not all OSes support icons and so the Alert with icon will feel alien in that OS.

One possible solution is to have two methods to create an Alert one for text only alerts and one in the case we want an Icon to be shown (if the underlying OS has no Icon support we simply decide to not show it).

This can be an example of API:

```cs
Alert(string title, string text, params IEnumerable<string>[] buttons);
Alert(string title, string text, Icon type, params IEnumerable<string>[] buttons);
```
I'm in doubt if makes sense to have simplified version of Alert called Info, Question, Warning and Error that automatically select the specific OS icon for the equivalent native MessageBox (for Error the X on the red circle for example).

[1] https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/navigation/pop-ups/

**Comment by jkoritzinsky** [comment] 2017-11-19 23:26
This is a duplicate of #670.

**Closed by jkoritzinsky** 2017-11-19 23:26 UTC
Labels: duplicate

**Comment by fanoI** [comment] 2017-11-20 15:11
No it is not "Native Message Box" but MessageBox done in Avalonia as any other element will have the Avalonia "style".

**Comment by jkoritzinsky** [comment] 2017-11-20 21:16
If you look at the comments on #670 you'll notice they propose a similar idea (specifically the comment about following UWP's implementation).
