### ISSUE TITLE
Hover transition on Button has strange behavior when moving over to fast

### ISSUE THREAD

**Issue by goudcode** [AvaloniaUI/Avalonia#10488] opened 2023-02-26 14:00 UTC
**Describe the bug**
When having a hover transitions on a Button, for example transforms, the behavior will flicker between the non hover and hover state.

**To Reproduce**
Create a Button in a Grid and add this styling:
```xml
<Grid.Styles>
  <Style Selector="Button">
	  <Setter Property="Background" Value="Transparent"/>
	  <Setter Property="Width" Value="50"/>
  </Style>
  <Style Selector="Button /template/ ContentPresenter">
	  <Setter Property="Transitions">
		  <Transitions>
			  <TransformOperationsTransition Property="RenderTransform" Duration="0:0:0.05"/>
		  </Transitions>
	  </Setter>
  </Style>
  <Style Selector="Button:pointerover /template/ ContentPresenter">
	  <Setter Property="Background" Value="Transparent"/>
	  <Setter Property="RenderTransform" Value="scale(1.1)" />
  </Style>
</Grid.Styles>
```

**Expected behavior**
The transform style should go to its initial state without bouncing.

**Screenshots**
Video to illustrate my issue:
https://user-images.githubusercontent.com/23435053/221414663-a32f1bf0-8af0-484a-aeb2-6eeea4b1c5cb.mp4

**Desktop (please complete the following information):**
- OS: Windows 10 (22H2)
- Version 0.10.18

**Comment by maxkatz6** [comment] 2023-02-26 14:35
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/5846
Workaround: define empty RenderTransform on `Button /template/ ContentPresenter`

**Closed by maxkatz6** 2023-02-26 14:35 UTC
Labels: bug
