### ISSUE TITLE
TransitioningContentControl with CrosFade flickers 1 frame for fade-out and fade-in in 11.0.0-preview7

### ISSUE THREAD

**Issue by llfab** [AvaloniaUI/Avalonia#11239] opened 2023-05-04 20:21 UTC
**Describe the bug**
After upgrading from 11.0.0-preview6 to 11.0.0-preview7 my TransitioningContentControl that uses a CrossFade-animation flickers 1 frame for each fade-out and fade-in as follows:
- the faded out control has decreasing opacity. Once that reaches 0 the control is displayed with opacity=1 for one frame
- the faded in control has increasing opacity. Once that reaches 1 the control is hidden or displayed with opacity=0 for one frame

**To Reproduce**

1. Go to https://github.com/llfab/Samples/tree/main/AvaloniaAnimationTest
2. Build and run application with existing preview7 => flickers
3. Change to preview6 (make sure to clean and rebuild solution) and run => runs correctly

**Expected behavior**
TransitioningContentControl transitions correctly as in preview6

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 11.0.0-preview7

**Additional context**
This may or may not be related to https://github.com/AvaloniaUI/Avalonia/issues/8805

**Comment by maxkatz6** [comment] 2023-05-04 21:01
Probably a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/11167

**Comment by llfab** [comment] 2023-05-04 21:03
> Probably a duplicate of #11167

Yes, most likely. Thanks.

**Closed** 2023-05-05 21:11 UTC
Labels: bug
