### ISSUE TITLE
loops animation

### ISSUE THREAD

**Issue by MosaIssei** [AvaloniaUI/Avalonia#9783] opened 2022-12-25 14:46 UTC
when I move fast on controls With Animation a loop animation happening  
for RenderTransform and Opacity i tested happened

https://user-images.githubusercontent.com/46990203/209472229-dc13838e-0ea4-4276-b5ff-57db21d2d4a6.mp4

code

```
<Style Selector="Button">
	<Setter Property="Background" Value="Transparent"/>
	<Setter Property="Margin" Value="4"/>
	<Setter Property="Padding" Value="2"/>

	<Setter Property="Transitions">
        <Transitions>
            <DoubleTransition Property="Opacity" Duration="0:0:0.1"></DoubleTransition>
            <TransformOperationsTransition Property="RenderTransform" Duration="0:0:0.1" />
        </Transitions>
    </Setter>
</Style>
...
<Style Selector="Button:pointerover">
	<Setter Property="Opacity" Value="0.7"></Setter>
	<Setter Property="Cursor" Value="hand"></Setter>
    <Setter Property="RenderTransform" Value="Scale(1.15)"/>
</Style>
```

- OS: windows 11
- Version 11.0.0 pre4
-

**Comment by DmitriyYukhanov** [comment] 2023-02-07 17:09
Duplicate of the https://github.com/AvaloniaUI/Avalonia/issues/5846

The workaround is to restore the `RenderTransform` to `none`:

```
<Style Selector="Button">
    <Setter Property="RenderTransform" Value="none"/>
    ...
</Style>
```

**Closed** 2023-02-07 17:09 UTC
Labels: bug
