### ISSUE TITLE
Avalonia on the WEB

### ISSUE THREAD

**Issue by TonyHenrique** [AvaloniaUI/Avalonia#1490] opened 2018-04-12 12:51 UTC
How to run Avalonia App on the Web Browser ?

There could be an Avalonia Page, we can run on the web browser.

**Comment by danwalmsley** [comment] 2018-04-12 14:03
Currently not possible, there is a discussion on how avalonia could run on Webassembly here
https://github.com/AvaloniaUI/Avalonia/issues/1387

**Comment by grokys** [comment] 2018-04-12 21:07
Closing this as a duplicate of #1387

**Closed by grokys** 2018-04-12 21:07 UTC
