### ISSUE TITLE
`WindowStartupLocation` has no effect in 0.10.10

### ISSUE THREAD

**Issue by duck-dev** [AvaloniaUI/Avalonia#6987] opened 2021-11-21 11:39 UTC
**Describe the bug**
I updated from Avalonia 0.10.3 to 0.10.10 recently and without changing anything in my code at all, a window suddenly didn't open in the center of the screen anymore and a dialog-window didn't open in the center of it's parent window anymore, but in the top left corner. It's important to note that I'm using `WindowStartupLocation="CenterScreen"`, respectively `WindowStartupLocation="CenterOwner"`.
It worked as expected in 0.10.3, but suddenly behaved differently after I updated to 0.10.10.

Are there any steps required in 0.10.10 that were not required in 0.10.3 I missed? I couldn't find anything in the changelogs of each version from 0.10.3 to 0.10.10.

**To Reproduce**

1. Use Avalonia 0.10.10
2. Add the `WindowStartupLocation` property definition to a window
3. Set it's value to `CenterScreen`
4. Open the window

The window doesn't open in the center of the screen, but rather in the top left corner. The same goes for dialog-windows with `WindowStartupLocation` being set to `CenterOwner`.

**Expected behavior**
The property `WindowStartupLocation` should do what it's supposed to do. In this case, open a window in the center of the screen or the parent-window.

**Desktop (please complete the following information):**

- OS: Linux (Pop! OS 21.04) <- based on Ubuntu
- Avalonia Version: 0.10.10 (updated from NuGet package)

**Comment by maxkatz6** [comment] 2021-11-21 23:33
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/6433

**Closed by maxkatz6** 2021-11-21 23:33 UTC
Labels: bug
