### ISSUE TITLE
ScrollViewer doesn't respect size constraint

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#3002] opened 2019-09-16 21:36 UTC
I added a simple ScrollViewer to add a vertical scrollbar:
```xaml
    <ScrollViewer IsVisible="{Binding MovesVisible}" VerticalScrollBarVisibility="Auto">
      <StackPanel Orientation="Vertical">
        <ItemsControl Items="{Binding Moves}">
          <ItemsControl.ItemsPanel>
            <ItemsPanelTemplate>
              <WrapPanel Orientation="Horizontal"/>
            </ItemsPanelTemplate>
          </ItemsControl.ItemsPanel>
        </ItemsControl>
        <ItemsControl Items="{Binding Party}">
          <ItemsControl.ItemsPanel>
            <ItemsPanelTemplate>
              <WrapPanel Orientation="Horizontal"/>
            </ItemsPanelTemplate>
          </ItemsControl.ItemsPanel>
        </ItemsControl>
      </StackPanel>
    </ScrollViewer>
```
The result:
![image](https://user-images.githubusercontent.com/29823718/64994832-b0de2f80-d8a7-11e9-9edd-5656d862baa6.png)

The original xaml:
```xaml
    <StackPanel IsVisible="{Binding MovesVisible}" Orientation="Vertical">
      <ItemsControl Items="{Binding Moves}">
        <ItemsControl.ItemsPanel>
          <ItemsPanelTemplate>
            <WrapPanel Orientation="Horizontal"/>
          </ItemsPanelTemplate>
        </ItemsControl.ItemsPanel>
      </ItemsControl>
      <ItemsControl Items="{Binding Party}">
        <ItemsControl.ItemsPanel>
          <ItemsPanelTemplate>
            <WrapPanel Orientation="Horizontal"/>
          </ItemsPanelTemplate>
        </ItemsControl.ItemsPanel>
      </ItemsControl>
    </StackPanel>
```
Original result:
![image](https://user-images.githubusercontent.com/29823718/64994958-00246000-d8a8-11e9-9183-8b9da204e2eb.png)

Sorry about the items being different in the two screenshots; my program randomizes the items each boot. Note that there are 8 colored buttons and 9 plain buttons in each case.

**Comment by Kermalis** [comment] 2019-09-16 22:05
I tested with 127 buttons and it still lined them all up in a straight line with no scrollbar.

**Comment by Kermalis** [comment] 2019-09-16 22:16
If I manually set the StackPanel's Width to 512 (which is the width of the control, so it should be the width of the ScrollViewer and StackPanel by default), then it will not go out the side. However, if I specify the StackPanel's Height to 128 (which is the height of the control), then I still get no vertical scrollbar and they go down as if I had no ScrollViewer.
![image](https://user-images.githubusercontent.com/29823718/64996916-36181300-d8ad-11e9-9583-7ccd2383c96e.png)
(The above screenshot is with the 127 buttons)

Settings Width and/or Height of the ScrollViewer does absolutely nothing, which is probably the bug.

**Comment by ahopper** [comment] 2019-09-17 05:06
Try setting horizontalScrollbarVisibility to disabled. Also what is the ScrollViewer contained in?

**Comment by Kermalis** [comment] 2019-09-17 15:01
Setting HorizontalScrollbarVisibility to disabled works but only when I manually set Width and Height of the ScrollViewer. If I don't, then they go down forever with no scrollbar (but don't go out sideways forever, which is weird.)
The ScrollViewer is in a StackPanel with Orientation=Vertical and that StackPanel is in a UserControl.

**Comment by ahopper** [comment] 2019-09-17 15:11
I think the outer StackPanel will be giving the ScrollViewer infinite room

**Comment by Kermalis** [comment] 2019-09-17 16:55
You're right, when I remove the outer StackPanel the problem goes away. That's pretty weird.

**Comment by grokys** [comment] 2019-09-17 22:27
This is the same as WPF (https://stackoverflow.com/questions/802821/how-can-i-get-scrollviewer-to-work-inside-a-stackpanel) which our `StackPanel` and `ScrollViewer` controls are based on, so I'd say this is by design. Going to close the issue.

**Closed by grokys** 2019-09-17 22:27 UTC
