### ISSUE TITLE
ProgressBar Minimum, Maximum and Value Properties Anomaly

### ISSUE THREAD

**Issue by jmojiwat** [AvaloniaUI/Avalonia#5368] opened 2021-01-27 08:17 UTC
**Describe the bug**
Setting the Maximum value does not have any effect on where Value is represented visually on the ProgressBar.

Value is always treated as a percentage between 0 and 100 range regardless of Minimum or Maximum.

**To Reproduce**
1. Setting Maximum doesn't do anything.
```xaml
        <ProgressBar 
            Minimum="0"
            Maximum="500"  // doesn't matter what value is set here.
            Value="50"
            />
```
![image](https://user-images.githubusercontent.com/1379702/105958237-4f41ee00-60b5-11eb-8a04-a3abaca53207.png)

2. Here, Minimum acts as a percentage cut off point for Value, so Value will not show up visually until it is greater than Minimum.
```xaml
        <ProgressBar 
            Minimum="50"
            Maximum="100"
            Value="51"
            />
```
![image](https://user-images.githubusercontent.com/1379702/105959379-c926a700-60b6-11eb-9427-19c33b7b387d.png)

**Expected behavior**
Maybe consider having Minimum, Maximum and Value properties as simple values so that setting:
Minimum=50
Maximum=100
Value=75

or
Minimum=50
Maximum=150
Value=100

would yield

![image](https://user-images.githubusercontent.com/1379702/105958237-4f41ee00-60b5-11eb-8a04-a3abaca53207.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.10.0

**Comment by pr8x** [comment] 2021-01-27 12:26
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/4570 ?

**Comment by jmojiwat** [comment] 2021-01-28 03:48
I'm still new to applying themes. There is a

```xaml
<FluentTheme Mode="Light"/>
```
in App.axaml though.

But #4570 doesn't mention the behaviour when Minimum property is set to a value above 0.

**Closed** 2021-02-19 18:19 UTC
Labels: bug
