### ISSUE TITLE
Dialogs Rendering, WindowStartupLocation.CenterOwner, Dialog overlay and arm-linux

### ISSUE THREAD

**Issue by Alocin1982** [AvaloniaUI/Avalonia#6259] opened 2021-07-15 16:12 UTC
**Describe the bug**
Hi everybody!
First of all, thank you all for the great Job!
I've some questions and concerns about  WindowStartupLocation.CenterOwner on arm-linux (Raspbian, in this case, the latest version) and the difference between rendering of Window (and Dialogs) on Windows 10 and Raspbian.
This is my situation:

**To Reproduce**

1. In a UserControl, add a button and link its "click" to a function to generate a new Window dynamically from code behind.
2. Declare as property of the window its WindowStartupLocation = CenterOwner.
3. The Window will use as Content a new UserControl, with its ViewModel in and some methods...
4. As the last instruction of the method, call the Avalonia Dialog and lunch it...

This is the Code behind:

```
   public class Configurations : UserControl
    {
        public Border BackgroundBorder;
        private DialogsViewModel _dialogs = new DialogsViewModel();

        public Configurations() {
            InitializeComponent();
        }
        
        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);

            BackgroundBorder = this.Get<Border>(nameof(BackgroundBorder));

            var db = new ConfigurationsCommand().GetConfigurationsData();
            DataContext = new ConfigurationsModel(db);
        }

        private void BtnDeleteConfiguration_Click(object sender, RoutedEventArgs args)
        {
            var button = sender as Button;
            var idSelectedConfig = (int?) button?.Tag ?? 0;
            string message = "";
            string title = "";
            var icon = Icon.Info;
            try
            {
                var result = new ConfigurationsCommand().DeleteConfigurationById(idSelectedConfig);
                if (result)
                {
                    title = "Congratulations";
                    message = "Successfully deleted";
                    icon = Icon.Success;
                    InitializeComponent();
                }
            }
            catch (Exception e)
            {
                title = "Attention Please";
                icon =  Icon.Error;
                message = e.Message.Contains("The association between entity types 'Configurations' and 'Executions' has been severed") 
                    ? "Impossible to delete this entity" 
                    : e.Message;
            }
            _dialogs.ShowMessage(title, message, icon);
        }


        private void BtnCreateNewConfiguration_Click(object sender, RoutedEventArgs args)
        {
            var button = sender as Button;
            var idSelectedConfig = (int?)button?.Tag ?? 0;
            var window = new Window
            {
                Width = 300,
                HasSystemDecorations = false,
                Height = 250,
                WindowStartupLocation = WindowStartupLocation.CenterOwner
            };
            window.Content = new CreateEditConfiguration(idSelectedConfig, window, BackgroundBorder, this);

            BackgroundBorder.IsVisible = true;
            window.ShowDialog(GetWindow());
        }

        private void BtnEditConfiguration_Click(object sender, RoutedEventArgs args)
        {
            var button = sender as Button;
            var idSelectedConfig = (int?)button?.Tag ?? 0;
            var window = new Window
            {
                Width = 300,
                HasSystemDecorations = false,
                Height = 250,
                WindowStartupLocation = WindowStartupLocation.CenterOwner
            };
            window.Content = new CreateEditConfiguration(idSelectedConfig, window, BackgroundBorder, this);

            BackgroundBorder.IsVisible = true;
            window.ShowDialog(GetWindow());
        }

        Window GetWindow() => Program.MainWindow;
    }
```

**Expected behavior**
Obviously, the Window 10 version is the result I'd like to see on Raspbian too... See the screenshot (I translated some of the code behind...but the problem is not the text)
1. the centre of the owner (or the centre of screen) is not maintained
2. transparency is not managed
3. popup overlay is not reached

What did I miss?

**Screenshots**
This is the result:

![AVALONIA](https://user-images.githubusercontent.com/58053265/123553806-a095fc80-d77d-11eb-8ff1-324de14b0254.png)

**Desktop (please complete the following information):**

- OS: Linux ARM - Raspbian
- Version 10 (buster)

**Additional context**

This is the code I've in the Program.cs file:

```
public static void Main(string[] args) {
	BuildAvaloniaApp().Start(AppMain, args);
}

public static AppBuilder BuildAvaloniaApp()
{
	return AppBuilder.Configure<App>()
		.UsePlatformDetect()
		.With(new X11PlatformOptions
		{
			EnableMultiTouch = true,
			UseGpu = true,
			OverlayPopups = true

		})
		.With(new Win32PlatformOptions
		{
			EnableMultitouch = true,
			AllowEglInitialization = true
		})
		.UseSkia();
}

private static void AppMain(Application app, string[] args)
{
	MainWindow = new MainWindow();
	app.Run(MainWindow);
}
```
Is it a known issue...or is it only my "inexperience"?
Thank you in advance for your reply...

**Comment by mork2020** [comment] 2021-08-28 07:19
With Avalonia 0.10.5 the dialogs are displayed centered on a Raspberry Pi using WindowStartupLocation="CenterOwner".
The feature/behaviour broke with changes (0.10.5 -> 0.10.6) in the method ShowDialog in Windows.cs -
the order of the call to SetWindowStartupLocation(owner.PlatformImpl) changed.

I reverted the order of the call to SetWindowStartupLocation(owner.PlatformImpl), like it was in 0.10.5, and compiled 0.10.7 with this change. On my Raspberry Pi the dialogs are now displayed centered again.

**Comment by Gillibald** [comment] 2021-08-28 13:17
That isn't the correct fix, to be honest. The startup position should be set before the actual window is shown. So this needs to be fixed inside the X11 code.

**Comment by maxkatz6** [comment] 2021-11-21 23:34
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/6433

**Closed by maxkatz6** 2021-11-21 23:34 UTC
Labels: bug
