### ISSUE TITLE
Disable window title buttons

### ISSUE THREAD

**Issue by herrwinfried** [AvaloniaUI/Avalonia#10124] opened 2023-01-29 16:33 UTC
**Is your feature request related to a problem? Please describe.**

The CanResize value does not turn off the Linux maximize button. And for a more effective solution, I think there should be support for disabling maximize, minimize and close buttons.

**Comment by Aurumaker72** [comment] 2023-01-29 18:12
Which compositor is being used?

**Comment by herrwinfried** [comment] 2023-01-29 18:15
> Which compositor is being used?

Are you talking about the CanResize Value?

**Comment by maxkatz6** [comment] 2023-01-29 19:12
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/3422

**Comment by grokys** [comment] 2023-01-30 09:29
Reopening as this is actually a bug that's distinct from #3422: on Windows the maximize button is disabled if `CanResize == false`. On macOS it should be disabled, but it's not.

**Comment by herrwinfried** [comment] 2023-01-30 10:54
> Reopening as this is actually a bug that's distinct from #3422: on Windows the maximize button is disabled if `CanResize == false`. On macOS it should be disabled, but it's not.

It doesn't work on Linux.

**Comment by Coloryr** [comment] 2023-02-02 07:45
You can try to make a new `headcontrol`

like [this](https://github.com/Coloryr/ColorMC/blob/master/src/ColorMC.Gui/UI/Controls/HeadControl.axaml)
and use in Window
```
<Window
    x:Class="ColorMC.Gui.UI.Windows.AddGameWindow"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:setting="clr-namespace:ColorMC.Gui.Utils.LaunchSetting"
    xmlns:views="clr-namespace:ColorMC.Gui.UI.Controls"
    Title="ColorMC"
    Width="800"
    Height="450"
    MinWidth="800"
    MinHeight="450"
    d:DesignHeight="450"
    d:DesignWidth="800"
    Background="Transparent"
    ExtendClientAreaChromeHints="NoChrome"
    ExtendClientAreaTitleBarHeightHint="-1"
    ExtendClientAreaToDecorationsHint="True"
    SystemDecorations="BorderOnly"
    mc:Ignorable="d">
    <Grid>
        <views:HeadControl
            Title="{setting:Localize AddGameWindow.Title}"
            HorizontalAlignment="Stretch"
            VerticalAlignment="Top"
            Min="False" />
```

![{(D3MCLZSWNQ9066@O9K@X3](https://user-images.githubusercontent.com/26276037/216262390-e5cd6482-033d-4ee3-b967-0c7b76682fe4.png)

**Comment by herrwinfried** [comment] 2023-02-02 08:27
> You can try to make a new `headcontrol`
> 
> like [this](https://github.com/Coloryr/ColorMC/blob/master/src/ColorMC.Gui/UI/Controls/HeadControl.axaml) and use in Window
> 
> ```
> <Window
>     x:Class="ColorMC.Gui.UI.Windows.AddGameWindow"
>     xmlns="https://github.com/avaloniaui"
>     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>     xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
>     xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
>     xmlns:setting="clr-namespace:ColorMC.Gui.Utils.LaunchSetting"
>     xmlns:views="clr-namespace:ColorMC.Gui.UI.Controls"
>     Title="ColorMC"
>     Width="800"
>     Height="450"
>     MinWidth="800"
>     MinHeight="450"
>     d:DesignHeight="450"
>     d:DesignWidth="800"
>     Background="Transparent"
>     ExtendClientAreaChromeHints="NoChrome"
>     ExtendClientAreaTitleBarHeightHint="-1"
>     ExtendClientAreaToDecorationsHint="True"
>     SystemDecorations="BorderOnly"
>     mc:Ignorable="d">
>     <Grid>
>         <views:HeadControl
>             Title="{setting:Localize AddGameWindow.Title}"
>             HorizontalAlignment="Stretch"
>             VerticalAlignment="Top"
>             Min="False" />
> ```
> 
> ![{(D3MCLZSWNQ9066@O9K@X3](https://user-images.githubusercontent.com/26276037/216262390-e5cd6482-033d-4ee3-b967-0c7b76682fe4.png)

Have you tested this on Linux?

**Comment by Coloryr** [comment] 2023-02-02 09:18
> > You can try to make a new `headcontrol`
> > like [this](https://github.com/Coloryr/ColorMC/blob/master/src/ColorMC.Gui/UI/Controls/HeadControl.axaml) and use in Window
> > ```
> > <Window
> >     x:Class="ColorMC.Gui.UI.Windows.AddGameWindow"
> >     xmlns="https://github.com/avaloniaui"
> >     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
> >     xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
> >     xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
> >     xmlns:setting="clr-namespace:ColorMC.Gui.Utils.LaunchSetting"
> >     xmlns:views="clr-namespace:ColorMC.Gui.UI.Controls"
> >     Title="ColorMC"
> >     Width="800"
> >     Height="450"
> >     MinWidth="800"
> >     MinHeight="450"
> >     d:DesignHeight="450"
> >     d:DesignWidth="800"
> >     Background="Transparent"
> >     ExtendClientAreaChromeHints="NoChrome"
> >     ExtendClientAreaTitleBarHeightHint="-1"
> >     ExtendClientAreaToDecorationsHint="True"
> >     SystemDecorations="BorderOnly"
> >     mc:Ignorable="d">
> >     <Grid>
> >         <views:HeadControl
> >             Title="{setting:Localize AddGameWindow.Title}"
> >             HorizontalAlignment="Stretch"
> >             VerticalAlignment="Top"
> >             Min="False" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![{(D3MCLZSWNQ9066@O9K@X3](https://user-images.githubusercontent.com/26276037/216262390-e5cd6482-033d-4ee3-b967-0c7b76682fe4.png)
> 
> Have you tested this on Linux?

linux macos all tested

**Comment by Aurumaker72** [comment] 2023-02-03 15:18
> 

I'm refering to your linux distribution's compositor/window manager. 
This bug is an annoyance, but it certainly seems fixable on X11 and Wayland.

**Closed** 2023-02-14 19:04 UTC
Labels: bug, api, os-macos, os-linux
