### ISSUE TITLE
Animation Duration must be smaller than Delay to show

### ISSUE THREAD

**Issue by lukaszossowski** [AvaloniaUI/Avalonia#10611] opened 2023-03-08 23:06 UTC
When using keyframe animation like this:

```
<Style Selector="Border">
			<Style.Animations>
				<Animation FillMode="Forward" Delay="0:0:2" Duration="0:0:2">
					<KeyFrame Cue="0%">
						<Setter Property="Opacity" Value="1.0"/>
					</KeyFrame>
					<KeyFrame Cue="100%">
						<Setter Property="Opacity" Value="0.0"/>
					</KeyFrame>
				</Animation>
			</Style.Animations>
</Style>
```
if the delay is bigger than duration, the animation doesn't play at all. Effectively if I want to use delay I need to set the Duration to at least the same time for it to work, but it just plays a 2 second animation after a 2 second delay. I can't have a 1 second animation after 2 seconds delay.

I'm on Preview 4.

**Comment by timunie** [comment] 2023-03-09 12:00
@lukaszossowski if you open bug reports for 11.0 previews, I would really appreciate if you can test them against latest nightly builds. Atm there are so many fixes going on, that it might have already changed. 

-----

Remark: I tried to reproduce with latest nightly and I can confirm the issue is still present. Interesting behavior.

**Comment by leonidcan** [comment] 2023-09-13 20:16
Is it fixed?

**Comment by timunie** [comment] 2023-09-14 07:13
@leonidcan don't know but don't think so. Is the issue gone for you?

**Comment by leonidcan** [comment] 2023-09-14 12:38
@timunie I am still on 10, was wondering if it was fixed in 11 :(

**Comment by maxkatz6** [comment] 2023-09-16 05:17
Yes, it was fixed https://github.com/AvaloniaUI/Avalonia/issues/11819

**Closed by maxkatz6** 2023-09-16 05:17 UTC
Labels: bug, area-animations
