### ISSUE TITLE
Styles regression - 11.0.x works, 11.1.x / master doesnt

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#15729] opened 2024-05-15 08:25 UTC
### Describe the bug

Styles seem to be applied differently between 11.0.x and 11.1.x

### To Reproduce

```
 <Button Content="Test"
          VerticalAlignment="Stretch"
          Foreground="White"
          Padding="0"
          VerticalContentAlignment="Stretch"
          Cursor="Hand"
          BorderThickness="0"
          Background="Transparent"
          FontSize="16" FontWeight="Bold">
    <Button.Template>
      <ControlTemplate>
        <ContentPresenter Content="{TemplateBinding Content}" 
                          Background="{TemplateBinding Background}">
          <ContentPresenter.Styles>
            <Style Selector="TextBlock">
              <Setter Property="Foreground" Value="{TemplateBinding Foreground}" />
              <Setter Property="FontSize" Value="{TemplateBinding FontSize}" />
              <Setter Property="VerticalAlignment" Value="Center" />
            </Style>
          </ContentPresenter.Styles>
        </ContentPresenter>
      </ControlTemplate>
    </Button.Template>
  </Button>
  ```

### Expected behavior

On 11.0.x we get.
<img width="725" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/4672627/11afc4f9-9705-4097-bcda-241410aba466">

Text is white and bold.

What we get on master / 11.1.x

<img width="624" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/4672627/08575d26-1888-4a44-8dd1-30ecbb6c1b36">

### Avalonia version

11.1.x

**Comment by grokys** [comment] 2024-05-15 17:53
Bisected and confirmed caused by https://github.com/AvaloniaUI/Avalonia/pull/13970.

**Comment by grokys** [comment] 2024-05-15 21:09
Ok, this one wasn't what I thought it was going to be!

Turns out that in the example above, the template bindings don't work even in 11.0.x. The only reason that they appear to work is that the two properties you're binding: `Foreground` and `FontSize` are inherited properties. The white foreground for example isn't coming from the `TemplateBinding` but is being inherited from the `Button`. The reason the template bindings don't work is that `TextBlock` doesn't have a templated parent! It's not part of the `Button` template - it's the button content.

You can test this out by adding a `Tag` property on the `Button` and trying to sett the `TextBlock.Tag` using a `TemplateBinding` in a style. The `Tag` won't be set on the `TextBlock` in either 11.0 or 11.1.

What changed from 11.0.x to 11.1 is that the failing template bindings now cause the default property value to take effect, blocking the inherited value. That behavior was changed for normal bindings in 11.0.0 (see #10189) but `TemplateBinding` was missed. #13970 simply made `TemplateBinding` have the same behavior as normal bindings.

Given that, I think I'm going to close this with "yes it's a breaking change, but the previous behavior was a bug".

**Closed by grokys** 2024-05-15 21:09 UTC
Labels: bug, regression
