### ISSUE TITLE
Memory leaks due to Garbage Collector not disposing controls with nested external controls

### ISSUE THREAD

**Issue by dfernandezramos** [AvaloniaUI/Avalonia#13834] opened 2023-12-05 12:48 UTC
## Describe the bug
Garbage Collector is not disposing Avalonia controls containing nested controls coming from another UserControl classes and turned invisible resulting on memory leaks.

## To Reproduce

1. Run the [AvaloniaLeakSample](https://github.com/LongoMatch/avalonialeaksample) application `git@github.com:LongoMatch/AvaloniaLeakSample.git`
2. Click on the 'Move to view 2' button
3. Click on the 'BACK' button
4. Repeat steps 2 & 3 several times until GC disposes unused objects

## Expected behavior
Mind the application output. `View2` is not being destroyed. You should see `"There is no leak on view 1"` and `"There is no leak on view 2"` messages several times but only `"There is no leak on view 1"` is being displayed.

## Screenshots

![Screenshot 2023-12-05 at 10 39 00](https://github.com/AvaloniaUI/Avalonia/assets/16648184/13cb2d88-d0e3-48b9-8dbd-3320be960764)
![Screenshot 2023-12-05 at 10 41 23](https://github.com/AvaloniaUI/Avalonia/assets/16648184/4438836d-c95d-465b-b1dc-f328fdf6d2a9)

## Environment

- OS: Tested on macOS Sonoma and Windows 10
- Avalonia-Version: 11.0.5

## Additional context
Important information: 

- Leak on "View 2" happens when using `<sample:NestedControl1>` (which just contains a button) AND setting `NestedControl.IsVisible = false;` on the code behind at the `OnInitialized ()` method.
- Leak also happens when using `<sample:NestedControl1>` AND setting its `IsVisible="False"` property on the XAML file.
- Not setting `<sample:NestedControl1>` as invisible or if we just use a `<Button>` instead does not leak even if we set that button as not visible on the code behind at the `OnInitialized ()` method or the XAML file.
- It seems it just happens with the button control. Changing `<Button>` for `<Rectangle>` or other controls in the nested control class does not produce the leak

**Comment by dfernandezramos** [comment] 2023-12-05 12:50
As a note: we have seen that the latest Avalonia nightly build `11.1.999-cibuild0042640-beta` is not reproducing this issue anymore. Maybe could you check this and try to port the fix to the next minor release?

Thanks a lot in advance

**Comment by timunie** [comment] 2023-12-05 14:19
if it works in nightly, we can close this ticket imo. If that PR will be / can be backported to 11.0.6, I cannot guarantee.

**Closed by timunie** 2023-12-05 14:19 UTC
Labels: bug

**Comment by ylatuya** [comment] 2023-12-05 16:30
@timunie could you please provide a link to the PR that fixes this memory leak? It's leaking the whole view and therefore all objects referenced by that view, including the ViewModel. I have been unable to find the PR from the commits lists and I would like to know if it has been backported or if it was labeled as `backport-candidate-11.0.x`.

Thanks!

**Comment by jp2masa** [comment] 2023-12-05 20:59
There are at least 3 PRs to fix memory leaks that were backported to 11.0.x: https://github.com/AvaloniaUI/Avalonia/pulls?q=is%3Apr+sort%3Aupdated-desc+memory+leak+label%3Abackported-11.0.x+is%3Aclosed.

There also seems to be a new git tag for 11.0.6, so it may be released soon. The 11.0.6 packages appear in the [nightly feed](https://nuget-feed-nightly.avaloniaui.net/v3/index.json), if you want to test.

**Comment by dfernandezramos** [comment] 2023-12-07 08:02
JFYI: Upgraded to Avalonia 11.0.6 on the sample app and the leak is still happening

**Comment by maxkatz6** [comment] 2023-12-07 08:38
Unrelated to the leak, but: don't use finalizers or IDisposable in your controls. It's not reliable, and controls are not disposed ever (but still should be garbage collected). 
Instead, use atteched/detached from visual tree events/overrides.

**Comment by maxkatz6** [comment] 2023-12-07 09:45
Checked where this issue was fixed on master.
Seems like it's not reproducible since https://github.com/AvaloniaUI/Avalonia/pull/12861
Added to the backport list.
