### ISSUE TITLE
Vscode extension

### ISSUE THREAD

**Issue by breadnone** [AvaloniaUI/Avalonia#5050] opened 2020-11-15 13:51 UTC
I know this beats the purpose of Avalonia ide. Me and some of us would pretty much appreciate with just a code completion for vscode.

**Comment by rstm-sf** [comment] 2020-11-15 14:46
Look at the [PimpMyAvalonia](https://marketplace.visualstudio.com/items?itemName=PrzemyslawOnak.pimp-my-avalonia) extension

**Comment by kekekeks** [comment] 2020-11-15 17:34
The latest previewer engine can render via HTML+WebSocket (e. g. Rider hosts previewer in a webview). Completion engine is a simple library that can be used by the language server.

What's currently missing for VSCode support is the letter I from the IDE acronym.

**Comment by rstm-sf** [comment] 2020-11-30 11:31
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/999

**Comment by maxkatz6** [comment] 2021-06-20 00:15
Closing as a duplicate

**Closed by maxkatz6** 2021-06-20 00:15 UTC
