### ISSUE TITLE
Error CS0122 'ViewModelBase "is unavailable due to its level of protection.

### ISSUE THREAD

**Issue by Latinoz** [AvaloniaUI/Avalonia#3380] opened 2019-12-21 07:49 UTC
Greeting!

After updating the project to version 0.9, an error began to pop up:
**"Error CS0122 'ViewModelBase "is unavailable due to its level of protection."**
As I understand it due to the fact that **class ViewModelBase** is **internal**?

.Net Core 2.2.0 + AvaloniaUI 0.9

![screen1](https://user-images.githubusercontent.com/16256418/71305046-622cbe00-23df-11ea-9da5-8107a761ddf4.PNG)
![screen2](https://user-images.githubusercontent.com/16256418/71305047-62c55480-23df-11ea-8ed9-f1ed00a1fdaa.PNG)
![screen3](https://user-images.githubusercontent.com/16256418/71305043-622cbe00-23df-11ea-980f-9f53dd84c8d2.PNG)
![screen4](https://user-images.githubusercontent.com/16256418/71305044-622cbe00-23df-11ea-9bcc-e3031b60f4fa.PNG)

**Comment by FoggyFinder** [comment] 2019-12-21 07:55
Duplicate of #3239

**Closed** 2019-12-21 08:04 UTC
