### ISSUE TITLE
Polygon Points Parsing Issue

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#11560] opened 2023-05-29 19:47 UTC
**Describe the bug**

After https://github.com/AvaloniaUI/Avalonia/pull/11073, `Polygon` isn't parsing XAML points the same as before.

**To Reproduce**

```xaml
<Polygon
  Points="0,40 40,40 40,0"
  Fill="Red"
  Stroke="Blue"
  StrokeThickness="1" />
```

**Expected behavior**

The above Polygon should Render; however, it doesn't. No exception occurs either -- just the Points aren't being set correctly I think.

**Work-around**

Use a full Path.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

**Comment by robloo** [comment] 2023-05-29 20:25
Polyline is also affected.

**Comment by robloo** [comment] 2023-05-29 22:26
Strangely the Polygon in Control Catalog works so there might be more to this. The Polygon was in a ControlTheme and I can post the full code later. Everything else, including Path, works though.

**Comment by maxkatz6** [comment] 2023-05-29 22:53
Currently used Points parse code (compile time)
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlLanguageParseIntrinsics.cs#L319-L332

Previously used Points parse code
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Markup/Avalonia.Markup.Xaml/Converters/PointsListTypeConverter.cs#L18-L28

**Comment by timunie** [comment] 2023-08-25 14:15
seems to be fixed in latest master: 
![image](https://github.com/AvaloniaUI/Avalonia/assets/47110241/d0f137e6-1636-452b-a114-defecf7e1953)

So I'm closing this issue for now. If you think it's not fixed, please update reproducing instructions and I'll reopen it.

**Closed by timunie** 2023-08-25 14:15 UTC
Labels: bug
