### ISSUE TITLE
FontWeight=Bold doesn't work on macOS

### ISSUE THREAD

**Issue by ForNeVeR** [AvaloniaUI/Avalonia#2667] opened 2019-06-16 11:30 UTC
Write the following program and run on macOS:

```csharp
using Avalonia;
using Avalonia.Controls;
using Avalonia.Logging.Serilog;
using Avalonia.Media;

namespace avaloniatest
{
    class Program
    {
        public static void Main(string[] args) => BuildAvaloniaApp().Start(AppMain, args);

        public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .LogToDebug()
                .UseReactiveUI();

        private static void AppMain(Application app, string[] args)
        {          
            var window = new Window() {Content = new TextBlock() {FontWeight = FontWeight.Bold, Text = "fooh"}};

            app.Run(window);
        }
    }
}
```

I expect that it will show a bold text, but the text in the `TextBlock` is rendered as normal. Works the same for `TextBox`.

**Comment by x2bool** [comment] 2019-06-16 11:40
FontWeight=Bold does work if you explicitly specify a font family that provides bold font weight. I don't know if this is expected behavior though.

<img width="201" alt="image" src="https://user-images.githubusercontent.com/892945/59563558-6baa2780-9044-11e9-9c47-437aeafb17a9.png">

**Comment by Gillibald** [comment] 2019-06-16 11:47
If your FontFamily doesn't have a Typeface with a weight of Bold the render pipeline uses the nearest match. Make your your FontFamily contains a Bold face.

**Comment by ForNeVeR** [comment] 2019-06-16 12:06
Should we maybe change the default font family on macOS, then? Or is it okay that the default font doesn't support bold?

**Comment by Gillibald** [comment] 2019-06-16 12:08
The default is the System's default. If that font doesn't fulfill your needs just change it on your Window to share the FontFamily on all children controls.

**Comment by ForNeVeR** [comment] 2019-06-16 12:10
According to [the wiki](https://en.wikipedia.org/wiki/List_of_typefaces_included_with_macOS), the default font on macOS should be Lucida Grande which should support bold.

**Comment by Gillibald** [comment] 2019-06-16 12:14
And what happens if you specify that font explicitly? Does it render correctly? I can't debug this because I do not own a Mac and that will never change.

**Comment by x2bool** [comment] 2019-06-16 12:14
Well, I totally agree with ForNeVeR. If FontFamily=Bold does not work on "Hello, World" app then it creates a wrong impression that it doesn't work at all. It took me a while to figure out why it does not make font bold with default typeface.

**Comment by x2bool** [comment] 2019-06-16 12:16
BTW The primary system font in OS X El Capitan and above is San Francisco.

**Comment by ForNeVeR** [comment] 2019-06-16 12:16
It works if I set `FontFamily=FontFamily.Parse("Lucida Grande")`, but I wasn't able to determine which is the default yet. `FontFamily.Default` returns a family with empty name in debugger.

**Comment by Gillibald** [comment] 2019-06-16 12:45
Will have a look shortly. Could be that the default lookup isn't working for the System's default

**Comment by Gillibald** [comment] 2019-06-16 13:21
Should work when my fix is merged

**Comment by dtchepak** [comment] 2019-10-22 01:47
This issue still exists on `0.9.0-preview3` when running the [original example](https://github.com/AvaloniaUI/Avalonia/issues/2667#issue-456631380) on Mojave (10.14.6).

**Comment by Gillibald** [comment] 2019-11-02 04:26
I can't reproduce this issue on Windows. Can't test on Mac. When I set `FontWeigt="Bold"` on my window everything is rendered bold.

**Comment by dtchepak** [comment] 2019-11-03 04:38
@Gillibald Yes it works fine on Windows.

**Comment by danwalmsley** [comment] 2019-11-06 12:05
<img width="597" alt="image" src="https://user-images.githubusercontent.com/4672627/68296911-9a757880-008d-11ea-8350-cbb769f65828.png">
Control catalog on OSX 10.14.6 bold font working?

**Comment by Gillibald** [comment] 2019-11-06 12:07
To repro this you have to set FontWeight to bold on the MainWindow

**Comment by Carlos487** [comment] 2020-05-03 17:18
The problem persist in 0.9.9 release in Mojave 10.14.6. I created a blank project and followed the steps in the styles section of the docs. The size of the text changes but not the weight. How can I provide you with more debugging information?

**Comment by maxkatz6** [comment] 2022-06-19 06:08
Works with custom fonts and fluent theme

**Closed by maxkatz6** 2022-06-19 06:08 UTC
Labels: bug, os-macos
