### ISSUE TITLE
SetWindowStartupLocation.CenterScreen - doesn't account for Window Size

### ISSUE THREAD

**Issue by najak3d** [AvaloniaUI/Avalonia#7650] opened 2022-02-19 13:57 UTC
Window.SetWindowStartupLocation method simply sets Window.Position to the "center of screen", rather than centering the Window's "Bounds" to center.  

The result of this bug is that the window's Top-Left corner is at center of screen, instead.

Here is the offending code:
```c#
                    Position = screen.WorkingArea.CenterRect(rect).Position;
```

Here's a code fix:
```c#
                    PixelPoint pos = screen.WorkingArea.CenterRect(rect).Position;
                    Position = new PixelPoint(pos.X - (int)(Bounds.Width / 2), pos.Y - (int)(Bounds.Height / 2));
```

ALSO -- looks like 'CenterOwner' has the exact same defect.

**Comment by maxkatz6** [comment] 2022-02-19 18:43
I am pretty sure it worked before (except linux). Is it OS specific?

**Comment by najak3d** [comment] 2022-02-19 22:17
> 
Not sure how this code could have EVER worked as written, unless "Position" of a window means "Position of the Center of Window", which seems unlikely.   They code is setting the "Position" of window at "Center of Area".

**Comment by maxkatz6** [comment] 2022-02-19 22:53
FYI, from [PixelRect.cs](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Media/PixelRect.cs#L187) file:
```csharp
public PixelRect CenterRect(PixelRect rect)
{
    return new PixelRect(
        X + ((Width - rect.Width) / 2),
        Y + ((Height - rect.Height) / 2),
        rect.Width,
        rect.Height);
}
```

'Center' here is a verb meaning 'Center the rectangle'.

> Is it OS specific

? 
We have [a known issue](https://github.com/AvaloniaUI/Avalonia/issues/6433) on Linux. If it's the case, this issue should be closed as duplicate, since I can't reproduce this problem on Windows and macOS.

**Comment by najak3d** [comment] 2022-02-20 08:23
You are 100% correct.  When I saw the issue (it centering the top-left corner), I misread this very obvious code.  Feeling like a fool here.

The bug was in our UrhoWindowImpl where "PlatformImpl?.DesktopScaling == 0"... thus the rect size was 0.  I've fixed our code now.

I apologize for wasting your time on this.  I will be more careful next time.  Kicking myself here.

PLEASE CLOSE THIS BUG as OPERATOR ERROR, or the equivalent.

**Closed** 2022-02-20 08:40 UTC
Labels: bug
