### ISSUE TITLE
Viewbox did not scale the content of Combobox and Flayout...

### ISSUE THREAD

**Issue by ngai6666** [AvaloniaUI/Avalonia#7750] opened 2022-03-04 17:28 UTC
After window resized, Label and Combobox are scaled correctly, but the content of combobox didn't scale at all.
See the sample code and screenshot below. 
Is there a workaround?

<Viewbox>
  <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center"
			  Width="400" Height="400">
	  <Label> label 1</Label>
	  <ComboBox>
		  <ComboBoxItem> Line 1 </ComboBoxItem>
		  <ComboBoxItem> Line 2 </ComboBoxItem>
		  <ComboBoxItem> Line 3 </ComboBoxItem>
		  <ComboBoxItem> Line 4 </ComboBoxItem>
	  </ComboBox>
  </StackPanel>
</Viewbox>

![image](https://user-images.githubusercontent.com/100010462/156811103-8c289e78-81d3-48cc-8218-8bbe206e5587.png)

**Comment by maxkatz6** [comment] 2022-03-05 15:28
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2631

**Closed** 2022-04-21 15:44 UTC
Labels: bug
