### ISSUE TITLE
 QML-like syntax engine

### ISSUE THREAD

**Issue by surfsky** [AvaloniaUI/Avalonia#3735] opened 2020-04-03 03:54 UTC
Can XAML syntax engine be replaced with QML-like syntax engine, or provide a conversion tool. QML syntax is really very concise and beautiful, and now XAML is a bit verbose.

For example: ButtonPage.xaml
``` xml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             x:Class="ControlCatalog.Pages.ButtonPage">
  <StackPanel Orientation="Vertical" Spacing="4">
    <TextBlock Classes="h1">Button</TextBlock>
    <TextBlock Classes="h2">A button control</TextBlock>
    <StackPanel Orientation="Horizontal"
                Margin="0,16,0,0"
                HorizontalAlignment="Center"
                Spacing="16">
      <StackPanel Orientation="Vertical" Spacing="8" Width="150">
        <Button>Button</Button>
        <Button Foreground="White">Foreground</Button>
        <Button Background="{DynamicResource ThemeAccentBrush}">Background</Button>
        <Button IsEnabled="False">Disabled</Button>
        <Button Content="Re-themed">
          <Button.Styles>
            <Style>
              <Style.Resources>
                <SolidColorBrush x:Key="ThemeBorderMidBrush">Red</SolidColorBrush>
                <SolidColorBrush x:Key="ThemeControlHighBrush">DarkRed</SolidColorBrush>
              </Style.Resources>
            </Style>
          </Button.Styles>          
        </Button>
      </StackPanel>
      <StackPanel Orientation="Vertical" Spacing="8" Width="150">
        <Button BorderThickness="0">No Border</Button>
        <Button BorderBrush="{DynamicResource ThemeAccentBrush}">Border Color</Button>
        <Button BorderBrush="{DynamicResource ThemeAccentBrush}" BorderThickness="4">Thick Border</Button>
        <Button BorderBrush="{DynamicResource ThemeAccentBrush}" BorderThickness="4" IsEnabled="False">Disabled</Button>
      </StackPanel>
    </StackPanel>    
  </StackPanel>
</UserControl>
```

QML-like  syntax code:

``` js
@UserControl
@Class ControlCatalog.Pages.ButtonPage

StackPanel {
    Orientation:"Vertical" 
    Spacing:"4"
    TextBlock{Classes:"h1" Text:"Button"}
    TextBlock{Classes:"h2" Text:"A button control"}
    StackPanel{
        Orientation:"Horizontal"
        Margin:"0,16,0,0"
        HorizontalAlignment:"Center"
        Spacing:"16"
        StackPanel{
            Orientation:"Vertical" Spacing:"8" Width:"150"
            Button{Text: "Button"}
            Button{Foreground:"White" Text:"Foreground"}
            Button{Background:"@ThemeAccentBrush" Text:"Background"}
            Button{IsEnabled:"False" Text:"Disabled"}
            Button{
                Text:"Re-themed"
                Style.Resources {
                    SolidColorBrush {ThemeBorderMidBrush:"Red"}
                    SolidColorBrush {ThemeControlHighBrush:"DarkRed"}
                }
            }
        }
        StackPanel{
            Orientation:"Vertical" Spacing:"8" Width:"150"
            Button {BorderThickness:"0" Text:"No Border"}
            Button {BorderBrush:"@ThemeAccentBrush" Text:"Border Color"}
            Button {BorderBrush:"@ThemeAccentBrush" BorderThickness:"4" Text:"Thick Border"}
            Button {BorderBrush:"@ThemeAccentBrush" BorderThickness:"4" IsEnabled:"False" Text:"Disabled"}
        }
    }   
}
```

**Comment by maxkatz6** [comment] 2020-04-03 04:11
Seems like duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2502

By the way, I don't really like multiple markup languages for one framework, and I really like xaml.

**Comment by surfsky** [comment] 2020-04-03 07:16
Well, I just saw #2502. It's very similar.
The grammar of QML is well refined, just liking poem. QML has several advantages:
1. Syntax like JSON
2. Concise binding syntax
3. Concise attribute syntax
4. Signal and slot
5. ...

The binding syntax of QML is very concise and I like it very much. In the following short example, When dragging sliderbar's handler, the TextBlock can display sliderbar's value in real time:

```JS
SliderBar { Id=“sld” Min=0 Max=100}
TextBlock { Text: sld.Value }
```

The other two characteristics of QML: property and signal/slot, which can be moved to .CS file and implemented by csharp built-in mechanism instead of interface layer code.
By the way, this qml-like language file maybe has the extension ".csml" (CSharp markup language)

**Comment by JamRemco** [comment] 2020-04-03 08:07
My 2 cents

But i like this Syntax
https://github.com/AvaloniaUI/Avalonia/issues/2502#issuecomment-490406757

Xaml is realy dense, which makes it hard to read.

Remco

**Comment by blackholeearth** [comment] 2020-04-05 16:56
Why write gui in different language than c# itself.

Check this: https://github.com/VincentH-Net/CSharpForMarkup

To create uı declarative way in c# , this lib defines static functions for ui controls.

Look at kotlin compose.  UI, backend both kotlin . They are trying to get away from  findbyviewid() garbage. 

People are trying to get away from ui lang being different than backend code.

İf you're gonna do this. İ hope it goes like c#for_markup did . Not another xxxML .

**Comment by grokys** [comment] 2020-04-06 15:58
Going to close this because as you say it's very similar to #2502. Let's keep discussion there.

**Closed by grokys** 2020-04-06 15:58 UTC
