### ISSUE TITLE
ComboBox ItemsSource does not support ObservableCollection's View

### ISSUE THREAD

**Issue by Hertzole** [AvaloniaUI/Avalonia#16609] opened 2024-08-06 14:13 UTC
### Describe the bug

First, I am **NOT** talking about the standard `ObservableCollection` but rather this package: [ObservableCollections](https://github.com/Cysharp/ObservableCollections)

The ComboBox does not support using [the views](https://github.com/Cysharp/ObservableCollections?tab=readme-ov-file#viewsortedview) created using something like `ObservableList`. It supports just using a `ObservableList` directly, but this may not always be preferable, like when using a sorted view. 

The views implement all the necessary interfaces, like IEnumerable, INotifyCollectionChanged, etc, but the ComboBox refuses to use them.

### To Reproduce

1. Download and open the [repo project zip file](https://github.com/user-attachments/files/16511450/Avalonia.Observable.Collections.zip)
2. Open up MainWindow.xaml and observe the bindings
3. Start the app and observe that only the first ComboBox (that is using the Items property directly) is populated

### Expected behavior

All the combo boxes from the repo project are populated with the entries from the Items property.

### Avalonia version

11.1.1

### OS

Windows

### Additional context

This problem exists for other controls, but I don't have all of them at hand right now. I feel like there shouldn't be any issues with [ObservableCollections](https://github.com/Cysharp/ObservableCollections) over the built-in ObservableCollection as they seem to implement the same interfaces. I really wish all the controls would support the much better [ObservableCollections](https://github.com/Cysharp/ObservableCollections).

**Comment by maxkatz6** [comment] 2024-08-06 21:57
This is likely an issue: https://github.com/Cysharp/ObservableCollections/issues/53
We need a IList there https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/ItemsSourceView.cs#L266-L269

INotifyCollectionChanged semantically requires an indexed collection, as NotifyCollectionChangedEventArgs literally operates with indexes. So Collection is not enough, it needs to be a List.

And INotifyCollectionChanged implies list is mutable, it should be a IList, not IReadOnlyList.

**Comment by Hertzole** [comment] 2024-08-11 21:54
If you don't mind me asking, why does it need to be an IList? It seems to throw anyways if you try to use any of the methods that would change the list.

**Comment by IanRawley** [comment] 2024-08-12 00:07
I think the discussion here is relevant: #8764

My understanding of the issue is that the problem is effectively that there is no non-generic IReadOnlyList, only IReadOnlyList<T>, and that it doesn't share any appropriate (for this scenario) common ancestors with IList.  It's the same problem for IList<T>.  And based on the linked discussion, working around it would require Reflection, which isn't desired.

**Comment by stevemonaco** [comment] 2024-08-15 15:40
Should be fixed by [ObservableCollections 2.2.0 release](https://github.com/Cysharp/ObservableCollections/releases/tag/2.2.0)

**Comment by timunie** [comment] 2024-10-06 08:02
@Hertzole I'm closing this as per comment in the linked package Avalonia support should be there for newer versions.

**Closed** 2024-10-06 08:02 UTC
Labels: by-design
