### ISSUE TITLE
The given key 'CompiledAvaloniaXaml.!EmbeddedResource+XamlIlClosure_1+XamlIlClosure_1' was not present in the dictionary

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/Avalonia#4449] opened 2020-08-06 17:07 UTC
I'm receiving

```
System.Collections.Generic.KeyNotFoundException: 
The given key 'CompiledAvaloniaXaml.!EmbeddedResource+XamlIlClosure_1+XamlIlClosure_1' was not present in the dictionary 
```
on latest stable (`0.9.12`) with CoreRt build.

There is no issue on `0.9.4`.

**Comment by kekekeks** [comment] 2020-08-06 18:05
Do you have the full stack trace?

**Comment by kekekeks** [comment] 2020-08-06 18:06
@danwalmsley @jmacato might be caused by reproducible compilation thingy.

**Comment by FoggyFinder** [comment] 2020-08-06 18:27
> Do you have the full stack trace?

only that

```
error : The given key 'CompiledAvaloniaXaml.!EmbeddedResource+XamlIlClosure_1+XamlIlClosure_1' was not present in the dictionary. [ProjectName.fsproj]
  System.Collections.Generic.KeyNotFoundException: The given key 'CompiledAvaloniaXaml.!EmbeddedResource+XamlIlClosure_1+XamlIlClosure_1' was not present in the dictionary.
     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
     at Internal.Metadata.NativeFormat.Writer.RecordVisitorBase.MapToPooledRecord[T](T rec)
     at ILCompiler.GeneratingMetadataManager.ComputeMetadata[TPolicy](TPolicy policy, NodeFactory factory, Byte[]& metadataBlob, List`1& typeMappings, List`1& methodMappings, List`1& fieldMappings, List`1& stackTraceMapping)
     at ILCompiler.AnalysisBasedMetadataManager.ComputeMetadata(NodeFactory factory, Byte[]& metadataBlob, List`1& typeMappings, List`1& methodMappings, List`1& fieldMappings, List`1& stackTraceMapping)
     at ILCompiler.DependencyAnalysis.MetadataNode.GetData(NodeFactory factory, Boolean relocsOnly)
     at ILCompiler.DependencyAnalysis.ObjectWriter.EmitObject(String objectFilePath, IEnumerable`1 nodes, NodeFactory factory, IObjectDumper dumper)
     at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper)
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
```

**Comment by kekekeks** [comment] 2020-08-06 18:45
Looks like a bug in the corert compiler. Might be confused by duplicate type names in different assemblies or something. Could you check with 0.9.11?

**Comment by kekekeks** [comment] 2020-08-06 18:59
I've confirmed that deterministic builds generate types with duplicate names

**Comment by Gillibald** [comment] 2020-08-06 19:30
Y the indices need to be generated globally

**Comment by FoggyFinder** [comment] 2020-08-06 20:04
> Could you check with 0.9.11?

Yep, 0.9.11 works indeed

**Comment by maxkatz6** [comment] 2020-10-20 21:17
Fixed with commit https://github.com/AvaloniaUI/Avalonia/commit/e5df3970e888ddcb62380f8cd3f08a9aaadddc85

**Closed by maxkatz6** 2020-10-20 21:17 UTC
Labels: bug, xaml-compiler

**Comment by FoggyFinder** [comment] 2020-10-20 21:27
Awesome. Now I can try upgrading to latest preview
