### ISSUE TITLE
Unable to use custom font in <Style>

### ISSUE THREAD

**Issue by Szymon-D** [AvaloniaUI/Avalonia#2939] opened 2019-09-07 18:13 UTC
Following code
```XAML
<Style Selector="Button">
    <Setter Property="FontFamily" Value="resm:someProj.Assets.SomeFont.ttf?assembly=resm:someProj#SomeFontName"/>
</Style>
```

throws an exception
```
Portable.Xaml.XamlObjectWriterException
  HResult=0x80131500
  Message=Set value of member '{clr-namespace:Avalonia.Styling;assembly=Avalonia.Styling}Setter.Value' threw an exception
  Source=Avalonia.Markup.Xaml
  StackTrace:
   at Portable.Xaml.XamlObjectWriterInternal.SetValue(XamlMember member, Object target, Object value)
   at Portable.Xaml.XamlObjectWriterInternal.SetValue(XamlMember member, Object value)
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteEndMember()
   at Portable.Xaml.XamlWriterInternalBase.WriteEndMember()
   at Portable.Xaml.XamlObjectWriter.WriteEndMember()
   at Portable.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.LoadFromReader(XamlReader reader, AvaloniaXamlContext context, IAmbientProvider parentAmbientProvider)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Type type, Object rootInstance)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj)
   at resm:someProj.Views.MainWindow.InitializeComponent() in C:\Users\x\Desktop\yr\Views\MainWindow.xaml.cs:line 77
   at resm:someProj.Views.MainWindow..ctor(MainWindowViewModel vm) in C:\Users\x\Desktop\y\Views\MainWindow.xaml.cs:line 28

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by danwalmsley** [comment] 2019-09-07 21:20
@kekekeks seen quite a few reports of this, something up in XamlIL?

**Comment by kekekeks** [comment] 2019-09-07 22:19
@danwalmsley as you can clearly see, the exception is rethrown by the Portable.Xaml.

**Comment by jmacato** [comment] 2019-09-08 05:40
@danwalmsley @kekekeks this is only an issue for older releases i think. Had encountered the same error in Wasabi (https://github.com/zkSNACKs/WalletWasabi/pull/2136) so i had to declare the font as a resource like so:
```
  <FontFamily x:Key="MonospacedFont">
        <x:Arguments>
          <x:String>Inconsolata</x:String>
          <x:Uri>resm:WalletWasabi.Gui.Assets.*.ttf?assembly=WalletWasabi.Gui</x:Uri>
        </x:Arguments>
   </FontFamily>
```

**Comment by grokys** [comment] 2019-09-09 11:12
Seems to be a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2194, which should be fixed on master, so going to close this. Please let us know if it's still a problem on the latest nightly releases.

**Closed by grokys** 2019-09-09 11:12 UTC
