### ISSUE TITLE
[Avalonia Browser] Using the IME input will result in repeated characters

### ISSUE THREAD

**Issue by BiDuang** [AvaloniaUI/Avalonia#11622] opened 2023-06-02 09:03 UTC
**Describe the bug**
Typing in textbox using IME results in repeated characters. For example, typing in Chinese or Japanese.

**To Reproduce**
1. Create a `Avalonia Cross Platform` project, add a `Textbox` control in the view
2. Build and run a Avalonia Browser project
3. Typing any characters in Chinese or Japanese via IME

**Expected behavior**
Enter the same characters displayed by the IME

**Screenshots**

Screen recording didn't included the IME interface, but you will understand the situation if you are familar with these languages.

For Chinese:

![Chn 00_00_00-00_00_30](https://github.com/AvaloniaUI/Avalonia/assets/40264028/eb63d596-ef29-4b4c-bc9f-011997ff7103)

For Japanese:

![Jap 00_00_00-00_00_30](https://github.com/AvaloniaUI/Avalonia/assets/40264028/90606eb1-1115-4820-9b7f-c187416d7d09)

For English (Contrast, no issue)

![Eng 00_00_00-00_00_30](https://github.com/AvaloniaUI/Avalonia/assets/40264028/09540bd5-208b-49f7-9cd0-f25f56b6134c)

**Running Environment**

- Mozilla Firefox 113.0.2 x64
- Avalonia 11.0.999-cibuild0035798-beta

**Comment by Gillibald** [comment] 2023-09-19 08:52
This is only an issue with Firefox

**Comment by johanpolson** [comment] 2024-03-24 11:57
I have tests on master and could not reproduce the problem.

![Animation](https://github.com/AvaloniaUI/Avalonia/assets/40406620/43da5e9e-fa69-4ab7-b08d-632fe2348a1a)

**Comment by timunie** [comment] 2024-03-24 12:45
Closing for now acc. to user feedback. If anyone can reproduce in 11.1 ping me.

**Closed by timunie** 2024-03-24 12:46 UTC
Labels: bug, os-browser, area-textprocessing
