### ISSUE TITLE
IDE high CPU load after upgrade project to Avalonia 11

### ISSUE THREAD

**Issue by tms320** [AvaloniaUI/Avalonia#11743] opened 2023-06-11 15:39 UTC
Hello!
I have upgraded my Avalonia projetct to v11 rc1.1 according to "Avalonia 11 Porting Guide".
The project is very simple:
![image](https://github.com/AvaloniaUI/Avalonia/assets/24802646/392ea0d0-f0ca-47e9-ab61-60b7ad391a4b)

When I open the solution in Microsoft Visual Studio 2022 the IDE CPU usage is very high:
![image](https://github.com/AvaloniaUI/Avalonia/assets/24802646/04a20b45-d797-4e63-992a-c151c3a23a4d)

When I close the solution or open Avalonia 0.10 project - the IDE CPU usage drops to 0-1 %.

OS: Windows 11 22H2
CPU: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
PS: Restart IDE or Windows doesn't help.

**Comment by jp2masa** [comment] 2023-06-11 16:01
Probably a duplicate of #10203, was fixed after RC (#11596).

**Comment by tms320** [comment] 2023-06-11 18:27
Yes, if I close axaml file (and previewer) - CPU load becomes normal.
I don't understand how to try the fix mentioned in #10203.

**Comment by maxkatz6** [comment] 2023-06-11 23:36
tms320 you can use nightly builds https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

**Closed by maxkatz6** 2023-06-11 23:36 UTC
Labels: bug
