### ISSUE TITLE
Don't reject items sources implementing INotifyCollectionChanged and IList<T> but not IList

### ISSUE THREAD

**Issue by Coding-Enthusiast** [AvaloniaUI/Avalonia#8788] opened 2022-08-20 09:26 UTC
ListBox items bound to an object implementing `INotifyCollectionChanged` and `IList<T>` throws an exception saying "Collection implements INotifyCollectionChanged by not IList." I believe on [this line](https://github.com/AvaloniaUI/Avalonia/blob/2c7ae3a50fdbf7878f8dadc72fc5ddf5b24cd546/src/Avalonia.Controls/ItemsSourceView.cs#L47).  This didn't use to happen in 0.10.6.  
It looks like only the first two methods of `IList` are used which also exist in `IList<T>`.
`IList` interface:

        object this[int index] { get; set; }
        int IndexOf(object value);
        bool IsFixedSize { get; }
        bool IsReadOnly { get; }
        int Add(object value);
        void Clear();
        bool Contains(object value);
        void Insert(int index, object value);
        void Remove(object value);
        void RemoveAt(int index);

 `IList<T>` interface:  

        T this[int index] { get; set; }
        int IndexOf(T item);
        void Insert(int index, T item);
        void RemoveAt(int index);

**Comment by rabbitism** [comment] 2022-08-20 10:26
I think this topic is discussed in #8764

**Comment by maxkatz6** [comment] 2022-08-20 10:58
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/8764

**Closed by maxkatz6** 2022-08-20 10:58 UTC
Labels: bug
