### ISSUE TITLE
Binding Convertert does not get triggered when ObservableCollection is changed

### ISSUE THREAD

**Issue by tisis2** [AvaloniaUI/Avalonia#13030] opened 2023-09-26 09:22 UTC
**Describe the bug**
bind to a ObservableCollection and do a value aggregation in a binding converter does not work. the binding does not get invalidated and reevaluated when the collection changes

**To Reproduce**
see example project

**Expected behavior**
the binding should be invalidated and updated whenever an item is added or removed in the observable collection

**Additional context**
[ObservableCollectionConverter.zip](https://github.com/AvaloniaUI/Avalonia/files/12725624/ObservableCollectionConverter.zip)

**Comment by timunie** [comment] 2023-09-26 11:15
That's not what ObservableCollection does. It doesn't fire PropertyChanged, it fires CollectionChanged which is a different event.

**Comment by timunie** [comment] 2023-09-26 11:25
I'd suggest to add a read-only property Sum in the ViewModel instead and raise PropertyChanged for it, as you already have. I'd just make the setter private. 

Alternative: 

```diff
public MainWindowViewModel()
{
    RemoveCommand = ReactiveCommand.Create<int>(Remove) ;
!   // Added a listener to CollectionChanged, which will notify the UI that collection has changed. 
!   // Don't do it. It's evil :-)
+   _items.CollectionChanged += (sender, args) => this.RaisePropertyChanged(nameof(Items));
}
```

As this is by design, I'll close the issue for now.

**Closed by timunie** 2023-09-26 11:25 UTC
Labels: bug

**Comment by tisis2** [comment] 2023-09-27 05:23
oh i see. i thought in itemscollection it is also done through the binding that it updates correctly when the collection changed. but i see it is an explicit listener that is registered
