### ISSUE TITLE
Button losing focus after click when it is binded to ReactiveCommand

### ISSUE THREAD

**Issue by dme-compunet** [AvaloniaUI/Avalonia#12978] opened 2023-09-21 18:16 UTC
**Describe the bug**
Button losing focus after click when it is binded to command created by `ReactiveCommand.Create()`

**To Reproduce**

1. Create new avalonia.mvvm project
2. Change the MainWindowViewModel.cs file content to:
```csharp
public class MainWindowViewModel : ViewModelBase
{
    public ICommand RxCommand { get; }

    public MainWindowViewModel()
    {
        RxCommand = ReactiveCommand.Create(() => Debug.WriteLine("RxCommand"));
    }

    public void ClassicCommand()
    {
        Debug.WriteLine("ClassicCommand");
    }
}

```
3. Change the MainWindow.axaml file content to:
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:BugExample.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="BugExample.Views.MainWindow"
        x:DataType="vm:MainWindowViewModel"
        Icon="/Assets/avalonia-logo.ico"
        Title="BugExample">

    <StackPanel>
        <Button Content="Classic command" Command="{Binding ClassicCommand}" />
        <Button Content="Reactive command" Command="{Binding RxCommand}" />
    </StackPanel>

</Window>
```
4. Navigate using the Tab key to 'Reactive command' button and press with the Space key, see that the button losed the focus.

**Expected behavior**
The button will remain focused

**Desktop (please complete the following information):**

- OS: Windows 10 22H2
- Version 11.0.4

**Comment by timunie** [comment] 2023-09-21 20:25
RelayCommand from the CommunityToolkit.MVVM package can configure this for async commands. Sync commands should not deactivate the button ar all iirc.

**Comment by maxkatz6** [comment] 2023-09-21 20:35
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/12705

**Closed by maxkatz6** 2023-09-21 20:35 UTC
Labels: bug
