### ISSUE TITLE
Unable to Handle Gestures.ScrollGestureEndedEvent

### ISSUE THREAD

**Issue by dmrayt** [AvaloniaUI/Avalonia#3413] opened 2020-01-07 16:34 UTC
An InvalidCastException occurs while trying to handle the `Gestures.ScrollGestureEndedEvent` with following code:

```csharp
        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
            AddHandler(Gestures.ScrollGestureEndedEvent, OnScrollGestureEnded);
        }

        private void OnScrollGestureEnded(object sender, ScrollGestureEventArgs e)
        {
            // do something
        }
```

```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Avalonia.Input.ScrollGestureEndedEventArgs' to type 'Avalonia.Input.ScrollGestureEventArgs'.
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|7_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args)
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.GestureRecognizers.ScrollGestureRecognizer.EndGesture()
   at Avalonia.Input.GestureRecognizers.ScrollGestureRecognizer.PointerCaptureLost(PointerCaptureLostEventArgs e)
   at Avalonia.Input.GestureRecognizers.GestureRecognizerCollection.HandlePointerCaptureLost(PointerCaptureLostEventArgs e)
   at Avalonia.Input.InputElement.OnPointerCaptureLost(PointerCaptureLostEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__25_10(InputElement x, PointerCaptureLostEventArgs e)
   at Avalonia.Interactivity.RoutedEvent`1.<>c__DisplayClass2_0`1.<AddClassHandler>g__Adapter|0(Object sender, RoutedEventArgs e)
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass21_0.<AddClassHandler>b__0(ValueTuple`2 args)
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 34
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 146
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.Pointer.Capture(IInputElement control)
   at Avalonia.Input.Pointer.Dispose()
   at Avalonia.Input.TouchDevice.ProcessRawEvent(RawInputEventArgs ev)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.X11.X11Window.<ScheduleInput>b__97_0()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken)
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at UITest.Program.Main(String[] args) in C:\Projects\_Test\Avalonia\UITest\UITest\Program.cs:line 32
```

The error is that `Gestures.ScrollGestureEndedEvent` is declared as "RoutedEvent\<ScrollGestureEventArgs\>" it should be of type "RoutedEvent\<ScrollGesture**Ended**EventArgs\>".

**Comment by aguahombre** [comment] 2020-01-08 09:30
This is a duplicate of #3108

**Closed** 2023-07-14 00:59 UTC
Labels: bug
