### ISSUE TITLE
Invoking OnPropertyChanged without changing the object property doesn't invoke Converter in MultiBinding

### ISSUE THREAD

**Issue by Zaspard** [AvaloniaUI/Avalonia#16446] opened 2024-07-24 14:07 UTC
### Describe the bug

ViewModel has two properties `object` (some class) and `struct` (bool). 
When `OnPropertyChanged` is invoked without changing the object property `Converter` in `MultiBinding` is not invoked. But when `OnPropertyChanged` is invoked without changing the `struct` property, there is no such problem.
The same problem does not occur when invoking `Converter` in `Binding` for both `object` and `struct`.

### To Reproduce

Project for test: [Example.zip](https://github.com/user-attachments/files/16362854/Example.zip)

1. Run project
2. Click on "UpdateObjectForMultiValueConverter" button

### Expected behavior

OnPropertyChanged invoked Converter in MultiBinding

### Avalonia version

11.1.0, master brunch

### OS

Windows

### Additional context

This happens because `false` is written to the `hasValueChanged` variable in `PublishValue()` (class `UntypedBindingExpressionBase`) and then the notification is ignored in `_sink`. 
![image](https://github.com/user-attachments/assets/6a098d13-c014-4510-b986-34c898790b91)

It is true that the `object` has not been changed because we have not updated it in property, but we wanted to make View redraw by invoking `OnPropertyChanged`.
When invoking `OnPropertyChanged` for a `Binding` this code is not used, so there is no such problem

Problem with `MultiBinding` is not observed in version 10.0.10

**Comment by workgroupengineering** [comment] 2024-07-24 15:01
Thinking is the same issue of #16084

**Comment by maxkatz6** [comment] 2024-07-24 22:13
Closing as a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/16084

**Closed by maxkatz6** 2024-07-24 22:13 UTC
Labels: bug
