### ISSUE TITLE
CompileAvaloniaXamlTask The process cannot access the file because it is being used

### ISSUE THREAD

**Issue by DamianSuess** [AvaloniaUI/Avalonia#12670] opened 2023-08-25 21:26 UTC
**Describe the bug**
After upgrading the project to Avalonia v11.0.0 and v11.0.4, I am getting failures to build due to CompileAvaloniaXamlTask process cannot access the file 'obj\Debug\Avalonia\original.pdb' because it is being used by another process.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "CompileAvaloniaXamlTask" task failed unexpectedly.
System.IO.IOException: The process cannot access the file 'obj\Debug\Avalonia\original.pdb' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Avalonia.Build.Tasks.CompileAvaloniaXamlTask.Execute() in /_/src/Avalonia.Build.Tasks/CompileAvaloniaXamlTask.cs:line 36
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	SampleSplitView	C:\Users\XXXX\.nuget\packages\avalonia\11.0.4\buildTransitive\AvaloniaBuildTasks.targets	120	
```

**To Reproduce**

1. Open project
2. Build project (`Ctrl + Shift + B`)
3. See error

**Sample Repository:**
* https://github.com/DamianSuess/Learn.PrismLibrary
* Pick any of the Avalonia Example solutions (_i.e. Avalonia-Ex1-IntroNav.sln_)

**Expected behavior**
The project should build without errors

**Workaround:**
1. Delete the `bin` and `obj` directories
2. Relaunch Visual Studio (in extreme cases)
3. Rebuild the project

This works for 2 or 3 builds and the issue happens again.

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/1216684/ae555f78-2b35-415f-9658-1385c5fee932)

- OS: Windows 10
- Version 11.0.0 and 11.0.4

**Additional context**
When building projects using Avalonia v0.10.21 this error was not occurring

**Comment by buzzware** [comment] 2023-10-26 04:24
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/5294

**Comment by lsoft** [comment] 2023-10-27 17:32
Hi!

We have faced with this issue to. To be honest every 3rd compilation pipeline fails on our compilation servers so the working process has been broken with endless reruns. We are in fire with this bug.

```
C:\Users\<user>\.nuget\packages\avalonia\11.0.4\buildTransitive\AvaloniaBuildTasks.targets(120,5): error MSB4018: непредвиденная ошибка при выполнении задачи "CompileAvaloniaXamlTask".
System.IO.IOException: Процесс не может получить доступ к файлу "obj\.sual\Debug\net7.0\Avalonia\original.pdb", так как этот файл используется другим процессом.
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   в Avalonia.Build.Tasks.CompileAvaloniaXamlTask.Execute() в /_/src/Avalonia.Build.Tasks/CompileAvaloniaXamlTask.cs:строка 36
   в Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   в Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [<here is the path to failed csproj>]
```

ANY(!) workaround will save us!...

**Comment by gritsenko** [comment] 2023-10-27 18:01
@lsoft мне помогло отключение компиляции xaml в csproj

    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <EnableAvaloniaXamlCompilation>false</EnableAvaloniaXamlCompilation>

но у меня нет axaml файлов в проекте.

по ссылке выше еще советуют отключить многопоточность при сборке

**Closed** 2023-10-31 08:43 UTC
Labels: bug

**Comment by drweb86** [comment] 2023-12-13 23:42
```
<AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
<EnableAvaloniaXamlCompilation>false</EnableAvaloniaXamlCompilation>
```
This will make executable not runnable


Below is the workaround

```
  <!-- Prevent compilation error Avalonia UI -->
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugSymbols>False</DebugSymbols>
    <DebugType>None</DebugType>
  </PropertyGroup>
```
