### ISSUE TITLE
TextBlock TextFormatting ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#4617] opened 2020-09-04 09:37 UTC
When displaying some strings in TextBlock I am getting the exception below. 
I will update here once I find the problematic string.

Exception Info: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at Avalonia.Utilities.ReadOnlySlice`1.Take(Int32 length)
   at Avalonia.Media.TextFormatting.ShapedTextCharacters.Split(Int32 length)
   at Avalonia.Media.TextFormatting.TextFormatterImpl.SplitTextRuns(List`1 textRuns, Int32 length)
   at Avalonia.Media.TextFormatting.TextFormatterImpl.PerformTextWrapping(List`1 textRuns, TextRange textRange, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak currentLineBreak)
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak)
   at Avalonia.Media.TextFormatting.TextLayout.UpdateLayout()
   at Avalonia.Media.TextFormatting.TextLayout..ctor(String text, Typeface typeface, Double fontSize, IBrush foreground, TextAlignment textAlignment, TextWrapping textWrapping, TextTrimming textTrimming, TextDecorationCollection textDecorations, Double maxWidth, Double maxHeight, Double lineHeight, Int32 maxLines, IReadOnlyList`1 textStyleOverrides)
   at Avalonia.Controls.TextBlock.CreateTextLayout(Size constraint, String text)
   at Avalonia.Controls.TextBlock.get_TextLayout()
   at Avalonia.Controls.TextBlock.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Presenters.ItemVirtualizer.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Blast.Program.Main(String[] args) in C:\Users\adirh\RiderProjects\Blast\Blast\Program.cs:line 44

**Comment by danwalmsley** [comment] 2020-09-04 10:20
@Gillibald

**Comment by adirh3** [comment] 2020-09-04 19:31
Found the problematic string, its really long, here is a txt file of it.
I might limit this on my end but I think it shouldn't crash anyway.
https://1drv.ms/t/s!AqOQDvYFLMuagc9AFcwaR06FZZFurQ

**Comment by Gillibald** [comment] 2020-09-04 19:36
Thanks for investigating the causing string. Will have a look shortly

**Comment by Gillibald** [comment] 2020-09-19 13:03
Your Text exceeds the maximum length of characters HarfBuzz can process. (UInt16.MaxValue) (65535) This causes issues at my end.  To fix this I need more time and most likly have to rework some part of the text formatting logic.

**Comment by adirh3** [comment] 2020-09-19 13:05
> Your Text exceeds the maximum length of characters HarfBuzz can process. (UInt16.MaxValue) (65535) This causes issues at my end. To fix this I need more time and most likly have to rework some part of the text formatting logic.

Fair enough, thanks for looking into this. 
I will just add a test for the string length before adding it to the GUI for now.

**Comment by Gillibald** [comment] 2020-09-19 13:11
Okay. This is kind of special because the text doesn't contain explicit line breaks. To solve this I have to process the text in chunks and limit everything to UInt16.MaxValue. Should be doable. Normally this wouldn't be an issue.

**Comment by Gillibald** [comment] 2020-09-19 13:15
I currently don't have the time to make the needed changes but I will most likly find some time at the end of the month.

**Comment by adirh3** [comment] 2020-09-19 13:15
> Okay. This is kind of special because the text doesn't contain explicit line breaks. To solve this I have to process the text in chunks and limit everything to UInt16.MaxValue. Should be doable. Normally this wouldn't be an issue.

Tbh, at least for me, I won't need to display all of this, and I can substring it at my end. But the main issue is that if a user (by mistake) pastes a string like this into TextBox it will crash as well, so take that into consideration.
Thanks

**Comment by khaledhosny** [comment] 2020-09-22 11:12
> Your Text exceeds the maximum length of characters HarfBuzz can process. (UInt16.MaxValue) (65535)

What is this limitation is coming from, I don’t think HarfBuzz has such a limitation.

**Comment by Gillibald** [comment] 2020-09-22 12:14
Just double checked. You are right HarfBuzz indeed handles cluster values beyond `65535` the issue is that we optimize for size and use uint16 values for clusters. So we might just check for an overflow but I don't see why we should handle text of that size.

**Comment by khaledhosny** [comment] 2020-09-22 13:35
In some countries, legal text most not have paragraph breaks, so 100s of pages are a single paragraph. LibreOffice, for example, took a considerable pain to raise that limit: https://wiki.documentfoundation.org/ReleaseNotes/4.3#Raise_limit_of_characters_in_paragraphs

**Comment by Gillibald** [comment] 2020-09-22 13:39
Thanks for that information. We might want to do the same.

**Comment by yyjdelete** [comment] 2020-09-28 04:09
https://github.com/AvaloniaUI/Avalonia/blob/3bf2330d285ffa73e014a498afec4c7716968f92/src/Avalonia.Visuals/Media/GlyphRun.cs#L374-L404
Maybe `_glyphClusters.Length` instead of `_glyphClusters.End` here since `Start` can be non-zero value?
And one strange thing is `ShapedTextCharacters.Split()` expected `GlyphRun.FindGlyphIndex()` return `[0, length]`, but `GlyphRun.FindNearestCharacterHit()` and `GlyphRun.GetDistanceFromCharacterHit()` expected `[0, length -1]`

**Comment by Gillibald** [comment] 2020-09-28 05:39
`Characters[GlyphClusters.Length]` isn't working. I don't think you understood what the code is doing.

**Comment by yyjdelete** [comment] 2020-09-28 11:27
@Gillibald 
That's exactly what I say in the latter line, ShapedTextCharacters.Split() expected `GlyphClusters.Length` can be return. Not sure `[0, length]` or `[1, length]`(FindGlyphIndex()+1)

>And one strange thing is ShapedTextCharacters.Split() expected GlyphRun.FindGlyphIndex() return [0, length], but GlyphRun.FindNearestCharacterHit() and GlyphRun.GetDistanceFromCharacterHit() expected [0, length -1]

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Media/TextFormatting/ShapedTextCharacters.cs#L98-L101

**Comment by Gillibald** [comment] 2020-09-28 14:13
Everything works as expected

![Screenshot 2020-09-28 161227](https://user-images.githubusercontent.com/5928797/94443513-8a82ed80-01a5-11eb-8048-ad353efe0a8f.png)

**Comment by Gillibald** [comment] 2020-09-28 14:27
A split at `Buffer[0]` makes no sense. In that case, there is nothing to split. The Split itself has to make sure we don't break a cluster in the middle etc.

**Comment by Gillibald** [comment] 2022-10-19 05:42
Haven't had any reports of such issue. So I close it for now.

**Closed by Gillibald** 2022-10-19 05:42 UTC
