### ISSUE TITLE
Memory leak in OpenGL control

### ISSUE THREAD

**Issue by hez2010** [AvaloniaUI/Avalonia#10631] opened 2023-03-10 18:01 UTC
**Describe the bug**
Memory leak in OpenGL control

**To Reproduce**
Run CC.NetCore with default options, and follow the below video.

https://user-images.githubusercontent.com/14960345/224390063-813c3101-a13e-4769-a6bd-eabe53d6ce8b.mp4

**Expected behavior**
The memory consumption shouldn't keep increasing. 

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: Avalonia build from master

**Comment by jp2masa** [comment] 2023-03-10 19:14
Duplicate of #10457?

**Comment by maxkatz6** [comment] 2023-04-19 01:19
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/10457

**Closed by maxkatz6** 2023-04-19 01:19 UTC
Labels: bug
