### ISSUE TITLE
Can not display iconfont

### ISSUE THREAD

**Issue by gaowei123** [AvaloniaUI/Avalonia#6408] opened 2021-08-12 03:54 UTC
there is a bug "Default font family name can't be null or empty", and i follow the #4427
using a CustomFontManagerImpl, then regist it at app.xaml.cs

but in this way the icon cannot display
the iconfont.ttf got from https://www.iconfont.cn/

![image](https://user-images.githubusercontent.com/17244869/129135706-b69c8fab-32a5-48e3-bb73-b3c744086c2b.png)

- OS:  linux - raspberry pi
- Version: 0.10.0

**Comment by DmitryNizhebovsky** [comment] 2021-09-03 09:12
Hi, I use the icon font remixicon. ttf https://remixicon.com/ and it works fine for me.
I use it as follows:
1) I create a Fonts.axaml file in the Styles folder with the following content

`<ResourceDictionary xmlns="https://github.com/avaloniaui"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:system="clr-namespace:System;assembly=netstandard">

    <FontFamily x:Key="RemixIconFont">avares://AssemblyName/Assets/Fonts/#remixicon</FontFamily>

	
	
    <system:String x:Key="RemixIconWarning">&#xeca1;</system:String>
    <system:String x:Key="RemixIconSpinner">&#xeec2;</system:String>
    <system:String x:Key="RemixIconAlbum">&#xee4b;</system:String>
    <system:String x:Key="RemixIconDocuments">&#xecc5;</system:String>
    <system:String x:Key="RemixIconMusic">&#xef83;</system:String>
    <system:String x:Key="RemixIconVideo">&#xf282;</system:String>
    <system:String x:Key="RemixIconChat">&#xeb4d;</system:String>
    <system:String x:Key="RemixIconDownload">&#xec5a;</system:String>
    <system:String x:Key="RemixIconSettings">&#xf0e8;</system:String>
    <system:String x:Key="RemixIconCloseEye">&#xecb3;</system:String>
    <system:String x:Key="RemixIconOpenEye">&#xecb5;</system:String>
    <system:String x:Key="RemixIconClose">&#xeb99;</system:String>
    <system:String x:Key="RemixIconDone">&#xeb81;</system:String>
    <system:String x:Key="RemixIconDown">&#xea4a;</system:String>
</ResourceDictionary>`

2) I connect it in the App.axaml file

`<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:AssemblyName"
             x:Class="AssemblyName.App">
    <Application.DataTemplates>
        <local:ViewLocator/>
    </Application.DataTemplates>

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceInclude Source="avares://AssemblyName/Styles/Fonts.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>

    <Application.Styles>
        <StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml"/>
    </Application.Styles>
</Application>`

3) I use the necessary icons

`<TextBlock Text="{StaticResource RemixIconDocuments}" FontFamily="{StaticResource RemixIconFont}"/>`

**Comment by maxkatz6** [comment] 2022-08-11 03:14
Closing as duplicate of https://github.com/AvaloniaUI/Avalonia/issues/4427

**Closed by maxkatz6** 2022-08-11 03:14 UTC
Labels: bug
