### ISSUE TITLE
Setting FontFamily to null triggers a NullReferenceException

### ISSUE THREAD

**Issue by MB-GA** [AvaloniaUI/Avalonia#15287] opened 2024-04-09 12:22 UTC
### Describe the bug

If the `FontFamily` field on an element is set to `null`, either directly by setting `{x:Null}` or indirectly via a binding, a `NullReferenceException` is raised internally once the element is evaluated. This will then crash the application as it never handles the exception.

### To Reproduce

Add this element to a View: `<TextBlock Text="hello" FontFamily="{x:Null}"/>`

You can also bind it from a ViewModel and setting it to `null` from there:

View: `<TextBlock Text="hello" FontFamily="{Binding Field}"/>`
ViewModel: `public FontFamily? Field => null;`

### Avalonia version

11.0.10

### OS

Windows

**Comment by MB-GA** [comment] 2024-04-09 13:25
> what is the use-case here?

None in particular: we're migrating from WPF, and in the process of this we ran into this bug. I'm only really reporting it to raise awareness of it since it can be hard to track down the source, as the exception occurs internally in Avalonia. IMO it should at least give information of where you're passing `null` in the view so you can figure out where the mistake is made.

**Comment by Symbai** [comment] 2024-10-15 21:54
@timunie This issue is already fixed. The PR author has just forgot to add this issue, instead he took his own issue number which was commented as a duplicate of this one: https://github.com/AvaloniaUI/Avalonia/pull/15896

**Closed** 2024-10-15 22:04 UTC
Labels: bug, area-textprocessing
