### ISSUE TITLE
11.0.x: build fails if any DllImport win32 api in app.axaml.cs 

### ISSUE THREAD

**Issue by scuzqy** [AvaloniaUI/Avalonia#12822] opened 2023-09-08 05:04 UTC
**Describe the bug**
App.axaml : Avalonia error AVLN:0004: Object reference not set to an instance of an object

**To Reproduce**
```powershell
dotnet new avalonia.app
```
import any win32 api in App.axaml.cs
```csharp
using System;
using System.Runtime.InteropServices;
/*...*/
public partial class App : Application
{
/*...*/
    [DllImport("user32.dll", CharSet = CharSet.Unicode)]
    public static extern int MessageBox(IntPtr hWnd, string text, string caption, uint type);
}
/*...*/
```
Build error "<path>/<to>/App.axaml : Avalonia error AVLN:0004: Object reference not set to an instance of an object"

but when DllImport stays in the same .cs only moved into another class, build ok
```csharp
internal class Test
{

    [DllImport("user32.dll", CharSet = CharSet.Unicode)]
    public static extern int MessageBox(IntPtr hWnd, string text, string caption, uint type);
}
public partial class App : Application
{
/*...*/
}
```

**Dev env:**
.NET 7
![image](https://github.com/AvaloniaUI/Avalonia/assets/80660355/5e5919af-5ef4-4c87-b453-9c127b9d9849)
Windows 10.0.19045

**Comment by timunie** [comment] 2023-09-08 05:59
Better to do the DLL import in a seperate class as you said. Write an interface `IMessageBoxService` which you can inject per platform. That way you can now support Windows, but extend later to MacOS or whatever.

**Comment by DmitryZhelnin** [comment] 2023-09-08 09:04
Duplicate of #10046

**Comment by timunie** [comment] 2023-09-08 09:09
closing as duplicate

**Closed by timunie** 2023-09-08 09:09 UTC
Labels: bug
