### ISSUE TITLE
Cannot Paste (i.e. in TextBox) in WASM app running in Mozilla Firefox browser

### ISSUE THREAD

**Issue by dbriard** [AvaloniaUI/Avalonia#10997] opened 2023-04-12 14:45 UTC
**Describe the bug**
Cannot Paste (i.e. in TextBox) in WASM app running in Mozilla Firefox browser.
Because of Limited Clipboard support in Firefox.

**To Reproduce**
1. Run the Avalonia WASM playground
2. Copy or Cut text in a TextBox control
3. Try to Paste it, using hotkey or context menu
4. Nothing is pasted

**Expected behavior**
We must be able to copy/paste when running app inside Firefox browser.

If that issue is technically impossible to solve, may be you can implement some kind of WorkaroundClipboard that would use internal storage when app is running is Firefox. At least to make Copy/Paste work inside the application.

I don't have example in mind, but I suppose there are WebGL games or programs running in Firefox where you can copy/paste in custom rendered textbox?

If you already know a workaround that I can implement myself, please tell me.

- OS: WASM
- Version 11 preview 6

**Comment by maxkatz6** [comment] 2023-04-12 16:36
> where you can copy/paste in custom rendered textbox?

Custom rendering is poorly supported in some browsers, especially Mozilla.
[clipboard.readText](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText) is not supported there.

As a fallback, it should be possible to handle it in this way:
```javascript
globalThis.addEventListener("paste", (e) => latestPaste = e.clipboardData.getData("text")));
```
and implement ReadClipboardTextAsync as:
```javascript
readClipboardTextAsync(): Promise<string> {
  if (globalThis.navigator.clipboard.readText) {
     return await globalThis.navigator.clipboard.readText();
  }
  else {
    return this.latestPaste ;
  }
}
```

**Comment by maxkatz6** [comment] 2023-04-12 16:37
Technically a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/9647, but I will close my issue instead

**Comment by dbriard** [comment] 2023-04-12 16:50
@maxkatz6 Thank you so much for the code snippet, I'll try tomorrow. I also found a method on the Unity's forum where they display a Paste button in the UI, that call JavaScript prompt, to receive the pasted text. I may give a try too, that's better than nothing...

For non-JavaScript developer like me, that would be very nice to have a working solution directly in Avalonia, (or an experimental control) even if not perfect (something that work between Avalonia controls, and may be a ugly paste button near text box only visible for Firefox, like NumberBox popup spin buttons may be?).

**Comment by dbriard** [comment] 2023-04-13 14:37
@maxkatz6 Hi, I tried your code, and other pieces of code I found on the Internet, with no success.

I tried to set both:
`addEventListener("paste", (event) => {});

onpaste = (event) => `{};``
in main.js

but my breakpoints in those two events are not hitted.
I also tried to add contenteditable="true" on avalonia-input-element, but that does not work.
by luck, breakpoints was hitted at one time, but I don't know how, may be from the Firefox's Inspector... 

I will see if I can override textbox copy/cut/paste to make it work using a fake clipboard in avalonia...

**Comment by kekekeks** [comment] 2023-04-13 14:49
`window.addEventListener("paste", e=> alert(e.clipboardData.getData("text")))` seems to work in firefox even if there is no focused `input` element

**Comment by kekekeks** [comment] 2023-04-13 14:50
I guess we need platform-specific clipboard routed events

**Comment by dbriard** [comment] 2023-04-13 17:11
@kekekeks Hi and thanks a lot for helping.

If you still could help, I have two issues:

1) Your alert work and I can see it, unless the TextBox got the focus :( So the code is not called when it is needed.

2) A nooby javascript or interop question I suppose:

In main.js, I added:
`let latestPaste = undefined;
if (navigator.userAgent.indexOf("Firefox") != -1) {
    window.addEventListener("paste", e => { latestPaste = e.clipboardData.getData("text"); alert(latestPaste); });
}`

In another file named helpers.js, I added the export function:
`export function getLastPastedText() {
	return latestPaste;
};`
helpers.js is loaded from program.cs with await JSHost.ImportAsync(...)

My issue is that if I add breakpoints in main.js, and in helpers.js, the content of "latestPaste" variable is not the same, it is ok in main.js, but it always have "undefined" value in helpers.js.

I tried to move the export function in main.js, but I cannot call it anymore from C#. (there is no call such as await JSHost.ImportAsync for main.js, as main.js is loaded in index.html).

**3) I am not sure if the issue is already reported but if you press Ctrl+A in TextBox from WASM, it do not SelectAll as expected, instead it write 'a' and replace the selection if any (in all browser, and in your playground application).**



So at the moment, as a workaround, I am using a static variable as Clipboard in a custom TextBox, with reflection to override default behavior. For example:

`private void TextBox_PastingFromClipboard(object? sender, Avalonia.Interactivity.RoutedEventArgs e)
        {
            var text = s_clipboardText;

            if (string.IsNullOrEmpty(text))
            {
                return;
            }

            s_snapshotUndoRedo ??= EnsureMethod("SnapshotUndoRedo", new Type[] { });
            s_handleTextInput ??= EnsureMethod("HandleTextInput");
            s_snapshotUndoRedo?.Invoke(this, null);
            s_handleTextInput?.Invoke(this, new object[] { text });
            e.Handled = true;
        }`

and this ugly method if I really need to inject text from outside the application:

`export function getPromptText(message, placeholder) {
	return prompt(message, placeholder);
};`

waiting for better...

**Comment by maxkatz6** [comment] 2023-04-13 18:53
@dbriard created a PR with workaround which hacks this problem with focused textbox.

>  I am not sure if the issue is already reported but if you press Ctrl+A in TextBox from WASM, it do not SelectAll as expected, instead it write 'a' and replace the selection if any (in all browser, and in your playground application).

Can't repro it on simple textbox in control catalog.

**Closed** 2023-04-13 20:27 UTC
Labels: bug, enhancement, help-wanted, os-browser

**Comment by dbriard** [comment] 2023-04-14 07:14
> @dbriard created a PR with workaround which hacks this problem with focused textbox.
> 
> > I am not sure if the issue is already reported but if you press Ctrl+A in TextBox from WASM, it do not SelectAll as expected, instead it write 'a' and replace the selection if any (in all browser, and in your playground application).
> 
> Can't repro it on simple textbox in control catalog.

@maxkatz6 I do not tried in Control Catalog, but with TextBox or XamlEditor here https://play.avaloniaui.net/ and with my v11 preview 6. May be it has been fixed since preview 6. It is WASM only (edge, chrome, firefox), Ctrl+A work perfectly fine when running in Desktop.

And a big thanks for the Firefox workaround!

**Comment by correabuscar** [comment] 2024-03-01 19:48
If anyone else got here for being unable to paste(2 ways from RMB context menu, MMB or Ctrl+V), in something such as the in-browser [Element](https://app.element.io/) which uses wasm, make sure `dom.event.clipboardevents.enabled` is `true` not `false` in `about:config` in firefox.
