### ISSUE TITLE
ListBox highlights the wrong item after adding to a sorted Realm-bound ItemsSource

### ISSUE THREAD

**Issue by polymath74** [AvaloniaUI/Avalonia#16087] opened 2024-06-22 01:51 UTC
### Describe the bug

I have a `ListBox` whose `ItemsSource` is bound to an `IRealmCollection`.
When I create a new item, I want to select it straight after it is added to the collection.
If the list is not sorted this works perfectly.
If the list is sorted (using `.OrderBy()`), and the new item is not at the end of the sorted list, the `ListBox` highlights the _following_ item (i.e. the one after the new one) - despite `SelectedItem` apparently correctly referring to the new item.

Screenshot showing correct item highlighted and selected when it is sorted to the end of the list:
<img width="1141" alt="correct_at_end" src="https://github.com/AvaloniaUI/Avalonia/assets/89322485/fefeb736-af2d-4a90-8e5f-2212665770dc">
Screenshot showing incorrect item highlighted, but selected item apparently correct, when the new item is sorted to non-last:
<img width="1141" alt="incorrect_at_start" src="https://github.com/AvaloniaUI/Avalonia/assets/89322485/e3752e99-2db9-451d-bc8c-e8742ea4896d">
(These screenshots obtained using demo project attached below.)

This works properly with an `ObservableCollection` where the new item is inserted before the end of the list.

My guess is that this has something to do with the order of arrival of notifications from Realm about the source list changing. I think the notification is arriving _after_ the `SelectedItem` is changed. (I have tested this separately using `.SubscribeForNotifications()` on the `IRealmCollection`, but it is hard to be sure because I don't know when Avalonia is actually getting notification(s).)

### To Reproduce

Model:
```
public partial class DemoItem : IRealmObject
{
    [PrimaryKey]
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}
```

ViewModel:
```
Realm _realm = Realm.GetInstance();

public IRealmCollection<DemoItem> AllItems { get; }

[Reactive]
public DemoItem? SelectedItem { get; set; }

public MainWindowViewModel()
{
    AllItems = _realm.All<DemoItem>()
        .OrderBy(x => x.Name) // <<-- This line breaks the ListBox selection behaviour on creation
        .AsRealmCollection();
}

public void AddItem()
{
    int newId = AllItems.OrderByDescending(x => x.Id).FirstOrDefault()?.Id + 1 ?? 1; // next higher number
    string newName = new string(...); // random string to randomise sort order - see attached code for details
    var item = new DemoItem { Id = newId, Name = $"Item {newName} {newId}", Description = $"Description for Item {newId}" };
    _realm.Write(() => _realm.Add(item));
    SelectedItem = item; // <<-- Trying to select the item that was just added
}

```

View:
```
<ListBox ItemsSource="{Binding AllItems}" SelectedItem="{Binding SelectedItem}">
    <ListBox.ItemTemplate>
        <DataTemplate>
            <TextBlock Text="{Binding Name}"/>
        </DataTemplate>
    </ListBox.ItemTemplate>
</ListBox>
```

When new created item is sorted to end of list -> works.
When new created item is sorted earlier in list -> `ListBox` highlights the following item instead.

Full project attached that reproduces the problem. It is a fairly simple modification of the MVVM template.
[Avalonia-GetStartedApp.zip](https://github.com/user-attachments/files/15934690/Avalonia-GetStartedApp.zip)

### Expected behavior

Item highlighted should match the `SelectedItem`.

### Avalonia version

11.0.10

### OS

macOS

### Additional context

I haven't tried this on Windows yet.. let me know if I need to.

Happy to help with Realm-related code if you need. Or you can try replacing the Realm stuff with an `ObservableCollection` and using `.Insert()` to order new items however you like - this worked fine for me.

This is a smaller reproduction of the more complex situation in my application.

**Comment by timunie** [comment] 2024-06-23 09:12
Could it be the operation is done async in that lib? If so, this is probably not supported.

**Comment by AnnDevNet** [comment] 2024-06-24 16:10
I don't know Realm, but I will try
_realm.Write(() => { _realm.Add(item); SelectedItem = item; });
or 
_realm.Write(() => { _realm.Add(item); Dispatcher.UIThread.Post(() => SelectedItem = item); });

**Comment by polymath74** [comment] 2024-06-25 00:12
The second one works! As also does:

_realm.Write(() => _realm.Add(item));
Dispatcher.UIThread.Post(() => SelectedItem = item);

Nice. Thanks!

On Tue, 25 Jun 2024 at 02:11, AnnDevNet ***@***.***> wrote:
>
> I don't know Realm, but I will try
> _realm.Write(() => { _realm.Add(item); SelectedItem = item; });
> or
> _realm.Write(() => { _realm.Add(item); Dispatcher.UIThread.Post(() =>
SelectedItem = item); });
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by polymath74** [comment] 2024-06-25 00:43
And yes @timunie Realm does almost everything async.

**Comment by timunie** [comment] 2024-06-25 04:16
If using the dispatcher works, this means it raises events in the non UI thread which is not supported by design. Will close this one. Feel free to open a new Q&A discussion if you have further questions

**Closed** 2024-06-25 04:16 UTC
Labels: by-design

**Comment by AnnDevNet** [comment] 2024-06-26 10:03
Sorry, my suggestion was just to see what happens and was not the final solution, although it works in some cases. Will this still work? A workaround is valid when there are no other solutions.
After studying the docs, Realm is indeed in lazy mode and the right way to do it is to add an event to react to the change, and therefore to set the SelectedItem in this event.
[React to change](https://www.mongodb.com/docs/atlas/device-sdks/sdk/dotnet/react-to-changes/)

**Comment by timunie** [comment] 2024-06-26 15:10
It's not a workaround. It is by design, that all notifications must be consumeable form the UI thread.

**Comment by AnnDevNet** [comment] 2024-06-28 22:34
Hello

Even if it is by design, it is not necessarily the right solution.
I know that on Windows there is a ui thread, but I don't know what happens on other platforms.

_realm.Write is a fake synchronous method, with, I imagine, async void tasks and with Dispatcher.UIThread.Post to return to the ui thread. So avoid if you want to get immediate feedback.

Maybe WriteAsync can work with a flow guarantee.
In this case, this would be the right solution (I haven't tested but it would be weird if an async method broke the flow):

@polymath74, can you tell me if this works?
await _realm.WriteAsync(() => _realm.Add(item));
SelectedItem = item;

And does realm guarantee that item inserted is the resulting object in the list. We have to test.
Otherwise, you have to find the object with the correct id.

**Comment by polymath74** [comment] 2024-06-28 23:20
@AnnDevNet Yes, that seems to work reliably too. Thanks! And I believe you are correct about the way the non-async Write() works.

The original code works fine in WPF (that's where I started using Realm!) so I was surprised at the different behaviour in Avalonia.
