### ISSUE TITLE
Upgrading to 11.1 breaks ClickOnce deployment

### ISSUE THREAD

**Issue by heuristicAL** [AvaloniaUI/Avalonia#16732] opened 2024-08-19 20:59 UTC
### Describe the bug

Running locally works fine using either my IDE or `dotnet run`.
When packing the application using a variation of the following command:
```console
msbuild MyApp.sln -t:restore,publish -p:Configuration=Release -p:PublishProfile="${{env.PUBLISH_PROFILE}}" -p:PublishDir="${{env.PUBLISH_PATH}}" -p:ApplicationRevision=${{github.run_number}} -p:PublishUrl="${{env.DEPLOY_DEST}}" -p:InstallUrl="${{env.DEPLOY_DEST}}"
```
It builds and publishes properly but, when trying to run the actual artifact produced by this, I get the following error:
```console
Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for MyApp.App.App, make sure to specify x:Class and include your XAML file as AvaloniaResource
   at void Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(object obj)
   at void Tesseract.App.App.Initialize()
   at void Avalonia.AppBuilder.SetupUnsafe()
   at void Avalonia.AppBuilder.Setup()
   at AppBuilder Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at int Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, string[] args, Action<IClassicDesktopStyleApplicationLifetime> lifetimeBuilder)
   at int MyApp.App.Program.Main(string[] args)
```

In this case, my Program.cs builds the Avalonia app this way:
```c#
public static AppBuilder BuildAvaloniaApp() {
  AppBuilder.Configure<App>().UsePlatformDetect().LogToTrace().UseReactiveUI();
}
```

Where `App` is class in the `MyApp.App` project.

My only possible thought here is the ClickOnce is weird and not properly packing the app, but this doesn't explain why it worked fine with Avalonia 11 and 10.

### To Reproduce

Try to deploy an app using ClickOnce and `msbuild`?

### Expected behavior

The output app should run as it did for v11.0

### Avalonia version

11.1.3

### OS

Windows

### Additional context

Unfortunately this is a Company app so I'm limited in the source code I can share. Hopefully the conditions causing the bug rings a bell to anyone more intimate with the changes from 11.0 => 11.1!

I should also mention that my `csproj` for this project look a LOT like the default `csproj` from the 11.1 template, and so should run fine.

**Comment by TomasOndrisak** [comment] 2024-08-26 11:38
I have the same problem. 👍

**Comment by timunie** [comment] 2024-08-26 17:50
@heuristicAL in case you have a support agreement the team may be able to help further. Otherwise try to reproduce in a simple sample and upload it here

**Comment by hanssonfredrik** [comment] 2024-09-05 11:49
Exactly the same problem here. This when deploying with ClickOnce.

**Comment by TomEdwardsEnscape** [comment] 2024-09-05 19:26
Fixed by #16835

**Comment by cauefelipe1** [comment] 2024-09-16 13:54
I checked the current [beta](https://github.com/AvaloniaUI/Avalonia/releases/tag/11.2.0-beta2) version containing the PR, but I got the same issue. Is it only for me?

**Comment by ouranosv** [comment] 2024-09-17 19:23
@cauefelipe1 I also still have the same issue.

**Comment by TomEdwardsEnscape** [comment] 2024-09-17 21:15
Can't reproduce it with `11.2.0-beta2`. I tried both `dotnet publish --no-build` and `msbuild MyApp.sln -t:restore,publish` (as stated in this bug). Both published working applications with XAML compilation.

**Comment by TomEdwardsEnscape** [comment] 2024-09-19 14:39
How are you publishing the project? Can you share the source code?

**Comment by hanssonfredrik** [comment] 2024-09-20 11:25
@TomEdwardsEnscape, it works fine if I publish it in a folder, but when I create a ClickOnce profile and publish it that way, I get the error above.

**Comment by TomEdwardsEnscape** [comment] 2024-09-21 16:07
The repro steps in the bug are missing the important step of actually publishing via the ClickOnce system. This is not the same as executing the given MSBuild command, and there are still issues due to the way ClickOnce generates its file layout.

The "entry point assembly" [is captured at evaluation time](https://github.com/dotnet/msbuild/blob/1205246b0fe49f0d00316c103cf0c381d96063d4/src/Tasks/Microsoft.Common.CurrentVersion.targets#L437). This means that even though our target executes at the correct time, there is a copy of the original file path that it doesn't know about and so can't update. As a result, the assembly being published doesn't have XAML compile output (all referenced assemblies are OK though).

I can think of three ways to fix this:

1. We replace the `_DeploymentManifestEntryPoint` item in `InjectAvaloniaXamlOutput`. I've tried this and it works. But the item has an underscored name, which indicates that it's considered private and may be changed or removed at any time. (It also has a metadata item that we have to replicate. Instead of hardcoding it we could write a task to copy all metadata to the new item.)
2. Microsoft updates their targets file so that the value isn't captured at evaluation time. There is no reason for them to do this, as the item isn't used until targets start executing. But that only fixes one instance of this problem.
3. We start overwriting the original build outputs from CSC instead of redirecting paths to our own outputs. Capturing the original paths at evaluation time wasn't a scenario that I considered during #13840. Somebody else could capture the values now or in the future. However, overwriting the originals is unexpected behaviour and runs the risk of reintroducing the original issue.

**Comment by fh-turbinestudios** [comment] 2024-09-21 16:41
Is step 1 something that I can do by my self?

**Comment by TomEdwardsEnscape** [comment] 2024-09-23 05:58
If you want a quick fix right now, you can add this to the project you are publishing:

```xml
<Target Name="ClickOnceAvaloniaXaml" AfterTargets="InjectAvaloniaXamlOutput"
        Condition="'@(AvaloniaResource)@(AvaloniaXaml)' != '' AND $(EnableAvaloniaXamlCompilation) != false">
  <ItemGroup>
    <!-- ClickOnce support -->
    <_DeploymentManifestEntryPoint Remove="@(_DeploymentManifestEntryPoint)" />
    <_DeploymentManifestEntryPoint Include="@(_AvaloniaXamlCompiledAssembly)">
      <TargetPath>$(TargetFileName)</TargetPath>
    </_DeploymentManifestEntryPoint>
  </ItemGroup>
</Target>
```

**Comment by hanssonfredrik** [comment] 2024-09-23 06:54
@TomEdwardsEnscape Thanks! That worked like a charm!

**Comment by TomEdwardsEnscape** [comment] 2024-09-23 18:48
@maxkatz6 please re-open this bug.

**Comment by TomEdwardsEnscape** [comment] 2024-09-24 07:13
I've listed three possibilities above, I'd like to hear what Avalonia team members think.

**Comment by MrJul** [comment] 2024-09-24 08:54
Good findings @TomEdwardsEnscape. Why isn't that capture in a target...

> I can think of three ways to fix this:
> 
>     1. We replace the `_DeploymentManifestEntryPoint` item in `InjectAvaloniaXamlOutput`. [...]
>     2. Microsoft updates their targets file [...]
>     3. We start overwriting the original build outputs from CSC [...]

In my opinion, 2. would be the best. I'll try to open a PR for MSBuild, but I wouldn't be surprised if the change is rejected. After all it's been working this way for what, 20 years now?

Even if it's accepted, we would still need a workaround for a while. I say we go with 1. to avoid reintroducing the previous issues with overwriting the original file. Yes, the item is private, but it hasn't changed for years and is unlikely to change at all (jinxing it). Feel free to open a PR.

**Closed** 2024-09-25 11:51 UTC
Labels: bug
