### ISSUE TITLE
TextBlock render wrong text in some situations.

### ISSUE THREAD

**Issue by liwuqingxin** [AvaloniaUI/Avalonia#16456] opened 2024-07-25 12:00 UTC
### Describe the bug

TextBlock will render a wrong text in some situations. It's Text property is "AAA" and it displays a "BBB"。

### Situations
1. Open the popup and close it by 'IsLightDismissEnabled'.
2. The result should be 0.

### Analysis
1. The render of MyTextBlock is called between the text updating by `'MediaContext.Instance.SyncDisposeCompositionTarget(this.CompositionTarget);'` of class `CompositingRenderer`.
2. And the render() will make TextBlock's TextLayout be recreated, with a temp text, which will be updated later.
3. Then, the TextLayout will be dirty and never be rebuilt.

### To Reproduce

I have made a demo to demonstrate it.
[Avalonia.TextBlock.Render.Demo_v11.1.0.zip](https://github.com/user-attachments/files/16377120/Avalonia.TextBlock.Render.Demo_v11.1.0.zip)

### Expected behavior

The MyTextBlock should display a "0" after the popup is closed in the demo.

### Avalonia version

11.1.0

### OS

Windows

**Comment by liwuqingxin** [comment] 2024-07-26 02:06
So, could the TextBlock skip the render calling if it's IsMeasureValid is false? Or just destroy the Textlayout if the IsMeasureValid is false after rendering?

**Comment by Gillibald** [comment] 2024-07-26 05:04
You sample causes a InvalidOperationException `Visual was invalidated during the render pass`

**Comment by maxkatz6** [comment] 2024-07-26 05:10
`Visual was invalidated during the render pass` is definitely an bug in the app.
Changing visual tree (exactly what LogService.ShowLog does internally) is not allowed from inside of Render call. That's by design. @liwuqingxin, you can add log messages on dispatcher call.

**Comment by maxkatz6** [comment] 2024-07-26 05:11
But ` It's Text property is "AAA" and it displays a "BBB"。` part needs to be clarified by author then.

**Comment by maxkatz6** [comment] 2024-07-26 05:14
Also, why do you early return from OnPropertyChanged method?
Base TextBox.OnPropertyChanged is never called for other properties because of that, which might cause unwanted behavior.

![image](https://github.com/user-attachments/assets/88447750-0c5a-4e2a-b566-5ab486b67b76)

**Comment by liwuqingxin** [comment] 2024-07-26 06:14
> Your sample causes an InvalidOperationException `Visual was invalidated during the render pass` This issue isn't related to text rendering

@Gillibald @maxkatz6  Sorry, I can not see that exception. But I have changed the code and removed the LogService, which is used to clarify the progress. Now without the LogService, you need to see the result by DevTools.

![image](https://github.com/user-attachments/assets/fcac8498-ff33-4715-8ebc-d09f275412d2)


> Also, why do you early return from OnPropertyChanged method?
> Base TextBox.OnPropertyChanged is never called for other properties because of that, which might cause unwanted behavior.

You are right. That's wrong. I need to filter some debugger breakings when debugging. I just forget to delete it. And, the whole MyTextBlock's logical is not necessary. It's for debugging. I have removed it.

**Comment by liwuqingxin** [comment] 2024-07-26 06:38
@maxkatz6 I don't think that the #16481 can fix this problem.

In the process of this problem, There are 4 changes to TextBlock's Text. After the 2nd change, The rendering, which is fired by `MediaContext.Instance.SyncDisposeCompositionTarget`, comes and rebuild the TextLayout by accessing TextBlock.TextLayout property.

In the `Layoutable.InvalidateMeasure()`, `if (!this.IsMeasureValid) return;` will skip the calling of `this.OnMeasureInvalidated();`. So the TextLayout will not be rebuilt anymore.

**Comment by liwuqingxin** [comment] 2024-07-26 06:43
@maxkatz6 @Gillibald  In the process of this problem, There are 4 changes to TextBlock's Text. After the 2nd change, The rendering, which is fired by `MediaContext.Instance.SyncDisposeCompositionTarget`, comes and rebuild the TextLayout by accessing TextBlock.TextLayout property.

In the `Layoutable.InvalidateMeasure()`, `if (!this.IsMeasureValid) return;` will skip the calling of `this.OnMeasureInvalidated();`. So the TextLayout will not be rebuilt anymore.

So with the pr #16481, can the rendering between the changes be prevented?

**Comment by maxkatz6** [comment] 2024-07-26 06:51
> So with the pr https://github.com/AvaloniaUI/Avalonia/pull/16481, can the rendering between the changes be prevented?

TextBlock will be invalidated on each Text change, but rendering is scheduled independently after. So, it won't render between text changes, if they happened right after each other.

**Closed** 2024-07-29 20:33 UTC
Labels: bug, needs-author-action
