### ISSUE TITLE
Window.Close on second Window shutdown application on Linux

### ISSUE THREAD

**Issue by ficnar** [AvaloniaUI/Avalonia#1746] opened 2018-07-11 15:09 UTC
When I open the second window from the main window and in second window call Window.Close, then occur shutdown application.
This occur only on Linux (I tried on CentOS). On Windows and MaxOSX it work properly.

**Comment by Gillibald** [comment] 2018-07-12 12:32
We have to make sure that both windows are present on Application.Current.Windows before closing if not that is the cause of the issue.

**Comment by ficnar** [comment] 2018-07-12 13:34
I am using the last distributed version 0.6.1. In this version, Application has not property Windows. But the similar field is Window.s_windows. In this field are correct my two windows.

**Comment by Gillibald** [comment] 2018-07-12 15:17
Pls try to use the latest nightly build. This part has changed lately.

**Comment by ficnar** [comment] 2018-07-12 16:21
In actual version 0.6.2 Build 5670-beta Window.Close works fine if the window opened by ShowDialog. If opened by Show, then shutdown application occure still.

**Comment by Gillibald** [comment] 2018-07-12 16:30
I wonder if the application is actually shutting down or if it crashes. Have you checked if all windows are added to Application.Current.Windows?

**Comment by ficnar** [comment] 2018-07-12 17:21
Application shutting down, no crash. In property Application.Current.Windows are two my Windows before calling Close, it is correct. Close window by cross button works fine.

**Comment by Gillibald** [comment] 2018-07-12 20:17
Probably have to debug it on a Linux machine. Will have a look at it when I have time.

**Comment by grokys** [comment] 2021-02-17 18:44
Should be fixed.

**Closed by grokys** 2021-02-17 18:44 UTC
Labels: bug, linux
