### ISSUE TITLE
Add support for non-empty constructors in View and UserControl

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#9635] opened 2022-12-06 00:32 UTC
**Is your feature request related to a problem? Please describe.**
When I try to use non-empty ctor in UserControls, a compile error will show:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/25716486/205776512-240d09ce-198a-42cf-bf31-07e71eb67138.png">

**Describe the solution you'd like**
Add support for non-empty constructors in View and UserControl

**Describe alternatives you've considered**
-

**Comment by maxkatz6** [comment] 2022-12-06 01:17
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2593

**Closed by maxkatz6** 2022-12-06 01:17 UTC
Labels: enhancement

**Comment by laolarou726** [comment] 2022-12-06 01:34
> Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2593

Any plans to fix it?

**Comment by laolarou726** [comment] 2022-12-06 15:49
> @laolarou726 done

Thank you guys so much! That's helped a lot.
