### ISSUE TITLE
[NativeAOT] System.NotSupportedException in UiaReturnRawElementProvider

### ISSUE THREAD

**Issue by AhmedZero** [AvaloniaUI/Avalonia#9478] opened 2022-11-19 20:38 UTC
**Describe the bug**
sometimes, I face that exception, and sometimes the app works well.
```
System.NotSupportedException: COM Interop requires ComWrapper instance registered for marshalling.
   at System.Runtime.InteropServices.ComWrappers.ComInterfaceForObject(Object) + 0x56
   at System.Runtime.InteropServices.ComWrappers.ComInterfaceForObject(Object, Guid) + 0x20
   at Avalonia.Win32.Interop.Automation.UiaCoreProviderApi.UiaReturnRawElementProvider(IntPtr hwnd, IntPtr wParam, IntPtr lParam, IRawElementProviderSimple el) + 0xa3
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) + 0x1f5f
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) + 0x80
   at MyProjectTest!<BaseAddress>+0x18ff93a
```

**To Reproduce**

**Expected behavior**
 The error should not happen.

**Screenshots**

**Desktop:**

- OS: Windows
- Version 11.0.0-preview4

**Additional context**
rd.xml
```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
	<Application>
		<Assembly Name="MyProjectTest" Dynamic="Required All" />
		<Assembly Name="Avalonia.Themes.Fluent" Dynamic="Required All" />
		<Assembly Name="Avalonia.Controls.DataGrid" Dynamic="Required All" />		
	</Application>
</Directives>
```
Program.cs
```C#
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using System;
using Avalonia.ReactiveUI;
using Splat;
using ReactiveUI;
using System.Reflection;
using MyProjectTest.Views;
using MyProjectTest.ViewModels;
using System.Runtime.InteropServices;
using Avalonia.Controls.Notifications;
using System.IO;

namespace MyProjectTest
{
    internal class Program
    {
     
        // Initialization code. Don't use any Avalonia, third-party APIs or any
        // SynchronizationContext-reliant code before AppMain is called: things aren't initialized
        // yet and stuff might break.
        [STAThread]
        public static void Main(string[] args) => BuildAvaloniaApp()
            .StartWithClassicDesktopLifetime(args);

        // Avalonia configuration, don't remove; also used by visual designer.
        public static AppBuilder BuildAvaloniaApp()
        {

            Locator.CurrentMutable.RegisterViewsForViewModels(Assembly.GetExecutingAssembly());
            return AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .LogToTrace().UseReactiveUI();
        }


    }
}
```
App.axaml.cs
```C#
using Avalonia;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Markup.Xaml;
using AmazonPriceTracking.ViewModels;
using AmazonPriceTracking.Views;

namespace AmazonPriceTracking
{
    public partial class App : Application
    {
        public override void Initialize()
        {
            AvaloniaXamlLoader.Load(this);
        }

        public override void OnFrameworkInitializationCompleted()
        {
            if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
            {
                desktop.MainWindow = new MainWindow()
                {
                    DataContext = new MainWindowViewModel()
                };
            }

            base.OnFrameworkInitializationCompleted();
        }
    }
}
```
App.axaml
```xml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
			              xmlns:local="clr-namespace:AmazonPriceTracking"
             x:Class="AmazonPriceTracking.App">
    <Application.Styles>
        <FluentTheme Mode="Light"/>
		<StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Fluent.xaml"/>
	</Application.Styles>
</Application>
```

**Comment by maxkatz6** [comment] 2022-11-20 02:39
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/8006

**Closed by maxkatz6** 2022-11-20 02:39 UTC
Labels: bug
