### ISSUE TITLE
canResize does not work on Linux.

### ISSUE THREAD

**Issue by herrwinfried** [AvaloniaUI/Avalonia#10125] opened 2023-01-29 17:57 UTC
**Describe the bug**
Even if you set [canResize](https://reference.avaloniaui.net/api/Avalonia.Controls/Window/F2AEF153) to false, window magnification works on Linux and the window grows 20% (not sure of its size). 

**To Reproduce**

1. Go to MainWindow.axaml
2. Create a window with the window tag.
3. Add the value [CanResize](https://reference.avaloniaui.net/api/Avalonia.Controls/Window/F2AEF153)="True" to the window.

**Expected behavior**
The size of the window does not change

**Desktop (please complete the following information):**

- OS: Linux (OpenSUSE Tumbleweed)
- Avalonia Version: 11.0.0-preview4

**Comment by maxkatz6** [comment] 2023-01-29 19:09
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/8329

**Closed by maxkatz6** 2023-01-29 19:09 UTC
Labels: bug, help-wanted, os-linux
