### ISSUE TITLE
ProgressBar rendering artifacts

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2015] opened 2018-10-24 10:11 UTC
![progressbarartifacts](https://user-images.githubusercontent.com/2297442/47423627-d345f680-d785-11e8-8002-bdd6960f9705.gif)

Repro: Just run the app, scroll in Preview tab item to ProgressBar's and wait.

https://github.com/wieslawsoltes/Avalonia/tree/7b90780404aa178a1e728c0acf764a73acb2a6ba/samples/ThemeEditor

Skia+OpenGL+Win7 x64

**Comment by danwalmsley** [comment] 2018-10-24 10:48
duplicate of https://github.com/AvaloniaUI/Avalonia/issues/1960

**Comment by kekekeks** [comment] 2018-10-24 11:01
I've noticed that happening even without scaling on Skia/OpenGL/X11, so I don't think it's an exact duplicate.

**Comment by jmacato** [comment] 2018-10-24 11:17
does this happen on ImmediateRenderer too?

**Comment by danwalmsley** [comment] 2018-10-24 11:18
@jmacato #1960 shows what happens on immediate
its different effect, its not related to dpi as 1960 incorrectly implies.

**Comment by donandren** [comment] 2018-10-24 12:34
this issue may be fixed in pr #2002

**Comment by grokys** [comment] 2019-02-19 15:58
Just taken another look at this and it seems to still be an issue. Problem seems to occur for me only when scaling is != 100% on both skia and D2D backends.

**Comment by danwalmsley** [comment] 2019-02-19 17:53
https://github.com/AvaloniaUI/Avalonia/issues/1960

**Closed** 2019-03-08 14:38 UTC
Labels: bug, rendering
