### ISSUE TITLE
Many binding errors when exiting desktop program

### ISSUE THREAD

**Issue by mike-ward** [AvaloniaUI/Avalonia#5163] opened 2020-12-10 13:53 UTC
When exiting my desktop program, I see many binding errors (Windows 10, 0.10 Preview 6). These bindings are valid when the program is in use.

While not fatal, it does create a lot of output in the debug console.

```
[Binding] Error in binding to 'Avalonia.Controls.ItemsRepeater'.'Width': 'Null value in expression '$parent[MainWindow, 0]'.' (ItemsRepeater #16246551)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #50315352)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #25911262)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #5223998)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #34829302)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #38891250)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #42371273)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #64268160)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #25935173)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #36446461)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #47192740)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #50261201)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #9915935)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #32075938)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #15337269)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #6128980)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #66479500)
[Binding] Error in binding to 'Avalonia.Controls.Button'.'Command': 'Null value in expression '$parent[UserControl, 0]'.' (Button #21982073)
```

**Comment by maxkatz6** [comment] 2023-01-28 01:41
Duplicate of #5762

**Closed by maxkatz6** 2023-01-28 01:41 UTC
