### ISSUE TITLE
Overlay Popups is not constrained by window bounds

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#5628] opened 2021-03-07 04:17 UTC
**Describe the bug**
Overlay Popups is not constrained by window bounds

**To Reproduce**

1. Enable OverlayPopups
2. Open any popup that doesn't fit the window bounds
4. See the issue, popup is cropped

**Screenshots**
![image](https://user-images.githubusercontent.com/3163374/110228733-63a5b180-7ed1-11eb-9f99-9f896dc89848.png)

**Expected behavior**
Popup bounds should be constrained by window bounds (on screenshot below Windows PopupHost is used, with the same expected behavior)
![image](https://user-images.githubusercontent.com/3163374/110228780-c5feb200-7ed1-11eb-9419-f8737bf36350.png)

**Desktop (please complete the following information):**

- OS: Windows (should be reproduceable on any)
- Version 0.10.0

**Comment by maxkatz6** [comment] 2021-03-07 04:18
It's critical on mobile devices, where all popups are overlay only.

**Comment by kekekeks** [comment] 2021-03-07 08:46
It used to work when overlay popups were initially implemented. I was specifically checking for that particular scenario.

We definitely need more automated testing for overlay popups, since people change popup logic and ignore overlay mode completely.

**Comment by simonhaines** [comment] 2021-11-05 00:53
@maxkatz6, just to add another data point, I am unable to reproduce this on Windows and Linux (with `OverlayPopups` set to true) and this issue may have been fixed by @MarchingCube as described in the resolution to #5766.

**Windows**
![windows](https://user-images.githubusercontent.com/18539/140440258-ba47545c-0519-480b-98a5-8ba03de7bd25.png)

**Linux**
![linux](https://user-images.githubusercontent.com/18539/140440277-6e1876b5-3388-480e-aa92-9aa6350d662d.png)

**Closed** 2021-11-05 01:06 UTC
Labels: bug
