### ISSUE TITLE
DefaultValueConverter does not work within styles

### ISSUE THREAD

**Issue by viktorspacil** [AvaloniaUI/Avalonia#16113] opened 2024-06-25 07:53 UTC
### Describe the bug

I had to newly explicitly register and specify DefaultValueConverter for bindings within styles to automatically convert Methods to ICommand. This is new behavior coming with the vesion 11.1.0-rc1, version 11.0.10 was ok. Minimal sample to simulate this behavior is attached. 
[TestApp.zip](https://github.com/user-attachments/files/15966920/TestApp.zip)

### To Reproduce

1. Start the app
2. Button "Click me" should be clickable but it is not (it is grey out/disabled)

You have to explicitly set the DefaultValueConverter converter on binding for the Command property within button style to get the button working.

### Avalonia version

11.1.0-rc1

**Comment by grokys** [comment] 2024-06-25 12:53
Thanks @viktorspacil - yep looks like a regression. The reason I couldn't reproduce is that the command is bound in a style - I didn't try that and seems we have no tests for this case.

The source of the problem is that the XAML compiler is producing a call to `CompiledBindingPathBuilder.Method` in this case instead of a `CompiledBindingPathBuilder.Command` even though it should be possible to determine that the method is being bound to a command here.

This worked before the binding refactor because the default value converter even in the case of compiled bindings used `MethodToCommandConverter` however after the binding refactor, `MethodToCommandConverter` is only used for reflection bindings as it's marked as `RequiresUnreferencedCode`.

I think the best fix will be to make the XAML compiler recognise that the binding needs to provide an `ICommand`.

I think the correct fix should be to

**Closed** 2024-06-26 02:49 UTC
Labels: bug, regression
