### ISSUE TITLE
compile the project error

### ISSUE THREAD

**Issue by bouyeijiang** [AvaloniaUI/Avalonia#11045] opened 2023-04-18 01:47 UTC
version:Avalonia 11.0.0 preview6

when i compile the project has an error:

09:42:44.637 [Error] 38964 <= "Unhandled exception. System.TypeLoadException: Method 'Load' in type 'Avalonia.Designer.HostApp.DesignXamlLoader' from assembly 'Avalonia.Designer.HostApp, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b' does not have an implementation."
09:42:44.639 [Error] 38964 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args)"
09:42:47.204 [Information]  Process exited while waiting for connection to be initialized.
09:42:47.206 [Information]  Process exited
09:42:47.207 [Information]  Stopping previewer process

**Comment by timunie** [comment] 2023-04-18 06:13
@bouyeijiang we need way more information. Best if you can prepare a minimal repo to reproduce the issue, so we can test on our own.

**Comment by bouyeijiang** [comment] 2023-04-18 07:36
mybe its due to plugin,but the project can run

**Comment by timunie** [comment] 2023-04-18 07:46
previewer can be a problem sometimes, yes. For example if the App has to do things that the previewer can't do. Do you think we can safely close this issue as for now?

**Comment by timunie** [comment] 2023-04-20 11:26
@bouyeijiang Closing this issue for now as it seems to be not reproduceable. If you provide a sample to reproduce, we can open it again for sure.

**Closed by timunie** 2023-04-20 11:26 UTC
Labels: bug, needs-repro
