### ISSUE TITLE
Right-clicking popup will open parent ContextMenu in top-left screen corner

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#5101] opened 2020-11-24 17:04 UTC
[repro_popup_ctx_menu_parent.patch.txt](https://github.com/AvaloniaUI/Avalonia/files/5591493/repro_popup_ctx_menu_parent.patch.txt)

**Comment by grokys** [comment] 2021-02-15 12:24
Caused by this hack:

https://github.com/AvaloniaUI/Avalonia/blob/cae9badc1c3220baa4400c3db3a3e548075c50fe/src/Avalonia.Controls/Primitives/PopupPositioning/IPopupPositioner.cs#L449-L450

What happens is:

- The context menu is assigned to the `ToggleButton`
- The toggle button opens a popup
- When the popup is right-clicked, the `ToggleButton` handles the click and requests to open the context menu
- `ContextMenu.Open(Control? control)` is called with the `ToggleButton` as the parameter
- The popup's `PlacementTarget` is set to the `ToggleButton`
- When the popup positioner code runs, it looks for the visual root to get the mouse position (the code linked above)
- The mouse isn't over that visual root as it's over the popup therefore a position of -1.-1 is returned
- The popup opens at -1, 1

**Comment by grokys** [comment] 2021-02-15 12:32
I think the easiest solution for now is to pass the clicked control as the placement target.

**Closed** 2021-02-16 15:11 UTC
Labels: bug
