### ISSUE TITLE
DataGrid Adaptive exception

### ISSUE THREAD

**Issue by Hzlin7** [AvaloniaUI/Avalonia#15897] opened 2024-06-03 12:04 UTC
### Describe the bug

I placed the StackPanel in the second row of the Grid with its RowDefinitions set to *, placed the DataGrid in the StackPanel and set the StackPanel VerticalAlignment to Top, and when I added the Items data, The height of the StackPanel does not automatically increase, it only updat

https://github.com/AvaloniaUI/Avalonia/assets/31055209/6fe1af8b-0b9f-4039-a969-88ee8a3ff0bc

es when I swipe the scroll bar.

### To Reproduce

This is my test code. 
```axaml
<Window
    x:Class="AvaloniaDataGridTest.Views.MainWindow"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:vm="using:AvaloniaDataGridTest.ViewModels"
    Title="AvaloniaDataGridTest"
    d:DesignHeight="450"
    d:DesignWidth="800"
    x:DataType="vm:MainWindowViewModel"
    Icon="/Assets/avalonia-logo.ico"
    mc:Ignorable="d">

    <Design.DataContext>
        <!--
            This only sets the DataContext for the previewer in an IDE,
            to set the actual DataContext for runtime, set the DataContext property in code (look at App.axaml.cs)
        -->
        <vm:MainWindowViewModel />
    </Design.DataContext>


    <Grid RowDefinitions="50,*,50">
        <StackPanel
            x:Name="top"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            Orientation="Horizontal">
            <Button
                Margin="0,0,0,10"
                HorizontalAlignment="Center"
                VerticalAlignment="Center"
                Command="{Binding MoreCommand}">
                More
            </Button>
            <Button
                Margin="10,0,0,10"
                HorizontalAlignment="Center"
                VerticalAlignment="Center"
                Command="{Binding LessCommand}">
                Less
            </Button>
        </StackPanel>

        <StackPanel
            Orientation="Horizontal"
            Grid.Row="1"
            x:Name="table"
            Background="#CCCCCC"
            Width="600" 
            HorizontalAlignment="Center" 
            VerticalAlignment="Top">
            <DataGrid
                x:Name="dataGrid"
                Background="#DCDCDC"
                CornerRadius="20"
                Width="400"
                ItemsSource="{Binding Items}">
                <DataGrid.Columns>
                    <DataGridTextColumn Binding="{Binding Age}" Header="Age" />
                    <DataGridTextColumn Binding="{Binding Name}" Header="Name" />
                </DataGrid.Columns>
            </DataGrid>
        </StackPanel>

        <StackPanel
            Grid.Row="2"
            x:Name="bottom"
            HorizontalAlignment="Center"
            Orientation="Horizontal">
            <Rectangle Fill="#DCDCDC" Width="100" Height="40">
            </Rectangle>
        </StackPanel>
    </Grid >

</Window>
```

### Avalonia version

11.0.0-rc2.2

### OS

Windows

**Comment by jp2masa** [comment] 2024-06-03 17:59
You shouldn't place a `DataGrid` inside a `StackPanel` or any other control that measures with infinite height (e.g. `Grid` row with `Height="Auto"`.

Related:

- https://github.com/AvaloniaUI/Avalonia/issues/14120#issuecomment-1878284648
- https://github.com/AvaloniaUI/Avalonia/issues/9726#issuecomment-1772320997
- https://github.com/AvaloniaUI/Avalonia/discussions/6196#discussioncomment-969671

**Comment by Hzlin7** [comment] 2024-06-04 02:42
When I write axaml like this, the behavior is also the same as in the video. I want the DataGrid height can automatically increase when adding data.
```axaml
    x:Class="AvaloniaDataGridTest.Views.MainWindow"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:vm="using:AvaloniaDataGridTest.ViewModels"
    Title="AvaloniaDataGridTest"
    d:DesignHeight="450"
    d:DesignWidth="800"
    x:DataType="vm:MainWindowViewModel"
    Icon="/Assets/avalonia-logo.ico"
    mc:Ignorable="d">

    <Design.DataContext>
        <vm:MainWindowViewModel />
    </Design.DataContext>

    <DataGrid
            x:Name="dataGrid"
            Background="#DCDCDC"
            Margin="20"
            CornerRadius="16"
            Width="400"
            VerticalAlignment="Top"
            ItemsSource="{Binding Items}">
        <DataGrid.Columns>
            <DataGridTextColumn Binding="{Binding Age}" Header="Age" />
            <DataGridTextColumn Binding="{Binding Name}" Header="Name" />
        </DataGrid.Columns>
    </DataGrid>

</Window>
```

**Comment by jp2masa** [comment] 2024-06-04 21:58
The behavior can't be the same. I just tested that code and it seems to work as you want, unless you want to disable the scroll bar. You can also set `MaxHeight` on your original example to make sure the height is not unbounded. Anyway, simply removing the wrapping `StackPanel` should work and would look good, in my opinion.

**Comment by Hzlin7** [comment] 2024-06-06 02:57
I want the behavior of adding data to the DataGrid to be the same as that of the ListBox.
```axaml
<Grid ColumnDefinitions="*,*" RowDefinitions="50,*">
    <Button Grid.ColumnSpan="2" x:Name="addButton" Command="{Binding MoreCommand}" Width="60" Height="30" HorizontalAlignment="Center" Content="Add"/>
    <ListBox Grid.Row="1"
             Grid.Column="0"
             ItemsSource="{Binding ListItems}"
             Margin="20"
             VerticalAlignment="Top"/>
    <DataGrid Grid.Row="1"
              Grid.Column="1"
              VerticalAlignment="Top"
              Margin="20"
              Background="#CECECE"
              CornerRadius="20"
              ItemsSource="{Binding DataItems}">
        <DataGrid.Columns>
            <DataGridTextColumn Binding="{Binding Age}" Header="Age" />
            <DataGridTextColumn Binding="{Binding Name}" Header="Name" />
        </DataGrid.Columns>
    </DataGrid>
</Grid>
```

https://github.com/AvaloniaUI/Avalonia/assets/31055209/3ce4dcd1-6d4c-42c4-8d89-bfda3e70dc13

**Comment by jp2masa** [comment] 2024-06-06 18:57
You're right, there is a difference when `VerticalAlignment="Top"`. I would recommend using `Stretch` (the default) if possible.

I think that the `DataGrid` should be remeasured when items change, but that is not happening.

**Comment by timunie** [comment] 2024-06-07 07:25
Duplicate of #9726

**Closed** 2024-06-07 07:25 UTC
Labels: bug, area-datagrid
