### ISSUE TITLE
WrapPanel inside Listbox (ItemsPanelTemplate) only work/wrap with FluentTheme.

### ISSUE THREAD

**Issue by H97-Git** [AvaloniaUI/Avalonia#15788] opened 2024-05-22 15:11 UTC
### Describe the bug

1. WrapPanel inside a ListBox doesn't wrap.
2. If used with anything else than FluentTheme.

![2024_05_22_16-59__wPl](https://github.com/AvaloniaUI/Avalonia/assets/32843752/a0ac1572-c6cb-4a1c-abe2-41e619eecfd4)
![2024_05_22_17-00__G7T](https://github.com/AvaloniaUI/Avalonia/assets/32843752/74980712-056e-4409-a8ab-2845f58e6970)

### To Reproduce

> Quick repo to reproduce

[Avalonia.Sandbox](https://github.com/H97-Git/Avalonia.Sandbox/blob/main/Views/MainWindow.axaml)

### Expected behavior

WrapPanel should wrap regardless of the theme used.

### Avalonia version

11.0.10

### OS

Windows

### Additional context

I was testing ActiPro theme/Controls inside my app and using the theme broke the layout for my file explorer.
At first I thought it was an ActiPro issue but with further testing I saw that WrapPanel inside ListBox only wrap with FluentTheme.

Maybe I did something wrong and this is not a bug but I will rather ask.

**Comment by MrJul** [comment] 2024-05-22 17:09
It isn't really related to `WrapPanel` itself.

The `HorizontalScrollBarVisibility` for `ListBox` is set to `Auto` in the Simple theme:
https://github.com/AvaloniaUI/Avalonia/blob/b30894cb5c1e2403b70e72853ffbd0176ad7c6dd/src/Avalonia.Themes.Simple/Controls/ListBox.xaml#L10

This gives the control infinite horizontal space, so as far as the `WrapPanel` is concerned, there's enough space and nothing is wrapped. The default is `Disabled`, which is what the Fluent theme uses.

Add `ScrollViewer.HorizontalScrollBarVisibility="Disabled"` to your `ListBox` and it'll work with all themes.

That being said, I'm leaving this issue open, as I'm not sure sure why the Simple theme uses `Auto` here. Git blame says that it was `Auto` for both themes in the post, then Fluent has been changed to `Disabled`, but Simple hasn't been touched.

I suggest we change the default to `Disabled` for the Simple theme too.

**Comment by MrJul** [comment] 2024-05-22 18:59
> I'm not sure how to:
> 
> > Add `ScrollViewer.HorizontalScrollBarVisibility="Disabled"` to your `ListBox` and it'll work with all themes.

As typed :) It's an attached property, like `Grid.Row`:
`<ListBox ScrollViewer.HorizontalScrollBarVisibility="Disabled" ...>`

**Comment by maxkatz6** [comment] 2024-05-23 08:39
Closing as by design. With options to redefine behavior.

**Closed by maxkatz6** 2024-05-23 08:39 UTC
Labels: bug

**Comment by timunie** [comment] 2024-05-23 09:44
@maxkatz6 do you think simple theme should be changed to follow FluentTheme here or not?
