### ISSUE TITLE
ContextMenu throws InvalidOperationException when the source collection changes

### ISSUE THREAD

**Issue by Kir-Antipov** [AvaloniaUI/Avalonia#4706] opened 2020-09-20 20:35 UTC
## Objective's description

I need а `ContextMenu` for each item in collection that provides actions related to each item in the same collection. Like so:

![example](https://user-images.githubusercontent.com/40232067/93721042-07a2d700-fb96-11ea-9509-899294310549.png)

## Implementation

So, there're ViewModel and View:

```c#
public class MainWindowViewModel : ViewModelBase
{
    public ObservableCollection<string> Items { get; } = new ObservableCollection<string>();

    public void Add() => Items.Add(DateTime.UtcNow.ToString("O"));

    public void Remove()
    {
        if (Items.Count > 0)
            Items.RemoveAt(0);
    }

    public void MenuItemClicked() { }
}
```

```xaml
<StackPanel>
    <ListBox Items="{Binding Items}">
        <ListBox.Styles>
            <Style Selector="TextBlock">
                <Setter Property="ContextMenu">
                    <ContextMenu>
                        <MenuItem Header="Inner" Items="{Binding $parent[ListBox].DataContext.Items}">
                            <MenuItem.Styles>
                                <Style Selector="MenuItem">
                                    <Setter Property="Header" Value="{Binding}"/>
                                    <Setter Property="Command" Value="{Binding $parent[ListBox].DataContext.MenuItemClicked}"/>
                                </Style>
                            </MenuItem.Styles>
                        </MenuItem>
                    </ContextMenu>
                </Setter>
            </Style>
        </ListBox.Styles>
        <ListBox.ItemTemplate>
            <DataTemplate>
                <TextBlock Text="{Binding}"/>
            </DataTemplate>
        </ListBox.ItemTemplate>
    </ListBox>
    <Button Command="{Binding Add}">Add</Button>
    <Button Command="{Binding Remove}">Remove</Button>
</StackPanel>
```

[Full MCVE](https://github.com/Kir-Antipov/Avalonia-Issue-4706)

## The problem

After the context menu has been initialized, the application crashes with an `InvalidOperationException` if I try to change the collection (add an item there or delete any).

If I change `ObservableCollection<string>` to `List<string>` and manually invoke `PropertyChanged` event for the `Items` property, than everything is ok. So I really feel like tagging @grokys, [who's huge fan of the `INotifyCollectionChanged` interface](https://twitter.com/grokys/status/1305767363535659009) :)

## Details

**Exception**: `System.InvalidOperationException`: 'Cannot change source while update is in progress.'
**Avalonia**: 0.10.0-preview5
**OS**: Win10
**StackTrace**: 

> at Avalonia.Controls.Selection.SelectionModel`1.SetSource(IEnumerable value)
   at Avalonia.Controls.Selection.SelectionModel`1.Avalonia.Controls.Selection.ISelectionModel.set_Source(IEnumerable value)
   at Avalonia.Controls.Primitives.SelectingItemsControl.OnDataContextEndUpdate()
   at Avalonia.StyledElement.DataContextNotifying(StyledElement element, Boolean updateStarted)
   at Avalonia.StyledElement.DataContextNotifying(IAvaloniaObject o, Boolean updateStarted)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.Avalonia.IAvaloniaObject.InheritedPropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, Optional`1 newValue)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.Avalonia.IAvaloniaObject.InheritedPropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, Optional`1 newValue)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.InheritanceParentChanged[T](StyledPropertyBase`1 property, IAvaloniaObject oldParent)
   at Avalonia.StyledPropertyBase`1.RouteInheritanceParentChanged(AvaloniaObject o, IAvaloniaObject oldParent)
   at Avalonia.AvaloniaObject.set_InheritanceParent(IAvaloniaObject value)
   at Avalonia.StyledElement.Avalonia.Controls.ISetLogicalParent.SetParent(ILogical parent)
   at Avalonia.Controls.ContextMenu.ContextMenuChanged(AvaloniaPropertyChangedEventArgs e)
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 148
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change)
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.Completed[T](StyledPropertyBase`1 property, IPriorityValueEntry entry, Optional`1 oldValue)
   at Avalonia.ValueStore.Avalonia.PropertyStore.IValueSink.Completed[T](StyledPropertyBase`1 property, IPriorityValueEntry entry, Optional`1 oldValue)
   at Avalonia.PropertyStore.ConstantValueEntry`1.Dispose()
   at Avalonia.Styling.PropertySetterInstance`1.Dispose()
   at Avalonia.Styling.StyleInstance.Dispose()
   at Avalonia.StyledElement.DetachStyles()
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.Avalonia.Controls.ISetLogicalParent.SetParent(ILogical parent)
   at Avalonia.StyledElement.ClearLogicalParent(IEnumerable`1 children)
   at Avalonia.StyledElement.LogicalChildrenCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Visual.LogicalChildrenCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyRemove(T item, Int32 index)
   at Avalonia.Collections.AvaloniaList`1.Remove(T item)
   at Avalonia.Controls.ItemsControl.OnContainersDematerialized(ItemContainerEventArgs e)
   at Avalonia.Controls.Primitives.SelectingItemsControl.OnContainersDematerialized(ItemContainerEventArgs e)
   at Avalonia.Controls.ItemsControl.<get_ItemContainerGenerator>b__11_1(Object _, ItemContainerEventArgs e)
   at Avalonia.Controls.Generators.ItemContainerGenerator.Dematerialize(Int32 startingIndex, Int32 count)
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.RemoveContainers(Int32 count)
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.RecycleContainersOnRemove()
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.ItemsChanged(IEnumerable items, NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.Presenters.ItemsPresenter.ItemsChanged(NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.Presenters.ItemsPresenterBase.Avalonia.Controls.Presenters.IItemsPresenter.ItemsChanged(NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.ItemsControl.ItemsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.Primitives.SelectingItemsControl.ItemsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.ItemsControl.Avalonia.Controls.Utils.ICollectionChangedListener.PostChanged(INotifyCollectionChanged sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.Utils.CollectionChangedEventManager.Entry.<Avalonia.Utilities.IWeakSubscriber<System.Collections.Specialized.NotifyCollectionChangedEventArgs>.OnEvent>g__Notify|6_0(INotifyCollectionChanged incc, NotifyCollectionChangedEventArgs args, List`1 listeners)
   at Avalonia.Controls.Utils.CollectionChangedEventManager.Entry.Avalonia.Utilities.IWeakSubscriber<System.Collections.Specialized.NotifyCollectionChangedEventArgs>.OnEvent(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Utilities.WeakSubscriptionManager.Subscription`1.OnEvent(Object sender, T eventArgs)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.RemoveItem(Int32 index)
   at System.Collections.ObjectModel.Collection`1.RemoveAt(Int32 index)
   at ContextMenu.ViewModels.MainWindowViewModel.Remove() in C:\Projects\Visual\Projects\ContextMenu\ContextMenu\ViewModels\MainWindowViewModel.cs:line 15
   at Avalonia.Data.Converters.MethodToCommandConverter.Execute(Object parameter)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__26_9(InputElement x, PointerReleasedEventArgs e)
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 36
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 150
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
-------------

**Comment by maxkatz6** [comment] 2020-09-20 21:15
It could be already fixed in the latest nightly packages. Can you check them?

**Comment by Kir-Antipov** [comment] 2020-09-20 21:16
> It could be already fixed in the latest nightly packages. Can you check them?

@maxkatz6, oh. Ok. Give me few minutes

**Comment by Kir-Antipov** [comment] 2020-09-20 21:38
@maxkatz6, yep, that's true. It's not the case for `0.10.999-cibuild0010825-beta` anymore. Now it throws new exception :D

Now collection changes without any issues, but when I click on the MenuItem, an `ArgumentOutOfRangeException` is thrown:

> at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at Avalonia.Collections.AvaloniaList`1.get_Item(Int32 index)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.Avalonia.LogicalTree.ILogical.NotifyDetachedFromLogicalTree(LogicalTreeAttachmentEventArgs e)
   at Avalonia.Controls.TopLevel.HandleClosed()
   at Avalonia.Controls.WindowBase.HandleClosed()
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)

Did I do something wrong with the example, or should I open a new issue?

**Comment by grokys** [comment] 2020-09-23 07:28
Taking a look into this a bit deeper, it the problem is that `<Style Selector="TextBlock">` causes a recursion - each `MenuItem` in the context menu has a `TextBlock` which displays the menu text. When the menu is shown, a context menu is attached to the `TextBlock` in the context menu.

This doesn't cause a problem because the nested context menu is never shown, _until_ the context menu is closed in which case it triggers a "detached from logical" event during the "detached from logical tree" event of the parent context menu item.

Detaching a control from the logical tree during a logical tree detachment should definitely be allowed, but I fear @maxkatz6's solution in #4707 is going to cause a memory spike on large trees.

We need to come up with a solution for this longer-term but in the meantime @Kir-Antipov - I'd suggest not attaching context menus to _all_ `TextBlock`s in the subtree, because as you've seen `TextBlock` is used by many controls. Either attach the context menu to the `ListBoxItem`s (tested and works fine) or apply a class to the `TextBlock`s in the data template.

Hope that helps! This time it wasn't the fault of `INotifyCollectionChanged` ;)

**Closed by grokys** 2020-09-23 07:28 UTC
