### ISSUE TITLE
Animations start with a one-frame delay in Avalonia 11

### ISSUE THREAD

**Issue by TomEdwardsEnscape** [AvaloniaUI/Avalonia#8805] opened 2022-08-22 09:46 UTC
**Describe the bug**
As of Avalonia 11 preview 1, controls are rendered for a single frame before animations begin. This is very noticeable if the animation is fading the control in by changing its opacity.

This does not happen in Avalonia 0.10.18

**To Reproduce**
Paste the following XAML into a new window, run it, and click the button:

```xaml
<Grid RowDefinitions="Auto,*">
    <ToggleButton Name="Toggle">Begin animation</ToggleButton>
    <Border Grid.Row="1" Background="Red" IsVisible="{Binding IsChecked, ElementName=Toggle}">
        <Border.Styles>
            <Style Selector="Border[IsVisible=true]">
                <Style.Animations>
                    <Animation Duration="0:0:1">
                        <KeyFrame Cue="0%">
                            <Setter Property="Opacity" Value="0.0"/>
                        </KeyFrame>
                        <KeyFrame Cue="90%">
                            <Setter Property="Opacity" Value="0.0"/>
                        </KeyFrame>
                        <KeyFrame Cue="100%">
                            <Setter Property="Opacity" Value="1.0"/>
                        </KeyFrame>
                    </Animation>
                </Style.Animations>
            </Style>
        </Border.Styles>
    </Border>
</Grid>
```

You will see the red border flicker on-screen as soon as the button is clicked.

**Expected behavior**
When the control's becomes visible its opacity is immediately set to zero, and no red border is drawn until the animation starts to raise the opacity value (after 900ms).

**Desktop (please complete the following information):**

- OS: Windows
- Version: 11 preview 1

**Comment by kekekeks** [comment] 2022-08-22 09:51
@jmacato

**Comment by amwx** [comment] 2023-03-24 23:18
I figured out if you add a setter to the style setting the opacity to 0 the animation runs as expected:
```xaml
<Style Selector="Border[IsVisible=true]">
    <Setter Property="Opacity" Value="0" />
    ....
</Style>
```

I wonder if this was an unintended side effect of the styling system changes for 11.0 rather than rendering that cause animations to be delayed 1 value frame in a style trigger?

**Comment by kekekeks** [comment] 2023-03-25 05:46
It happens because animation timer is desynchronized from preparing the next frame. We'll be introducing something similar to WPF's MediaContext to deal with that.

**Comment by maxkatz6** [comment] 2023-05-30 22:52
I believe it was fixed after https://github.com/AvaloniaUI/Avalonia/pull/11552
Let me know if it's still reproducible

**Comment by tomenscape** [comment] 2023-05-31 14:54
It's fixed. 👍

**Comment by tomenscape** [comment] 2023-07-03 11:33
It's broken again in RC2.2 👎

**Comment by tomenscape** [comment] 2023-07-03 12:03
This is already a bug report containing a reproducible sample. We're going to open a new issue via the paid support channel later today.

**Comment by timunie** [comment] 2023-07-03 12:20
Okay, if it's the exact same issue to reproduce, let me open it again.

**Comment by TomEdwardsEnscape** [comment] 2023-08-15 07:21
The test case above is working again in 11.0.3. 

This one is still broken:

```xml
<Animation Delay="0:0:0.3" Duration="0:0:0.2">
    <KeyFrame Cue="0%">
        <Setter Property="Opacity" Value="0.0"/>
    </KeyFrame>
    <KeyFrame Cue="100%">
        <Setter Property="Opacity" Value="1.0"/>
    </KeyFrame>
</Animation>
```

But the bug can be worked around by adding `FillMode="Both"` to the animation.

**Comment by TomEdwardsEnscape** [comment] 2023-08-15 07:31
Perhaps that animation should produce a flicker though, given that it has a delay? It didn't in 0.10 but perhaps _that_ was a bug.

I've replaced the delay with a three-keyframe curve which keeps the opacity at 0 for 0.3 seconds, and that is working nicely.

**Comment by timunie** [comment] 2023-08-15 07:40
@TomEdwardsEnscape do you think this issue should be kept open or can be closed? from your messages I'm unsure rn.

**Comment by TomEdwardsEnscape** [comment] 2023-08-15 08:04
Since my product is no longer affected by this problem, as far as I'm concerned the bug can be closed. But you may want to keep it open (or file a new one) depending on what the intended behaviour of the second test case is.

The fact that setting `FillMode` changes behaviour is also a bit surprising, but maybe I just don't understand what that property is doing.

**Comment by jmacato** [comment] 2023-08-15 08:31
@TomEdwardsEnscape I think i need to make a proper docs with FillModes haha :) Some other folks have been confused by it too

**Comment by timunie** [comment] 2023-08-15 08:51
@jmacato in that case, should we move this issue into docs instead?

**Comment by jmacato** [comment] 2023-08-15 08:52
@timunie i think we can close this and open a new on on docs (i think we already have it iirc)

**Comment by timunie** [comment] 2023-08-15 08:59
Closing this in favor of https://github.com/AvaloniaUI/avalonia-docs/issues/134

**Closed by timunie** 2023-08-15 08:59 UTC
Labels: bug
