### ISSUE TITLE
CalendarDatePicker All months disappear after select

### ISSUE THREAD

**Issue by yukina3230** [AvaloniaUI/Avalonia#10163] opened 2023-02-02 06:48 UTC
**Describe the bug**
When I select a month in the calendar, after that all the months text disappear

**To Reproduce**

1. Go to CalendarDatePicker
2. Click on calendar button
3. Select month and day

**Screenshots**
Select March and choose a day
![image](https://user-images.githubusercontent.com/75545944/216248616-4a5159e1-a193-4edd-a5b2-62987a57d303.png)

Open the calendar again
![image](https://user-images.githubusercontent.com/75545944/216249805-b8a4dfdd-5613-4599-bc32-c589eb8e5e73.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 11.0.0-preview4

**Comment by rabbitism** [comment] 2023-02-02 15:09
I think this is fixed in #9580

**Comment by timunie** [comment] 2023-02-02 15:29
@rabbitism you may be right. In that case you can use nightly builds for now, until preview 5 arrives.

**Comment by maxkatz6** [comment] 2023-02-02 15:44
Yes, closing this as a duplicate of #8864

**Closed by maxkatz6** 2023-02-02 15:44 UTC
Labels: bug
