### ISSUE TITLE
Pop ups broken

### ISSUE THREAD

**Issue by josephnarai** [AvaloniaUI/Avalonia#7399] opened 2022-01-20 04:04 UTC
Hi All,
    I've updated from 0.10.10 to 0.10.11 in my project and the pop up windows are now broken. They constantly flash between their location next to the mouse cursor where I pop them up and the top left corner of the screen. Their size seems to also change between normal scale and some kind of zoomed in scale. Please see videos showing the issue below.
    Note that IF the level meter is unchanging (so that there is no drawing to the windows under the pop up objects) then the pop up works as it should. The only difference between the two builds is changing the Avalonia version.
    Working version (0.10.10):

https://user-images.githubusercontent.com/14188194/150271060-7895053b-202f-4166-89ff-367e2e4f8a3e.mp4

    Broken version (0.10.11):

https://user-images.githubusercontent.com/14188194/150271125-48e78779-de23-4611-a360-664c1d40fbb0.mp4

    For the moment I've just reverted back to 0.10.10.
    Please let me know if you need me to do any other tests.
    I've not made a simple test project, but can try if that helps someone resolve the issue quickly.
    Thanks.
Joseph

**Comment by maxkatz6** [comment] 2022-01-20 05:26
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/7249

**Closed by maxkatz6** 2022-01-20 05:26 UTC

**Comment by josephnarai** [comment] 2022-01-20 05:29
Thanks Max.
