### ISSUE TITLE
DataContext inheritance issue

### ISSUE THREAD

**Issue by Seekeer** [AvaloniaUI/Avalonia#10242] opened 2023-02-06 16:59 UTC
I have following code:

```xaml
    <TabItem Header="Accounts"
				 d:DataContext="{Binding AccountsViewModelAccounts}"
				 >
			<StackPanel>
				<DataGrid AutoGenerateColumns="False" Name="accounts" Grid.Row="1"
						  Items="{Binding CollectionView}" >
					<DataGrid.Columns>
						<DataGridTextColumn Binding="{Binding Path=Name}" Header="Name" Width="150" IsReadOnly="True"/>
					</DataGrid.Columns>
				</DataGrid>
			</StackPanel>
		</TabItem>
```
And got error.
But when I move DataContext to grid I got items from **AccountsViewModelAccounts.CollectionView**
```xaml
		<TabItem Header="Accounts"
				 >
			<StackPanel>
				<DataGrid AutoGenerateColumns="False" Name="accounts" Grid.Row="1"
				 d:DataContext="{Binding AccountsViewModelAccounts}"
						  Items="{Binding CollectionView}" >
					<DataGrid.Columns>
						<DataGridTextColumn Binding="{Binding Path=Name}" Header="Name" Width="150" IsReadOnly="True"/>
					</DataGrid.Columns>
				</DataGrid>
			</StackPanel>
		</TabItem>
```
In WPF both piece of code will lead to the same results.

**Comment by maxkatz6** [comment] 2023-02-06 22:50
> And got error.

What error?

> In WPF both piece of code will lead to the same results.

Just to be clear, it's only a previewer related issue? As you are using design data context.
Or the same issue with normal data context usage? Like, settings "DataContext" instead of "d:DataContext".

**Comment by Seekeer** [comment] 2023-02-07 09:45
> What error?
DataGrid is trying to bind to TabControl's **DataContext.CollectionView** not **DataContext.AccountsViewModelAccounts.CollectionView**

> it's only a previewer related issue?
Nope. When I'm replacing it with plain DataContext issue remains the same.

**Comment by maxkatz6** [comment] 2023-02-07 10:41
@Seekeer if it's an error, please attach full message and stacktrace. If it's an error in the console log, please attach full error message. 
Ideally, minimal sample project would help. 

Because, normally, this kind of code works just fine.

**Comment by maxkatz6** [comment] 2023-04-09 01:28
Duplicate of #10958
(closing this one, as another has simpler repro)

**Closed by maxkatz6** 2023-04-09 01:28 UTC
Labels: needs-repro
