### ISSUE TITLE
Harmonise `AvaloniaObject` equality comparison

### ISSUE THREAD

**Issue by tomenscape** [AvaloniaUI/Avalonia#11602] opened 2023-06-01 08:31 UTC
[`AvaloniaObject.Equals` and `GetHashCode` are overridden](https://github.com/AvaloniaUI/Avalonia/blob/f52fa669f3ef1e7e21478444b2a991bbe23dc02a/src/Avalonia.Base/AvaloniaObject.cs#L171-L200), but only to seal the methods and prevent derived types from overriding them. This is fine at runtime, but causes static code analysis tools to think that the type has special equality logic. In my project this leads to annoying compile warnings every time we use `==` to compare two controls. Our CI rejects any commit containing these warnings.

**To Reproduce**

1. Compare two `AvaloniaObject` variables with `==`
2. Run Resharper on your solution with `PossibleUnintendedReferenceComparison` enabled
3. Resharper will warn about the comparison

**Expected behavior**
There are two options:

1. `AvaloniaObject` should stop overriding `Equals` and `GetHashCode`. An analyzer diagnostic can be emitted to warn anyone who tries to override those methods in a derived type.
2. `AvaloniaObject` should also provide `operator ==` and `operator !=`, so that code analysis tools think that everything is customised and stops warning about it.

I think option 1 is preferable, because sealing the methods does not stop users from defining their own static equality operators.

**Desktop**

- OS: N/A
- Version 11 RC 1.1

**Comment by kekekeks** [comment] 2023-06-01 08:47
Since ReSharper doesn't complain about System.Windows.DependencyObject, I believe that the issue is on the Resharper side, so we should open an issue at youtrack.jetbrains.com

**Comment by MrJul** [comment] 2023-06-01 11:29
Indeed, ReSharper added an hardcoded exception for `DependencyObject`. The warning was present for many years before. See https://youtrack.jetbrains.com/issue/RSRP-301767/Possible-unintended-reference-comparison-for-DependencyObject (I can't believe I reported that 11 years ago, time flies!). An external annotation would have been better...

**Comment by kekekeks** [comment] 2023-06-01 15:49
https://youtrack.jetbrains.com/issue/RSRP-492562/Possible-unintended-reference-comparison-for-AvaloniaObject

**Comment by maxkatz6** [comment] 2023-06-01 18:58
> Note that WPF's DependencyObject doesn't override == operator. I suppose there is a perf penalty for doing so.

Is it really a problem with modern runtime? I am pretty sure if will be inlined to the same code nowadays.

**Comment by Mikolaytis** [comment] 2023-06-02 20:17
I've recently measured method call vs operator call = 0 difference in benchmark. You can check this also.

**Comment by kekekeks** [comment] 2023-07-03 09:56
Fixed in rider

**Closed by kekekeks** 2023-07-03 09:56 UTC
Labels: bug
