### ISSUE TITLE
Animating `Opacity` causes incorrect z-ordering while animation plays

### ISSUE THREAD

**Issue by Splitwirez** [AvaloniaUI/Avalonia#3445] opened 2020-01-17 15:34 UTC
Sorry I'm so late submitting this. While working on my Aero theme for Avalonia ( https://github.com/Splitwirez/avalonia-aero-theme ), I found that animating a Border's opacity seems to cause incorrect z-ordering while the animation is playing. In this case, I have (among other things) several `Border`s and a `ContentPresenter` in my `Button` ControlTemplate. I used separate `Border`s for each state (idle, hover, pressed, etc) and tried to animate their opacity to fade between states. This method works flawlessly in WPF (which is where I first used it), but in Avalonia, whichever `Border` is currently having its opacity animated seems to appear overtop of everything else, including the `ContentPresenter`. The end result is that the `Button`'s content appears to fade out and then snap back to 100% opacity when the `Button` is hovered over, clicked, etc. This affects all of the controls I've restyled so far, not just `Button`s. It's actually even worse for `TabItem`s - when hovering over the selected `TabItem`, the hover `Border` appears over not only the content, but also the the Selected-state `Border`, which should obstruct it so the animation isn't visible at all. (I could just specialize that one animation to not play for the selected `TabItem`, but that doesn't apply to all the other manifestations of this problem).

I've attached a simpler repro app containing a subset of the affected Aero styles and further explanation. IIUC it requires .NET Core 3.

**Comment by Splitwirez** [comment] 2020-01-17 15:38
...having trouble attaching files at the moment, so here's the repro I tried to attach before, now via Google Drive: https://drive.google.com/uc?export=download&id=1Gu6lfjkJ1nijCWY59jie2oCcJGbbARAZ

**Comment by grokys** [comment] 2020-01-17 15:44
Yeah I took a look at this a while ago and our renderer layering is basically broken by design :(

I think the only short-term solution is to disable render layers in the renderer until we get chance to rewrite it.

**Comment by Splitwirez** [comment] 2020-01-17 15:50
Right, that was sort of the sense I'd gotten from prior talk with @jmacato ...

Thankfully, I'm not urgently in need of a "short-term solution" - I can't speak for others, but my affected case isn't a part of some commercial app or anything with a deadline, it's just a theme I've been working on in the hopes that upon its (eventual) completion, I may be able to offer it to Avalonia application developers seeking a flashier (and possibly more nostalgia-inducing?) look for their apps. 

That said, for the moment, it would be nice to be able to preview (and potentially show off) my theme as it is intended to appear, so to that end...is disabling layers something a given Avalonia application would do, or is that to be done within Avalonia itself? And if the former, how would one go about doing so?

In any case, best wishes with that eventual rewrite, to you and/or whoever eventually takes up the challenge.

Also, I guess I should mention that the animations work just fine in the Avalonia previewer within Visual Studio...for some reason...

**Comment by kekekeks** [comment] 2020-01-17 17:07
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2244

**Closed by kekekeks** 2020-01-17 17:07 UTC
