### ISSUE TITLE
Can i set two fonts in a textbox?

### ISSUE THREAD

**Issue by RunMonkey** [AvaloniaUI/Avalonia#7283] opened 2021-12-30 09:24 UTC
I have an application scenario where I can input some special characters. I must load the special character font (there are only special characters here). These characters are not in normal fonts,

I set FontFamily = "Arial, specialfont" to display normal characters but not special characters;

Set FontFamily = "specialfont, Arial" to display special characters, but normal characters cannot be displayed.

In WPF, setting FontFamily = "Arial, specialfont" can all display normally. Can it be supported in Avalonia? Is there any way to achieve it?
![twofonts](https://user-images.githubusercontent.com/15755247/147738740-4bfa89fe-219a-41ce-9cf2-8c7f1ccd3dbe.png)

**Comment by Gillibald** [comment] 2021-12-30 10:45
The TextBox currently doesn't support font fallback this feature will be added in january
Duplicate of: #4708

**Closed by Gillibald** 2021-12-30 10:45 UTC
Labels: enhancement
