### ISSUE TITLE
XAMLIL Support For Nested Classes with x:DataType

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#9673] opened 2022-12-11 21:28 UTC
**Is your feature request related to a problem? Please describe.**

WinUI supports nested classes in x:DataType using a syntax similar to `x:DataType="local:X+Y"` (where `+` is used instead of `.`). Avalonia should support nested classes with x:DataType with a similar syntax. This enables a few edge cases with compiled bindins that don't currently work.

**Describe the solution you'd like**

I found somewhat of a discussion about this for UWP/WinUI here (see the end of the thread):

https://social.msdn.microsoft.com/Forums/SECURITY/en-US/f709a02e-06c1-4b5d-b6c7-948f1dc80927/how-do-i-use-nested-models-inside-xdatatype-in-a-uwp-app?forum=wpdevelop

**Describe alternatives you've considered**

 * Move the nested class out to the same level as the parent
 * Don't use compiled bindings, reflection bindings will work at runtime

**Additional context**

Interestingly, Rider already supports this syntax for Avalonia. `x:DataType="local:X+Y"` will not show any errors. However, it will fail to compile saying the class can't be found.

**Comment by grokys** [comment] 2022-12-15 11:01
I think this is a duplicate of #2725.

I think we just need to get https://github.com/AvaloniaUI/Avalonia/pull/7354 reviewed and merged to fix it.

**Closed by grokys** 2022-12-15 11:01 UTC
Labels: enhancement

**Comment by robloo** [comment] 2022-12-15 12:45
Yea, this is a duplicate of #2725. Should have found it.
