### ISSUE TITLE
ComboBox XAML initial selected item not shown

### ISSUE THREAD

**Issue by arklumpus** [AvaloniaUI/Avalonia#4610] opened 2020-09-03 14:24 UTC
Might be related to #4606

In 0.10.0-preview4 and preview5, the initial selected item of a ComboBox is not shown, if it was set in the XAML through SelectedIndex. It is shown as expected if it was instead set in the code-behind or through SelectedItem.

That is, the following doesn't work (this used to work fine up to 0.10.0-preview3):

```XAML
  <ComboBox Name="ComboBox" SelectedIndex="0">
    <ComboBox.Items>
      <ComboBoxItem Name="ComboBoxItem">Selected item should be shown</ComboBoxItem>
    </ComboBox.Items>
  </ComboBox>
```

While the following works:

```XAML
  <ComboBox Name="ComboBox" SelectedItem="{ResolveByName ComboBoxItem}">
    <ComboBox.Items>
      <ComboBoxItem Name="ComboBoxItem">Selected item should be shown</ComboBoxItem>
    </ComboBox.Items>
  </ComboBox>
```

Adding the ComboBox without the selected item in the XAML and setting it in the constructor also works:

```XAML
  <ComboBox Name="ComboBox">
    <ComboBox.Items>
      <ComboBoxItem Name="ComboBoxItem">Selected item should be shown</ComboBoxItem>
    </ComboBox.Items>
  </ComboBox>
```

```CSharp
this.FindControl<ComboBox>("ComboBox").SelectedIndex = 0;

// OR

this.FindControl<ComboBox>("ComboBox").SelectedItem = this.FindControl<ComboBoxItem>("ComboBoxItem");
```

**Comment by Maximkaaa** [comment] 2023-08-18 04:36
Still an issue 3 years later.

**Comment by timunie** [comment] 2023-08-18 10:20
@Maximkaaa you are welcome to file a PR fixing the issue.

**Comment by timunie** [comment] 2023-08-18 11:32
Update: looks like this issue is solved in Avalonia 11.0 release, see picture below: 
![image](https://github.com/AvaloniaUI/Avalonia/assets/47110241/f274323a-56c0-456b-a185-0e2e46b172e3)

No code behind needed for me. Please double-check using 11.0. If it's still an issue, please provide a minimal sample. 

For now, I'm closing this, but will re-open if it's still reproduceable for anyone using 11.0. Plesae share some not working sample code in that case. Thx 🙏

**Closed by timunie** 2023-08-18 11:32 UTC

**Comment by Maximkaaa** [comment] 2023-08-22 09:51
Hey, @timunie . I've updated nugets to the current patch 11.0.4, but am still seeing this issue in my project. Since it's not reproduced by a simple example I would guess that it might be affected by the layout UI (for example, my control is inside a Flyout) or by a binding (but this seems unlikely). Unfortunately, this issue has quite low priority for my at the moment, so I cannot spent much time investigating it. If I come around with a simple way to reproduce the issue, I'll add more info here or create a new issue.

**Comment by timunie** [comment] 2023-08-22 10:27
Could also be the order of property in xaml.

However please open a Q&A if you have a way to reproduce. If we find it's a bug, we can still create an issue
