### ISSUE TITLE
Child window supported?

### ISSUE THREAD

**Issue by joaompneves** [AvaloniaUI/Avalonia#3281] opened 2019-11-22 15:58 UTC
### Version
- Avalonia 0.8.1
- Windows 10

### Behavior
- I'm trying to embed CEF browser into an Avalonia window without using OSR (CEF off-screen rendering) but the browser surface flickers and disappears
- I'm setting the browser window as a child window of my Avalonia main window and positioning the browser window on the pretended coordinates

Are child windows supported in Avalonia? Is there anything I can do to fix this behavior?
Using the same technique on WPF works ok.

![](https://i.imgur.com/EsMHTDk.gif)

**Comment by kekekeks** [comment] 2019-11-22 17:12
Might be caused by the lack of `WS_CLIPCHILDREN` on Avalonia window. Try turning it on via `SetWindowLong`

**Comment by joaompneves** [comment] 2019-11-22 17:27
Thanks. It fixes the problem. Do you foresee any problems with that?

**Comment by danwalmsley** [comment] 2019-11-24 17:08
@joaompneves have you seen ... https://github.com/VitalElement/CefGlue.Core?

**Comment by joaompneves** [comment] 2019-11-24 17:19
@danwalmsley I did a while ago, but unfortunately that fork lacks lots of functionality so I ended-up creating a fork from the original.
Check it out: https://gitlab.com/xiliumhq/chromiumembedded/cefglue/merge_requests/2

Btw this problem appeared in an attempt to have an Avalonia version without OSR, because CEF is currently facing major OSR stack rewrite and is very unstable.

**Comment by danwalmsley** [comment] 2019-11-24 17:39
nice,if it gets merged let me know and ill put a link to it from the cef.core repo, as thats not really maintained anymore. Are you expecting they will accept the Avalonia specific parts into the main repo?

**Comment by joaompneves** [comment] 2019-11-24 17:42
Yes, I have already talked with the main maintainer and he was open to accepting my contribution. Expecting more developments in the next days.

**Comment by danwalmsley** [comment] 2019-11-24 17:48
nice, I look forward to seeing how this develops, quite a lot of people are asking for a solution in this area :)

**Comment by joaompneves** [comment] 2019-11-24 17:55
It would be nice to have more people contributing to this. i faced some problems with the port to Avalonia (due to some Avalonia bugs, already reported) and here are still some gaps that need to be filled, ex: the browser popups implementation.

**Comment by joaompneves** [comment] 2019-11-26 17:45
Trying to get the main window handle in OSX but I'm getting a zero handle. Works fine in Windows.
```
((Window) control.GetVisualRoot()).PlatformImpl.Handle.Handle
```

Whats the appropriate way?

**Comment by kekekeks** [comment] 2019-11-26 18:42
What exactly do you expect to get as a window handle?

**Comment by joaompneves** [comment] 2019-11-26 18:54
I don't know how the OSX windowing system works, but was expecting something similiar with Windows. The thing is I'm trying to embed cefglue the same way I did on windows, and the cef api needs the handle of the parent window.

**Comment by danwalmsley** [comment] 2019-11-26 20:05
@joaompneves CefGlue.Core works on OSX have a look what we did there!

**Comment by kekekeks** [comment] 2019-11-26 21:30
Cocoa doesn't have a concept of "window handles". There are `NSView` and `NSWindow` *objects* and that's it.

**Comment by joaompneves** [comment] 2019-11-26 22:20
@danwalmsley just to be clear, I already have an Avalonia CefGlue version working on mac wusing OSR. Now I'mt trying to have a variant without OSR, using child windowns. On Windows works like a charm.

 @kekekeks Is it possible to achieve a similar effect on Cocoa? I mean, have a Window that is a child of another?

**Comment by joaompneves** [comment] 2019-11-26 23:14
Seems that I need the underlying NSView

https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=12727

**Comment by kekekeks** [comment] 2019-11-27 05:55
I don't think that we can fit `NSView*` into simple `IPlatformHandle` because of reference counting semantics and the fact that one can need either NSView or NSWindow. We can do something like
```cs
interface IMacOSTopLevelPlatformHandle
{
      IntPtr NSView {get;}
      IntPtr GetNSViewRetained();
      IntPtr NSWindow {get;}
      IntPtr GetNSWindowRetained();
}
```

**Comment by joaompneves** [comment] 2019-11-27 10:04
Hum ok. Any way I can get those pointers (even with reflection) to test now?

**Closed** 2019-11-28 14:21 UTC
