### ISSUE TITLE
Adding a new Avalonia item automatically adds remove entries in the .csproj file for the .xaml file

### ISSUE THREAD

**Issue by Karl255** [AvaloniaUI/Avalonia#4144] opened 2020-06-19 07:15 UTC
Every time I add a new UserControl or Window to the project, these 2 entries get added to the .csproj file:
```cs
  <ItemGroup>
    <AvaloniaResource Remove="Views\Test.xaml" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Views\Test.xaml" />
  </ItemGroup>
```
I need to manually remove them each time.

Steps to reproduce this: same as in the tutorial in the Avalonia docs.

**Comment by Gillibald** [comment] 2020-06-19 07:42
Duplicate of AvaloniaVS#157

**Closed** 2020-06-19 07:43 UTC
