### ISSUE TITLE
Add DisplayMemberPath and SelectedValuePath properties

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia#4718] opened 2020-09-23 01:32 UTC
Avalonia seems to be missing the [DisplayMemberPath](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.itemscontrol.displaymemberpath?view=netcore-3.1) property for ItemsControl and the [SelectedValuePath](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.selector.selectedvaluepath?view=netcore-3.1#System_Windows_Controls_Primitives_Selector_SelectedValuePath) property for Selector. This would be useful for higher-level controls like ComboBox. Please add them.

**Comment by maxkatz6** [comment] 2020-09-23 02:04
Can't it be replaced with item template?

**Comment by derekantrican** [comment] 2020-09-30 00:24
I found the workaround for `DisplayMemberPath` using something like:

              <ComboBox.ItemTemplate>
                <DataTemplate>
                  <TextBlock Text="{Binding Name}"/>
                </DataTemplate>
              </ComboBox.ItemTemplate>

Is there a similar workaround for `SelectedValuePath`?

**Comment by maxkatz6** [comment] 2020-09-30 03:32
I don't think it is possible now.
As a workaround you can create additional property in your viewmodel.

**Comment by magom001** [comment] 2021-08-09 15:03
Seems to a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/1409

**Comment by magom001** [comment] 2021-08-09 15:05
@derekantrican have you found a simple workaround? It is a no-brainer in wpf.  Displaying a combox in a datagrid is a nightmare without these properties.

**Comment by derekantrican** [comment] 2021-08-09 16:41
I think I ended up doing what @maxkatz6 suggested and creating another property in the viewmodel

**Comment by WizMe-M** [comment] 2022-04-03 11:51
> I found the workaround for `DisplayMemberPath` using something like:
> 
> ```
>           <ComboBox.ItemTemplate>
>             <DataTemplate>
>               <TextBlock Text="{Binding Name}"/>
>             </DataTemplate>
>           </ComboBox.ItemTemplate>
> ```

This isn't working with MultiBinding and StringFormat. Next template

                <ComboBox.ItemTemplate>
                    <DataTemplate>
                        <TextBlock>
                            <TextBlock.Text>
                                <MultiBinding StringFormat="{}{1} {0}">
                                    <Binding Path="FirstName" />
                                    <Binding Path="SecondName" />
                                </MultiBinding>
                            </TextBlock.Text>
                        </TextBlock>
                    </DataTemplate>
                </ComboBox.ItemTemplate>

causes `(unset) (unset)` over placeholder when its null.
How could it be fixed?

**Comment by thomaslevesque** [comment] 2022-04-19 21:33
The lack of DisplayMemberPath is easy to work around with a data template (although excessively verbose). The lack of SelectedValuePath, on the other hand, is really annoying. It really makes the viewmodel much more complicated than it needs to be.

**Comment by CollinAlpert** [comment] 2022-04-20 21:18
I am also really struggling without SelectedValuePath. This would be really cool to have.

**Comment by ahmedmohammedfawzy** [comment] 2022-05-30 15:33
I hope this get implemented soon.

**Comment by maxkatz6** [comment] 2022-05-30 23:41
SelectedValuePath as it is in WPF won't be implemented. We need a reflection friendly solution.
Alternatively, it's possible to implement SelectedValuePath as it is in WPF, but with requiring x:DataType, so compiler will know exact type.

**Comment by thomaslevesque** [comment] 2022-05-31 07:59
> Alternatively, it's possible to implement SelectedValuePath as it is in WPF, but with requiring x:DataType, so compiler will know exact type.

I assume this would be specified on the DataTemplate?
Sounds good to me! I don't mind having to specify the type, as long as I can use the feature.

**Comment by timunie** [comment] 2022-09-08 06:35
I feel like `DisplayMemberPath` could be `DisplayMemberBinding (type: IBinding?)` instead. This would have the following benefits imo: 
- Internally it would be converted into a binding anyway
- You can use `CompiledBinding` or `ReflectionBinding` based on your needs
- You can pass StringFormat inside the Binding 
- You can also use `MultiBinding`

I have no idea if that would also work for `ValueMemberPath` in a similar way. 

What do you think? Would this be a good addition to Avalonia?

**Closed** 2023-02-08 23:40 UTC
Labels: enhancement, area-xaml

**Comment by langsisi** [comment] 2025-04-07 01:03
> SelectedValuePath as it is in WPF won't be implemented. We need a reflection friendly solution. Alternatively, it's possible to implement SelectedValuePath as it is in WPF, but with requiring x:DataType, so compiler will know exact type.

I don't understand how to implement SelectedValuePath

**Comment by timunie** [comment] 2025-04-07 08:49
@langsisi please see the PR for details: https://github.com/AvaloniaUI/Avalonia/pull/10180
