### ISSUE TITLE
Windows/Linux font size differences

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#286] opened 2015-10-24 11:31 UTC
Xaml based perspex app differ with font sizes on Windows and Linux.

Windows 10 x64:
![windows](https://cloud.githubusercontent.com/assets/2297442/10710288/111fb0ba-7a53-11e5-86ab-4a0a75bd1379.PNG)

XUbuntu 15.04 x64:
![linux](https://cloud.githubusercontent.com/assets/2297442/10710289/153ce316-7a53-11e5-91c9-30e7629f2b37.PNG)

The system configuration is default, no DPI setting have been changed.

**Comment by grokys** [comment] 2015-11-29 10:52
Duplicate of #219. Closing other issue as this one has a better description.

**Comment by danwalmsley** [comment] 2017-02-04 17:08
It may help if we add an api to distribute fonts via embedded resource, so we can ensure the same font is used also.

**Comment by kekekeks** [comment] 2017-02-14 09:24
Our default font is Segoe UI which is *not* included in Linux and OS X installations.
See compatibility table: http://www.apaddedcell.com/sites/www.apaddedcell.com/files/fonts-article/final/index.html

**Comment by kekekeks** [comment] 2017-10-12 23:59
![default](https://user-images.githubusercontent.com/1067584/31524453-76c64568-afc2-11e7-8d14-d4265a190d7e.png)
Font sizes in ControlCatalog look mostly same now (size differences are there because of different typefaces), so I'm closing this.

**Closed by kekekeks** 2017-10-12 23:59 UTC
Labels: duplicate, gtk2

**Comment by kekekeks** [comment] 2017-10-13 00:00
![default](https://user-images.githubusercontent.com/1067584/31524497-b5100534-afc2-11e7-8120-fef4230fb08a.png)
