### ISSUE TITLE
Template programs cannot run in Ubuntu

### ISSUE THREAD

**Issue by qfmee** [AvaloniaUI/Avalonia#11269] opened 2023-05-07 10:14 UTC
Template programs can run in Windows, but cannot run in Ubuntu。

Ubuntu 22.04
Avalonia 11.0.0-preview7

error message：

Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl) in /_/src/Avalonia.Base/Media/FontManager.cs:line 37
   at Avalonia.Media.FontManager.get_Current() in /_/src/Avalonia.Base/Media/FontManager.cs:line 59
   at Avalonia.Media.Typeface.get_GlyphTypeface() in /_/src/Avalonia.Base/Media/Typeface.cs:line 87
   at Avalonia.Rendering.Composition.Compositor.get_DiagnosticTextRenderer() in /_/src/Avalonia.Base/Rendering/Composition/Compositor.cs:line 43
   at Avalonia.Rendering.Composition.Compositor.CreateCompositionTarget(Func`1 surfaces) in /_/src/Avalonia.Base/Rendering/Composition/Compositor.Factories.cs:line 17
   at Avalonia.Rendering.Composition.CompositingRenderer..ctor(IRenderRoot root, Compositor compositor, Func`1 surfaces) in /_/src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs:line 59
   at Avalonia.X11.X11Window.CreateRenderer(IRenderRoot root) in /_/src/Avalonia.X11/X11Window.cs:line 386
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver) in /_/src/Avalonia.Controls/TopLevel.cs:line 185
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver) in /_/src/Avalonia.Controls/WindowBase.cs:line 55
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl) in /_/src/Avalonia.Controls/WindowBase.cs:line 51
   at Avalonia.Controls.Window..ctor(IWindowImpl impl) in /_/src/Avalonia.Controls/Window.cs:line 223
   at Avalonia.Controls.Window..ctor() in /_/src/Avalonia.Controls/Window.cs:line 214
   at AvaloniaApplication10.MainWindow..ctor()
   at AvaloniaApplication10.App.OnFrameworkInitializationCompleted()
   at Avalonia.AppBuilder.Setup() in /_/src/Avalonia.Controls/AppBuilder.cs:line 302
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilder.cs:line 199
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214
   at AvaloniaApplication10.Program.Main(String[] args)

**Comment by timunie** [comment] 2023-05-07 10:38
Which Avalonia version? 

Also plese fill out issue template next time. If you have a general question, join our telegram chat or use discussion. Thx.

**Comment by qfmee** [comment] 2023-05-07 14:13
Ubuntu 22.04
Avalonia 11.0.0-preview7

**Comment by maxkatz6** [comment] 2023-05-07 16:43
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/4427

**Closed by maxkatz6** 2023-05-07 16:43 UTC
Labels: bug

**Comment by qfmee** [comment] 2023-05-08 09:21
I found that the ubuntu system is set to English without any problem, but it cannot run when set to Chinese language! hope future versions can solve this problem.
