### ISSUE TITLE
Passing Binding to `ConverterParameter` casts to a `Binding` object instead of actual type

### ISSUE THREAD

**Issue by duck-dev** [AvaloniaUI/Avalonia#6865] opened 2021-11-04 16:21 UTC
**Describe the bug**
I am trying to pass the `Design.DataContext` itself (= ViewModel instance) as a `ConverterParameter` to the converter linked to the property. However, I receive the parameter as a `Binding` object, while I expect and require an object of the view model's type. I understand this is natural behaviour, because there is probably nothing between the `ConverterParameter` and the `Binding` itself that interprets it as the view model, as I suppose, but I'm wondering what the workaround for that would be. 

**To Reproduce**
XAML (entire file as used in my project https://github.com/duck-dev/Grade-Management/blob/f7822e4c4361d679b9fd880ca2193476f7d49086/src/Views/AddPages/AddGradeWindow.axaml#L56):
```xaml
<Design.DataContext>
        <namespace:XViewModel/>
</Design.DataContext>

<TextBox Text="{Binding SomeProperty, Converter={StaticResource SomeConverter},
                ConverterParameter={Binding}}"/>
```

Converter (entire class as used in my project https://github.com/duck-dev/Grade-Management/blob/f7822e4c4361d679b9fd880ca2193476f7d49086/src/Converters/MonthConverter.cs#L19):
```cs
public class SomeConverter : IValueConverter
{
     public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
     {
          // parameter's type is Binding, while XViewModel is expected
     }
}
```
**Expected behavior**
I expect the parameter of the converter (`ConvertBack` function) to be a `XViewModel` object instead of a `Binding` object.

**Desktop (please complete the following information):**

- OS: Linux (Pop! OS 21.04)
- Avalonia Version: 0.10.3

**Comment by maxkatz6** [comment] 2021-11-04 18:07
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/6840

**Comment by maxkatz6** [comment] 2021-11-04 18:08
@duck-dev instead of Binding+ConverterParameter you should use MultiBinding with IMultiValueConverter

**Closed by maxkatz6** 2021-11-04 18:07 UTC
Labels: bug

**Comment by duck-dev** [comment] 2021-11-04 22:19
@maxkatz6 I saw #6840 , but I figured out that it wasn't exactly comparable. As far as I've understood, I couldn't use the conventional way with `Convert` and `ConvertBack` with a MultiBinding. That's why I asked nonetheless.

Is it really not possible to achieve this using a binding and the converter, without having to access the elements by their name for example in the code-behind.

**Comment by maxkatz6** [comment] 2021-11-04 22:40
Binding to ConvertParameter is not supported. ConvertBack is unrelated at this point.

**Comment by duck-dev** [comment] 2021-11-04 22:41
> ConvertBack is unrelated at this point.

What do you mean by that? What does that effectively mean?
