### ISSUE TITLE
OpenGlControlBase calls OnOpenGlInit twice

### ISSUE THREAD

**Issue by wannkunstbeikor** [AvaloniaUI/Avalonia#12680] opened 2023-08-27 19:34 UTC
**Describe the bug**
The virtual method `OnOpenGlInit` is called twice in the initializing of the `OpenGlControlBase` class, I dont know if this is intended, it was not like this before, it got changed with [this](https://github.com/AvaloniaUI/Avalonia/commit/d714f37fce8b01b38f2ad61fc2bd2d7fb981b88a) commit. In the method [`InitializeAsync`](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.OpenGL/Controls/OpenGlControlBase.cs#L186) the method [`EnsureInitializedCore`](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.OpenGL/Controls/OpenGlControlBase.cs#L70) gets called, this method calls [`OnOpenGlInit`](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.OpenGL/Controls/OpenGlControlBase.cs#L112), after that the `InitializeAsync` method calls it [aswell](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.OpenGL/Controls/OpenGlControlBase.cs#L217)

**To Reproduce**
1. Create a control that inherits from `OpenGlControlBase`
2. Use it in an Application
3. You will see that the method `OnOpenGlInit` is called twice

I also updated [OpenTkAvalonia](https://github.com/SamboyCoding/OpenTKAvalonia) to avalonia 11.0.4, so this already does everything and [logs to the console](https://github.com/wannkunstbeikor/OpenTKAvalonia/blob/master/OpenTKAvalonia/BaseTkOpenGlControl.cs#L86) if its called twice

**Expected behavior**
That `OnOpenGlInit` is only called once like before

**Desktop (please complete the following information):**

- OS: Linux Mint Cinnamon
- Version 21.1

**Comment by maxkatz6** [comment] 2023-08-29 07:53
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/10371

**Closed by maxkatz6** 2023-08-29 07:53 UTC
Labels: bug
