### ISSUE TITLE
IPlatformRenderInterface.LoadBitmap API doesn't work with async-only input streams

### ISSUE THREAD

**Issue by Red6789** [AvaloniaUI/Avalonia#12444] opened 2023-08-05 11:50 UTC
![image](https://github.com/AvaloniaUI/Avalonia/assets/131952234/1467300b-49ce-4b0e-b085-9b15246cab6d)
This code runs on the desktop, and the picture can be displayed normally, but it cannot be displayed normally when it is run in the browser.

**Comment by Red6789** [comment] 2023-08-05 11:52
![image](https://github.com/AvaloniaUI/Avalonia/assets/131952234/bbe12f1b-0930-49db-a21b-7c95f8d179b8)
![image](https://github.com/AvaloniaUI/Avalonia/assets/131952234/4c1800f2-fdb5-466c-88f3-b0e39448d650)
![image](https://github.com/AvaloniaUI/Avalonia/assets/131952234/07638328-a32c-4a5a-ab4e-032228bda385)
More photo

**Comment by Red6789** [comment] 2023-08-05 11:53
Avalonia version : 11.0.2

**Comment by maxkatz6** [comment] 2023-08-06 01:33
OpenReadAsync will work. But Path property won't return you anything but file name on browser. 

> but it cannot be displayed normally when it is run in the browser.

Can you define "cannot be displayed normally"? Is it an empty picture? Or an error? Or something else wrong? 

Can you create a minimal repro that can be downloaded?
Also, can you try to copy your stream to the MemoryStream using CopyToAsync, and then pass this memory stream to a bitmap.

**Comment by Red6789** [comment] 2023-08-07 06:50
Hi, I created a test code
https://github.com/Red6789/AboutAvalonia
I also found a new problem, that is, the filter conditions of the file selector also do not work in the browser

Windows 10 : 22H2 （19045.3208）
VS2022 : 17.6.5
Avalonia: 11.0.2
Chrome:  115.0.5790.170
Net Sdk: 7.0.306

**Comment by Red6789** [comment] 2023-08-07 06:51
The sample code is to select a jpg or png image and display it on the ui.

**Comment by Red6789** [comment] 2023-08-07 06:52
@maxkatz6

**Comment by maxkatz6** [comment] 2023-08-29 09:02
> I also found a new problem, that is, the filter conditions of the file selector also do not work in the browser

Because you have specified wrong filters. 
Check "Defining custom file types" on the https://docs.avaloniaui.net/docs/next/concepts/services/storage-provider/file-picker-options page

This issue is caused by skia reading the stream synchronously when browser file streams can only be read asynchronously.
I am going to close this issue and open another one more specific - https://github.com/AvaloniaUI/Avalonia/issues/12707

Current workaround is 
```diff
             await using var stream = await storageFile.OpenReadAsync();
+            var memoryStream = new MemoryStream();
+            await stream.CopyToAsync(memoryStream);
+            memoryStream.Seek(0, SeekOrigin.Begin);
-            Avatar = new Bitmap(stream);
+            Avatar = new Bitmap(memoryStream);
```

**Closed by maxkatz6** 2023-08-29 09:02 UTC
Labels: bug, help-wanted, breaking-change
