### ISSUE TITLE
XAML Previewer failure issue on version 11.0.0 rc1.1

### ISSUE THREAD

**Issue by pyking-wang** [AvaloniaUI/Avalonia#11766] opened 2023-06-13 13:22 UTC
**Describe the bug**
live previewer failed when I modified XAML.
This seems to only happen in the latest version.

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/76192669/ecd06069-914a-425a-be37-5508a05fc3b7)
![image](https://github.com/AvaloniaUI/Avalonia/assets/76192669/82deac51-883b-4e27-a5be-cddd334e7417)
The first image shows the expected results for the stable version and preview 7, which is correct. 
The second image shows the results of the test at 11.0.0 rc1.1
This problem is bothering me.

**Desktop:**
- OS: Windows
- Version 11.0.0 rc1.1
- IDE Visual Studio2022

**Comment by liugangnhm** [comment] 2023-06-13 13:42
same issue , see https://github.com/AvaloniaUI/AvaloniaVS/issues/334#issue-1748933035

**Comment by workgroupengineering** [comment] 2023-06-13 15:13
Have you tried with https://github.com/AvaloniaUI/Avalonia/pull/11755?

**Comment by jpgarza93** [comment] 2023-06-13 19:20
having same issue

**Comment by maxkatz6** [comment] 2023-06-13 21:36
Duplicate of https://github.com/AvaloniaUI/AvaloniaVS/issues/334#issue-1748933035

**Closed by maxkatz6** 2023-06-13 21:36 UTC
Labels: bug
