### ISSUE TITLE
Geometry.Transform animation bug + memory leak

### ISSUE THREAD

**Issue by mishun** [AvaloniaUI/Avalonia#3394] opened 2019-12-29 11:13 UTC
Hi!
Not completely sure that it's a bug, but it worked in WPF.

I'm trying to create moving pictures by updating Transform property like that:
```F#
// Program.fs
namespace Test

open System
open Avalonia
open Avalonia.Controls
open Avalonia.Controls.ApplicationLifetimes
open Avalonia.Controls.Shapes
open Avalonia.Layout
open Avalonia.Media
open Avalonia.Markup.Xaml
open Avalonia.Threading


type MainWindow () as this =
    inherit Window ()

    let mutable angle = 0.0
    let transform = MatrixTransform ()
    let canvas = Canvas (Background = SolidColorBrush (Colors.White))

    do
        for i in 0 .. 400 do
            let line = LineGeometry (Point (5.0 * float i, 0.0), Point (5.0 * float i, 100.0), Transform = transform)
            let path = Path (Stroke = SolidColorBrush (Colors.Black), StrokeThickness = 1.0, Data = line)
            canvas.Children.Add path

        let button = Button (Content = "Update")
        button.Click.Add (fun _ ->
            angle <- angle + 0.1
            transform.Matrix <- Matrix.CreateRotation angle
        )

        this.Title <- "Test"
        this.Content <-
            let sp = StackPanel (Orientation = Orientation.Vertical)
            sp.Children.Add button
            sp.Children.Add canvas
            sp


type App () =
    inherit Application()

    override this.Initialize () =
        AvaloniaXamlLoader.Load this

    override __.OnFrameworkInitializationCompleted () =
        base.OnFrameworkInitializationCompleted ()
        match base.ApplicationLifetime with
            | :? IClassicDesktopStyleApplicationLifetime as desktop ->
                desktop.MainWindow <- MainWindow ()
            | _ -> ()


module Test =
    let BuildAvaloniaApp() =
        AppBuilder.Configure<App>()
            .UsePlatformDetect()

    [<EntryPoint>]
    let main (args: string[]) =
        BuildAvaloniaApp().StartWithClassicDesktopLifetime(args)

```
I expect picture to rotate a bit each time I press the button, but nothing is actually happening until I try to resize the window. Adding
```F#
Dispatcher.UIThread.InvokeAsync ((fun _ -> this.InvalidateVisual ()), DispatcherPriority.Background) |> ignore
```
at the end of Button.Click handler changes nothing. If I regenerate the picture each time by changing handler to:
```F#
        button.Click.Add (fun _ ->
            angle <- angle + 0.1
            transform.Matrix <- Matrix.CreateRotation angle

            canvas.Children.Clear ()
            for i in 0 .. 400 do
                let line = LineGeometry (Point (5.0 * float i, 0.0), Point (5.0 * float i, 100.0), Transform = transform)
                let path = Path (Stroke = SolidColorBrush (Colors.Black), StrokeThickness = 1.0, Data = line)
                canvas.Children.Add path
        )
```
then it works as expected, but it seems that memory is leaking by a couple MB per button press. Tested under Win10

My .fsproj and .xaml files just in case:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="**\*.xaml.fs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="**\*.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.9.1" />
    <PackageReference Include="Avalonia.Desktop" Version="0.9.1" />
  </ItemGroup>
</Project>
```
```xml
<Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:ATG.BladeGeometry.UI"
             x:Class="Test.App">

  <Application.Styles>
    <StyleInclude Source="avares://Avalonia.Themes.Default/DefaultTheme.xaml" />
    <StyleInclude Source="avares://Avalonia.Themes.Default/Accents/BaseLight.xaml" />
  </Application.Styles>
</Application>
```

**Comment by kekekeks** [comment] 2019-12-29 11:33
Unfortunately you need to invalidate the visual the transform is applied to (`LineGeometry` in your case). 

We currently lack automatic visual invalidation for many things that could change their internal state including MatrixTransform. That could be fixed by making `MatrixTransform` to implement `IAffectsRender`, but it becames a bit wonky when it comes to transforms with nested transforms like `TransformGroup`. 

We really need a proper automatic invalidation mechanism, most likely on the renderer level, but I guess we should do it manually for now instead of not having it at all. Like we are going to do in [DrawingImage PR](https://github.com/AvaloniaUI/Avalonia/pull/3378)

@grokys

**Comment by mishun** [comment] 2019-12-29 16:24
Thank you for explanation!
From what I see, in principle I can declare a descendant of MatrixTransform implementing IAffectRender in application code and make it work that way.

I poked around a little bit more, and it seems that the reason for memory leak was that MatrixTransform was keeping references to all LineGeometry that ever used it: if I create separate MatrixTranform for every set of LineGeometry memory seems to be correctly reclaimed.

**Comment by maxkatz6** [comment] 2023-07-10 23:19
Duplicate of #4748

**Closed by maxkatz6** 2023-07-10 23:19 UTC
Labels: bug, area-composition, area-animations
