### ISSUE TITLE
StyleResource does not work for attached properties when defined in different xaml file

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#621] opened 2016-07-28 19:13 UTC
When style `Resource` is defined in different .xaml file (in this case `App.xaml`) than when evaluated in attached properties (Xaml Behaviors action) the value is null.

```XAML
<UserControl x:Class="BehaviorsTestApplication.Controls.ChangePropertyActionControl"
             xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:vm="clr-namespace:BehaviorsTestApplication.ViewModels;assembly=BehaviorsTestApplicationPcl"
             xmlns:i="clr-namespace:Avalonia.Xaml.Interactivity;assembly=Avalonia.Xaml.Interactivity"
             xmlns:ia="clr-namespace:Avalonia.Xaml.Interactions.Core;assembly=Avalonia.Xaml.Interactions"
             xmlns:behaviors="clr-namespace:BehaviorsTestApplication.Behaviors;assembly=BehaviorsTestApplicationPcl"
             xmlns:actions="clr-namespace:BehaviorsTestApplication.Actions;assembly=BehaviorsTestApplicationPcl">
    <Grid RowDefinitions="5*,*" ColumnDefinitions="50*,5,50*">
        <Rectangle Name="ChangePropertyRectangle" Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="3" Margin="5" Fill="{StyleResource PinkBrush}" Stroke="{StyleResource GrayBrush}" StrokeThickness="5"/>
        <Button Name="pinkButton" Content="Pink" Grid.Row="1" Grid.Column="0" Margin="5,0,0,5" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
            <i:Interaction.Behaviors>
                <ia:EventTriggerBehavior EventName="Click" SourceObject="{Binding #pinkButton}">
                    <ia:ChangePropertyAction TargetObject="{Binding #ChangePropertyRectangle}" PropertyName="Fill" Value="{StyleResource PinkBrush}"/>
                </ia:EventTriggerBehavior>
            </i:Interaction.Behaviors>
        </Button>
        <Button Name="yellowButton" Content="Yellow" Grid.Row="1" Grid.Column="2" Margin="0,0,5,5" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
            <i:Interaction.Behaviors>
                <ia:EventTriggerBehavior EventName="Click" SourceObject="{Binding #yellowButton}">
                    <ia:ChangePropertyAction TargetObject="{Binding #ChangePropertyRectangle}" PropertyName="Fill" Value="{StyleResource YellowBrush}"/>
                </ia:EventTriggerBehavior>
            </i:Interaction.Behaviors>
        </Button>
    </Grid>
</UserControl>
```

The ` Value="{StyleResource YellowBrush}"` does not work:
```XAML
<ia:ChangePropertyAction TargetObject="{Binding #ChangePropertyRectangle}" PropertyName="Fill" Value="{StyleResource YellowBrush}"/>
```

The App.xaml:
```XAML
<Application x:Class="BehaviorsTestApplicationPcl.BehaviorsTestApp"
             xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <Application.Styles>
        <StyleInclude Source="resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"/>
        <StyleInclude Source="resm:Avalonia.Themes.Default.Accents.BaseLight.xaml?assembly=Avalonia.Themes.Default"/>
        <Style Selector="TabStripItem">
            <Setter Property="Margin" Value="5"/>
            <Setter Property="FontSize" Value="16"/>
        </Style>
        <Style>
            <Style.Resources>
                <SolidColorBrush x:Key="BlackBrush">Black</SolidColorBrush>
                <SolidColorBrush x:Key="GrayBrush">Gray</SolidColorBrush>
                <SolidColorBrush x:Key="RedBrush">Red</SolidColorBrush>
                <SolidColorBrush x:Key="BlueBrush">Blue</SolidColorBrush>
                <SolidColorBrush x:Key="YellowBrush">Yellow</SolidColorBrush>
                <SolidColorBrush x:Key="PinkBrush">Pink</SolidColorBrush>
            </Style.Resources>
        </Style>
    </Application.Styles>
</Application>
```

Full reproduction: https://github.com/XamlBehaviors/XamlBehaviors/tree/Controls

1. Run https://github.com/XamlBehaviors/XamlBehaviors/tree/Controls/samples/BehaviorsTestApplication
2. Go to `ChangePropertyAction` tab
3. Click `Yellow` button
4. Background should be set to yellow color using `<SolidColorBrush x:Key="YellowBrush">Yellow</SolidColorBrush>`

If you move `Style.Resources` definitions to `UserControl` all works as expected.

**Comment by grokys** [comment] 2016-07-29 16:56
I think this is a duplicate of #492 - it happens with all properties, not just attached properties. Closing unless you say otherwise.

**Closed by grokys** 2016-07-29 16:56 UTC
