### ISSUE TITLE
AvaloniaXamlLoader.Load fails to load any resource if non-latin symbols exists in project path

### ISSUE THREAD

**Issue by dngulin** [AvaloniaUI/Avalonia#2760] opened 2019-07-21 21:22 UTC
Environment:
```
$ dotnet --version
2.2.108
```
```
$ uname -a
Linux t490 5.2.1-arch1-1-ARCH #1 SMP PREEMPT Sun Jul 14 14:52:52 UTC 2019 x86_64 GNU/Linux
```

Avalonia version: 0.8.1.

How to reproduce:
1. Create a direcitory `/tmp/test`
2. Create default project in this directory: `dotnet new avalonia.app -o App`
3. Build and run the project. Everything works!
4. Repeat previous steps for a directory `/tmp/тест` and obtain the error:
```
Unhandled Exception: System.IO.FileNotFoundException: Unable to find view for App.App
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Type type, Object rootInstance) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 90
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 45
   at App.App.Initialize() in /tmp/тест/App/App.xaml.cs:line 10
   at Avalonia.Controls.AppBuilderBase`1.Setup() in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 302
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args) in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 153
   at App.Program.Main(String[] args) in /tmp/тест/App/Program.cs:line 12
```

The error happens in the `AssetLoader.cs` (actual values in comments):
```
if (uri.Scheme == "avares")
{
    var (asm, path) = GetResAsmAndPath(uri);
    if (asm.AvaloniaResources == null)
        return null;
    asm.AvaloniaResources.TryGetValue(path, out var desc);
    return desc;
}
// uri: avares://App/file:///tmp/тест/App/App.xaml/tmp/тест/App/App.xaml
// path: /file:///tmp/%D1%82%D0%B5%D1%81%D1%82/App/App.xaml/tmp/%D1%82%D0%B5%D1%81%D1%82/App/App.xaml
// related key in AvaloniaResources: /file:///tmp/%D1%82%D0%B5%D1%81%D1%82/App/App.xaml/tmp/тест/App/App.xaml
```

**Comment by kekekeks** [comment] 2019-07-22 05:16
Non uri-safe (e. g. cyrilic) symbols in paths are currently broken for some reason, that's a known issue.

**Comment by rstm-sf** [comment] 2020-12-05 15:22
Duplicate of #2555

**Comment by maxkatz6** [comment] 2022-05-25 08:26
Duplicate

**Closed by maxkatz6** 2022-05-25 08:26 UTC
Labels: bug
