### ISSUE TITLE
Avalonia Moonlight/Silverligth.

### ISSUE THREAD

**Issue by CarlosEX** [AvaloniaUI/Avalonia#5314] opened 2021-01-16 16:49 UTC
**Is your feature request related to a problem? Please describe.**
It is not related to any fault.

**Describe the solution you'd like**
It would be something very powerful, to be able to host our WPF projects on WEB servers, and for them to work in the Browser.  An improved version of SilverLight but looking at the world of WebAssembly. In summary, create our applications normally, and via CLI, publish and host on a WEB server, however the end user, would not need to download or install anything on the machine. All employee in The Browser via WebAssembley.

**Describe alternatives you've considered**
I found that Moonlight (SilverLight/Mono branch) existed that is used to run WPF with Linux in the Browser, but it no longer has support and advises against its use.
[https://www.mono-project.com/docs/web/moonlight/](url)
![200px-MoonlightLogo](https://user-images.githubusercontent.com/33513870/104817698-93093d80-5801-11eb-8933-6fb0e24ac0ac.png)

**Additional context**
Maybe there may already be some solution that would provide that possibility, and if so, please pass it to me. 
Thank you very much.

**Comment by jp2masa** [comment] 2021-01-16 17:10
Duplicate of #1387.

**Comment by CarlosEX** [comment] 2021-01-16 17:32
Thanks, I'm closing so there's no redundancy. Thank you very much.

**Closed** 2021-01-16 17:33 UTC
