### ISSUE TITLE
Avalonia on Raspbian

### ISSUE THREAD

**Issue by TheColonel2688** [AvaloniaUI/Avalonia#1072] opened 2017-07-16 04:24 UTC
Is Avalonia compatible raspbian yet? I would assume it would be in theory has it would just need to bind to a gtk build that was built for the pi correct? Has this been tested? Or is there work going on in this area?

Sorry if this is the wrong place for this question. I did not know here else to ask.

**Comment by kekekeks** [comment] 2017-07-16 18:27
You need to either use Mono as your runtime and our old GTK# backend or somehow obtain an ARM build of libSkiaSharp.

**Comment by TheColonel2688** [comment] 2017-07-17 01:08
Is the GTK# back end you speak of no longer maintained?

**Comment by snikeguo** [comment] 2017-07-20 02:41
@kekekeks  I do not understand why you  use GTK? Why not use OPENGL？

**Comment by kekekeks** [comment] 2017-07-20 08:32
You need something to create windows to render on, you know

**Comment by MaitreDede** [comment] 2017-09-13 22:36
Hi,
I am also interested in using Avalonia on Raspbian. For rendering backend, OpenGLmay be the preferred rendering engine, since it can render directly to hardware, without X installed. There is also OpenVG that can be used. You can see the available low-level libraries available [here](https://github.com/raspberrypi/firmware/tree/master/hardfp/opt/vc/lib) and samples [here](https://github.com/raspberrypi/firmware/tree/master/hardfp/opt/vc/src/hello_pi).

There are other things to consider, like handling inputs, to have a fully working solution, but at least, displaying things can be a good start.

**Comment by kekekeks** [comment] 2017-09-14 16:59
There is no MIT (or compatible) licensed OpenVG library that meets our requirements. And the only reliable and feature-rich library that can render 2D graphics on top of OpenGL is Skia.

**Comment by MaitreDede** [comment] 2017-09-14 20:27
It is possible to call opengl functions directly, and it works nice. I have also used Qt directly on the raspberry pi without X installed. It uses direct opengl calls also.
I have not found usefull help on how to get Skia running on Raspbian.

**Comment by kekekeks** [comment] 2017-09-14 20:50
Ask @mterwoord, he had some success in compiling `libSkiaSharp.so` for ARM. If you manage to get `libSkiaSharp.so` binary, you could probably use our `/dev/fb0` backend for direct framebuffer access. It also some initial support for touchscreen/mouse input via `libevdev2`

**Comment by mterwoord** [comment] 2017-09-15 09:22
I had things working with .net core 2.0 and GTK (not sure 2 or 3) and a self-built libskia.

See https://github.com/terwoord/skiasharp-raspberry for a buildscript.

Improvements are welcome. :)

**Comment by nicolasr75** [comment] 2018-04-05 01:26
I used @mterwoord 's build script to build a libskia. My Avalonia app contains nothing more than a main window with a grid with two TextBlocks in it. When I try to run it on my Raspberry PI with Raspbian, the main window gets displayed but without any content. When I drag the window around it  looks like it crashed. The terminal output does not show any errors though:

Any idea what could be wrong or where I could look for more information to diagnose what went wrong?

**Comment by nicolasr75** [comment] 2018-04-05 23:25
After a few more tests with two different Raspberry PIs, I noticed a difference between Raspbian and Linux Mate:
- on Linux Mate my test app seems to work almost fine. The app does not correctly refresh when it was hidden by another window. As soon as my mouse moves over one of the buttons it refreshes though.
- on Linux Raspbian the app starts but no text is drawn at all! The labels are completely missing, the buttons don't show their text. Apart from that the buttons are clickable, so the app is not crashed (as I first had thought)

Any idea why text drawing could fail on Raspbian?

@kekekeks you mentioned /dev/fb0 with libSkiaSharp. Can you tell me what this is about and how I could use it?

(BTW, if anyone is willing to do tests on a Raspberry, I would enjoy to provide one. Remote access via SSH, Teamviewer, XRDP would be possible. I could install either Linux Mate or Raspbian)

**Comment by mterwoord** [comment] 2018-04-06 05:59
I'm using yocto to build my own linux distribution, and had issues with a different font to be used.
Maybe that's what's going wrong for you?

**Comment by nicolasr75** [comment] 2018-04-08 22:43
@mterwoord You are right. If I set the font of my window explicitly to Courier or the default font of Raspbian (Piboto light) all the text is displayed. I am not Linux expert enough to diagnose this any further so I will stick with this solution for now.

**Comment by daniel-lerch** [comment] 2018-05-15 20:25
The next problem on Raspbian is that image scaling does not work like mentioned in #1486 . By setting `Stretch="None"` I disabled scaling but Avalonia rendered the image correctly.

Maybe someone can investigate this problem. I'm not deep enough in this topic to test a later version of libSkiaSharp than 1.57.1 from May 2017 used in [mterwoord's build script](https://github.com/terwoord/skiasharp-raspberry).

**Comment by LordBenjamin** [comment] 2018-12-29 14:37
* Avalonia 0.7.0
* libSkiaSharp 1.68.0
* Raspian 9 (stretch)

I can reproduce the issue reported by @nicolasr75 where no text is displayed on Raspian.

I am also seeing incorrect colours - my test app is supposed to display rectangles with green, orange and red backgrounds. This works on Windows, however on Raspian the colours rendered are green, light blue and dark blue.

I use a converter to bind the `Border.Background` property to my viewmodel:

```c#
switch (status) {
    case Status.OK:
        return Brushes.Green;
    case Status.Warning:
        return Brushes.Orange;
    case Status.Failure:
        return Brushes.Red;
    default:
        throw new InvalidOperationException();
}
```

Github is not letting me upload a screenshot just now.

**Comment by kekekeks** [comment] 2018-12-29 18:11
Is there some reliable way to reproduce the issue in QEMU? We hack the hardware to repro, unfortunately.

**Comment by LordBenjamin** [comment] 2018-12-29 20:05
I would be happy to try and find the minimum C# / Avalonia repro for these two issues.

I'm not familiar with QEMU though, and from a quick search it seems like getting Raspian running under QEMU is a bit involved (custom kernels etc).

If anyone has a prebuilt environment or scripted setup, that would be much appreciated.

**Comment by LordBenjamin** [comment] 2018-12-29 22:54
I was able to resolve the missing text issue by... installing the fonts :)

```
sudo apt-get install ttf-mscorefonts-installer
```

Looks like the default font in Avalonia is one of the Microsoft ones?

**Comment by mattleibow** [comment] 2018-12-30 10:05
If you have a look at what I do with the swapping of the colors for GTK#, I check the platform color format first. You could write a utility function that swaps only on some platforms.

You don't need to che k the actual platform, just the platform color that skia reports.

**Comment by kekekeks** [comment] 2018-12-30 10:13
It seems that GTK selects different X11 visual depending on the platform. I think it should be fixed after we switch from GTK to X11 backend. For now we could add pixel format override option to GtkOptions.

**Comment by LordBenjamin** [comment] 2018-12-30 13:03
I forced my application to depend on the `SkiaSharp 1.68.0` package (overriding `Avalonia.Skia`'s dependency on `1.60.1`) and now the R/B channels are consistently wrong on both Windows and Linux using the default brushes.

Raspian:
![image](https://user-images.githubusercontent.com/13396705/50547526-d4d2e580-0c32-11e9-9b42-21b05e5fde7d.png)

Windows:
![image](https://user-images.githubusercontent.com/13396705/50547535-24b1ac80-0c33-11e9-8fbd-f8d18c8c7579.png)

**Comment by canton7** [comment] 2019-04-19 13:33
Quick summary for those coming in cold (Avalonia 0.8.0):

 - Reference the Avalonia.Skia.Linux.Natives NuGet package to get libSkiaSharp
   - You might need `Condition="'$(TargetFramework)' == 'netcoreapp2.1'"` to stop it being included on .net framework builds
 - Set the `FontFamily` of you window explicitly to Courier or the default font of Raspbian (Piboto light), *or* `sudo apt-get install ttf-mscorefonts-installer`

The above worked for me, although I haven't tested the image stretching issue.

**Closed** 2021-12-21 17:56 UTC
Labels: question, linux
