### ISSUE TITLE
Can avalonia be used within monogame.

### ISSUE THREAD

**Issue by willmotil** [AvaloniaUI/Avalonia#1969] opened 2018-10-15 11:45 UTC
If this is already possible is there a tutorial how to do it ?

**Comment by danwalmsley** [comment] 2018-10-15 11:54
I don't believe anyone has tried this before.

**Comment by amerkoleci** [comment] 2018-10-16 05:50
Avalonia support directx hosting and uses opengl when using skia sharp, dunno how opengl host would work

**Comment by jkoritzinsky** [comment] 2018-10-21 20:58
This is a duplicate of #216.

**Comment by kekekeks** [comment] 2018-10-24 06:57
One has to implement the windowing platform's set of interfaces to run Avalonia inside a game. There is nothing that prevents it, just some work that needs to be done. 

It would preferred to keep the UI in background thread, though, since it will drop your framerate considerably otherwise.

**Closed** 2021-08-22 02:03 UTC
Labels: duplicate, question

**Comment by damian-666** [comment] 2023-01-16 02:41
7 days ago :     https://github.com/AvaloniaInside/AvaloniaInside.MonoGame      works somewhat ok.     similar to the craftwork one a bit slower , uses writeable bitmap
