### ISSUE TITLE
Failed to launch debug adapter for Browser app

### ISSUE THREAD

**Issue by DVaughan** [AvaloniaUI/Avalonia#14614] opened 2024-02-14 16:09 UTC
## Overview
An unmodified new browser app fails to launch via Debug in Visual Studio in Chrome and Edge.
The browser window remains blank. 
**I can navigate to http://localhost:5001/index.html** But break points are not hit.

After a while a Visual Studio dialog appears with:
```
Failed to launch debug adapter.

Unable to launch browser: "Could not open wss://localhost:5001/debug?browser=wsAFF127/0/0/1A62911F devtoolsFbrowserF1f81c9ac...
```
Things I've tried:
* Same problem on a Windows 10 and a Windows 11 machine.
* Reordered the applicationUrl setting in launchSettings.json to open the 'http' URL.
* Updated all Nuget packages and extensions.
* Ensured that project references Avalonia.Browser
* Chose 'yes' to trust development certificate.
* Tried changing the working directory in project properties to `C:\DevTemp\AvaloniaApplication2\AvaloniaApplication2.Browser\bin\Debug\net7.0\browser-wasm`

## To Reproduce

1. Open Visual Studio 2022
2. Create new Avalonia Project selecting only 'Web' target
3. Build project
4. F5

## Expected behavior
Page loads in browser when launching a debug session. 

## Environment 

- OS: Windows 10 and Windows 11. Chrome and Edge
- Avalonia-Version:  11.0.9

**Comment by jp2masa** [comment] 2024-02-14 17:14
Duplicate of #14500/#14570? It appears to be a VS 17.8.6 bug: https://github.com/AvaloniaUI/Avalonia/discussions/14570#discussioncomment-8429361.

What VS version are you using? 17.9.0 was released yesterday, no idea if it's still broken.

**Comment by DVaughan** [comment] 2024-02-14 17:44
Thanks for your response.
I have 17.9.0
I was using an older version until today. The issue also occurred before I updated.
Do you know if there's a workaround?

**Comment by maxkatz6** [comment] 2024-02-15 05:10
Closing as a duplicate and unrelated.

**Closed by maxkatz6** 2024-02-15 05:10 UTC
Labels: bug
