### ISSUE TITLE
XAMLIL:  "Avalonia.Styling.Setter is only valid inside Avalonia.Styling.Style" 

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#8563] opened 2022-07-21 16:46 UTC
> Avalonia.Styling.Setter is only valid inside Avalonia.Styling.Style

I am trying to construct some complex animation from XAML. The Animation is not embedded in a `<Style>` and XAMIL apparently doesn't like that. Is there any reason for this restriction? Seems perfectly fine to construct `Animation` etc. outside of `<Style>` context.

**Comment by maxkatz6** [comment] 2022-07-21 17:56
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/6960

We need a type information.

**Closed by maxkatz6** 2022-07-21 17:56 UTC
Labels: bug

**Comment by pr8x** [comment] 2022-07-21 19:35
Ah, I see. It needs the type to resolve the property name. In theory I could bind `{x:Static Control.BackgroundProperty}` right? In that case it wouldn't need the type.
