### ISSUE TITLE
[Android] Sample project from this repo is very laggy

### ISSUE THREAD

**Issue by Alex-Dobrynin** [AvaloniaUI/Avalonia#7678] opened 2022-02-23 02:44 UTC
I downloaded this repo and built sample project for android and ran it. If say that it lags when scrolling or drawing is to say nothing. Every ui interaction is accompanied with big delay about few secs.

OnePlus 9 Pro Android 12

**Comment by maxkatz6** [comment] 2022-02-23 03:22
Did you build it in release mode with AOT enabled?
It isn't fast. But definitely way faster than "big delay about few secs" on my OnePlus 7T Pro Android 11.

**Comment by Alex-Dobrynin** [comment] 2022-02-28 14:50
I didnt change any settings of android demo project ControlCatalog.Android

**Comment by Alex-Dobrynin** [comment] 2022-03-01 11:23
Its not so easy to do, because when downloading project from github and truying to build it fails. tons of errors. I need to fix dependencies manually. and after last try, i deleted the project from pc

**Comment by maxkatz6** [comment] 2022-03-01 11:50
Well, sadly that's xamarin experience on .net.

**Comment by Gillibald** [comment] 2022-03-15 14:45
`<RunAOTCompilation>True</RunAOTCompilation>` is the SDKs default in release mode

**Comment by maxkatz6** [comment] 2022-03-15 15:39
> Firstly if you do recommend to use <RunAOTCompilation>True</RunAOTCompilation> it should be set by default in ControlCatalog.Android.csproj for Release build

Oh, you are right. It was enabled before, but was disabled with another PR. Good catch.

> PS it would be cool to publish ControlCatalog to Android/iOS markets :))))

Yeah, we want something like this. "Wordle-onia" will go first to the apple store.
ControlCatalog is definitely can't be in the public markets, because it's more suitable for developers to test many controls. Not really representable. Instead, some nice application with control samples should be. @danwalmsley and @jmacato were working on this.

> I'v tried to buid it from VS2022... and i do see some strange errors

Building in VS sometimes is pita. Majority of the dev team are using Rider and never saw most of VS-specific errors.
I saw this one what you mentioned before doing android/ios projects, but can't reproduce it anymore. 

> Let's go to command line and use dotnet build .\Avalonia.sln -c Release:

Yes, this one is definitely broken. After these two recent PRs:
https://github.com/AvaloniaUI/Avalonia/pull/7756
https://github.com/AvaloniaUI/Avalonia/pull/7781
ControlCatalog.Android was updated to work with new API, but that test project wasn't.
I will make a PR to fix it.

**Comment by ili** [comment] 2022-03-15 16:45
@maxkatz6 cool :-):-)
Will wait for fix & demo app (Wordle-onia is not looking to be representable from *my* side small controls number, and previosly i'v faced with perfomance problems on low-end device)

Anyway, please, make the solution buildable :-)

**Comment by hez2010** [comment] 2022-03-17 04:58
IIRC the GPU backend (OpenGL ES) of Avalonia for Android hasn't been enabled? Then I think it's expected to be laggy on Android.

**Comment by maxkatz6** [comment] 2022-03-17 21:05
@hez2010 It is enabled by default.

**Comment by geocine** [comment] 2022-07-22 17:32
> Note that NDK might fail if you SDK is installed in program files directory. It can't work if there are spaces in the path. So you would need to reinsall/move/symlink android SDK to another directory and change it in xamarin settings.
 
After moving to another directory how do I change xamarin settings? I am building the application using `dotnet build -c Release` and I am getting `No Android NDK found` issues on windows

**Comment by geocine** [comment] 2022-07-22 18:40
On release mode I have to set it to following. Else I only see a white screen
```xml
<PropertyGroup Condition="'$(Configuration)'=='Release' and '$(TF_BUILD)' == ''">
    <RunAOTCompilation>True</RunAOTCompilation>
    <EnableLLVM>False</EnableLLVM>
    <EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
</PropertyGroup>
```

**Closed** 2022-11-08 17:22 UTC
Labels: bug, os-android
