### ISSUE TITLE
Window cropped when moving between different monitor dpi

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#4107] opened 2020-06-11 22:48 UTC
Hey,

I'm having an issue that my window is not rendered properly when I move it between monitors with different dpi settings in Windows 10.
It happens only if I move the Window with SHIFT + WIN + Left/Right
Example (I'm moving the window between monitors with the keyboard)-
![Blast-DPI-Issue](https://user-images.githubusercontent.com/27368554/84446008-464afc00-ac4d-11ea-96b5-582654b2c390.gif)

Also it isn't related to Acylic/WindowTransparencyLevel, I checked it.
This is probably happening because the window is resized due to DPI changes and my window is cropped because it has static width/height for all the controls.
This is also happening with the Control Catalog but since the controls scale with window size it's not cropped, just shrinked.
Is this the expected behavior? it can be problematic for borderless windows.

Thanks

**Comment by kekekeks** [comment] 2020-06-12 08:15
So, to repro this one needs:
- Win 10 setup with 2 monitors with different DPI
- any Avalonia window, even empty one works
- move the window between monitors by pressing SHIFT + WIN + Left/Right

The issue is that window doesn't resize itself to reflect the logical size and retains its previous pixel size.


Did I understand the issue correctly?

**Comment by adirh3** [comment] 2020-06-12 12:53
> So, to repro this one needs:
> 
> * Win 10 setup with 2 monitors with different DPI
> * any Avalonia window, even empty one works
> * move the window between monitors by pressing SHIFT + WIN + Left/Right
> 
> The issue is that window doesn't resize itself to reflect the logical size and retains its previous pixel size.
> 
> Did I understand the issue correctly?

Yes at least for me. I checked it with 300% 4k monitor + 100% 1080p. Also there was a different in the refresh rates 60/144. I don't think any of the above matters though but I can't test with other setups at the moment.
Also, I can help with testing it, it might be a wndproc message that is not being handled(?).

**Comment by kekekeks** [comment] 2020-06-12 15:18
We are handling WM_DPICHANGED [here](https://github.com/AvaloniaUI/Avalonia/blob/4e0dabbd51d57b256f8addecd5e263b6eebdfceb/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs#L89). It looks like that our handler attempts to resize the window, but something might be failing here.

**Comment by MrJul** [comment] 2024-11-19 11:31
I couldn't reproduce the issue at all on Avalonia 11.2.1 and Windows 11 23H2.

Setup:
 - Monitor 1: 150% scaling, 75hz refresh rate
 - Monitor 2: 100% scaling, 144Hz refresh rate

I've tried to move various Avalonia windows from one monitor to another and back, several times, with Win+Shift+Left/Right.

As the issue is 4 years old, dating back to Avalonia 0.9, I'm going to close this. We've had so many changes regarding rendering and window size handling since that version that it has probably already been fixed.

Please ping me if you can still reproduce this on Avalonia 11.2.1.

**Closed by MrJul** 2024-11-19 11:31 UTC
Labels: bug, os-windows
