### ISSUE TITLE
XmlnsDefinition not working

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#7222] opened 2021-12-20 21:43 UTC
I'm having this issue in 2 different projects. It works when I set explicit declaration such as

    xmlns:md="clr-namespace:MvvmDialogs.Avalonia;assembly=MvvmDialogs.Avalonia"

If I want to set a custom namespace in AssemblyInfo

```c#
[assembly: XmlnsPrefix("https://github.com/fantasticfiasco/mvvm-dialogs", "md")]
[assembly: XmlnsDefinition("https://github.com/fantasticfiasco/mvvm-dialogs", "MvvmDialogs")]
[assembly: XmlnsDefinition("https://github.com/fantasticfiasco/mvvm-dialogs", "MvvmDialogs.Avalonia")]
```

and declare the custom namespace

    xmlns:md="https://github.com/fantasticfiasco/mvvm-dialogs"

It works at runtime, but the designer throws

> Unable to resolve type DialogServiceViews from namespace https://github.com/fantasticfiasco/mvvm-dialogs

How to make this work?

**Comment by kekekeks** [comment] 2021-12-21 09:09
There is currently an issue with previewer (#7200), the workaround is to force your assembly to be loaded by adding `GC.KeepAlive(typeof(TypeInRefencedAssembly))` to `App.OnFrameworkInitializationCompleted`.

**Comment by maxkatz6** [comment] 2022-06-23 21:23
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/7200

**Closed by maxkatz6** 2022-06-23 21:23 UTC
Labels: bug
