### ISSUE TITLE
DataContext not getting GC'd/Finalized

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Avalonia#12123] opened 2023-07-10 07:17 UTC
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/12109

<div type='discussions-op-text'>

<sup>Originally posted by **nic547** July  9, 2023</sup>
Using the Avalonia .NET Core template, updating to Avalonia11 and editing the mainWindow like following:
```
public partial class MainWindow : Window
{

    public MainWindow()
    {
        DataContext = new ViewModel();
        InitializeComponent();
    }

    private void Button_OnClick(object? sender, RoutedEventArgs e)
    {
        new MainWindow().Show();
    }

    private void Button_GC_Click(object? sender, RoutedEventArgs e)
    {
        GC.Collect();
    }
}

public class ViewModel
{
    ~ViewModel()
    {
        Debug.WriteLine("Finalized called");
    }

    private readonly byte[] someData = new byte[65536];

}
```

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1">
    <StackPanel>
	    <Button Click="Button_OnClick">Open New Window</Button>
        <Button Click="Button_GC_Click">GC</Button>
	</StackPanel>  
</Window>

```

After opening and closing new windows, I cannot observe the "ViewModel" getting finalized. Additionally a Memory Snapshot (VS) will reveal as many Instances of the ViewModel as Windows were opened, despite only one being open.

Is there something I need to do to properly "clean up" a closed window?

(Full code: https://github.com/nic547/AvaloniaRepro)

Edit: Does work as expected in 11 preview 8, but not in 11 rc1.1 and 11
</div>

**Comment by maxkatz6** [comment] 2023-08-02 23:54
Likely to be a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/8240, if automation was used in any way

**Comment by flexxxxer** [comment] 2023-08-03 01:22
Reproduced with any automation turned off (like ms windows screen reader). @maxkatz6 i am currently working on this

**Comment by timunie** [comment] 2023-08-03 07:55
@flexxxxer I assigned you. If you decide to stop working on it, ping me.

**Comment by flexxxxer** [comment] 2023-08-06 08:04
Fixed with #12430

**Comment by flexxxxer** [comment] 2023-08-07 13:42
@timunie i think you can close this issue

**Comment by timunie** [comment] 2023-08-07 13:44
@flexxxxer fyi in Fixed Issues, write Fixes #TheIssueNumber. "Fixes" and "Closes" are key words for Github.

**Closed** 2023-08-07 13:44 UTC
Labels: bug, regression
