### ISSUE TITLE
Drag and drop captures mouse but doesn't release it

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#2795] opened 2019-07-30 13:22 UTC
Go to the drag and drop page in ControlCatalog and drag the "Drag Me" control into the "Drop some text or files here" control. Now try and change pages in the left sidebar. You can't because the "Drag Me" control still has mouse capture.

**Comment by mat1jaczyyy** [comment] 2019-08-07 23:08
I'm hitting this as well.

**Comment by KvanTTT** [comment] 2019-08-08 13:10
Yes, it's annoying. Actually, it's not possible to do anything because of mouse capture.

**Comment by kekekeks** [comment] 2019-08-09 11:36
Drag&Drop code preprocess the raw mouse up event and prevent `MouseDevice` from handling it. That is caused by dnd support being a huge hack and basically being broken by design.

**Comment by kekekeks** [comment] 2019-08-09 11:41
To be clear, the bug was already there before pointer events refactoring, if pointer was captured before initiating a drag there was noone to actually release the pointer capture.

**Comment by mat1jaczyyy** [comment] 2019-08-09 13:47
Hoping this one is fixed soon, my entire app is unusable.

**Comment by wieslawsoltes** [comment] 2019-08-09 13:49
> Hoping this one is fixed soon, my entire app is unusable.

Have same issue with my Dock library.

**Comment by kekekeks** [comment] 2019-08-09 14:58
DnD emulation has to be rewritten to utilize pointer capture instead of previewing the raw pointer events since it's obviously isn't smart enough to understand those. We might need a better API for capturing the pointer by a non-control though.

**Comment by kekekeks** [comment] 2019-08-09 15:00
BTW, do we need keyboard-driven drag&drop?

**Comment by mat1jaczyyy** [comment] 2019-08-09 15:40
In my situation there is no need for keyboard-driven dnd. Might be nice for some other apps though.

**Comment by KvanTTT** [comment] 2019-08-09 15:58
@kekekeks I don't think so: it's a very unusual case.

**Comment by jmacato** [comment] 2019-08-11 01:42
#2827 has fixed this issue (I retested the repro described), please reconfirm on your side @mat1jaczyyy

**Comment by mat1jaczyyy** [comment] 2019-08-11 03:13
Yes, the issue seems to be fixed.

**Comment by jmacato** [comment] 2019-08-11 03:51
Awesome, closing this now :)

**Closed by jmacato** 2019-08-11 03:51 UTC
Labels: bug

**Comment by HendrikMennen** [comment] 2019-09-05 15:35
I have this issue again with the newest preview while using Window.BeginMoveDrag(). For some reason on Linux only, Windows still runs fine.
