### ISSUE TITLE
Unable to load Perspex (TargetInvocationException)

### ISSUE THREAD

**Issue by mafshin** [AvaloniaUI/Avalonia#406] opened 2016-02-06 06:05 UTC
I just got a `TargetInvocationException` in the designer (VS2015-Update1, Windows 10 x64).

The app is built and can be executed successfully, but the designer crashes with the following exception:

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Perspex.DesignerSupport.DesignerAssist.<>c.<Init>b__5_0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Perspex.DesignerSupport.DesignerAssist.Init(Dictionary`2 shared)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Perspex.Designer.AppHost.PerspexAppHost.DoInit(String targetExe, StringBuilder logger)
   at Perspex.Designer.AppHost.PerspexAppHost.Init(String targetExe)`

**Comment by grokys** [comment] 2016-02-07 15:55
Could you give some more information about what is in the XAML file that you're editing?

**Comment by mafshin** [comment] 2016-02-08 04:18
It is the default app created by Visual Studio extension. No changes made to the default template.

**Comment by kemmis** [comment] 2016-07-13 14:11
I get this same error. I'm able to reproduce it by just doing File > New > Project > Perspex Application Template. Then open either of the two paml files. I'm on Windows 10 with VS 2015 Update 3, PerspexVS 0.2.0.0.

![2016-07-13 10_09_33-perspexapplication2 - microsoft visual studio](https://cloud.githubusercontent.com/assets/647545/16806308/fdaad5a6-48e1-11e6-91d4-fca217264054.png)

**Comment by jkoritzinsky** [comment] 2018-05-19 02:52
Since we've changed our designer backend I'm going to close this. Please open a new issue if it's still a problem.

**Closed by jkoritzinsky** 2018-05-19 02:52 UTC
Labels: bug, designer
