### ISSUE TITLE
OpenglPage Memory Leak

### ISSUE THREAD

**Issue by Gilfoylex** [AvaloniaUI/Avalonia#11056] opened 2023-04-18 12:06 UTC
`https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/Pages/OpenGlPage.xaml` 

Memory usage increases wildly when displayed in full screen on a 4k resolution monitor
![99d465e2-b332-4378-a916-f729529de7d6](https://user-images.githubusercontent.com/15212559/232772094-45ca1edc-b24e-4735-8101-d9cc5b10b890.jpg)

**Comment by maxkatz6** [comment] 2023-04-19 01:19
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/10457

**Closed by maxkatz6** 2023-04-19 01:19 UTC
Labels: bug
