### ISSUE TITLE
ListBox scrolling causes "The control already has a visual parent"

### ISSUE THREAD

**Issue by SuperJMN** [AvaloniaUI/Avalonia#7621] opened 2022-02-16 11:40 UTC
**Describe the bug**
Scrolling the items of a ListBox produces:
> System.InvalidOperationException: 'The control already has a visual parent.'

**To Reproduce**

1. Create a new Avalonia Application from template
2. Open MainWindow.axaml
3. Add this XAML to it:
   ```csharp
   <ListBox>
        <ListBoxItem>asdfasdf</ListBoxItem>
        <ListBoxItem>asdfasdf</ListBoxItem>
        <ListBoxItem>asdfasdf</ListBoxItem>
        <ListBoxItem>asdfasdf</ListBoxItem>
        <ListBoxItem>asdfasdf</ListBoxItem>
        <ListBoxItem>asdfasdf</ListBoxItem>
        <ListBoxItem>asdfasdf</ListBoxItem>
        <ListBoxItem>asdfasdf</ListBoxItem>
        <ListBoxItem>asdfasdf</ListBoxItem>
        <ListBoxItem>asdfasdf</ListBoxItem>
        <ListBoxItem>asdfasdf</ListBoxItem>
        <ListBoxItem>asdfasdf</ListBoxItem>
        <ListBoxItem>asdfasdf</ListBoxItem>
    </ListBox>
   ```
4. Run the application
5. Resize the window so the ListBox shows a scrollbar. Make it show half of the items, approximately.
6. Scroll down to show the hidden items, either with the mouse scroll-whell or with tapping the scrollbar control itself.
7. You'll get the exception. You'll also notice that the last elements are shifted to the right side of the ListBox.

**Expected behavior**
No exception at all.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 22000.493

**Additional context**
Using Avalonia packages v0.10.12

**Comment by grokys** [comment] 2022-02-16 15:49
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/4265#issuecomment-797222259

Solution for now is to disable virtualization if you're using inline `ListBoxItem`s. I intended to fix this in https://github.com/AvaloniaUI/Avalonia/pull/4779 but `ItemsRepeater` is so broken I gave up on it.

Maybe I'll have time to fix this sometime, who knows...

**Closed by grokys** 2022-02-16 15:49 UTC
Labels: bug

**Comment by SuperJMN** [comment] 2022-02-21 09:05
Thanks, Steven! I'll use the workaround for now
