### ISSUE TITLE
Disable maximize button in avilonia

### ISSUE THREAD

**Issue by rukhsar29** [AvaloniaUI/Avalonia#5147] opened 2020-12-07 13:05 UTC
I want to disable maximize button or hide it.

**Comment by kekekeks** [comment] 2020-12-07 13:57
You can set `CanResize` to `false`

**Comment by rukhsar29** [comment] 2020-12-07 18:02
Not working in windows.

**Comment by jhofinger** [comment] 2020-12-08 09:35
See https://github.com/AvaloniaUI/Avalonia/issues/437#issuecomment-493003671. Duplicate?

**Comment by Symbai** [comment] 2021-09-16 06:47
> You can set `CanResize` to `false`

I can confirm this works fine in Windows 10, maximize button gets disabled. This issue can probably be closed

**Comment by Nickelony** [comment] 2021-11-14 11:59
Well... on my side, the maximize button doesn't disappear with these settings, so this is still an issue.
Using Avalonia 0.10.10 and Windows 11 (22000.318)

**Comment by mysteryx93** [comment] 2021-12-12 17:00
Minimize button is still enabled. WIth MessageBox.Avalonia, it's particularly an issue because the minimize/maximize buttons leave very little space for the MessageBox title! And you can minimize the MessageBox!?

**Comment by maxkatz6** [comment] 2023-01-29 19:11
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/3422

**Closed by maxkatz6** 2023-01-29 19:11 UTC
