### ISSUE TITLE
x:Name on Behaviors / project build fails

### ISSUE THREAD

**Issue by vaLP2eh** [AvaloniaUI/Avalonia#9194] opened 2022-10-15 06:49 UTC
**Describe the bug**
I would like to reference to named behaviors (x:Name) in XAML.
When using x:Name for a behavior the project doesn't compile anymore.

Error: `Avalonia error XAMLIL: Unable to resolve suitable regular or attached property Name on type ...`

**To Reproduce**

1. Add a simple control to your project.
2. Add a behavior to your project.
3. Use that behavior on one of your elements in your control using `<Interaction.Behaviors>` and assign a name to it using `x:Name`.
4. Building your project will fail showing the error above.

**Expected behavior**
Assigning names to behaviors should work as it does for other elements.

**Comment by maxkatz6** [comment] 2022-10-15 07:17
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2998

**Closed by maxkatz6** 2022-10-15 07:17 UTC
Labels: bug
