### ISSUE TITLE
Tree expand issue in DevTools

### ISSUE THREAD

**Issue by Whiletru3** [AvaloniaUI/Avalonia#16204] opened 2024-07-02 20:13 UTC
### Describe the bug

In the DevTools, if we want to expand a node without selecting the node first, the scrollviewer return to the offset Y 0. this is annoying when the tree is deep like in this gif :

![tree expand in devtools](https://github.com/AvaloniaUI/Avalonia/assets/4248852/b985f41e-47d1-42e3-a54a-b064ad738f9f)

### To Reproduce

activate the DevTools, open some nodes in the tree without selecting the node

### Expected behavior

The expected behaviour (like in 0.10.x) is to be able to open a node without selecting it and stay at the current offset Y

### Avalonia version

11.0.10 11.0.11 11.1.xxx

### OS

Windows, macOS

**Comment by maxkatz6** [comment] 2024-07-02 21:14
Can you try with this PR https://github.com/AvaloniaUI/Avalonia/pull/14417 ? Just wonder if it helps with scenario too.

**Comment by workgroupengineering** [comment] 2024-07-03 06:49
duplicate of #11704

**Comment by timunie** [comment] 2024-07-03 11:23
closing as duplicate

**Closed by timunie** 2024-07-03 11:23 UTC
Labels: bug, area-dev-tools
