### ISSUE TITLE
Slider's `Thumb.DragStarted` and `Thumb.DragCompleted` aren't working

### ISSUE THREAD

**Issue by define-private-public** [AvaloniaUI/Avalonia#4210] opened 2020-07-01 05:03 UTC
I have this XAML:

```
        <Slider DockPanel.Dock="Right"
                Orientation="Horizontal"
                Value="{Binding PlaybackSliderValue}"
                Thumb.DragStarted="OnPlaybackSliderDragStarted"
                Thumb.DragCompleted="OnPlaybackSliderDragCompleted"
                Minimum="0"
                Maximum="1000000"/>
```

I see in the Avalonia repo that `DragStarted` and `DragCompleted` are in `Thumb`, but when I tried to attach my handlers to them, I was treated with this at the `dotnet run` level:

```
/home/ben/Projects/AvaloniaSamples/BassoonJukebox/Views/JukeboxView.xaml(68,10,68,10): Avalonia error XAMLIL: Unable to resolve suitable regular or attached property DragStarted on type Avalonia.Controls:Avalonia.Controls.Primitives.Thumb (line 68 position 10) Line 68, position 10. [/home/ben/Projects/AvaloniaSamples/BassoonJukebox/BassoonJukebox.csproj]

The build failed. Fix the build errors and run again.
```

**Comment by define-private-public** [comment] 2020-07-02 04:48
If I wanted to implement support for this myself and then submit the PR, what would I need to do?

**Comment by jmacato** [comment] 2020-07-02 06:15
If you want to override the properties of slider, it's best if you just make a new control with Slider as base class... but if you need some kind of slider for a media player, take a look at this code: https://github.com/jmacato/Synfonia/blob/master/Synfonia.Gui/Controls/SeekSlider.cs

**Comment by define-private-public** [comment] 2020-07-08 04:12
I'm moreso trying to make some simple demo apps for Avalonia right now.  (Mainly as a way to learn the API).  I'm trying to port over a tiny audio player app I made in GtkSharp.  The slider was used to show where playback was for the user, but also they could click on the thumb and drag to to change the location in the music.

**Comment by xiaokun** [comment] 2022-08-12 03:19
I had the same problem. This bug seems to be still unresolved in the latest version (0.10.17). Is there any other solution to this problem now? Many thanks.

**Comment by maxkatz6** [comment] 2022-08-13 02:25
Routed attached events are not supported in the XAML,
duplicate of https://github.com/AvaloniaUI/Avalonia/issues/4009

**Comment by maxkatz6** [comment] 2022-08-13 02:25
@xiaokun you can do it from the code behind

**Closed by maxkatz6** 2022-08-13 02:25 UTC
