### ISSUE TITLE
when  set `{x:Null}` to any control's `FontFamily` property, application will crashed

### ISSUE THREAD

**Issue by Luoyingliang** [AvaloniaUI/Avalonia#15873] opened 2024-05-31 03:52 UTC
### Describe the bug

in WPF, set `{x:Null}` to any control's `FontFamily` property, it will fallback to the default fontfamily rather than throw exception, but in Avalonia (version 11.0.10) will throw a exception and application crashed

### To Reproduce

set `{x:Null}` to any control's `FontFamily` property

### Expected behavior

fallback to the default fontfamily

### Avalonia version

11.0.10

### OS

Windows, Linux, Android

**Comment by appel1** [comment] 2024-05-31 07:18
Duplicate of #15287 ? 

And perhaps setting FontFamily to null should fail property validation as it works in WPF?

**Comment by Luoyingliang** [comment] 2024-05-31 07:33
> Duplicate of #15287 ?
> 
> And perhaps setting FontFamily to null should fail property validation as it works in WPF?

yep, it's duplicated.
right, it's work in WPF

**Comment by rabbitism** [comment] 2024-05-31 07:36
There are multiple RPs related to font loading now, so we probably need to ask @Gillibald to check if any previous PR already fixed this issue.

**Comment by Luoyingliang** [comment] 2024-05-31 08:19
> There are multiple RPs related to font loading now, so we probably need to ask @Gillibald to check if any previous PR already fixed this issue.

ok

**Closed** 2024-07-16 07:21 UTC
Labels: bug
