### ISSUE TITLE
Avalonia.Diagnostic causing version conflict for Microsoft.CodeAnalysis.CSharp

### ISSUE THREAD

**Issue by Nemonek** [AvaloniaUI/Avalonia#14501] opened 2024-02-05 21:19 UTC
## Describe the bug
I'm working on a personal project with Avalonia MVVM application project in .NET8 and I was looking around to look into Dapper and /or Entity Framework. When I tried to install EF, more precisely the Microsoft.EntityFrameworkCore.Design v8.0.1 packet I got this error from NuGet: NU1107. The message says that I need to install Microsoft.CodeAnalysis.CSharp 4.5.0, and from what I understood my project is using the version 3.8.0 due to a dependency of the Avalonia.Desing packet.

Here the hierarchy, if I can call it so, of the dependency: 
 MyPersonalProject -> Microsoft.EntityFrameworkCore.Design 8.0.1 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.CSharp (= 4.5.0) 
MyPersonalProject -> Avalonia.Diagnostics 11.0.7 -> Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 -> Microsoft.CodeAnalysis.CSharp (= 3.8.0).	

## Environment
- OS: Windows 10
- Avalonia-Version: 11.0.7
- Visual Studio 2022 17.8.3
- .NET version of the project: 8
- Project Template: Avalonia .NET MVVM App
- .NET version installed in the device: 6 - 7 - 8

**Comment by maxkatz6** [comment] 2024-02-06 00:40
Version conflict is not a bug, as it happens all the time. You would need to consolidate version by pinning it in your project

Also it's not an issue anymore in 11.1 nightly builds, as Scripting package was removed from the dev tools, so closing as resolved.

**Closed by maxkatz6** 2024-02-06 00:40 UTC
Labels: bug
