### ISSUE TITLE
Adding SplitView results in binding error.

### ISSUE THREAD

**Issue by sekulicb** [AvaloniaUI/Avalonia#8100] opened 2022-05-08 19:03 UTC
**Describe the bug**
Adding SplitView control in Xaml results in binding error : [Binding] Error in binding to 'Avalonia.Controls.ColumnDefinition'.'Width': 'Null value in expression '{empty}' at ''.' (ColumnDefinition #2533231)A

**To Reproduce**
Add grid -> add SplitView control -> add simple content to it, such as TextBlock -> build project and run

**Expected behaviour**
Should not throw the binding error

**Screenshots**
![image](https://user-images.githubusercontent.com/20758693/167311396-2fbfb116-c6ff-43a1-ac33-e4a072084623.png)

**Desktop (please complete the following information):**

- OS: Win 10
- Version 21H2

**Additional context**
Avalonia 0.10.13, .NET 6

**Comment by amwx** [comment] 2022-06-10 00:13
This has been around since it was ported (I even left a comment about it in the template). The binding eventually evaluates, but when first loading the template it fails. Harmless, but annoying.
https://github.com/AvaloniaUI/Avalonia/blob/709ad86626071dd18b68df53f226fdbee3992151/src/Avalonia.Themes.Fluent/Controls/SplitView.xaml#L39-L43

It looks like when the template is first applied, the InheritanceParent on the ColumnDefinition is null, and the anchor for the binding is null so it has no way to evaluate `TemplatedParent.TemplateSettings.PaneColumnGridLength`

![image](https://user-images.githubusercontent.com/40413319/172965013-e54c63b9-bdcc-462e-9279-cbb5afde26b1.png)

I just set a breakpoint where the binding error is logged and followed the call stack up until Avalonia.AvaloniaObjectExtensions.Bind, right after the XamlIl stuff loading the template.

I'm wondering if this is related to DefinitionBase not being a StyledElement because other bindings like this work when a template is loaded but this has always failed.

**Comment by maxkatz6** [comment] 2023-01-28 01:41
Duplicate of #5762

**Closed by maxkatz6** 2023-01-28 01:41 UTC
Labels: bug
