### ISSUE TITLE
TimePcker with secons display

### ISSUE THREAD

**Issue by mate1213** [AvaloniaUI/Avalonia#14170] opened 2024-01-11 07:23 UTC
## Describe the solution you'd like
TimePcker should have a bool which sets to seconds shown.

## Describe alternatives you've considered
If I create a separate Textbloxk for it, the unified designes will broke.

## Additional context
I have to set time stamps on videos, therefore I need to select seconds too. (maybe frames or miliseconds too)

If it is okay, I can help implement it if needed.

**Comment by timunie** [comment] 2024-01-11 07:37
Duplicate of #12045

**Closed by timunie** 2024-01-11 07:37 UTC
Labels: enhancement
