### ISSUE TITLE
Main Window isn't displayed when setting WindowState to FullScreen before first render

### ISSUE THREAD

**Issue by comet56us** [AvaloniaUI/Avalonia#4006] opened 2020-05-27 14:50 UTC
Setting `WindowState=FullScreen` on my main window anytime before it is first rendered is causing it to never render. If I instead set the `WindowState` in the `Render()` override, or anything that happens after that, it works as expected.

I'm running on Windows 10.

The `Window` is set up with the boilerplate code:
```
public override void OnFrameworkInitializationCompleted()
{
   if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
   {
      desktop.MainWindow = new MainWindow
      {
         DataContext = new MainWindowViewModel(),
      };
   ...
```

The `Window` starts with a `Grid` with a few controls, one of which starts some `Animations` immediately. It also has some resources and styles.

@danwalmsley 
Using nightly build 0.9.999-cibuild0007800-beta

**Comment by mgnslndh** [comment] 2023-09-23 12:58
This isssue covers the same problem as #4204 and that one has been closed because the issue is fixed. Having WindowState=FullScreen in XAML works fine on Avalonia 11.0.4 Windows Desktop.

Perhaps this issue can be closed? @comet56us @danwalmsley

**Comment by timunie** [comment] 2023-09-23 13:21
Closing this as outdated. Please ping me if reproducible in 11.0

**Closed by timunie** 2023-09-23 13:21 UTC
