### ISSUE TITLE
ColorView overlaps ColorPicker split button

### ISSUE THREAD

**Issue by VMMachal** [AvaloniaUI/Avalonia#13550] opened 2023-11-09 07:51 UTC
## Describe the bug
The new ColorPicker for Avalonia doesn't seem to have a support for displaying the ColorView placement anywhere else but upward from the split button. This causes an overlap of the split button by the ColorView  if the button is positioned more closer to the top border of the screen. 

## To Reproduce
Create ColorPicker dropdown in a UI where it is close to top part of your screen. Click the dropdown to open ColorView and see it overlaps the button.

1. Create ColorPicker dropdown in xaml.
2. Start the app and move it to the top so the ColorPicker is close to top screen border.
3. Click the ColorPicker split button dropdown.
4. See the overlap of the split button by the ColorView.

## Expected behavior
If it is about to overlap the ColorPicker, it should be displayed beneath the split button and vice-versa. Or there should be an option to control how ColorView placement happens.

## Screenshots
[https://ibb.co/GFxCC8m](url)

## Environment
- OS: [Windows]
- Avalonia-Version: [11.0.5]

## Additional context
I couldn't find any control template for ColorPicker or ColorView, so maybe this would help to create own style with the placement option.

**Comment by timunie** [comment] 2023-11-09 08:23
@VMMachal the build in styles are here: https://github.com/AvaloniaUI/Avalonia/tree/master/src/Avalonia.Controls.ColorPicker/Themes 

As far as I can see the position seems to be hard coded. https://github.com/AvaloniaUI/Avalonia/blob/9cd8dda5206ffbcb6705ada2ae8d3753aaaf9caf/src/Avalonia.Controls.ColorPicker/Themes/Fluent/ColorPicker.xaml#L52-L55

@robloo do you think we could move this into a style, so the placement can be overridden by the user?

**Comment by robloo** [comment] 2023-11-09 15:04
@VMMachal 

> This causes an overlap of the split button by the ColorView if the button is positioned more closer to the top border of the screen.

Yes, but if the ColorPicker is at the bottom of the screen you have a problem again. The solution is to make this configurable.

@timunie 

> As far as I can see the position seems to be hard coded.

Yes, this is a mistake for sure. I thought I had it on my todo list at one point but it seems to have fallen off and been forgotten -- perhaps because of the below.

> do you think we could move this into a style, so the placement can be overridden by the user?

My instinct is that the solution for this is actually to add a `FlyoutPlacement` property. That's way easier to use and understand than another style in this case. Interestingly, UWP/WinUI doesn't seem to have that property either and you have to set it the same way on the Flyout itself (like a ToolTip). So this is a new idea... or one that was discussed and decided against.

So I'm considering the following:

 1. I would like to add a `FlyoutPlacement` property. However, some rules have to be defined for how that applies:
     * By default, controls that DO NOT provide their own flyout CANNOT have a `FlyoutPlacement` property. This follows what we have now and UWP/WinUI. It's the standard for both Flyout and ToolTip to define this on a new instance itself.
     * Controls that DO provide a flyout themselves MUST have a `FlyoutPlacement` property.
        * That includes `ColorPicker`, `ComboBox`, etc.
        * But does NOT `Button`, `DropDownButton`, etc.
     * Note: `ComboBox` really shouldn't be called a "Drop Down" and needs to be generalized to a flyout concept as well. Someone might want it to open upwards... it has the same issues we are discussing here with ColorPicker just we've all gotten used to it by now.
  2. If not the above, I would add a lightweight styling resource to control this with the existing styles.
  3. Possibly along with num. 2 I can pull out the flyout style as well so it can overriden as you suggest. This seems like a last resort IMO but should be considered.

I'm going to think about this a little more. Ideas more than welcome.

**Comment by timunie** [comment] 2023-11-09 15:07
@robloo thanks for sharing your detialed thoughts with us. Imo we need a way to swap position once it overlaps. AnchorAndGravity should be able to do this, but I can't get my head around how to specify this correctly 😆

**Comment by robloo** [comment] 2023-11-09 15:11
@timunie I think I accidentally opened up a larger can of worms here. Like I said, other controls will benefit from this discussion `ComboBox`, `AutoCompleteBox`, `ColorPicker`... anything that has a "flyout", "popup" or "drop-down" implemented by the control itself. I'll start a more detailed spec for what can be done here and compare the controls -- probably open a new issue for it too.

I'll take care of this issue as well though. I might just do num. 2 and 3 quickly in a PR to close this out while the long-term fix is better considered.

> Imo we need a way to swap position once it overlaps.

Well, that's a different problem still, lol

**Comment by VMMachal** [comment] 2023-11-09 15:34
I'll throw my 2 cents. Easiest way to get a solution here is to think about the ColorView and screen bounds. Since ColorView is hard coded for ~340px height, then if the current ColorView bounds would intersect current screen height or width, it should just be displayed on opposite side of the ColorPicker split button.
Doesn't have to do anything else. I only need to see the original split button that started the event, as that's the one the color applies to. If I'd wanted some specific stuff, I'd just do the ColorView fixed in some specific position and toggle the visibility.

**Comment by robloo** [comment] 2023-11-09 15:39
@VMMachal, yes as a concept. But this type of logic cannot be hard-coded into the control. It needs to come from the Flyout or lower level Popup. In this case we already have the functionality to do this in Popup. The problem, as @timunie pointed out, is how to specify this correctly -- or expose it as properties -- of the control. The control is presently using the high-level Flyout.

**Comment by timunie** [comment] 2023-11-10 09:00
@robloo I found our issue: https://github.com/AvaloniaUI/Avalonia/blob/9cd8dda5206ffbcb6705ada2ae8d3753aaaf9caf/src/Avalonia.Controls/Flyouts/PopupFlyoutBase.cs#L426-L429

In this code it is hardcoded to Slide when the Popup positions. If I change this to `FlipY` it works as expect and is much nice imo. I will discuss with the team if we:
1. want to make it an AvaloniaProperty of PopupFlyoutBase and make this styleable (my favorite)
2. we need to live with it as it's by design 
3. we want to introduce a behavior change here and hardcode Flip instead of Slide

**Closed** 2023-11-13 16:20 UTC
Labels: bug

**Comment by markusalbrecht-procam** [comment] 2023-12-13 14:36
FIXED in the latest version of **Avalonia11.0.0.6**
