### ISSUE TITLE
Binding Crash with "System.ExecutionEngineException" or "System.NullReferenceException"

### ISSUE THREAD

**Issue by Alex-Dall** [AvaloniaUI/Avalonia#5434] opened 2021-02-06 22:46 UTC
When running the following code the programm crashs if there are tow many updates of the Propoerty. The issue only happens on Windows.

```
public class MyViewModel : ReactiveObject
{
        private string _text;

        public string Text
        {
            get => _text;
            set
            {
                this.RaiseAndSetIfChanged(ref _text, value);
            }
        }
}
```

`<TextBox Grid.Column="0" Grid.Row="1" Grid.ColumnSpan="3" Text="{Binding Text}" ></TextBox>`

 - OS: Windows (Works on Linux, Mac not tested)
 - Version 0.10.0, 0.9.10 (have not tested more than these two versions)

Error message:
`A Exception of the type "System.NullReferenceException" happend in Unknown Modul.`
or
`A Exception of the type "System.ExecutionEngineException" happend in Unknown Modul.`

**Comment by danwalmsley** [comment] 2021-02-06 23:44
@Alex-Dall please provide the code to do too many updates to the property... or a zip with a simple repro for debugging. Thanks.

**Comment by Alex-Dall** [comment] 2021-02-07 11:36
The code updating the property is the following:
```
private void MessageReceived(object sender, MidiReceivedEventArgs e)
{
     _model.Text += "SomeText\n";              
}
```
```
readonly MyViewModel _model = new MyViewModel();
private IMidiAccess _midi;
private void InitializeComponent()
{
     AvaloniaXamlLoader.Load(this);
     DataContext = _model;   
     if (IsWindows)
        _midi = new WinMMMidiAccess();
     else
        _midi = new AlsaMidiAccess();
}
```
 ```
var port = _midi.OpenInputAsync(portNr).Result;
port.MessageReceived += MessageReceived;
```
The program should receive Midi-Notes form a Midi-Device and print them to the TextBox. The crash happens when I play to many notes in a short time.
The real code in the MessageReceived is of course different, but i have tested the program with only the line above in the MessageReceived method and the error still happens when I play to many Midi-Notes.

The error do not happen if I comment out like the following. So the problem have to be in "this.RaiseAndSetIfChanged()" Method. I have also tried the "this.RaiseAndSetIfChanged" Method instead, but the error is still there.
```
public class MyViewModel : ReactiveObject
{
        private string _text;

        public string Text
        {
            get => _text;
            set
            {
               // this.RaiseAndSetIfChanged(ref _text, value);
            }
        }
}
```

I have done some testing and found out that the amount of updates is not the problem. I ran the following code without any error:
```
Thread thread = new Thread(SendMessages);
thread.Start();
```
```
private void SendMessages()
{
     while (true)
     {
         _model.Text += "SomeText\n";
         Thread.Sleep(10);
     }
}
```

I have also set the Avalonia Log Level to Verbose, but there are no logs that indicates an error.

I have tried it on Linux again, but there is no chance to reproduce this error on Linux. I can play as many notes as I want, and the application is still working.

**Comment by Gillibald** [comment] 2021-02-07 12:27
A call stack would help here. Also is there a reason why you don't await `OpenInputAsync`?

**Comment by kekekeks** [comment] 2021-02-07 12:46
@Alex-Dall it seems that you are updating the view model from a non-UI thread which is not supported.

**Comment by Alex-Dall** [comment] 2021-02-07 14:19
@kekekeks Yes thats what I try. If this is not supported is there any way to delegte de update?

**Comment by jp2masa** [comment] 2021-02-07 19:03
Something like this should work:

```cs
private void MessageReceived(object sender, MidiReceivedEventArgs e)
{
    Dispatcher.UIThread.InvokeAsync(
        () =>
        {
            _model.Text += "SomeText\n";
        }
    );
}
```

**Comment by Alex-Dall** [comment] 2021-02-07 19:10
@jp2masa  When I add your Invoke Code still the same error happens

**Comment by danwalmsley** [comment] 2021-02-07 21:56
@Alex-Dall did you make a call to UseReactiveUI in the AppBuilder calls when initialising Avalonia?

**Comment by Alex-Dall** [comment] 2021-02-07 21:59
Yes I did. Here is my App Builder:
```
    class Program
    {
        public static void Main(string[] args) => BuildAvaloniaApp()
            .StartWithClassicDesktopLifetime(args);

        public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UseReactiveUI()
                .UsePlatformDetect()
                .LogToTrace();
    }
```

**Comment by cezarypiatek** [comment] 2022-11-06 14:29
I think I experience the same issue. Avalonia UI 11 preview 3. Stacktrace as below
![image](https://user-images.githubusercontent.com/7759991/200176607-c4a2ad21-8481-4978-a15a-9c650d864ff4.png)

**Comment by timunie** [comment] 2022-11-06 16:08
Can you share a minimal sample on GitHub?

**Comment by cezarypiatek** [comment] 2022-11-06 21:21
I might try, but it's not deterministic. I guess this is because the WeakEvents lose the actual reference....

**Comment by timunie** [comment] 2022-11-07 08:24
@cezarypiatek Let's see. If you manage to do so, or if you can share all your code, it may be easier for us to get the root cause. 

Thanks for your effort.

**Comment by maxkatz6** [comment] 2022-11-08 00:27
Original issue was caused by invoking UI code on non UI thread. So I am closing this.

@cezarypiatek your issue seems to be same as here https://github.com/AvaloniaUI/Avalonia/issues/8810

**Closed by maxkatz6** 2022-11-08 00:27 UTC
Labels: bug
