### ISSUE TITLE
Parent window disappears when closing modal child

### ISSUE THREAD

**Issue by Fido789** [AvaloniaUI/Avalonia#4868] opened 2020-10-14 21:36 UTC
Hello,

I have a parent window and a modal child:

![1](https://user-images.githubusercontent.com/12424763/96047426-61d14800-0e75-11eb-988f-60a25fdbaa86.png)

When I am closing this child, sometimes parent disappears for a split second:

![2](https://user-images.githubusercontent.com/12424763/96047508-888f7e80-0e75-11eb-9543-6101c1ba63de.png)

And comes back:

![3](https://user-images.githubusercontent.com/12424763/96047688-cab8c000-0e75-11eb-9e3e-568503396f22.png)

It looks ugly. Can I fix if myself somehow or is it a bug?

**Comment by maxkatz6** [comment] 2020-10-14 22:30
I also can confirm, that main window is minimized after dialog one closed in my app.

**Comment by MarchingCube** [comment] 2020-10-23 20:56
I think I have found out the reason for this, our win32 implementation is not enabling parent window fast enough so Windows just picks another window in z-order and activates it.

https://stackoverflow.com/questions/18183289/winapi-window-is-sent-to-back-when-using-enablewindow-function

**Comment by maxkatz6** [comment] 2020-10-24 04:32
There are more issues actually.

First (fixed with #4928):
1. Open new window with ```.ShowDialog(Parent)```.
2. Close dialog window.
3. Parent is minimized for the moment and then comes back.

Second (isn't fixed with the PR):
1. Restart application (for some reason it can be reproduced only once on my machine)
2. Open new window with ```.ShowDialog(Parent)```
3. Focus another application.
4. Focus back avalonia application,
2. Close dialog window.
3. Parent is minimized for the moment and then comes back.

Third (isn't fixed with the PR):
1. Open new window with ```.Show(Parent)``` (not a dialog).
2. Focus another application.
3. Focus back avalonia application,
4. Close child window.
5. Parent is minimized and doesn't come back.
Record with third bug, attention the on task bar
![asdf](https://user-images.githubusercontent.com/3163374/97067817-ac4a7700-158f-11eb-99c4-764ff3ea3666.gif)

**Comment by MarchingCube** [comment] 2020-10-24 14:57
@maxkatz6 I've updated my PR and at least on my machine it fixes issues with windows minimizing in two remaining cases as well.

**Comment by Fido789** [comment] 2020-10-24 19:29
@MarchingCube I would gladly try it, but unfortunately I don't know how to find the correct version. I thought the build number is 11582

![image](https://user-images.githubusercontent.com/12424763/97091919-c0e64800-163f-11eb-9202-f93cc47a9a71.png)

But I cannot see any version with such a number

![image](https://user-images.githubusercontent.com/12424763/97091939-d9566280-163f-11eb-9d9b-2c1e19f6951a.png)

**Closed** 2020-10-25 13:03 UTC
