### ISSUE TITLE
Center aligned text trimmed when control has enough space

### ISSUE THREAD

**Issue by techyian** [AvaloniaUI/Avalonia#13574] opened 2023-11-10 22:00 UTC
## Describe the bug
Center aligned text using `HorizontalContentAlignment` causes end character to be clipped.

The issue I'm running into seems very similar to #6643 however that ticket was closed due to not being able to reproduce. 

I have created a Button and Label control within a StackPanel as a basic test which is defined as follows:

```
<StackPanel Orientation="Vertical" Width="1366" HorizontalAlignment="Center">
	<Button HorizontalContentAlignment="Center" Width="250">Hello123456789</Button>		
	<Label Width="250" HorizontalContentAlignment="Center">Hello123456789</Label>
</StackPanel>
```

When the application runs the number 9 is cut off partially and this appears to be due to using the `HorizontalContentAlignment` attribute, when this is removed the text shows correctly. Increasing the `Width` attribute against the child controls has no effect. I'm unsure whether this is an issue with my environment, as I would assume that center aligning text as a label or as part of a button is quite a common task? I'm very new to desktop app development.

I would also like to add that I've tried both the Fluent and Simple themes but the result is the same.

## To Reproduce
Create basic Avalonia application and add the code defined above.

## Expected behavior
The text should not be clipped if there is a large enough `Width` defined against the control and there is enough room in the parent.

## Screenshots

![image](https://github.com/AvaloniaUI/Avalonia/assets/13114804/8a7a3f23-233e-4c9e-b526-9876b1d16db5)

## Environment 

- OS: Windows 10 Enterprise 22H2
- Avalonia-Version: 11.0.5

## Additional context
N/A

**Comment by timunie** [comment] 2023-11-13 11:37
I can't reproduce using the snippet above. Do you have some display scaling added? 
![image](https://github.com/AvaloniaUI/Avalonia/assets/47110241/67a31698-064b-4bec-a1f6-9bfefbb9ec88)


could be related to https://github.com/AvaloniaUI/Avalonia/issues/13298

**Comment by techyian** [comment] 2023-11-13 21:05
@timunie - very strange, today this isn't happening for me. Scaling is at 125%. I'll monitor this as I develop the app further and respond if it happens again. I agree with the ticket you referred to as it does sound very similar.

**Comment by timunie** [comment] 2023-11-14 05:35
Will close this as duplicate. Please comment on the other ticket if you found out how to trigger. Other monitor? Other font?

**Closed by timunie** 2023-11-14 05:35 UTC
Labels: bug, area-textprocessing
