### ISSUE TITLE
How can I change the binding value after losing focus

### ISSUE THREAD

**Issue by qfmee** [AvaloniaUI/Avalonia#10259] opened 2023-02-08 06:01 UTC
TextBox changes the binding value immediately by default. How can I change the binding value after losing focus？ Like WPF's textBox
for example: WPF code: `<TextBox  Text="{Binding MyValue,UpdateSourceTrigger=LostFocus}" />`

**Comment by maxkatz6** [comment] 2023-02-08 06:17
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/3754
There is also hints how can it be done without UpdateSourceTrigger.

**Closed by maxkatz6** 2023-02-08 06:17 UTC

**Comment by qfmee** [comment] 2023-02-08 06:40
Thank you！ Is UpdateSourceTrigger planning to join avalonia?

**Comment by maxkatz6** [comment] 2023-02-08 06:50
Not in 11.0. Possibly in 11.x later this year.
