### ISSUE TITLE
Multiline TextBox scrolls first line offscreen on enter

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2614] opened 2019-06-04 10:18 UTC
I found some strange behaviour with entering text into a multiline TextBox.
I setup a multiline textbox inside a grid.

```
  <Grid RowDefinitions="Auto,Auto">
    <TextBlock Text="Test"/>
    <TextBox Grid.Row="1" AcceptsReturn="True" MinHeight="35" NewLine="&#x0a;" FontSize="18" />
  </Grid>
```

Enter some text; everything looks OK so far.

![image](https://user-images.githubusercontent.com/17591364/58871275-98138a80-86b9-11e9-8ae6-626e11f0c147.png)

Now hit enter; the entered text disappears.

![image](https://user-images.githubusercontent.com/17591364/58871338-b5485900-86b9-11e9-963c-ad4914368d27.png)

I expected the TextBox to resize for two lines with the cursor on the second line and both lines visible.
The TextBox has resized but scrolled the top line offscreen.

**Comment by Gillibald** [comment] 2019-06-04 10:27
This is most likely not a bug of the TextBox. Current Grid implementation is broken. Pls try to use a DockPanel instead.

**Comment by aguahombre** [comment] 2019-06-04 10:32
Thanks, but a I need a Grid in my application.
I guess I will have to wait for a fix to the Grid control.
Is there a PR for the Grid problem?

**Comment by wieslawsoltes** [comment] 2019-06-04 10:33
@aguahombre https://github.com/AvaloniaUI/Avalonia/pull/2563

**Comment by grokys** [comment] 2019-06-05 11:59
The WPF `Grid` has now been merged to master, so hopefully this will be fixed!

**Comment by jmacato** [comment] 2020-02-20 04:39
Re-tested on master, seems to be working as intended now.

**Closed by jmacato** 2020-02-20 04:39 UTC
Labels: bug
