### ISSUE TITLE
IPlatformHandle.Handle is null from version 0.10.14.

### ISSUE THREAD

**Issue by modmanx** [AvaloniaUI/Avalonia#8310] opened 2022-06-08 21:47 UTC
Some months ago I made an application which successfully created a control to which I got Handle which was passed to other program to embed own content (dx video).

Today I tried to update all nuget packages to latest version (avalonia, desktop, diagnostics and reactievui) and although program compiles and runs fine, parent.Handle returns 0x000000...
![image](https://user-images.githubusercontent.com/865727/172723116-64727745-821f-4b9a-9bff-83c110374db3.png)

I took sample code from https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog.NetCore/NativeControls/Win/EmbedSample.Win.cs
This sample compiles and runs fine on my computer.

I tried to find what could be the cause by comparing version 13 and 14, but did not find anything.

Is there anyone who could have a clue? :)

- OS: Windows
- Version 10

**Comment by maxkatz6** [comment] 2022-06-08 22:35
You are missing app.manifest file https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog.NetCore/app.manifest

Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/8177

**Comment by maxkatz6** [comment] 2022-06-08 22:36
In 11.0 nightly it throws an exception with details about app.manifest.

**Closed by maxkatz6** 2022-06-08 22:35 UTC
Labels: bug
