### ISSUE TITLE
'x' character is replaced by multplication in TextBlock.Text (Avalonia 11.1.4)

### ISSUE THREAD

**Issue by Kruno313** [AvaloniaUI/Avalonia#17282] opened 2024-10-15 12:10 UTC
### Describe the bug

I format my values as hexadecimal (with "0x" preamble) and output them on TextBlock.
I noticed that the x is replaced with an higher placed x, so "0x1A30" looks like multiplication operation. It is done only when x is between numbers. 
It looks strange and it's wrong.

### To Reproduce

`<TextBlock Text="0x1234" />`

It is obvious in designer.

### Expected behavior

TextBlock should not change text. Searching and replacing makes it only slover for no benefit, making only problems.

### Avalonia version

11.1.4

### OS

Windows

**Comment by timunie** [comment] 2024-10-15 13:12
please provide some sample code to reproduce

**Comment by Gillibald** [comment] 2024-10-15 14:10
This is just regular text shaping. Use a different font or disable the font feature.

**Comment by Kruno313** [comment] 2024-10-15 18:55
> This is just regular text shaping. Use a different font or disable the font feature.

No, text like "x0x23" has first x normal and second x changed.

**Comment by Kruno313** [comment] 2024-10-15 18:58
> please provide some sample code to reproduce

It was not visible:
`<TextBlock Text="0x1234" />`

**Comment by maxkatz6** [comment] 2024-10-15 21:12
@Kruno313 since you haven't mentioned which font are you using, I assume it's Inter. Inter is a default font used in our templates.

I uploaded Inter font into https://fontdrop.info/ font viewer webapp, and input your text `x0x1234`.
![image](https://github.com/user-attachments/assets/5ad152ec-aebe-4a92-94e7-242f46cdb70a)

Avalonia renders this text as expected from the font. I am closing this issue as `by design`.

> TextBlock should not change text. Searching and replacing makes it only slover for no benefit, making only problems.

https://en.wikipedia.org/wiki/Ligature_(writing)

**Closed by maxkatz6** 2024-10-15 21:12 UTC
Labels: bug

**Comment by maxkatz6** [comment] 2024-10-15 21:22
@Kruno313 it's also possible to disable specific font features:
```
<TextBlock Text="x0x1234" FontFeatures="-calt" />
```

For a complete FontFeatures syntax, see https://harfbuzz.github.io/harfbuzz-hb-common.html#hb-feature-from-string

**Comment by Kruno313** [comment] 2024-10-16 08:34
Thanks.
I have never heard about this and never noticed it in Win-Framework or other Libraries (I use the Hexadecimal formatting often).
