### ISSUE TITLE
DispatcherUnhandledException alternative

### ISSUE THREAD

**Issue by ltetak** [AvaloniaUI/Avalonia#13393] opened 2023-10-26 08:04 UTC
## Is your feature request related to a problem? Please describe.
Log and handle unhandled UI exceptions without app crash in the way WPF does. This is convenient to log fatal exceptions as well as to handle some non-critical ones.

## Describe the solution you'd like
It was possible before to extend the **IPlatformThreadingInterface**. One could handle exceptions there and restart the **RunLoop** if the exception was considered not terminating
pseudocode:
```
    public void RunLoop(CancellationToken cancellationToken)
        {
            tryagainloop:
            try
            {
                _inner.RunLoop(cancellationToken);
            }
            catch (Exception e)
            {
                if (Handle(e))
                {
                  goto tryagainloop;
                }
            }
        }
```

## Describe alternatives you've considered
Either make the IPlatformThreadingInterface extendable again or make it as an Avalonia feature.

**Comment by maxkatz6** [comment] 2023-11-03 22:33
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/8418

**Closed by maxkatz6** 2023-11-03 22:33 UTC
Labels: enhancement
