### ISSUE TITLE
Deffered renderer sometimes does not dispose all layers

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1314] opened 2017-12-12 14:32 UTC
https://files.gitter.im/AvaloniaUI/Avalonia/nFRX/image.png

I'm not sure how to trigger this, but iv seen it a few times. Will try to find out more.

**Comment by jkoritzinsky** [comment] 2017-12-12 17:48
This might be related to/duplicate of #1187.

**Comment by grokys** [comment] 2017-12-12 21:01
Just to check: this is happening when shutting down the application, right?

**Comment by danwalmsley** [comment] 2017-12-15 14:28
no, this is happening at run time.

**Comment by danwalmsley** [comment] 2017-12-15 14:29
I can usually trigger it by changing my colour scheme a few times, with skia backend, and changing editor tabs in AS, but seems pretty random

**Comment by danwalmsley** [comment] 2017-12-15 20:55
![image](https://user-images.githubusercontent.com/4672627/34060143-4a375376-e1da-11e7-8a59-14113cfda21a.png)
getting this quite a lot now

**Comment by grokys** [comment] 2019-03-02 16:29
@danwalmsley are you still seeing this?

**Comment by grokys** [comment] 2021-02-17 16:07
Closing this as it's been stale for years.

**Closed by grokys** 2021-02-17 16:07 UTC
Labels: bug, needs-repro, perf
