### ISSUE TITLE
Transparency Fail when Packaged for Microsoft Store App

### ISSUE THREAD

**Issue by premsundaram** [AvaloniaUI/Avalonia#10312] opened 2023-02-11 20:33 UTC
The Issue:

We are developing a cross platform app.  We have set the window transparency as follows in the view and are also wanting to hide the top title so we use the following commands:

ExtendClientAreaToDecorationsHint="True"
 ExtendClientAreaChromeHints="NoChrome"
TransparencyLevelHint="Transparent"

If I run the app on my development machine on windows and we build the app it works fine.  The top toolbar does not show, the window is transparent and I am also able to resize the window.

However, when I package the app for deployment to the Microsoft app store the resulting packaged app does not support the transparency and window appears normal, no transparency.

BUT: when packed the same code on Mac it DOES work!

Furthermore if we set 'ExtendClientAreaToDecorationsHint'=False then transparency works but the top toolbar shows (as expected).

An Alternative we tried:
We then tried the idea of setting additional command of 'SystemDecorations' = None.
This solved the issue so we now have transparency and no top title, but now we can't resize the window!
(This is also known behavior per documentation).  If I try the other setting of 'Border only' that again makes the window non-transparent but now resize works (expected behavior)

FYI:  I am creating a 'package' in the VS app by adding the VS Packaging project to the solution.  This is the standard normal way as I have done on other apps.  I have tried setting many different 'capabilities' etc. but even things like 'fullTrust' do not work.

It is a very hard bug to fix since if you build on VS on the desktop things work if you run the app but when 'packaged' they do not.

Any help or ideas much appreciated.  I think the 'solution' could be to have a new systemdecorations option like 'None' but that allows resize of window.  OR we figure out why the packaging makes the initial method of transparency not work on Windows yet works on Mac. 
 
thanks
Prem

**Comment by amwx** [comment] 2023-02-11 20:47
Make sure you're publishing with `win7-x64` or `win10-x64`. `win-x64` fails to include a dll or something like that and breaks the transparency stuff, IIRC

**Comment by premsundaram** [comment] 2023-02-11 20:57
thank you - do you know where i set that? I will take a look !

**Comment by premsundaram** [comment] 2023-02-11 23:25
I did try to add this command in the Packaging file under a <propertygroup> <RuntimeIdentifier>win10-x64</RuntimeIdentifier> but that did not work

<img width="355" alt="image" src="https://user-images.githubusercontent.com/62580233/218285329-b40a6979-3d1c-4840-885c-1fb6c006d533.png">

**Comment by amwx** [comment] 2023-02-12 00:15
It seems VS doesn't recognize that for some reason, but you can try from the command line:

`dotnet publish -c Release -o OutputDir -r win10-x64 --self-contained` (adjust the other publish commands to your needs)

**Comment by premsundaram** [comment] 2023-02-12 00:26
thanks i will try to do

**Comment by maxkatz6** [comment] 2023-02-12 09:51
Was fixed in master. There are workarounds for older versions.

**Closed by maxkatz6** 2023-02-12 09:51 UTC
Labels: bug

**Comment by premsundaram** [comment] 2023-02-13 02:26
> Was fixed in master. There are workarounds for older versions.

this is fixed? i don't understand  - not sure why this was closed.

**Comment by maxkatz6** [comment] 2023-02-13 03:59
@premsundaram yes, it was changed in the master branch, but not yet released in preview.
Again, it's not a bug as it was an intended behavior where you need to use win7-x64 runtime identifier, until MS did it hard to do.

As an alternative, you can reference this nuget package with this specific version in your project:
```xml
<PackageReference Include="Avalonia.Angle.Windows.Natives" Version="2.1.0.2023020321" />
```
It will have the same behavior as currently master branch has.

**Comment by premsundaram** [comment] 2023-02-13 04:52
@maxkatz6 oh, thank you! much appreciated!
