### ISSUE TITLE
[0.10.0-rc1] Dynamically adding Items to ItemControl causes StackOverflow Exception 

### ISSUE THREAD

**Issue by xormak** [AvaloniaUI/Avalonia#5183] opened 2020-12-16 21:22 UTC
**Situation:**
I have an ItemControl with a StackPanel PanelTemplate inside a ScrollView.
A button in the same view adds new Objects to an ObservableCollection of a custom type.
The ItemControl has a custom UserControl as DataTemplate and has its Items attribute bound to the ObservableCollection.
The custom UserControl Contains a basic Grid, StackPanel, TextBlock and Button.

**Issue:**
When an object is added to the ObservableCollection and a new instance of the DataTemplate is created the Application crashes with a StackOverflow Exception.

**Observed Behavior:**
Removing the Button from the custom UserControl fixes the issue. The Button in question has no Command, Styling etc. 
Because of that I am pretty sure the issue lies in the creation of a Button in that specific scenario. 

Unfortunately I have no idea what could cause this and after a very quick passing glance haven't found anything in Avalonia source that could have told me either.

I am not sure what exactly is causing this so I thought I'd open an Issue about it.
Or is there an obvious solution that my brain just wouldn't think of on its own?

**Comment by danwalmsley** [comment] 2020-12-17 02:32
@xormak you will need to post the code required to reproduce the issue.

**Comment by xormak** [comment] 2020-12-17 05:32
Right, sorry!
(Left out irrelevant clutter for readability)

Mainwindow
```xaml
<Window xmlns="https://github.com/avaloniaui"
        Content="{Binding ActiveView}"
</Window>
```

VM_Main, Datacontext of Mainwindow
```cs
class VM_Main : VM_Base
{
    public VM_Main()
    {
        SetActiveView(View.LIST_Char);
    }

    public Control ActiveView { get; set; }
    public VM_Base ActiveViewModel { get; set; }

}
```

V_LIST_Char
```xaml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:ss="clr-namespace:SwiftSheet;assembly=SwiftSheet"
             x:Class="SwiftSheet.V_LIST_Char">
  
  <Grid RowDefinitions="* Auto">
    
    <ScrollViewer>
      <ItemsControl Grid.Row="0" Items="{Binding ActiveViewModel.Characters}">
        <ItemsControl.ItemsPanel>
          <ItemsPanelTemplate>
            <StackPanel />
          </ItemsPanelTemplate>
        </ItemsControl.ItemsPanel>
        <ItemsControl.DataTemplates>
          <DataTemplate>
            <ss:V_LIST_ITEM_Char DataContext="{Binding}"/>
          </DataTemplate>
        </ItemsControl.DataTemplates>
      </ItemsControl>
    </ScrollViewer>
    
    <Button Grid.Row="1" Content="+" Command="{Binding ActiveViewModel.AddChar}"
            Width="50" Height="50" FontSize="50" Padding="0 -40" Margin="10">
      <Button.Styles>
        <Style Selector="Button">
          <Setter Property="Background" Value="CornflowerBlue"/>
          <Setter Property="Foreground" Value="White"/>
        </Style>
        <Style Selector="Button /template/ ContentPresenter">
          <Setter Property="CornerRadius" Value="50"/>
        </Style>
      </Button.Styles>
    </Button>
  </Grid>
  
</UserControl>
```

VM_LIST_Char
```cs
class VM_LIST_Char : VM_Base
{
    public VM_LIST_Char()
    { 
        Characters = new ObservableCollection<Character>();
    }

    public ObservableCollection<Character> Characters { get; set; }

    void AddChar()
    {
        Characters.Add(new Character("New Character"));
    }
}
```

Character
```cs
class Character : M_Base
{
    public Character(string name)
    {
        Name = name;
    }
    public string Name { get; set; }
}
```

V_LIST_ITEM_Char.axaml
```xaml
<UserControl xmlns="https://github.com/avaloniaui"
             x:Class="SwiftSheet.V_LIST_ITEM_Char">
  
  <Grid ColumnDefinitions="* Auto">
    
    <StackPanel Grid.Column="0">
      <TextBlock Text="{Binding Name}"/>
    </StackPanel>

    <Button Grid.Column="1" Content="Edit"/>
  </Grid>
  
</UserControl>
```

These are the relevant axaml structures and classes.
I use FODY to implement INotifyPropeprty.

The Button in V_LIST_Char adds a new Item to Characters in VM_LIST_Char
When the object gets represented in the ItemsControl in V_LIST_Char the Application crashes with the StackOverflow Exception.
When i remove the Button from V_LIST_ITEM_Char however, the application does NOT crash despite nothing else changing.

The exact same behavior can also be observed when I replace the ItemsControl with a ListBox.

**Comment by donandren** [comment] 2020-12-17 21:55
try `ItemTemplate ` instead `DataTemplates`
```xaml
        <ItemsControl.ItemTemplate>
          <DataTemplate>
            <ss:V_LIST_ITEM_Char DataContext="{Binding}"/>
          </DataTemplate>
        </ItemsControl.ItemTemplate>
```

**Comment by xormak** [comment] 2020-12-17 22:45
> try `ItemTemplate ` instead `DataTemplates`
> 
> ```
>         <ItemsControl.ItemTemplate>
>           <DataTemplate>
>             <ss:V_LIST_ITEM_Char DataContext="{Binding}"/>
>           </DataTemplate>
>         </ItemsControl.ItemTemplate>
> ```

Huh. Yea that seems to fix the issue for now. 
Seems like a weird behavior though.

Could still be worth checking out for someone that understands what happens there? Especially coming from more standard WPF this seems not very intuitive. Not necessarily headache inducing but weird nonetheless.

But thank you!

**Comment by maxkatz6** [comment] 2020-12-17 23:26
> Seems like a weird behavior though.

DataTemplates is kinda dangerous here without providing x:DataType, because it will be applied for inner content presenters. In your case it is applied recursively that caused StackOverflow. 

@grokys @kekekeks can we make x:DataType required for DataTemplates? Or at least add some logger warning.

**Comment by grokys** [comment] 2020-12-18 15:42
@maxkatz6 do you mean `DataType` (not `x:DataType` - that's for compiled bindings)?

If so I think that's https://github.com/AvaloniaUI/Avalonia/issues/724. Last time I looked at it (6 years ago!) it wasn't possible, but may now be possible.

**Comment by grokys** [comment] 2020-12-18 15:44
> Especially coming from more standard WPF

WPF doesn't have `DataTemplates` - it only has `ItemTemplate`.

**Comment by xormak** [comment] 2020-12-18 16:57
> > Especially coming from more standard WPF
> 
> WPF doesn't have `DataTemplates` - it only has `ItemTemplate`, so our syntax is identical to WPF.

Then my memory is all mixed up already, my bad. 

> DataTemplates is kinda dangerous here without providing x:DataType, because it will be applied for inner content presenters. In your case it is applied recursively that caused StackOverflow.

I see! That makes sense, thank you!

And defining a DataTemplate without DataType is very much possible. Might make sense to include warnings or to make it required. 

Still a little bit confused why it only happens when i add a button to the templated item but for now I'll just keep the info i got here in mind!

**Comment by acaly** [comment] 2020-12-20 04:33
I ran into exactly the same issue some time ago.

> Still a little bit confused why it only happens when i add a button to the templated item

Because button internally uses a ```ContentPresenter```, which finds ```DataTemplate```s from its parent controls for its content (typically a string). Because there is no other template defined nearby for ```string```, it would instantiate the entire template and use them as its content. The content then contains a new instance of the same button, which infinitely create the same template again and again.

I would rather prefer changing the behavior of ```DataTemplate``` to match nothing if no type is provided (which actually makes sense), because this mistake is so easy to make.

**Comment by lordzomat** [comment] 2020-12-23 15:19
I tried to upgrade my program to `0.10.0-rc1` and also got an `StackOverflowException` on my TreeView which is loaded dynamically.

This is my XAML:
```
<TreeView x:Name="NavigationTreeView" Grid.Row="0" Grid.Column="0" Items="{Binding TreeNodes}">
	<TreeView.DataTemplates>
		<TreeDataTemplate DataType="models:TreeNode" ItemsSource="{Binding Nodes}">
			<StackPanel Orientation="Horizontal">
				<StackPanel.ContextMenu>
					<ContextMenu IsVisible="{Binding IsRootNode}">
						<MenuItem Header="Remove"></MenuItem>
					</ContextMenu>
				</StackPanel.ContextMenu>
				<Image Source="{Binding Image}"/>
				<TextBlock Margin="5,0,0,0" Foreground="Black" Text="{Binding DisplayName}"/>
				<TextBlock Margin="10,0,0,0" Foreground="Gray" Text="{Binding SizeDisplayValue, StringFormat='({0})'}" HorizontalAlignment="Right"/>
			</StackPanel>
		</TreeDataTemplate>
	</TreeView.DataTemplates>
</TreeView>
```

I already did a test by replacing `<TreeView.DataTemplates>` with `<TreeView.ItemTemplate>` but the error persists.

**Comment by maxkatz6** [comment] 2022-05-26 04:27
Initial problem was caused by #5726 and #724, so closing this one as a duplicate.

If there are still problems with a tree view, please open a new issue.

**Closed by maxkatz6** 2022-05-26 04:27 UTC
