### ISSUE TITLE
Deffered Renderer broken on Hi DPI monitors

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#1918] opened 2018-09-24 23:50 UTC
https://i.imgur.com/JpXDFCh.png

@kekekeks knows more.

**Comment by nc4rrillo** [comment] 2018-09-25 13:58
Is this a recent regression?

**Comment by jmacato** [comment] 2018-09-25 13:59
@nc4rrillo seems to be after the unify timers PR merge

**Comment by danwalmsley** [comment] 2018-09-25 14:01
@jmacato did you manage to repro on linix, set scaling = 2 causes it, and resize window to trigger.

**Comment by jmacato** [comment] 2018-09-25 14:10
Yep i can repro, maximizing it then restore triggers the bug
![screenshot from 2018-09-25 22-08-08](https://user-images.githubusercontent.com/16554748/46019914-b5965a80-c10f-11e8-98b5-22daa6392ae4.png)

**Comment by KvanTTT** [comment] 2018-09-30 06:57
Maybe related issue: https://github.com/AvaloniaUI/Avalonia/issues/1890

**Comment by grokys** [comment] 2018-10-09 20:40
I can't repro this on Windows. Is it a Linux/Mac-only bug or am I missing something?

**Comment by danwalmsley** [comment] 2018-10-10 13:37
after finding issues with scaling and fixing on win32, was still unable to repo on windows, so I guess this has to be something specific to Linux / mac backends

**Comment by grokys** [comment] 2018-10-24 07:42
Managed to repro this on win32 after applying #2010. It seems to be a skia issue as it doesn't occur when using D2D backend.

**Comment by kekekeks** [comment] 2019-01-15 10:37
This should be fixed by https://github.com/AvaloniaUI/Avalonia/pull/2011/commits/37c65262ac1db3f2cf89669253a44639adcd03fe in X11 backend PR.

Please, check using `0.7.1-build1179-beta` build from [PR feed](https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed#pr-feed)

**Closed** 2019-03-02 00:23 UTC
Labels: bug, rendering
