### ISSUE TITLE
ListBoxItems have a second parent

### ISSUE THREAD

**Issue by ArchLeaders** [AvaloniaUI/Avalonia#9344] opened 2022-11-03 00:03 UTC
**Describe the bug**
ListBoxItems that are hidden when the ListBox is initialized have a second ListBoxItem parent (see screenshot)

Other behaviors include freezing when scrolling _back up_ or throwing `System.InvalidOperationException: 'The control already has a visual parent.'` in the application startup root (`Program.cs:Main()`) when the broken items are revealed.

**To Reproduce**

1. Create a new Avalonia Desktop project
2. Add a `ListBox` to `MainWindow.axaml`
3. Set the `ListBox` height to `500`
4. Add enough `ListBoxItems` with any `Content` to make the `ListBox` scrollable.

**Expected behavior**
The `ListBox.Items` should remain consistent when scrolling and no errors/freezing should occur while scrolling.

**Screenshots**
<img width="500" src="https://user-images.githubusercontent.com/80713508/199623641-d41cfe5a-7daf-4db2-b8bb-a16b6f251963.png">

**Desktop (please complete the following information):**

- OS: Windows 10 Home x64
- Version: `19043.2130`

**Additional context**
This problem occurred in `0.10.18` and `avalonia11-preview3`, no other versions were explicitly tested for this issue.

**Comment by maxkatz6** [comment] 2022-11-03 02:22
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/4265#issuecomment-797222259
You can find a workaround there too

**Closed by maxkatz6** 2022-11-03 02:22 UTC
Labels: bug

**Comment by ArchLeaders** [comment] 2022-11-03 02:43
Oh my bad. Thanks.
