### ISSUE TITLE
Avalonia Bind Error

### ISSUE THREAD

**Issue by DenisT90** [AvaloniaUI/Avalonia#9219] opened 2022-10-18 06:08 UTC
**Describe the bug**
Bind error

**To Reproduce**

1. Start desktop project
2. See errors

**Expected behavior**
We expected that there would be no errors

**Desktop (please complete the following information):**
- OS: Windows
- Version 11.0.0-preview2

**Additional context**
You can see an example here:
https://github.com/DenisT90/AvaloniaBindError 

example errors:
[Binding]Error in binding to '{ {M11:1 M12:0} {M21:0 M22:1} {M31:0 M32:0} }'.'ScaleX': 'Null value in expression '{empty}' at ''.'(ScaleTransform #47145209)
[Binding]Error in binding to '{ {M11:1 M12:0} {M21:0 M22:1} {M31:0 M32:0} }'.'ScaleY': 'Null value in expression '{empty}' at ''.'(ScaleTransform #47145209)
[Binding]Error in binding to 'Avalonia.Animation.Animation'.'IterationCount': 'Null value in expression '{empty}' at ''.'(Animation #4152081)

**Comment by maxkatz6** [comment] 2022-10-18 06:41
Same issue
https://github.com/AvaloniaUI/Avalonia/issues/9218
https://github.com/AvaloniaUI/Avalonia/issues/8100
https://github.com/AvaloniaUI/Avalonia/issues/5762
https://github.com/AvaloniaUI/Avalonia/issues/5163

**Comment by maxkatz6** [comment] 2023-01-28 01:41
Duplicate of #5762

**Closed by maxkatz6** 2023-01-28 01:41 UTC
Labels: bug
