### ISSUE TITLE
Android application crashes if left for 2-3 hours

### ISSUE THREAD

**Issue by chris835** [AvaloniaUI/Avalonia#9038] opened 2022-09-27 19:55 UTC
**Describe the bug**
A blank Avalonia application running on Android crashes after about 2-3 hours.

**To Reproduce**
Create an application using "dotnet new avalonia.xplat" and deploy to an android device. Set it up to not go to sleep. Wait a few hours and poof the app will be gone.

**Expected behavior**
The application should keep running indefinitely.

- OS: Tested on a Samsung Galaxy Tab A7 Lite with android 12 + x64 android emulator with API level 30
- 11.0.0-preview1

**Additional context**
[logcat-1.txt](https://github.com/AvaloniaUI/Avalonia/files/9659198/logcat-1.txt)

**Comment by chris835** [comment] 2022-10-05 19:46
Update: Initial testing seems to indicate the bug is not present in 0.10.999-cibuild0022654-beta.

**Comment by Adam--** [comment] 2023-11-06 21:16
I'm not with the Avalonia team, but have an interest in running an Avalonia application in an always on kiosk style state so I thought I'd try to reproduce your issue.

I was **unable** to reproduce this issue on an ARM32 device with Android 7.1 using Visual Studio 17.7.2 (Windows) with Xamarin.Android SDK 13.2.1.2 (Mono d9a6e87). I created a new application using the templates and changed the View/ViewModel to show the time with 1 second updates just so I could see that it was still updating and not frozen. I ran this app for 7 hours.

This of course isn't any proof that the issue is no longer there, just that it didn't crash for me with my setup this one instance. I'm careful with saying this because we've had crashes like this with Xamarin Forms (monoandroid) after running many days on some devices intermittently.

**Comment by maxkatz6** [comment] 2023-11-07 00:22
@Adam-- thank you for your feedback!

I am going to close this issue, as it hasn't reproduce since. And our android backend had lots of changes after first preview.

**Closed by maxkatz6** 2023-11-07 00:22 UTC
Labels: bug, os-android

**Comment by Adam--** [comment] 2023-11-07 02:00
Certainly. That original issue does appear to be monoandroid related rather than Avalonia related. 

For what it's worth, my test app did end up crashing after 9 hours and 45 minutes. The only thing I see in the logs are it complaining about being low on memory minutes prior to the crash. I can put in a separate issue for that though.

```
11-06 18:42:07.042   497 24215 I ActivityManager: Low on memory:
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     8559: surfaceflinger (pid 218) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     4129: zygote (pid 222) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     3888: media.codec (pid 229) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     2697: logd (pid 191) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     2358: audioserver (pid 224) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     2095: mediaserver (pid 232) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     1970: media.extractor (pid 231) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     1517: mediadrmserver (pid 230) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     1345: cameraserver (pid 225) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     1231: sdcard (pid 590) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     1114: drmserver (pid 226) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     1062: vold (pid 201) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     1007: wpa_supplicant (pid 663) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N      922: netd (pid 233) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N      719: /init (pid 1) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N      673: keystore (pid 228) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N      645: adbd (pid 220) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N      583: gatekeeperd (pid 236) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N      555: lmkd (pid 216) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N      538: installd (pid 227) native
11-06 18:42:07.043   497 24215 I ActivityManager:   ntv   N     3033: (Other native)
11-06 18:42:07.044   497 24215 I ActivityManager:   sys   P    37677: system (pid 497) fixed
11-06 18:42:07.044   497 24215 I ActivityManager:   pers  P    20258: com.android.systemui (pid 582) fixed
11-06 18:42:07.044   497 24215 I ActivityManager:   fore  T   846545: com.CompanyName.AvaloniaTest (pid 6218) top-activity
11-06 18:42:07.044   497 24215 I ActivityManager:   fore  IB   17009: com.android.inputmethod.latin (pid 22669) service
11-06 18:42:07.044   497 24215 I ActivityManager:                        com.android.inputmethod.latin/.LatinIME<=Proc{497:system/1000}
11-06 18:42:07.044   497 24215 I ActivityManager:             962129: TOTAL
11-06 18:42:07.044   497 24215 I ActivityManager:   MemInfo:    27,324K slab,       832K shmem,     7,088K vm alloc,    10,852K page tables     2,752K kernel stack
11-06 18:42:07.044   497 24215 I ActivityManager:                  180K buffers,    97,344K cached,    49,372K mapped,    20,692K free
11-06 18:42:07.044   497 24215 I ActivityManager:   ZRAM:    71,280K RAM,   307,196K swap total,         0K swap free
11-06 18:42:07.044   497 24215 I ActivityManager:   Free RAM:    68,844K
11-06 18:42:07.044   497 24215 I ActivityManager:   Used RAM: 1,010,977K
11-06 18:42:07.044   497 24215 I ActivityManager:   Lost RAM:  -132,929K
```
...


```
11-06 18:47:18.404   497 19491 I ActivityManager: Low on memory:
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     8615: surfaceflinger (pid 218) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     7229: zygote (pid 222) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     3890: media.codec (pid 229) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     2920: logd (pid 191) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     2359: audioserver (pid 224) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     2092: mediaserver (pid 232) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     1968: media.extractor (pid 231) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     1518: mediadrmserver (pid 230) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     1344: cameraserver (pid 225) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     1232: sdcard (pid 590) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     1114: drmserver (pid 226) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     1071: vold (pid 201) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     1011: wpa_supplicant (pid 663) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N      916: netd (pid 233) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N      719: /init (pid 1) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N      674: keystore (pid 228) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N      645: adbd (pid 220) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N      583: gatekeeperd (pid 236) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N      560: lmkd (pid 216) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N      539: installd (pid 227) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N      525: servicemanager (pid 217) native
11-06 18:47:18.404   497 19491 I ActivityManager:   ntv   N     2573: (Other native)
11-06 18:47:18.404   497 19491 I ActivityManager:   sys   P    44444: system (pid 497) fixed
11-06 18:47:18.404   497 19491 I ActivityManager:   pers  P    20196: com.android.systemui (pid 582) fixed
11-06 18:47:18.404   497 19491 I ActivityManager:   fore  T   855623: com.CompanyName.AvaloniaTest (pid 6218) top-activity
11-06 18:47:18.404   497 19491 I ActivityManager:             964360: TOTAL
11-06 18:47:18.405   497 19491 I ActivityManager:   MemInfo:    27,428K slab,       832K shmem,     7,088K vm alloc,    10,184K page tables     2,728K kernel stack
11-06 18:47:18.405   497 19491 I ActivityManager:                  180K buffers,    95,108K cached,    51,576K mapped,    19,460K free
11-06 18:47:18.405   497 19491 I ActivityManager:   ZRAM:    71,280K RAM,   307,196K swap total,         0K swap free
11-06 18:47:18.405   497 19491 I ActivityManager:   Free RAM:    63,172K
11-06 18:47:18.405   497 19491 I ActivityManager:   Used RAM: 1,012,620K
11-06 18:47:18.405   497 19491 I ActivityManager:   Lost RAM:  -128,900K
```
...
```
11-06 18:50:44.983   497   508 W ActivityManager: Slow operation: 130ms so far, now at getContentProviderImpl: after start process
11-06 18:50:44.983   497   508 W ActivityManager: Slow operation: 130ms so far, now at getContentProviderImpl: updating data structures
11-06 18:50:44.983   497   508 W ActivityManager: Slow operation: 130ms so far, now at getContentProviderImpl: done!
11-06 18:50:45.179 12880 12880 W System  : ClassLoader referenced unknown path: /system/priv-app/ExtServices/lib/arm
11-06 18:50:45.210   497   664 I WindowManager: WIN DEATH: Window{4dc1274 u0 SurfaceView - com.CompanyName.AvaloniaTest/crc64113b608fdc6f371c.MainActivity}
11-06 18:50:45.211   497  6121 D GraphicsStats: Buffer count: 1
11-06 18:50:45.219   497   739 I ActivityManager: Process com.CompanyName.AvaloniaTest (pid 6218) has died
11-06 18:50:45.219   497   739 D ActivityManager: cleanUpApplicationRecord -- 6218
11-06 18:50:45.220   497   739 W ActivityManager: Force removing ActivityRecord{b8ba863 u0 com.CompanyName.AvaloniaTest/crc64113b608fdc6f371c.MainActivity t70}: app died, no saved state
11-06 18:50:45.227   497   541 W InputDispatcher: channel '27296cb com.CompanyName.AvaloniaTest/crc64113b608fdc6f371c.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-06 18:50:45.227   497   541 E InputDispatcher: channel '27296cb com.CompanyName.AvaloniaTest/crc64113b608fdc6f371c.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-06 18:50:45.291   497 16860 I WindowManager: WIN DEATH: Window{27296cb u0 com.CompanyName.AvaloniaTest/crc64113b608fdc6f371c.MainActivity}
11-06 18:50:45.292   497 16860 W InputDispatcher: Attempted to unregister already unregistered input channel '27296cb com.CompanyName.AvaloniaTest/crc64113b608fdc6f371c.MainActivity (server)'
11-06 18:50:45.327 13208 13208 W System  : ClassLoader referenced unknown path: /system/priv-app/ContactsProvider/lib/arm
11-06 18:50:45.334   497   739 W art     : Long monitor contention with owner Binder:497_4 (664) at void com.android.server.wm.WindowState$DeathRecipient.binderDied()(WindowState.java:1799) waiters=2 in void com.android.server.wm.WindowManagerService.notifyAppRelaunchesCleared(android.os.IBinder) for 112ms
```

**Comment by Adam--** [comment] 2023-11-10 13:45
Quick follow up. I ran my sample in release for 2 days with 2 textblocks updating every 100 ms. It has not crashed. The previous run was in debug with the debugger detached, which probably isn't a fair test.
