### ISSUE TITLE
Styles not working properly

### ISSUE THREAD

**Issue by YWilix** [AvaloniaUI/Avalonia#11923] opened 2023-06-27 18:14 UTC
I have these styles in my project for a pause button but they are not working properly 
```xaml
    <Style Selector="Button.PauseButton:not(.Paused)">
      <Setter Property="Width" Value="20"/>
      <Setter Property="Height" Value="25"/>
      <Setter Property="Background">
        <ImageBrush Source="avares://Speedy/Designs/Icons/ContinuedIcon.png"/>
      </Setter>
      <Setter Property="OpacityMask">
        <ImageBrush Source="avares://Speedy/Designs/Icons/ContinuedIcon.png"/>
      </Setter>
    </Style>

    <Style Selector="Button.PauseButton:disabled:not(.Paused) /template/ ContentPresenter#PART_ContentPresenter">
      <Setter Property="Background">
        <ImageBrush Source="avares://Speedy/Designs/Icons/ContinuedIcon.png"/>
      </Setter>
      <Setter Property="OpacityMask">
        <ImageBrush Source="avares://Speedy/Designs/Icons/ContinuedIcon.png"/>
      </Setter>
      <Setter Property="Opacity" Value="0.8"/>
    </Style>
    
    <Style Selector="Button.PauseButton:pointerover:not(.Paused) /template/ ContentPresenter#PART_ContentPresenter">
      <Setter Property="Background">
        <ImageBrush Source="avares://Speedy/Designs/Icons/ContinuedIcon.png"/>
      </Setter>
      <Setter Property="OpacityMask">
        <ImageBrush Source="avares://Speedy/Designs/Icons/ContinuedIcon.png"/>
      </Setter>
      <Setter Property="Opacity" Value="0.87"/>
    </Style>

    <Style Selector="Button.PauseButton.Paused" >
      <Setter Property="Width" Value="20"/>
      <Setter Property="Height" Value="25"/>
      <Setter Property="Background">
        <ImageBrush Source="avares://Speedy/Designs/Icons/StoppedIcon.png"/>
      </Setter>
      <Setter Property="OpacityMask">
        <ImageBrush Source="avares://Speedy/Designs/Icons/StoppedIcon.png"/>
      </Setter>
    </Style>

    <Style Selector="Button.PauseButton.Paused:pointerover /template/ ContentPresenter#PART_ContentPresenter">
      <Setter Property="Background">
        <ImageBrush Source="avares://Speedy/Designs/Icons/StoppedIcon.png"/>
      </Setter>
      <Setter Property="OpacityMask">
        <ImageBrush Source="avares://Speedy/Designs/Icons/StoppedIcon.png"/>
      </Setter>
      <Setter Property="Opacity" Value="0.87"/>
    </Style>

    <Style Selector="Button.PauseButton.Paused:disabled /template/ ContentPresenter#PART_ContentPresenter">
      <Setter Property="Background">
        <ImageBrush Source="avares://Speedy/Designs/Icons/StoppedIcon.png"/>
      </Setter>
      <Setter Property="OpacityMask">
        <ImageBrush Source="avares://Speedy/Designs/Icons/StoppedIcon.png"/>
      </Setter>
      <Setter Property="Opacity" Value="0.8"/>
    </Style>
```

### this is the buttons code :

```xaml
<Button Name="PauseButton" Classes.Paused="{Binding IsPaused}" Classes="PauseButton" IsEnabled="{Binding IsCopyingFiles}" Click="PauseButtonClicked"/>
```

### and these are the icons : 

**StoppedIcon.png :** 

![StoppedIcon](https://github.com/AvaloniaUI/Avalonia/assets/87858497/6eb23df1-434f-4dc1-ae4d-183d544049b1)

**ContinuedIcon.png :**

![ContinuedIcon](https://github.com/AvaloniaUI/Avalonia/assets/87858497/fcd41a35-6424-4621-ac86-494cb144f09b)

when I change the IsPaused and IsCopyingFiles Properties inside the window constructor the styles functions properly but when I change them inside an event handler for a button this happens 

![image](https://github.com/AvaloniaUI/Avalonia/assets/87858497/02ad0861-9786-40af-90fd-83c7bdfbfdee)

**this is what the event handler contains :**

```csharp
        _DataContext.IsCopyingFiles = true;
        _DataContext.IsPaused = false;
```

**Comment by maxkatz6** [comment] 2023-06-27 21:05
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/10917. OpacityMask doesn't call control.InvalidateVisual() on changing its contents

**Closed by maxkatz6** 2023-06-27 21:05 UTC
Labels: bug
