### ISSUE TITLE
DataGrid cell double-click to edit not working - Avalonia 11.0.6

### ISSUE THREAD

**Issue by alexandrehtrb** [AvaloniaUI/Avalonia#13928] opened 2023-12-12 20:16 UTC
With Avalonia 11.0.6, double-click to edit on a DataGrid text cell does not work. The cell does not enter into edition mode.

If Avalonia 11.0.5 is used, everything works as expected.

Tested with Windows 11 and .NET 8.

**Comment by jp2masa** [comment] 2023-12-12 21:14
Duplicate of #13843?

**Closed** 2023-12-12 22:48 UTC
Labels: bug
