### ISSUE TITLE
Log warnings for ListBoxes IsScrollInertiaEnabled in 11.0.0-preview7

### ISSUE THREAD

**Issue by llfab** [AvaloniaUI/Avalonia#11241] opened 2023-05-04 21:11 UTC
**Describe the bug**
For all ListBoxes a log warning appears as follows:
```Error in binding to 'Avalonia.Input.GestureRecognizers.ScrollGestureRecognizer'.'IsScrollInertiaEnabled': 'Null value in expression '{empty}' at '$self.TemplatedParent'.'(ScrollGestureRecognizer #59952436)```

**To Reproduce**
Use ListBoxes with scrolling enabled

**Expected behavior**
There should be no warning like in 11.0.0-preview6

**Desktop (please complete the following information):**

- OS:  Windows 10
- Version: 11.0.0-preview7

**Comment by llfab** [comment] 2023-05-04 21:37
This is where the log comes from:
![image](https://user-images.githubusercontent.com/31031996/236335496-1634cbf7-474d-4711-8212-7c50c5acc81a.png)

**Comment by llfab** [comment] 2023-05-04 22:32
Also happens in ControlCatalog:
![image](https://user-images.githubusercontent.com/31031996/236343360-7839d207-f311-4218-a6dc-ca53016f8f4b.png)

Seems like normal behavior but optimally you do not want warnings from your framework when everything is kind of normal.

**Comment by jp2masa** [comment] 2023-05-04 22:39
Duplicate of #11148?

**Comment by grokys** [comment] 2023-05-05 21:08
Yeah looks like a duplicate, closing this issue, let's continue in #11148

**Closed** 2023-05-05 21:08 UTC
Labels: bug
