### ISSUE TITLE
ThemeDictionaries not using Dark by default

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#10403] opened 2023-02-20 02:35 UTC
I'm using the new ThemeDictionaries to set Light/Dark colors.

If I run that in a sample project, defined with `<FluentTheme />`, it automatically starts as Dark, but takes resources `Default` instead of `Dark`

```xaml
<ResourceDictionary>
  <ResourceDictionary.ThemeDictionaries>
    <ResourceDictionary x:Key="Default">
      <Color x:Key="UniqueColor">Red</Color>
      <SolidColorBrush x:Key="UniqueColorBrush" Color="{StaticResource UniqueColor}" />
    </ResourceDictionary>
    <ResourceDictionary x:Key="Dark">
      <Color x:Key="UniqueColor">Blue</Color>
      <SolidColorBrush x:Key="UniqueColorBrush" Color="{StaticResource UniqueColor}" />
    </ResourceDictionary>
  </ResourceDictionary.ThemeDictionaries>
</ResourceDictionary>
```

Avalonia11-preview5
OS: Garuda Linux

**Comment by maxkatz6** [comment] 2023-02-20 04:36
Can you add some details? Minimal project to reproduce?
This code should work.

**Comment by mysteryx93** [comment] 2023-02-20 05:50
Can you take MediaPlayerUI and run the sample project?
https://github.com/mysteryx93/MediaPlayerUI.NET

**Comment by mysteryx93** [comment] 2023-02-21 05:04
I did further testing. Made interesting discoveries.

Reproducing in `App.axaml` in a simple project.

This works.
```xaml
<ResourceDictionary.ThemeDictionaries>
    <ResourceDictionary x:Key="Default">
        <Color x:Key="StartColor">#FFE6E6E6</Color>
        <Color x:Key="EndColor">#FFA4A4A4</Color>
        <SolidColorBrush x:Key="UniqueColorBrush" Color="{StaticResource StartColor}" />
    </ResourceDictionary>
    <ResourceDictionary x:Key="Dark">
        <Color x:Key="StartColor">#878787</Color>
        <Color x:Key="EndColor">#D7373737</Color>
        <SolidColorBrush x:Key="UniqueColorBrush" Color="{StaticResource StartColor}" />
    </ResourceDictionary>
</ResourceDictionary.ThemeDictionaries>
```

This does not work
```xaml
<ResourceDictionary.ThemeDictionaries>
    <ResourceDictionary x:Key="Default">
        <Color x:Key="StartColor">#FFE6E6E6</Color>
        <Color x:Key="EndColor">#FFA4A4A4</Color>
    </ResourceDictionary>
    <ResourceDictionary x:Key="Dark">
        <Color x:Key="StartColor">#878787</Color>
        <Color x:Key="EndColor">#D7373737</Color>
    </ResourceDictionary>
</ResourceDictionary.ThemeDictionaries>
<SolidColorBrush x:Key="UniqueColorBrush" Color="{StaticResource StartColor}" />
```

This does not work either.
```xaml
<ResourceDictionary.ThemeDictionaries>
    <ResourceDictionary x:Key="Default">
        <Color x:Key="StartColor">#FFE6E6E6</Color>
        <Color x:Key="EndColor">#FFA4A4A4</Color>
        <LinearGradientBrush x:Key="UniqueColorBrush" EndPoint="50%,100%" StartPoint="50%,0%">
            <GradientStop Color="{DynamicResource StartColor}" Offset="0" />
            <GradientStop Color="{DynamicResource EndColor}" Offset="1" />
        </LinearGradientBrush>
    </ResourceDictionary>
    <ResourceDictionary x:Key="Dark">
        <Color x:Key="StartColor">#878787</Color>
        <Color x:Key="EndColor">#D7373737</Color>
        <LinearGradientBrush x:Key="UniqueColorBrush" EndPoint="50%,100%" StartPoint="50%,0%">
            <GradientStop Color="{DynamicResource StartColor}" Offset="0" />
            <GradientStop Color="{DynamicResource EndColor}" Offset="1" />
        </LinearGradientBrush>
    </ResourceDictionary>
</ResourceDictionary.ThemeDictionaries>
```

To reproduce, copy/paste those snippets into App.axaml and display it in your view

```xaml
<TextBlock Text="{Binding Greeting}" HorizontalAlignment="Center" VerticalAlignment="Center"
               Foreground="{DynamicResource UniqueColorBrush}" FontSize="42" />
```

**Comment by maxkatz6** [comment] 2023-02-21 05:16
> This does not work

This one is expected. UniqueColorBrush doesn't have any information about current theme to choose.
How to fix: define UniqueColorBrush inside of the dictionaries.

> This does not work either.

This one will work with StaticResource, I think. Without any feature drawbacks, as it doesn't need to be dynamic, when expected color will be always there.
But I will check why it doesn't work with DynamicResource.

**Comment by mysteryx93** [comment] 2023-02-21 05:35
It works with StaticResource.

It is annoying to have to repeat the brushes twice though.

**Comment by maxkatz6** [comment] 2023-02-21 08:03
@mysteryx93 weirdly, I can't reproduce this bug with dynamic resource:
```csharp
[Fact]
public void _10403()
{
    // See https://github.com/AvaloniaUI/Avalonia/issues/10403
    var themeVariantScope = (ThemeVariantScope)AvaloniaRuntimeXamlLoader.Load(@"
<ThemeVariantScope xmlns='https://github.com/avaloniaui'
                   xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'>
    <ThemeVariantScope.Resources>
        <ResourceDictionary>                
            <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key='Default'>
                    <Color x:Key='StartColor'>#FFE6E6E6</Color>
                    <Color x:Key='EndColor'>#FFA4A4A4</Color>
                    <LinearGradientBrush x:Key='UniqueColorBrush' EndPoint='50%,100%' StartPoint='50%,0%'>
                        <GradientStop Color='{DynamicResource StartColor}' Offset='0' />
                        <GradientStop Color='{DynamicResource EndColor}' Offset='1' />
                    </LinearGradientBrush>
                </ResourceDictionary>
                <ResourceDictionary x:Key='Dark'>
                    <Color x:Key='StartColor'>#878787</Color>
                    <Color x:Key='EndColor'>#D7373737</Color>
                    <LinearGradientBrush x:Key='UniqueColorBrush' EndPoint='50%,100%' StartPoint='50%,0%'>
                        <GradientStop Color='{DynamicResource StartColor}' Offset='0' />
                        <GradientStop Color='{DynamicResource EndColor}' Offset='1' />
                    </LinearGradientBrush>
                </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>
        </ResourceDictionary>
    </ThemeVariantScope.Resources> 
    <Border Background='{DynamicResource UniqueColorBrush}' />
</ThemeVariantScope>");
    var border = (Border)themeVariantScope.Child!;

    themeVariantScope.RequestedThemeVariant = ThemeVariant.Light;
    Assert.Equal(Color.Parse("#FFE6E6E6"), ((ILinearGradientBrush)border.Background)!.GradientStops[0].Color);
    
    themeVariantScope.RequestedThemeVariant = ThemeVariant.Dark;
    Assert.Equal(Color.Parse("#878787"), ((ILinearGradientBrush)border.Background)!.GradientStops[0].Color);
}
```

**Comment by maxkatz6** [comment] 2023-02-21 08:09
Ah, I see now. It works in unit tests, because theming isn't broken here.
What is broken - renderer invalidation. 

I will close it as a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/8266 (same issue with GradientStop not updating on UI).
Hopefully https://github.com/AvaloniaUI/Avalonia/pull/8896 will cover it or composition renderer will handle brushes (which is planned, but probably not in 11.0).

**Closed by maxkatz6** 2023-02-21 08:09 UTC
Labels: bug, needs-repro
