### ISSUE TITLE
Binding Drop Down to List<string> produces drop down full of "System.String"

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#623] opened 2016-07-29 08:18 UTC
Also if you put in a datatemplate. with a textblock.

then you get what I would have expected to be default behaviour, but then the selected item (when drop down is closed) says "System.String"

**Comment by danwalmsley** [comment] 2016-07-29 08:19
Probably same as #605

**Comment by grokys** [comment] 2016-07-29 16:54
I'm unable to repro this. Steps taken in ControlCatalog to repro:

- Add `this.DataContext = new[] { "Foo", "Bar", "Baz" };` to `DropDownPage.cs`
- Add `<DropDown Items="{Binding}"/>` to DropDownPage.xaml

Result is:

![image](https://cloud.githubusercontent.com/assets/1775141/17256437/d2a125fc-55bd-11e6-8001-a100b1ea459a.png)

I'll need a more detailed repro.

**Comment by danwalmsley** [comment] 2016-07-31 21:52
![image](https://cloud.githubusercontent.com/assets/4672627/17279647/8343a3a8-5771-11e6-8265-fe1c41e5a970.png)

**Comment by danwalmsley** [comment] 2016-07-31 21:54
Just re-tested, and still getting this

Code looks like this:
```
<DropDown Grid.Column="3" Padding="0" Margin="0 1" Items="{Binding ColumnOptions}" SelectedIndex="{Binding SelectedColumnIndex, Mode=TwoWay}"/>

private int[] ColumnSettings = { 1, 2, 4, 8, 16, 32, 64 };

        public List<string> ColumnOptions => ColumnSettings.ToList().ConvertAll(delegate (int i) { return i.ToString(); });
```

**Comment by danwalmsley** [comment] 2016-07-31 21:54
Perhaps it has to do with being in a separate assembly.

**Comment by grokys** [comment] 2016-08-02 23:53
Could you try to create a simple repro? It shouldn't be that hard I imagine. I don't know how to get to that view in AvalonStudio.

**Comment by x2bool** [comment] 2016-11-20 07:29
I have the same issue except it's the other way around:

![image](https://cloud.githubusercontent.com/assets/892945/20461321/4bb31116-af0b-11e6-8716-2ef89826936e.png)

```
public class TopMenuItem
{
    public string Title { get; set; }
}
```

 ```
TopMenuItems = new List<TopMenuItem>()
                {
                    new TopMenuItem { Title = "Home" },
                    new TopMenuItem { Title = "Test" }
                };
```

```
<DropDown
        Items="{Binding TopMenuItems}"
        SelectedItem="{Binding SelectedTopMenuItem}"
        Height="50"
        VerticalAlignment="Center">
        
        <DropDown.ItemTemplate>
          <DataTemplate>
            <StackPanel>
              <TextBlock Text="{Binding Title}" FontSize="18" />
            </StackPanel>
          </DataTemplate>
        </DropDown.ItemTemplate>
        
      </DropDown>
```

**Comment by danwalmsley** [comment] 2016-11-20 12:01
@x2bool can you confirm if you are on the nightly nuget package?

https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

**Comment by x2bool** [comment] 2016-11-25 19:13
@danwalmsley No. I am on the stable package. Is this fixed on the nightly build?

**Comment by danwalmsley** [comment] 2016-11-28 11:08
@x2bool it might be! I don't have time to check! but the stable feed is a very long way behind.

We are looking to do a new release soon I believe.

**Comment by milkinllc** [comment] 2017-01-09 22:04
Looks like the issue is in MemberSelector utilization when binding to the list of mutable POCOs. Overriding ToString() on POCO or make them immutable would make a hack. I am using current nightly and problem still exists.

**Comment by jkoritzinsky** [comment] 2017-10-18 22:01
I'm going to close this. We can re-open if anyone can find a small repro for this.

@milkinllc can you write a unit test or minimal repro for this? If you can, we'll re-open the issue.

**Closed by jkoritzinsky** 2017-10-18 22:01 UTC
Labels: bug, needs-repro

**Comment by LorenVeri** [comment] 2022-09-10 04:37
If I binding list object, how to get item in list when click text-block? 
ListDateTime = new List<DateTimeModel>
            {
                new DateTimeModel(0, "Hôm qua"),
                new DateTimeModel(1, "Hôm nay"),
                new DateTimeModel(2, "Tháng trước"),
                new DateTimeModel(3, "Đầu tuần tới nay"),
                new DateTimeModel(4, "Đầu tháng tới nay"),
                new DateTimeModel(7, "7 ngày qua"),
                new DateTimeModel(15, "15 ngày qua"),
                new DateTimeModel(30, "30 ngày qua"),
                new DateTimeModel(90, "90 ngày qua")
            };

**Comment by LorenVeri** [comment] 2022-09-10 04:43
@x2bool If I binding list object, how to get item in list when click text-block?
ListDateTime = new List
{
new DateTimeModel(0, "Hôm qua"),
new DateTimeModel(1, "Hôm nay"),
new DateTimeModel(2, "Tháng trước"),
new DateTimeModel(3, "Đầu tuần tới nay"),
new DateTimeModel(4, "Đầu tháng tới nay"),
new DateTimeModel(7, "7 ngày qua"),
new DateTimeModel(15, "15 ngày qua"),
new DateTimeModel(30, "30 ngày qua"),
new DateTimeModel(90, "90 ngày qua")
};

<DropDown
						PlaceholderText="Thời gian"
						Name="ListDateTime"
						SelectedItem="{Binding DataContext.SelectDateCommand, ElementName = ListDateTime}"
						Items="{Binding ListDateTime}"
						Height="25"
						VerticalAlignment="Center">
						<DropDown.ItemTemplate>
							<DataTemplate>
								<StackPanel>
									<TextBlock Text="{Binding Name}"/>
								</StackPanel>
							</DataTemplate>
						</DropDown.ItemTemplate>
					</DropDown>

I want when user click on textblock with element name, i get that item
