### ISSUE TITLE
Native AOT is completely broken on MacOS with `TargetFramework=net8.0-macos` for Avalonia

### ISSUE THREAD

**Issue by Arktische** [AvaloniaUI/Avalonia#17425] opened 2024-11-04 07:37 UTC
### Describe the bug

Native AOT will always fail on MacOS with `TargetFramework=net8.0-macos` because Avalonia generates redundant dll files which results in name conflict for dotnet ILC. 

### To Reproduce

Create a new Avalonia project 
```bash
dotnet new avalonia.mvvm -o testapp
```
Then add PInfo.list to the project directory
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDisplayName</key>
	<string>testapp</string>
	<key>CFBundleIdentifier</key>
	<string>com.test.testapp</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1.0</string>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</dict>
</plist>

```

Then modify `testapp.csproj` and set `TargetFramework` to `net8.0-macos`
```bash
dotnet publish -r osx-arm64 -c Release /p:PublishAot=true
```

Then it throws 
```
Unhandled Exception: System.CommandLine.CommandLineException: Multiple input files matching same simple name /Users/xxx/Documents/testapp/obj/Release/net8.0-macos/osx-arm64/Avalonia/testapp.dll /Users/xxx/Documents/testapp/obj/Release/net8.0-macos/osx-arm64/Avalonia/testapp.dll
```

### Expected behavior

The NativeAOT publish should pass.

### Avalonia version

11.1.0+

### OS

macOS

### Additional context

If the `TargetFramework` is `net8.0`, it won't fail

**Comment by maxkatz6** [comment] 2024-11-04 23:07
It was fixed in .NET 9. Inherently it was caused by AOT compiler not using `IntermediateAssembly` msbuild property in .NET 8.

Relevant PRs:
https://github.com/AvaloniaUI/Avalonia/pull/14966 (this one hack-fixed the issue for normal AOT, but not Xamarin+NativeAOT)
https://github.com/dotnet/runtime/pull/99732 (proper fix in the SDK)

**Comment by maxkatz6** [comment] 2024-11-04 23:08
You can add this target to your CSPROJ file as a hack for .NET 8 version.
Or I recommend using .NET 9, if that's possible for you.

```
  <!-- Hack for Avalonia + Xamarin + NativeAOT combination not working on .NET 8 (but working on .NET 9) -->
  <Target Name="AvaloniaXamarinNativeAotHack"
          DependsOnTargets="InjectIlcAvaloniaXamlOutput;_XamarinComputeIlcCompileInputs"
          BeforeTargets="WriteIlcRspFileForCompilation"
          Condition="$([MSBuild]::VersionLessThan($(TargetFrameworkVersion), '9.0')) AND $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'macos'">
    <ItemGroup>
      <ManagedBinary Remove="@(_AvaloniaXamlCompiledAssembly)" />
      <IlcCompileInput Remove="@(_AvaloniaXamlCompiledAssembly)" />
    </ItemGroup>
  </Target>
```

**Closed by maxkatz6** 2024-11-04 23:08 UTC
Labels: bug
