### ISSUE TITLE
Binding an array element using the indexer throws an error at compile time, while a List works properly

### ISSUE THREAD

**Issue by MammaMiaDev** [AvaloniaUI/Avalonia#13975] opened 2023-12-16 16:26 UTC
## Describe the bug
Accessing an element inside an array using the indexer from the view:
```
<TextBlock Text="{Binding Stats[0].Stat.Name }" />
```
throws an error at compile time:
```
> PokemonView.axaml(15,24): 
Error AVLN:0004 Avalonia: Unable to resolve property or method of name 'Stat' on type 'System.Array'
```

If I use a `List` or an `ObservableCollection`, instead of an `Array`, the project compiles and starts correctly. Am I missing some basic concept here?

## To Reproduce

Create a view that uses `PokemonFull` as view model, and binds a `TextBlock.Text` to `Stats[0].Stat.Name`:
```xml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:models="clr-namespace:PokeloniaUI.Models"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="PokeloniaUI.Views.PokemonView"
             x:DataType="models:PokemonFull"
             d:DataContext="{x:Static models:PokemonFull.CreatePokemon}">

    <StackPanel Orientation="Vertical" Spacing="10">
        <TextBlock Text="{Binding Name}" Margin="15" Theme="{StaticResource TitleTextBlockStyle}"/>
        <Rectangle Width="96" Height="96" Fill="Aquamarine"/>
        <StackPanel Orientation="Horizontal" Margin="15" HorizontalAlignment="Center" >
            <TextBlock Text="{Binding Stats[0].Stat.Name }" Margin="0 0 30 0"/>
            <TextBlock Text="{Binding Stats[0].BaseStat}" Margin="0 0 30 0"/>
            <ProgressBar Value="{Binding Stats[0].BaseStat}" Maximum="200"/>
        </StackPanel>
    </StackPanel>
    
</UserControl>
```

Create the PokemonFull record:
```c#
public record PokemonFull(
    int BaseExperience,
    string Name,
    PokemonStat[] Stats,
    PokemonType Types,
    PokemonSprite Sprites)
{
    public static PokemonFull CreatePokemon => 
        new(150,
            "Bulbasaur",
            [new PokemonStat(69, 0, new ExternalReference("boh", "boh"))],
            new PokemonType(1, new ExternalReference("", "")), 
            new PokemonSprite("", ""));
}
```

Compile and see the error.

## Expected behavior
The project is able to compiler and run. The view is able to `PokemonFull.Stats` elements using the indexer. 

## Environment

- OS: Windows
- Avalonia-Version: 11.0.6

**Comment by jp2masa** [comment] 2023-12-16 20:45
Duplicate of #12886?

**Comment by MammaMiaDev** [comment] 2023-12-16 21:54
> Duplicate of #12886?

Yes, thanks for pointing out. Should I close this?

**Comment by timunie** [comment] 2023-12-17 07:25
@MammaMiaDev yes, in Avalonia we close duplicates 🙂. Otherwise these issues stay open for ever.

**Closed by timunie** 2023-12-17 07:25 UTC
Labels: bug
