### ISSUE TITLE
Android app in Release mode gets stuck in splash screen

### ISSUE THREAD

**Issue by lukaszossowski** [AvaloniaUI/Avalonia#8972] opened 2022-09-15 21:59 UTC
**Describe the bug**
Changing android app from Debug to Release mode and debugging it with VS causes it to get stuck in the splash screen.

**To Reproduce**

1. Create a Cross Platform Avalonia Application from official template.
2. Set configuration to Release
3. Deploy to phone.
4. App does not go pas splash screen.

**Expected behavior**
It should close splash screen and open main window.

**Desktop (please complete the following information):**

- OS: Android

**Comment by timunie** [comment] 2022-09-16 07:33
Maybe something goes wrong on start up. Try to do some logging to find the root cause: https://docs.avaloniaui.net/docs/getting-started/logging-errors-and-warnings

**Comment by lukaszossowski** [comment] 2022-09-16 08:32
> Maybe something goes wrong on start up. Try to do some logging to find the root cause: https://docs.avaloniaui.net/docs/getting-started/logging-errors-and-warnings

I am not sure how to do that in Android unfortunately, and where would the trace be. 

However, after doing some sumb debugging by using Vibrations as "breakpoint" it seems that the OnResume() override in SplashActivity never gets called. I tried overriding OnStart() as wel, but it also never gets called.

How should I proceed?

**Comment by maxkatz6** [comment] 2022-10-03 19:30
@lukaszossowski please try to get logs with `AndroidEnvironment.UnhandledExceptionRaiser` event. You can save an exception to the log file (note, that it might be saved to the virtual/internal memory with android sandbox restrictions).

**Comment by lukaszossowski** [comment] 2022-10-05 21:48
> please try to get logs with `AndroidEnvironment.UnhandledExceptionRaiser` event. You can save an exception to the log file (note, that it might be saved to the virtual/internal memory with android sandbox restrictions).

Could you please explain how to do that or point me in the right direction? Unfortunately I have basically zero experience in this kind of stuff.

**Comment by timunie** [comment] 2022-10-06 07:09
1. I use Serilog for logging: https://serilog.net . I think they have a logger for Android as well, check out their docs. 
2. See https://stackoverflow.com/questions/48499328/how-to-catch-all-exceptions-in-try-catch-block-in-xamarin-android for an example how to log an error in Xamarin. Avalonia should work similar.

**Comment by tristanlabelle** [comment] 2022-10-31 21:40
Is this and #9230 the same? I'm seeing this gray screen with the debug configuration. I can see the data binding for the `MainViewModel` being executed so it may have more to do with rendering. `AndroidEnvironment.UnhandledExceptionRaiser` is not raised and I'm not seeing anything suspicious with `Information`-level logs enabled. I can even see that a layout pass runs successfully. Any other ideas?

**Comment by CYLMos** [comment] 2022-11-02 04:33
I also has this problem. in debug mode, it's always good, but in release, it will get stuck.
I also tried this project [AvaloniaUI/Wordle-onia](https://github.com/AvaloniaUI/Wordle-onia) and do some changes (change to .net 6) and test, and it also stopped in splash screen.

**Comment by timunie** [comment] 2022-11-02 05:29
@CYLMos what exactly did you change and does it run without these changes? 

Maybe we can figure out the root case together 😃

**Comment by lukaszossowski** [comment] 2022-11-02 07:50
> @CYLMos what exactly did you change and does it run without these changes?

For me it turns out that Startup Tracing enabled was causing the issues. After disabling that the app works in release mode as well.

**Comment by CYLMos** [comment] 2022-11-02 11:03
> 

All of the TargetFramework are changed to net6.
And in global.json, the value of version are changed to one of the net 6 version (Sorry I can't check now).
I also modify MainActivity and SplashActivity because of 11.0 version of Avalonia.

MainActivity:
````
[Activity(Label = "Wordle.Android", Theme = "@style/MyTheme.NoActionBar", Icon = "@drawable/icon", LaunchMode = LaunchMode.SingleInstance, ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize)]
    public class MainActivity : AvaloniaMainActivity
    {
    }
````

SplashActivity
````
[Activity(Theme = "@style/MyTheme.Splash", MainLauncher = true, NoHistory = true)]
    public class SplashActivity : AvaloniaSplashActivity<App>
    {
        protected override AppBuilder CustomizeAppBuilder(AppBuilder builder)
        {
            return base.CustomizeAppBuilder(builder);
        }

        protected override void OnResume()
        {
            base.OnResume();

            StartActivity(new Intent(Application.Context, typeof(MainActivity)));
        }
    }
````

**Comment by CYLMos** [comment] 2022-11-02 11:05
@lukaszossowski 
I tried to disable it, but I got the same issue.

**Comment by CYLMos** [comment] 2022-11-10 07:17
Some updates,
I upgrade my Avalonia package to ﻿0.10.999-cibuild0023268-beta and it's working.

**Comment by timunie** [comment] 2022-11-10 12:26
@CYLMos thank you for the testing and the feedback. Acc. to this I'll close this issue now as completed. 

@lukaszossowski or @CYLMos if the bug happens again with a newer preview build please open an new issue.

**Closed by timunie** 2022-11-10 12:26 UTC
Labels: bug, os-android
