### ISSUE TITLE
Apps in release crashes on Android

### ISSUE THREAD

**Issue by PerfectlyFineCode** [AvaloniaUI/Avalonia#8635] opened 2022-07-31 21:44 UTC
**Describe the bug**
Apps in release doesn't work on Android,
just a completely white screen or an empty screen with the Avalonia logo. 
But that's all.

**To Reproduce**

1. Create Avalonia Cross Platform Application
2. Build in release mode for Android
3. Run the app
4. See app crashing

**Expected behavior**
It should actually render the app and work.

**Screenshots**
![image](https://user-images.githubusercontent.com/70201838/182046484-786ff872-403f-48b5-9288-bfb200076e34.png)

**Desktop (please complete the following information):**

- OS: Windows 11, run on Android 12.0
- Version (Windows 22000.778), (Android 12.0)
- Avalonia Version: 0.10.999-cibuild0019226-beta

**Comment by timunie** [comment] 2022-08-01 04:21
Which version of Avalonia do you use? I think you need the latest nightly build for Android support.

**Comment by PerfectlyFineCode** [comment] 2022-08-01 11:33
> Which version of Avalonia do you use? I think you need the latest nightly build for Android support.

0.10.999-cibuild0019226-beta

**Comment by jeromemanzano** [comment] 2022-08-02 02:06
We are experiencing this as well. We are using `0.10.999-cibuild0021683-beta`

This is what I'm seeing on logcat

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.PlatformNotSupportedException: Arg_PlatformNotSupported
        at System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte_Intrinsified(Byte* , UIntPtr )
        at System.Text.Unicode.Utf8Utility.GetPointerToFirstInvalidByte(Byte* , Int32 , Int32& , Int32& )
        at System.Text.UTF8Encoding.GetCharCount(Byte* , Int32 )
        at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
        at System.Text.Encoding.GetString(Byte* , Int32 )
        at System.String.CreateStringForSByteConstructor(Byte* pb, Int32 numBytes)
        at System.String.Ctor(SByte* value)
        at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr )
        at Java.Interop.TypeManager.GetClassName(IntPtr )
        at Android.Runtime.JNIEnv.RegisterJniNatives(IntPtr , Int32 , IntPtr , IntPtr , Int32 )
```

**Comment by maxkatz6** [comment] 2022-08-02 04:04
Closing as it seems to be bug in dotnet runtime. 
@PerfectlyFineCode please ping me to reopen this issue, if workaround from @jeromemanzano 's link doesn't work for you or you have different crash log.

**Closed by maxkatz6** 2022-08-02 04:04 UTC
Labels: bug

**Comment by PerfectlyFineCode** [comment] 2022-08-06 22:02
@maxkatz6 Seems like it still has an issue for me in release mode, disabled AOT compilation.

If you need project I can send it over.

The app still crashes with the error.
```lua
08-06 23:51:10.713 E/AndroidRuntime(21960): android.runtime.JavaProxyThrowable: System.InvalidOperationException: Cannot call Measure using a size with NaN values.
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Avalonia.Layout.Layoutable.Measure(Size availableSize)
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Avalonia.Layout.Layoutable.Measure(Size availableSize)
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Avalonia.Layout.LayoutManager.InnerLayoutPass()
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Avalonia.Android.AndroidThreadingInterface.<Signal>b__5_0()
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Java.Lang.Thread.RunnableImplementor.Run()
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Java.Lang.IRunnableInvoker.n_Run(IntPtr , IntPtr )
08-06 23:51:10.713 E/AndroidRuntime(21960):    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
08-06 23:51:10.713 E/AndroidRuntime(21960): 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
08-06 23:51:10.713 E/AndroidRuntime(21960): 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
08-06 23:51:10.713 E/AndroidRuntime(21960): 	at android.os.Handler.handleCallback(Handler.java:938)
08-06 23:51:10.713 E/AndroidRuntime(21960): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-06 23:51:10.713 E/AndroidRuntime(21960): 	at android.os.Looper.loop(Looper.java:223)
08-06 23:51:10.713 E/AndroidRuntime(21960): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
08-06 23:51:10.713 E/AndroidRuntime(21960): 	at java.lang.reflect.Method.invoke(Native Method)
08-06 23:51:10.713 E/AndroidRuntime(21960): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-06 23:51:10.713 E/AndroidRuntime(21960): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by timunie** [comment] 2022-08-08 06:18
Try it with latest master / prerelease again. There was a huge fix recently, see: #8691 

Also you can download the ControlCatalog as APK from [[here]](https://1drv.ms/u/s!AqsF0_O_NBsGk40JUIAHKAxHdW18VA?e=35JSPq) to test on your own. I've a Samsung S20FE and it works (okay, there are some rough edges, but most things work ...)

**Comment by PerfectlyFineCode** [comment] 2023-07-16 14:02
Yeah, it still crashes.

**Comment by dfernandezramos** [comment] 2023-11-14 10:52
Hi mates, is this still a thing? I am experiencing this exception on my Avalonia 11.0.4 application when I compile in Release mode:

```
[Warn  11:45:04.988] Caught an exception - System.PlatformNotSupportedException: Arg_PlatformNotSupported (in `Avalonia.Base')
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at MyApp.MainClass.Main(String[] args)
```

**Comment by timunie** [comment] 2023-11-14 11:02
@dfernandezramos that must be smth else I guess.

**Comment by maxkatz6** [comment] 2023-11-15 23:02
@dfernandezramos it looks like your are running desktop app on android.

**Comment by dfernandezramos** [comment] 2023-11-16 07:37
Hey guys @maxkatz6 & @timunie thanks for your feedback. My app is a desktop application. I just wrote in this issue because of the exception message is the same one. I've seen that the issue is a service I am starting only on release mode with conditional compilation code (`#if !DEBUG`). Maybe an unhandled exception that leads to that error. I need to investigate what is it failing but false alarm. Thanks again!
