### ISSUE TITLE
Starting browser project fails out of the box

### ISSUE THREAD

**Issue by mate1213** [AvaloniaUI/Avalonia#16491] opened 2024-07-26 15:41 UTC
### Describe the bug

I Create a project in VS2022 i'm starting the application without any modification the webpage crashes:
![image](https://github.com/user-attachments/assets/3c3bed90-b6e9-4e5e-b305-bedd08f2f974)
`Failed to load resource: the server responded with a status of 404 (Not Found)`
```
Uncaught Error: One or more errors occurred. (TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:34461/_framework/avalonia.js)
    at Jn (marshal-to-js.ts:349:18)
    at Tl (marshal-to-js.ts:306:28)
    at dotnet.native.wasm:0x1fad7
    at dotnet.native.wasm:0x1bf9f
    at dotnet.native.wasm:0xf16c
    at dotnet.native.wasm:0x1e7f1
    at dotnet.native.wasm:0x1efe7
    at dotnet.native.wasm:0xcfbc
    at dotnet.native.wasm:0x44213
    at e.<computed> (cwraps.ts:338:24)
```

### To Reproduce

Generate a project in VS2022 with the following parameters:
- version1:
  - Target: Destop, WASM
  -  DesignPattern: ReactiveUI
  - Features: Compiled Bindings
- Version 2
  - Target: Destop, WASM
  -  DesignPattern: ComunityToolkit
  - Features: Compiled Bindings, EmbeddedSupport, MeadowPlatform
- Version 3
  - Target: WASM
  -  DesignPattern: ComunityToolkit
  - Features: Compiled Bindings
- Version 4
  - Target: WASM
  -  DesignPattern: ReactiveUI
  - Features: NONE

Start the project browser mode.
Open development tools in browser.
Wait for the errors (takes 5-10 secs)

### Expected behavior

The webpage loading.

### Avalonia version

11.1.0

### OS

WebAssembly

**Comment by maxkatz6** [comment] 2024-07-27 05:21
Duplicate of these discussions https://github.com/AvaloniaUI/Avalonia/discussions/16467#discussioncomment-10153273 and https://github.com/AvaloniaUI/Avalonia/discussions/16472

Make sure you have latest templates, .NET SDK and workloads installed as well as you are properly publishing/building your project.

**Closed by maxkatz6** 2024-07-27 05:21 UTC
Labels: bug
