### ISSUE TITLE
DataGrid does not allow edit the first DataGridTemplateColumn

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#13892] opened 2023-12-10 17:32 UTC
## Describe the bug
When using an `DataGrid` to edit properties using `DataGridTemplateColumn`, the first column does not allow edit, it enter in edit mode but editing control is disabled -- Not possible to manually input or using the spinner.
However, if I add a dummy column first, eg: `<DataGridTextColumn/>` all other columns edit ok.

## To Reproduce

```xaml
<DataGrid Name="PhasedExposuresGrid"
          Margin="0, -15, 0, 0"
          BorderBrush="Gray"
          BorderThickness="1"
          MinWidth="720"
          MinHeight="170"
          CanUserReorderColumns="False"
          CanUserResizeColumns="False"
          CanUserSortColumns="False"
          GridLinesVisibility="Horizontal"
          IsReadOnly="False"
          SelectionMode="Extended"
          ClipboardCopyMode="IncludeHeader"
          HeadersVisibility="All"
          ItemsSource="{Binding Operation.PhasedExposures}"
          RowHeaderWidth="40"
          LoadingRow="PhasedExposuresGrid_OnLoadingRow">
    <DataGrid.Columns>
        <DataGridTemplateColumn Header="Bottom exposure time" MinWidth="180" Width="Auto">
            <DataGridTemplateColumn.CellTemplate>
                <DataTemplate>
                    <TextBlock Text="{Binding BottomExposureTime, StringFormat='{}{0:F2}s'}"
                               VerticalAlignment="Center" HorizontalAlignment="Center" />
                </DataTemplate>
            </DataGridTemplateColumn.CellTemplate>
            <DataGridTemplateColumn.CellEditingTemplate>
                <DataTemplate>
                    <NumericUpDown Value="{Binding BottomExposureTime}"
                                   FormatString="F2"
                                   Minimum="0"
                                   Maximum="1000"
                                   Increment="0.50"
                                   Classes="ValueLabel ValueLabel_s"
                                   HorizontalAlignment="Stretch"/>
                </DataTemplate>
            </DataGridTemplateColumn.CellEditingTemplate>
        </DataGridTemplateColumn>

        <DataGridTemplateColumn Header="Bottom iterations" MinWidth="180" Width="Auto">
            <DataGridTemplateColumn.CellTemplate>
                <DataTemplate>
                    <TextBlock Text="{Binding BottomIterations, StringFormat='{}{0}px'}"
                               VerticalAlignment="Center" HorizontalAlignment="Center" />
                </DataTemplate>
            </DataGridTemplateColumn.CellTemplate>
            <DataGridTemplateColumn.CellEditingTemplate>
                <DataTemplate>
                    <NumericUpDown Value="{Binding BottomIterations}"
                                   Minimum="0"
                                   Maximum="65535"
                                   Increment="1"
                                   Classes="ValueLabel ValueLabel_px"
                                   HorizontalAlignment="Stretch"/>
                </DataTemplate>
            </DataGridTemplateColumn.CellEditingTemplate>
        </DataGridTemplateColumn>

        <DataGridTemplateColumn Header="Normal exposure time" MinWidth="180" Width="Auto">
            <DataGridTemplateColumn.CellTemplate>
                <DataTemplate>
                    <TextBlock Text="{Binding ExposureTime, StringFormat='{}{0:F2}s'}"
                               VerticalAlignment="Center" HorizontalAlignment="Center" />
                </DataTemplate>
            </DataGridTemplateColumn.CellTemplate>
            <DataGridTemplateColumn.CellEditingTemplate>
                <DataTemplate>
                    <NumericUpDown Value="{Binding ExposureTime}"
                                   FormatString="F2"
                                   Minimum="0"
                                   Maximum="1000"
                                   Increment="0.50"
                                   Classes="ValueLabel ValueLabel_s"
                                   HorizontalAlignment="Stretch"/>
                </DataTemplate>
            </DataGridTemplateColumn.CellEditingTemplate>
        </DataGridTemplateColumn>

        <DataGridTemplateColumn Header="Normal iterations" MinWidth="180" Width="Auto">
            <DataGridTemplateColumn.CellTemplate>
                <DataTemplate>
                    <TextBlock Text="{Binding Iterations, StringFormat='{}{0}px'}"
                               VerticalAlignment="Center" HorizontalAlignment="Center" />
                </DataTemplate>
            </DataGridTemplateColumn.CellTemplate>
            <DataGridTemplateColumn.CellEditingTemplate>
                <DataTemplate>
                    <NumericUpDown Value="{Binding Iterations}"
                                   Minimum="0"
                                   Maximum="65535"
                                   Increment="1"
                                   Classes="ValueLabel ValueLabel_px"
                                   HorizontalAlignment="Stretch"/>
                </DataTemplate>
            </DataGridTemplateColumn.CellEditingTemplate>
        </DataGridTemplateColumn>
    </DataGrid.Columns>
</DataGrid>
```

## Expected behavior
The first column to be editable as well.

## Screenshots
![image](https://github.com/AvaloniaUI/Avalonia/assets/113281/1ea77387-00be-40aa-a49a-bae6aa013513)
![image](https://github.com/AvaloniaUI/Avalonia/assets/113281/42b1f32c-1371-48fd-a57b-908536713ca9)
![image](https://github.com/AvaloniaUI/Avalonia/assets/113281/a0262f37-819d-45be-8d49-fcf1665be2d2)

## Environment 

- OS: Windows 11
- Avalonia-Version: 11.0.6

## Additional context

My current hacky solution is to have a invisible first column, so all the rest is editable:

```xaml
<DataGridTextColumn MinWidth="0" Width="0" IsVisible="False"/>
```

**Comment by timunie** [comment] 2023-12-10 18:59
can you test nightly?

**Comment by sn4k3** [comment] 2023-12-10 19:26
> can you test nightly?

Works correctly with nightly

**Comment by timunie** [comment] 2023-12-10 20:21
Okay then it will be fixed also in 11.1 latest, if not 11.0.7

Closing this for now

**Closed** 2023-12-10 20:21 UTC
Labels: bug

**Comment by maxkatz6** [comment] 2023-12-11 05:16
Likely with this https://github.com/AvaloniaUI/Avalonia/pull/13845 PR

**Comment by sn4k3** [comment] 2024-01-17 16:38
Bug persists with 11.0.7 :(

**Comment by timunie** [comment] 2024-01-18 09:13
@sn4k3 can you also test nightly? If nightly also fails, I'll re-open this issue.

**Comment by timunie** [comment] 2024-01-18 10:05
@sn4k3 I'm not able to reproduce it using nightly. Could you probably file a minimal sample if the issue persists for you? I wonder it it is related to any event handler or something else not seen in the XAML.

**Comment by sn4k3** [comment] 2024-01-18 17:52
It works with the current nightly as it did with https://github.com/AvaloniaUI/Avalonia/issues/13892#issuecomment-1849058464
On a release event I was expecting that all changes on master and nightly would be merged on the release?

**Comment by maxkatz6** [comment] 2024-01-18 23:55
> On a release event I was expecting that all changes on master and nightly would be merged on the release?

No, only what was backported.
Editing issue was backported though.

**Comment by sn4k3** [comment] 2024-01-19 22:46
The other bugs I noticed has been fixed on release. Like unable to check a checkbox on a DataGrid, but this one persists... Better to reopen the issue?

**Comment by sn4k3** [comment] 2024-02-08 18:35
Fixed on latest release
