### ISSUE TITLE
Canvas. Artifacts. Animation.

### ISSUE THREAD

**Issue by greedywizard** [AvaloniaUI/Avalonia#10873] opened 2023-04-01 13:02 UTC
**Describe the bug**
Graphics artifacts when animate with canvas.

**To Reproduce**

1. Create MVVM template.
2. Add `<Canvas>`
3. Create several Path type shapes
4. Add child elements using the `canvas.Сhildren.Add()` method
5. Add moving to the shapes.
6. Move shapes on canvas using ` TransformGroup().Children.Add(new TranslateTransform())`

**Expected behavior**
Moving shapes without artifacts.

**Screenshots**
![Screenshot 2023-04-01 155252](https://user-images.githubusercontent.com/22398454/229290017-c6054b1e-b3d4-4bea-a78c-06c38c8d0e69.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0.0 - preview 6

**Additional context**
Artifacts disappear if I resize the window.
Also, artifacts do not appearr if I add `.With(new Win32PlatformOptions{ UseWindowsUIComposition = false})`
and `.UseDirect2D1()` to the AppBuilder.
Artifacts do not appear if I run app with WSL2.

[https://github.com/greedywizard/AvaloniaCanvasBug](url) - repo with project.

Code which use for moving.
```
  public double DeltaX
    {
        get => _deltaX;
        set
        {
            _deltaX = value;
            Update();
        }
    }

    public double DeltaY
    {
        get => _deltaY; 
        set
        {
            _deltaY = value;
            Update();
        }
    }

    private void CanvasOnPointerReleased(object? sender, PointerReleasedEventArgs e)
    {
        _moving = false;
    }

    private void CanvasOnPointerPressed(object? sender, PointerPressedEventArgs e)
    {
        _moving = true;
        e.Pointer.Capture(_canvas);
        _lastPoint = e.GetPosition(_canvas);
    }

    private void CanvasOnPointerMoved(object? sender, PointerEventArgs e)
    {
        var pos = e.GetPosition(_canvas);

        PointerX = pos.X;
        PointerY = pos.Y;

        if (_moving)
        {
            var point = e.GetPosition(_canvas);

            var (deltaX, deltaY) = point - _lastPoint;
            DeltaX += deltaX;
            DeltaY += deltaY;
            
            _lastPoint = point;
        }
    }

    private void Update()
    {
        foreach (var figure in Figures)
        {
            figure.Update(DeltaX, DeltaY, Zoom);
        }
    }
    
    //Update shapes
    public void Update(double deltaX, double deltaY, double zoom)
    {
        _shape.Data = Path;
        var transform = new TransformGroup();
        
        transform.Children.Add(new TranslateTransform(deltaX, deltaY));
        transform.Children.Add(new ScaleTransform(zoom, zoom));
        
        _shape.RenderTransform = transform;
    }
```

**Comment by robloo** [comment] 2023-04-01 17:01
This has been an ongoing issue for a while. I can't find the other issues at the moment though.

As far as I know the root cause is Skia itself drawing outside the bounds of where it should be, especially when using a corner radius with anti-aliasing (see below). There are various ideas to fix this: no anti-aliasing in these cases, invalidating +1 px outside bounds (PR didn't work and was closed I think) as well as building Skia separately just for Avalonia to get the latest with bug fixes.

IMO this is almost at release blocker level but I don't think it's high on the core team's priority list. I've also seen something similar in the Avalonia XPF examples: Canvas invalidation doesn't seem to work in all cases there either but the cause looks different.

Avalonia Border with CornerRadius
![image](https://user-images.githubusercontent.com/17993847/229304313-d538aec5-ea25-41cc-9b51-e94d550511af.png)

**Comment by timunie** [comment] 2023-08-21 07:42
@greedywizard can you double-check if this issue is solved for you using latest nightly?

**Comment by maxkatz6** [comment] 2023-08-29 08:00
Closing as it should be fixed in the latest master. Please ping me if it's still an issue.

**Closed by maxkatz6** 2023-08-29 08:00 UTC
Labels: bug, area-rendering
