### ISSUE TITLE
German locale causes crash on parsing Path Markup

### ISSUE THREAD

**Issue by mat1jaczyyy** [AvaloniaUI/Avalonia#2391] opened 2019-03-25 23:20 UTC
```cs
Arc.Data = Geometry.Parse($"M {x_start},{y_start} A {radius},{radius} {angle} {large} 1 {x_end},{y_end}");
```

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.InvalidDataException: Invalid double value
   at Avalonia.Media.PathMarkupParser.ReadDouble(ReadOnlySpan`1& span)
   at Avalonia.Media.PathMarkupParser.AddArc(ReadOnlySpan`1& span, Boolean relative)
   at Avalonia.Media.PathMarkupParser.Parse(String pathData)
   at Avalonia.Media.StreamGeometry.Parse(String s)
```

(Windows) This issue is caused by the computer using a German locale, which uses the `,` character as the decimal point. I believe the Path Markup parser reads `{x_start},{y_start}` as a single number because of this, and then crashes when it encounters A. Switching to an US locale, which uses the `.` character as the decimal point, resolves the issue. Avalonia should be able to parse this correctly as we cannot expect users to change their locale to have an app work properly.

**Comment by grokys** [comment] 2019-03-26 00:17
This is by design: the geometry syntax expects `,` to be a separator not a decimal point. This is the only thing that makes sense otherwise a path string could be interpreted differently depending on locale, which would cause a lot of problems.

I'm pretty sure this is the same in [WPF](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/path-markup-syntax) and [SVG](https://stackoverflow.com/a/51479051) for example.

If you want to format the string using string interpolation you should surround the string with a call to [`System.FormattableString.Invariant`](https://stackoverflow.com/a/29338846).

Closing because I think this is expected behavior.

**Closed by grokys** 2019-03-26 00:17 UTC

**Comment by mat1jaczyyy** [comment] 2019-03-26 00:29
oh, i think i got it upside down: my `x_start` is a double and will have a , instead which confuses the engine. thanks for the clarification
