### ISSUE TITLE
Applications don't render correctly under ElementaryOS 0.4.1

### ISSUE THREAD

**Issue by egee-irl** [AvaloniaUI/Avalonia#1603] opened 2018-05-20 19:18 UTC
ElementaryOS is a Linux distribution based on Ubuntu and uses a pure GTK & Vala desktop environment called Pantheon. Since ElementaryOS is built on pure GTK3 3.18, I figured it would be a good development environment to write GTK & Avalonia applications against.

Much to my surprise, Avalonia doesn't appear to work at all on ElementaryOS. I tried both project templates from VisualStudio and both of them render [this broken square](https://imgur.com/a/NOQzhjS) of an application.

I have two branches in my repository, one for the regular project template, and another for the mvvm project template - https://github.com/egee-irl/XplatformTest

I am using the binary Nvidia drivers version 384.111 if that helps.

**Comment by danwalmsley** [comment] 2018-05-20 19:27
@kekekeks any ideas?

**Comment by danwalmsley** [comment] 2018-05-20 19:27
Are any messages appearing on the console? Does this os use X Server, wayland or other?

**Comment by egee-irl** [comment] 2018-05-20 19:40
This error appears in the console:
`(dotnet:2525): Gtk-CRITICAL **: gtk_window_resize: assertion 'width > 0' failed`

I'm running Xserver - no Wayland here!

**Comment by egee-irl** [comment] 2018-05-20 22:52
Interestingly, my sample code works perfectly fine on Ubuntu 18.04, which is using Gnome 3.28. ElementaryOS' Pantheon is based on GTK libs 3.18.9. Perhaps this is a GTK version issue?

**Comment by egee-irl** [comment] 2018-06-17 15:18
The version of GTK that ElementaryOS appears to be a forked version of GTK 3.18. Internally, this version is referenced as version 3.18.9.

I tested my simple Avalonia application on a fresh install of Ubuntu 16.04 which uses GTK 3.18.3 and it worked perfectly fine.

I am unsure why exactly Avalonia applications do not work on ElementaryOS, however since it is a somewhat smaller distro, I don't think this is a major issue for the Avalonia project in general.

I would perhaps note in the documentation that ElementaryOS is ostensibly not supported by Avalonia.

**Comment by SaitDev** [comment] 2018-06-18 10:48
:slightly_frowning_face: im not sure if elementaryOS modified gtk, but im sure 3.18.9 was an official release  http://ftp.gnome.org/pub/gnome/sources/gtk+/3.18/

**Comment by jmacato** [comment] 2018-08-20 10:12
This issue was prematurely closed. I'll keep this open till this is resolved

**Comment by akiraKido** [comment] 2018-09-06 04:51
Using Ubuntu 18.04,
- template: avalonia.mvvm
    - `gtk_window_resize: assertion 'width > 0' failed`
- template: avalonia.app
    ```
    Gtk-CRITICAL **: 13:46:03.180: gtk_application_new: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed

    Gtk-CRITICAL **: 13:46:03.765: gtk_window_resize: assertion 'width > 0' failed
    ```

**Comment by jmacato** [comment] 2018-09-08 16:52
@akiraKido that's a known issue (#1800) and it's not relevant to this one.

**Comment by peterzeller** [comment] 2018-11-27 23:35
I have the same problem running ElementaryOS (elementaryos-5.0-stable.20181016.iso) in Virtualbox. 

- I tried installing xfce4 as the Desktop environment, but it has the same problem.
- Other Gtk applications are not effected (I tried the GtkSharp dotnet template from https://github.com/GtkSharp/GtkSharp), so it seems to be an Avalonia problem
- If I run an application with a canvas element, the canvas is drawn correctly but the rest of the application (window border etc.) is not drawn

**Comment by kekekeks** [comment] 2018-11-28 07:10
Please, try running control catalog from [this branch](https://github.com/kekekeks/Perspex/tree/x11) after adding `UseX11();` [here](https://github.com/kekekeks/Perspex/blob/x11/samples/ControlCatalog.NetCore/Program.cs#L40).

That should switch it to using X11 backend.

**Comment by kekekeks** [comment] 2018-11-28 07:14
Prebuilt binary here: https://mega.nz/#!0l4UnSDK!PckJnXJUpBeet53Cl8Cgiqf7v8pB2VSuhQD1kgjcUXM

**Comment by peterzeller** [comment] 2018-11-28 22:50
The prebuilt binary works fine under ElementaryOS :+1:

**Comment by SaitDev** [comment] 2018-11-29 02:41
try with prebuilt bin
```
System.DllNotFoundException: Unable to load DLL 'X11': The specified module or one of its dependencies could not be found.
   at Avalonia.X11.XLib.XInitThreads()
```
How can I install x11 dll?

**Comment by kekekeks** [comment] 2018-11-29 06:08
You probably need `libx11-dev` package. I'll change it later to look for `libX11.so.6` so `-dev-` package won't be needed.

**Comment by SaitDev** [comment] 2018-11-29 06:44
There are some controls doesnt work well but thats another topic. Avalonia is rendering fine on elementary os now

**Comment by leo60228** [comment] 2019-01-26 20:59
I get this problem on NixOS. Will try the forked branch.

**Comment by leo60228** [comment] 2019-01-26 22:13
The forked branch worked, but didn't render text. I updated to the nightly and the square changed color from white to blue. If I install libSkiaSharp (NixOS doesn't include it by default), I get this exception:
```
Unhandled Exception: System.InvalidOperationException: Failed to create Skia render target surface
   at Avalonia.Skia.SurfaceRenderTarget..ctor(CreateInfo createInfo) in D:\a\1\s\src\Skia\Avalonia.Skia\SurfaceRenderTarget.cs:line 41
   at Avalonia.Skia.DrawingContextImpl.CreateRenderTarget(Size size, Nullable`1 format) in D:\a\1\s\src\Skia\Avalonia.Skia\DrawingContextImpl.cs:line 633
   at Avalonia.Skia.DrawingContextImpl.CreateLayer(Size size) in D:\a\1\s\src\Skia\Avalonia.Skia\DrawingContextImpl.cs:line 228
   at Avalonia.Rendering.RenderLayers.Update(Scene scene, IDrawingContextImpl context) in D:\a\1\s\src\Avalonia.Visuals\Rendering\RenderLayers.cs:line 24
   at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(Func`1 contextFactory, Boolean recursiveCall) in D:\a\1\s\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 275
   at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite) in D:\a\1\s\src\Avalonia.Visuals\Rendering\DeferredRenderer.cs:line 233
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect) in D:\a\1\s\src\Avalonia.Controls\TopLevel.cs:line 259
   at Avalonia.Gtk3.WindowBaseImpl.OnDraw(IntPtr gtkwidget, IntPtr cairocontext, IntPtr userdata) in D:\a\1\s\src\Gtk\Avalonia.Gtk3\WindowBaseImpl.cs:line 270
   at Avalonia.Gtk3.Gtk3Platform.RunLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Gtk\Avalonia.Gtk3\Gtk3Platform.cs:line 107
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.Base\Threading\Dispatcher.cs:line 65
   at Avalonia.Application.Run(Window mainWindow) in D:\a\1\s\src\Avalonia.Controls\Application.cs:line 237
   at MacroInstaller.Program.Main(String[] args) in /home/leo60228/MacroInstaller/Program.cs:line 11
```

**Comment by leo60228** [comment] 2019-01-26 22:17
It appears that neither ElementaryOS nor NixOS package SkiaSharp. This may be the cause of the issue.

**Comment by kekekeks** [comment] 2019-01-27 07:34
We are shipping our own build of SkiaSharp via nuget package - https://www.fuget.org/packages/Avalonia.Skia.Linux.Natives. Your issue seems to be caused by some EGL initialization problems. Please, try the latest nightly build since it's using GLX directly.

**Comment by kekekeks** [comment] 2019-01-27 13:43
Try disabling hardware acceleration: `.UseX11(new X11PlatformOptions{UseGpu=false});`

**Comment by leo60228** [comment] 2019-01-27 13:45
Is UseX11 in the nightlies?

**Comment by kekekeks** [comment] 2019-01-27 13:45
Yes, latest nightly build

**Comment by kekekeks** [comment] 2019-01-27 13:46
>NixOS doesn't follow FHS


```
readelf -d libSkiaSharp.so |grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libfontconfig.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
```

We are also using `libGL.so.1`, `libX11.so.6` and various X11 libraries via `DllImport` (i. e. `dlopen`+`dlsym`).

**Comment by leo60228** [comment] 2019-01-27 13:50
Okay. Is there any way I could compile my own? NixOS doesn't even have /lib
or /usr/lib .

**Comment by kekekeks** [comment] 2019-01-27 13:55
We don't have any hardcoded paths. As I've shown above, there are only SO-names, so ignoring FHS shouldn't be an issue.

You can try building your own one following instructions here: https://github.com/mono/SkiaSharp/wiki/Building-on-Linux

**Comment by kekekeks** [comment] 2019-01-27 13:57
I'm closing this issue since Elementaly OS support (which was probably broken because of the patched GTK or something) seems to be fixed according to https://github.com/AvaloniaUI/Avalonia/issues/1603#issuecomment-442724316 


For NixOS open a separate issue.

**Closed** 2019-01-27 18:13 UTC
