### ISSUE TITLE
The `Closing` window event is triggered in AXAML Preview in Visual Studio.

### ISSUE THREAD

**Issue by VladiStep** [AvaloniaUI/Avalonia#13657] opened 2023-11-19 15:14 UTC
## Describe the bug
Every time when you edit something in the AXAML code of a window that has `Closing` event, that event handler is being called.

## To Reproduce

1. Add a `Closing` event to a window.
2. Make sure that there was the window preview visible (or currently visible).
3. Edit something in the AXAML code of the window.

## Expected behavior
The `Closing` event shouldn't being called.

## Environment 

- OS: Windows 10
- Avalonia-Version: 11.0.5
- Visual Studio version: 2022, 17.7.5

## Additional context
I have a message box that asks you if you are really want to close the window, and this message box is being shown every time when I edit the AXAML code.

**Comment by VladiStep** [comment] 2023-11-19 15:19
https://github.com/AvaloniaUI/Avalonia/assets/45438625/4ae4ab1f-3b8b-463a-8fd8-839e1e79b5aa

![image](https://github.com/AvaloniaUI/Avalonia/assets/45438625/4d129814-b952-4875-b799-02139f918fba)

**Comment by timunie** [comment] 2023-11-20 06:45
You can use `if(Design.IsDesignMode)` to skip the event.

**Comment by VladiStep** [comment] 2023-11-20 18:35
> You can use `if(Design.IsDesignMode)` to skip the event.

I didn't know about this, thanks!
Though, this doesn't change the fact that it should not be triggered in the first place.

**Comment by TomEdwardsEnscape** [comment] 2023-11-21 09:37
Should it not be triggered? What about `Opened`, `Loaded`, and `Unloaded`?

Since these can all perform important tasks and are expected to be called in the real application, it seems reasonable to me that all of them (and `Closing`/`Closed`) should be raised in the designer. It's up to the user to check `InDesignMode` if they want to skip certain code paths.

**Comment by timunie** [comment] 2023-11-21 10:15
@TomEdwardsEnscape I think the same. However technically the designer is not a window so I don't know 100 % and wanted to have a confirmation from @avaloniaui-team before closing it as by-design.

**Comment by maxkatz6** [comment] 2023-11-21 23:34
Yeah, I don't see why it shouldn't be triggered either.

**Comment by timunie** [comment] 2023-11-22 07:28
I'm gonna close this as by design. If someone want's to skip this event in the designer, we have a proper [solution](https://github.com/AvaloniaUI/Avalonia/issues/13657#issuecomment-1818322382) for it.

**Closed** 2023-11-22 07:28 UTC
Labels: area-designer, by-design
