### ISSUE TITLE
Previewer not working

### ISSUE THREAD

**Issue by xiejiang2014** [AvaloniaUI/Avalonia#14035] opened 2023-12-25 19:30 UTC
## Describe the bug
Previewer not working

## To Reproduce
1. Create an "Avalonia .Net App(AvaloniaUI)"
2. Add an "Avalonia UserControl(AvaloniaUI)"
3. Build porject.
Some usercontrols preview fine, others don't, and I can't find the difference between them.
I haven't even changed their code.

## Expected behavior
Previewer works fine.

## Screenshots
Previewer :
![image](https://github.com/AvaloniaUI/Avalonia/assets/44390984/3916768e-3bee-45af-b294-8b323f2448f1)

Error List:
![image](https://github.com/AvaloniaUI/Avalonia/assets/44390984/dd4869eb-c3db-4e6b-b1e5-077e9d952737)

```
Internal compiler error while transforming node XamlX.Ast.XamlAstNamePropertyReference:
XamlX.XamlTypeSystemException: Unable to resolve type Avalonia.Data.RelativeSource
   at XamlX.TypeSystem.XamlTypeSystemExtensions.GetType(IXamlTypeSystem sys, String type)
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.AvaloniaXamlIlWellKnownTypes..ctor(TransformerConfiguration cfg)
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.AvaloniaXamlIlWellKnownTypesExtensions.GetAvaloniaTypes(AstTransformationContext ctx)
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.AvaloniaXamlIlResolveClassesPropertiesTransformer.Transform(AstTransformationContext context, IXamlAstNode node)
   at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node) Line 1, position 2.
```

## Environment 
- OS: Windows 10
- Avalonia-Version: 11.0.6
- Avalonia For Visual Studio 2022-Version: 11.5

**Comment by timunie** [comment] 2023-12-25 19:38
Duplicate of #14033

**Closed** 2023-12-25 19:38 UTC
Labels: bug
