### ISSUE TITLE
Application published with ReadyToRun not launching after updating nuget packages from 0.10.3 to 0.10.6

### ISSUE THREAD

**Issue by D0ctorWh0** [AvaloniaUI/Avalonia#6336] opened 2021-07-30 19:27 UTC
I installed Avalonia extension to Visual Studio 2019 and created project with Avalonia template. Publishing with ReadyToRun was working well. But then I noticed that there is an update from version 0.10.3 to 0.10.6. After updating nuget packages publishing with ReadyToRun still works, but the application won't start. If I downgrade nuget packages to 0.10.3 all becomes normal again.

**Comment by maxkatz6** [comment] 2021-07-30 19:46
It works perfectly for me.
Can you share any logs from your application (try catch in Main() usually has some info) or from the OS (event viewer in windows or console in macos)?

**Comment by D0ctorWh0** [comment] 2021-07-30 20:01
Application: AvaloniaApplication2.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'Avalonia.Controls, Version=0.10.6.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Avalonia.Controls, Version=0.10.6.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'
   at AvaloniaApplication2.Program.Main(String[] args)

**Comment by maxkatz6** [comment] 2021-07-30 20:07
Do you publish it as a single file (PublishSingleFile)?

**Comment by D0ctorWh0** [comment] 2021-07-30 20:18
I tried both publishing with PublishSingleFile and without it

Here is my project: [https://1drv.ms/u/s!AoJ4Bx_49cOvlgI_6i8oRJlTPh1g?e=bqiJnq](url)

published files are in \bin\Release\net5.0\publish folder

**Comment by maxkatz6** [comment] 2021-07-30 21:16
Seems like a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/4543

I have no idea why it's a problem. Not sure if Avalonia is related.

**Comment by maxkatz6** [comment] 2021-07-30 21:16
Just for case, I tried to build your project, and removing "obj" folder did help me.

**Comment by D0ctorWh0** [comment] 2021-07-30 21:21
Oh... I forgot that sometimes deleting obj folder solves problems. Thanks, after deleting obj folder and building everything works

**Comment by maxkatz6** [comment] 2021-07-31 02:14
Closing it for now, because it doesn't seems as a problem in Avalonia.
Otherwise ping me to reopen it.

**Closed by maxkatz6** 2021-07-31 02:14 UTC
Labels: bug
