### ISSUE TITLE
Crash when pick a file with OpenFileDialog - System.ComponentModel.Win32Exception

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaUI/Avalonia#8584] opened 2022-07-24 15:56 UTC
**Describe the bug**
Program crash when pick a file with OpenFileDialog.
I can't replicate this on my machine and never experienced this, but multiple users have reported this not-so-often bug. Some this only happen when loading from USB drive, other from internal SSD but not from USB drive.

## Crash 1 https://github.com/sn4k3/UVtools/issues/495

Loading from USB drive:

```
System.ComponentModel.Win32Exception (0x80004002): Interfaz no compatible
   at Avalonia.Win32.SystemDialogImpl.<>c__DisplayClass2_0.<ShowFileDialogAsync>b__0() in /_/src/Windows/Avalonia.Win32/SystemDialogImpl.cs:line 120
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UVtools.WPF.MainWindow.OpenFile(Boolean newWindow, FileDecodeType fileDecodeType) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\MainWindow.axaml.cs:line 1013
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 278
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at UVtools.WPF.Program.Main(String[] args) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\Program.cs:line 70
Category: Application
```

```
Operative system: Microsoft Windows 10.0.18363 X64
Processor: AMD Ryzen 5 5600X 6-Core Processor             
Processor cores: 12
Memory RAM: 10.92 / 31.93 GB
Runtime: win10-x64
Framework: .NET 6.0.5
AvaloniaUI: 0.10.14
```

## Crash 2 https://github.com/sn4k3/UVtools/issues/518

Loading from SSD internal drive:

```
System.ComponentModel.Win32Exception (0x80070057): Параметр задан неверно.
   at Avalonia.Win32.SystemDialogImpl.<>c__DisplayClass2_0.<ShowFileDialogAsync>b__0() in /_/src/Windows/Avalonia.Win32/SystemDialogImpl.cs:line 120
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at UVtools.WPF.MainWindow.OpenFile(Boolean newWindow, FileDecodeType fileDecodeType) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\MainWindow.axaml.cs:line 1015
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at UVtools.WPF.Program.Main(String[] args) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\Program.cs:line 70
Category: Application
```

```
Operative system: Microsoft Windows 6.1.7601 Service Pack 1 X64
Processor: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Processor cores: 8
Memory RAM: 5.56 / 31.87 GB
Runtime: win7-x64
Framework: .NET 6.0.7
AvaloniaUI: 0.10.16
```

**Comment by timunie** [comment] 2022-07-26 14:25
@sn4k3 I wonder about this: 
> UVtools.WPF.MainWindow.OpenFile

Can it be that you have WPF and Avalonia mixed?

**Comment by timunie** [comment] 2022-07-26 14:44
Looking into your code I see: 

https://github.com/sn4k3/UVtools/blob/315ce3bc0dfc7a950138473f66ac83e0fa119f6c/UVtools.WPF/MainWindow.axaml.cs#L1013

Can it be that the given path does not exist for some reason?

**Comment by sn4k3** [comment] 2022-07-26 14:52
If user not changed the defaults, it's null/empty by default.
But he [complains](https://github.com/sn4k3/UVtools/issues/518#issuecomment-1193338515) that when loading file from internall SSD it trigger the crash, but loading from a USB works correctly, that discard the default path setting.
I also had open his file and works for me. This is not a common bug, i had at least 4 reports about this, is very rare bug.

Can you check if by loading his file trigger any error under your machine? https://github.com/sn4k3/UVtools/releases/latest
[NippleBlock-NPT-Block.pwmb](https://drive.google.com/file/d/1-J0ZJW4ZBt3ZbzOsIWUGdPB_JOY3I5m9/view?usp=sharing)

**Comment by timunie** [comment] 2022-07-28 09:42
@sn4k3 can't reproduce at all. Also tried invalid dir names, still just works.

**Comment by sn4k3** [comment] 2022-07-28 12:45
> @sn4k3 can't reproduce at all. Also tried invalid dir names, still just works.

Yes, it's a very rare bug. I had about 4 reports of this in a fair user number. And the most anoying part is that work if from usb and the other from disk but not otherwise... One had win7 and other win10. What both share in common is a non-english language OS. Can name path raise the problem? The crash happens just after select the file.

**Comment by timunie** [comment] 2022-07-28 14:10
> Can name path raise the problem

Yes, this can be the issue. As I said, white spaces or other invalid chars can be a problem.

**Comment by maxkatz6** [comment] 2022-07-28 16:01
Tried to open `C:\привет мир\幸福\` folder and file with same `幸福` name inside of it on the internal SSD. Seems to work fine. Although I don't have USB drive near me to test.

**Comment by sn4k3** [comment] 2022-07-28 16:07
Humm... Let-me ask the user to participate here in order to debug here. Maybe he can do some test for us...

**Comment by maxkatz6** [comment] 2022-07-28 16:09
Currently inner exception with specific error line is lost.
In next stable 0.10.x version there will be fixed error handling in this class.
See https://github.com/AvaloniaUI/Avalonia/commit/2d2cd97b55f82fe811ebd8cbce9e1e933fe940a8

Logging this inner exception should help as well in finding the problem.

**Comment by maxkatz6** [comment] 2022-07-28 16:13
@sn4k3 if you can remote debug it on user's machine, I hope it's possible to step into this implementation code and see after which step it fails.

**Comment by srozinov** [comment] 2022-08-03 08:30
@sn4k3 I performed some research and discovered that the crash doesn't depends on file itself but strongly depends on how it opens.
1. If you open it using full path traveling in open dialog from C: -> Users -> ... etc - the file opens fine no matter either international characters occurs or not in the path.
2. If you open it using shortcut links under "Favorities" or "Libraries" (I have set-up some) on the left pane of the open dialog - it definitely crashes.

If you wish I can record screen of that. Hope this can help :-)

**Comment by timunie** [comment] 2022-08-03 09:32
That's interesting. Maybe we should double-check this in the Control Catalog or a sandbox App.

**Comment by sn4k3** [comment] 2022-08-03 14:48
After enable libraries and put a file there it open just fine for me, but i'm with windows 11, it may result in different path style with Windows 7?

**Comment by srozinov** [comment] 2022-08-03 15:59
Or maybe internation chars in library names... OK I'll test it under Windows 10 now.

**Comment by srozinov** [comment] 2022-08-03 16:20
OK couldn't reproduce crash in Windows 10 under any circumstances. Libraries, Favorities, links to directory, direct open file tested. All works fine. It seems an Windows 7 specific issue.

**Closed** 2023-11-16 00:10 UTC
Labels: bug, help-wanted, needs-repro, os-windows
