### ISSUE TITLE
Localization doesn't work with Default Resource File Added by Visual Studio

### ISSUE THREAD

**Issue by Elbon-Eastmage** [AvaloniaUI/Avalonia#14150] opened 2024-01-08 22:24 UTC
## Describe the bug
The resource file created by Visual Studio cannot be used in an axaml file by default.

## To Reproduce
1. Set up a new Avalonia project with the name Translation.
2. Set the Translation.Desktop project as the Startup project.
3. Right-click on on the Assets folder, and go to Add->New Item...
4. Select Resources File from the list, change the name to Resources.resx, and click Add.
5. In the resx editor, put Translation in the Name and Value fields of the first row.
6. Open up MainWindow.axaml in the Views folder.
7. Underneath the xmlns:x line, add xmlns:assets="clr-namespace:Translation.Assets"
8. Replace the string of the Window Title attribute with "{x:Static assets:Resources.Translation}"
9. Attempt to run the program.

## Expected behavior
The program should run with Translation in the title bar of the Window.

## Environment

- OS: Windows 11
- Avalonia-Version: 11.0.2

## Workaround
1. Right-click on the project in the Solution Explorer and select Edit Project File.
2. Delete the following from the file:
```
<ItemGroup>
  <AvaloniaResource Update="Assets\Resources.Designer.cs">
    <DesignTime>True</DesignTime>
    <AutoGen>True</AutoGen>
    <DependentUpon>Resources.resx</DependentUpon>
  </AvaloniaResource>
  <AvaloniaResource Update="Assets\Resources.resx">
    <Generator>ResXFileCodeGenerator</Generator>
    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
  </AvaloniaResource>
</ItemGroup>
```
3. Save the file.
4. Also delete:
```
<ItemGroup>
  <EmbeddedResource Remove="Assets\Resources.resx" />
</ItemGroup>
```
5. Save the file again.
6. Go to the Resources.resx file.
7. Change the Access Modifier at the top of the editor to Public.
8. Click Yes on the warning dialog.
9. Go to File and select Save All.
10. Attempt to run the program. The Window should come up with Translation in its title bar!
11. Any other resource files added after this should only need to have
```
<ItemGroup>
  <EmbeddedResource Remove="Assets\(Name of resource file)" />
</ItemGroup>
```
removed from the project file in order to work.

## Additional context
I ran into this bug when following the [Avalonia Localization Tutorial](https://docs.avaloniaui.net/docs/guides/implementation-guides/localizing). After coming across this [bug report](https://github.com/AvaloniaUI/Avalonia/issues/12159) and [discussion](https://github.com/AvaloniaUI/Avalonia/discussions/12164), I tried setting the accessibility level for the Resources.resx file to public. However, while this sometimes worked, it sometimes didn't.

Eventually, I discovered that the generated Resources.Designer.cs file was parented to Resources.resx. If I deleted the ItemGroup for the designer file in the project file and saved it, the designer file would be unparented. This, combined with the other steps I outlined, would allow (finally!) the Resources.resx file to be reliably used for localization.

Even if this bug doesn't get fixed, I hope my workaround will help other people avoid the pain I went through figuring this out.

**Comment by timunie** [comment] 2024-01-09 05:26
We need a not working sample here. It works for me. Also please use latest version which is 11.0.6 or nightly to open issues. Thx.

**Comment by Elbon-Eastmage** [comment] 2024-01-09 20:46
Thanks for the heads up about the latest version. I just tried it out, but the bug still persists. Here is the sample:
[TranslationBug.zip](https://github.com/AvaloniaUI/Avalonia/files/13878881/TranslationBug.zip)

I hope this helps!

**Comment by timunie** [comment] 2024-01-10 14:57
strange thing here, it doesn't work with your resources but if I add them on my own in the same folder, it works directly. So no idea how to help here besides asking you to check your resx tooling. Another option for smaller Apps is to use DynamicResources.

**Comment by Elbon-Eastmage** [comment] 2024-01-10 21:13
Don't you just love inconsistent bugs?

I have a couple of questions.

First, when you added a Resources.resx file, did the generated Resources.Designer.cs file get placed as a child of it?

Second, where would I go in Visual Studio to check my resx tooling?

**Comment by timunie** [comment] 2024-01-11 05:29
I've a stupid idea. What if you name the file different? Like Translations? If that works that would still be weird but worth a try

**Comment by timunie** [comment] 2024-01-11 10:58
Okay I guess the issue is that the Resource is marked as AvaloniaResource which may be wrong here. Rider does it correctly, but VS not. If I mark the file as EmbeddedResource on my own, it works as expected. 

If I use a different folder than Assets (Lang for example) it also does it right. Docs may need an update here.

**Closed by timunie** 2024-01-11 10:58 UTC
Labels: bug
