### ISSUE TITLE
Control not visible

### ISSUE THREAD

**Issue by mterwoord** [AvaloniaUI/Avalonia#1333] opened 2017-12-24 12:58 UTC
See attached file [AvaloniaRepro.zip](https://github.com/AvaloniaUI/Avalonia/files/1584837/AvaloniaRepro.zip)

Contains a custom control (MyControl) which "dynamically" creates a control (hardcoded to MyUserControl in the test).

With daily build 0.5.2-build4248-alpha and current "release" on nuget, this works fine, but with latest master, the usercontrol isn't shown. The control is added to the visual tree, but not the children.

**Comment by danwalmsley** [comment] 2017-12-25 22:04
![image](https://user-images.githubusercontent.com/4672627/34343216-9299c08a-e9bf-11e7-9b03-d5f5781a8ea9.png)

**Comment by mterwoord** [comment] 2017-12-27 17:09
With master (of 1-2 days ago..) I get:

![afbeelding](https://user-images.githubusercontent.com/114143/34387895-00b14fc6-eb31-11e7-8897-fba880c10552.png)

with an empty mainform. The MyUserControl entry in the visual tree cannot be expanded (meaning, it thinks there are no children there), but the COntent of the MyUserControl is of type Border (which is correct)

**Comment by grokys** [comment] 2018-01-07 14:28
I've taken a look into this and it's actually expected behavior, however unintuitive. What is happening is that when `ContentPresenter` detects that it's in a control template, it expects the parent control to handle the bookkeeping of the logical tree - `ContentControl` does this via `ContentControlMixin` for example.

This is because when you have a `ContentControl` with a `ContentPresenter`, then the control displayed by the `ContentPresenter` is actually the logical child of the `ContentControl`. There's no way that the  `ContentPresenter` knows how to handle this, so it just says "I'm in a control template, that's my parent's business".

The simple way to fix this would be to simply inherit from `ContentControl` instead of directly from `TemplatedControl`. Another way to fix it would be to use `ContentControlMixin` which will handle the bookkeeping for you.

I think there are better ways we could do all this that would make this behavior less surprising, I probably need to do another pass on how `ContentControl`/`ContentPresenter` interact. That will come later however, so closing this for now.

**Closed by grokys** 2018-01-07 14:28 UTC
