### ISSUE TITLE
Extreme memory usage in GPUInterop

### ISSUE THREAD

**Issue by Tape-Worm** [AvaloniaUI/Avalonia#10457] opened 2023-02-24 06:45 UTC
**Describe the bug**
I've been using the GPUInterop sample to build my own interop layer for my D3D11 graphics library and Avalonia. And I actually got it working!  So.. yay! 

However, when it ran for a few seconds, the memory usage became insane. Just consuming a ton of RAM.  So, to ensure that I didn't do anything wrong I ran the GPUInterop sample (with DISCO turned on) and waited for like 5-10 seconds. That's when I saw this:
![image](https://user-images.githubusercontent.com/9710137/221110483-0100e65a-8cad-4f7a-8443-8e83acf1784c.png)
As you can see, the memory usage is crazy.

In my own code, I was able to stop the memory leakage when I commented out this line of code:
```LastPresentation = _surface.UpdateWithKeyedMutexAsync(_imported, 1, 0);```

**To Reproduce**
Run the GPUInterop sample for several seconds and turn the DISCO slider up.

**Expected behavior**
Stable memory usage.

**Desktop (please complete the following information):**

- OS: Windows 11
- GPU: Geforce 3090 RTX (Driver 527.56)
- Avalonia Version: Latest from master (pulled prior to running the GPUInterop sample).

**Comment by Tape-Worm** [comment] 2023-02-24 20:50
I just wanted to add that I have the same issue with the D3D11 and the Vulkan demo, so it doesn't seem to be API specific.

**Comment by jcyuan** [comment] 2023-02-28 12:37
feels like something related with #10503

**Comment by afunc233** [comment] 2023-05-11 08:39
any improve ?

**Comment by jcyuan** [comment] 2023-05-27 09:14
.... i found the same bug here. 😱

**Comment by jcyuan** [comment] 2023-06-01 00:51
> any improve ?

it was fixed

**Comment by kekekeks** [comment] 2023-06-01 05:22
We've localized the issue ([SKSurface is being destroyed without an active context here](https://github.com/AvaloniaUI/Avalonia/blob/57eb77b474a2070a2b85983e213909cb2f925727/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionDrawingSurface.cs#L44)), but the fix isn't pushed yet since we were busy wrapping up changes required for RC1.

**Comment by afunc233** [comment] 2023-06-01 05:39
> We've localized the issue ([SKSurface is being destroyed without an active context here](https://github.com/AvaloniaUI/Avalonia/blob/57eb77b474a2070a2b85983e213909cb2f925727/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionDrawingSurface.cs#L44)), but the fix isn't pushed yet since we were busy wrapping up changes required for RC1.

wow thx your reply , and RC1 means Avalonia RC1？

**Comment by Tape-Worm** [comment] 2023-06-08 02:04
> We've localized the issue ([SKSurface is being destroyed without an active context here](https://github.com/AvaloniaUI/Avalonia/blob/57eb77b474a2070a2b85983e213909cb2f925727/src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionDrawingSurface.cs#L44)), but the fix isn't pushed yet since we were busy wrapping up changes required for RC1.

So does this mean it's not in the master nightly build yet?

**Comment by maxkatz6** [comment] 2023-06-08 03:28
@Tape-Worm possible fix should be in the master as for now https://github.com/AvaloniaUI/Avalonia/pull/11643

**Comment by Tape-Worm** [comment] 2023-06-08 03:58
OK. I see the changes in the code. But it looks like the nuget packages on the nightly ci build are from yesterday, I'm guessing those changes haven't made it up there yet since I'm still experiencing memory issues. I'll try to check it tomorrow.

**Comment by hez2010** [comment] 2023-06-27 12:20
Can confirm this has been fixed in master.

**Closed** 2023-06-27 20:57 UTC
Labels: bug

**Comment by hez2010** [comment] 2023-06-28 19:06
I hit this issue again on WSL with the master branch.
While on Windows this cannot be reproduced again.

**Comment by Tape-Worm** [comment] 2023-07-03 21:43
So, I pulled from the avalon-all nuget packages (the nightly masters haven't been updated since June 5th), and everything looks great.  I'm able to get my stuff rendering with no memory issues.

Have a look:
<img width="1586" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/9710137/651d5403-89f5-467e-8ee3-9087feb8d73d">

**Comment by timunie** [comment] 2023-07-04 07:27
Note: Nightly feed has moved to: https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed
