### ISSUE TITLE
Multitouch input crashes Avalonia app on Raspberry Pi 4B / Linux (arm-x64)

### ISSUE THREAD

**Issue by lubomirtrubac** [AvaloniaUI/Avalonia#14249] opened 2024-01-17 16:05 UTC
## Describe the bug
Application with some dummy button (no event wired), hold with two fingers for a couple of seconds, sometimes needs more than one try. Application crashes to console with unhandled System.NullReferenceException. Tried on Raspbian x64 Lite using DRM and Raspbian x64 with full desktop - behavior is the same.

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Input.Gestures.PointerReleased(RoutedEventArgs ev)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.TouchDevice.ProcessRawEvent(RawInputEventArgs ev)
   at Avalonia.RawEventGrouper.Dispatch(RawInputEventArgs ev)
   at Avalonia.Controls.Platform.ManagedDispatcherImpl.RunLoop(CancellationToken token)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at LinuxFramebufferPlatformExtensions.StartLinuxDirect(AppBuilder builder, String[] args, IOutputBackend outputBackend, IInputBackend inputBackend)
   at ARTRA.Dochadzka.Terminal.Desktop.Program.Main(String[] args)

## To Reproduce

1. Follow steps to run Avalonia App on Raspberry Pi at: https://docs.avaloniaui.net/docs/guides/platforms/rpi/running-on-raspbian-lite-via-drm
2. Add a dummy button to the main view
3. Run application
4. Touch that button repeatedly with 2+ fingers 
5. Application crashes

## Expected behavior
Application should stay open

## Environment 

- OS: Linux - Raspbian x64 Lite / full with desktop
- Avalonia-Version: 11.0.7
- HW: Raspberry Pi 4B 8GB

**Comment by maxkatz6** [comment] 2024-01-17 23:07
Should be fixed in the master: https://github.com/AvaloniaUI/Avalonia/pull/14140/files

**Comment by lubomirtrubac** [comment] 2024-01-18 14:50
Thank you for your advice. No, it is not fixed in nightly builds, I have tried:
11.0.999-cibuild0043664-beta
11.1.999-cibuild0043666-beta
Both behave the same - using 2+ touches simultaneously and holding for a couple of seconds repeatedly crashes the app, now without any stacktrace info, just straight to console.

11.0.999
This version behaves a little differently - application just freezes and does not respond anymore.

**Comment by pkstrsk** [comment] 2024-03-23 16:10
We are also experiencing the same problem, latest version of Avalonia.

**Comment by zabolotnev** [comment] 2024-03-25 09:53
@maxkatz6 The problem is in [Gestures.PointerReleased](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Input/Gestures.cs#L300). In some cases value `s_lastHeldPointer` is `null` and `s_isHolding` is `true`. It looks like some kind of race condition, or unexpected order of calls. Anyway it causes NRE. I'll try to submit a PR today.

**Comment by lubomirtrubac** [comment] 2024-03-25 10:39
@lsoft @pkstrsk Hello, unfortunately no - I did not even try to find a solution, because I had to implement other parts of the app first. 
@zabolotnev Thank you for finding a solution. Hope it will be solved in upcomming release of Avalonia.

**Comment by maxkatz6** [comment] 2024-04-05 23:55
Fixed by https://github.com/AvaloniaUI/Avalonia/pull/15117

**Closed by maxkatz6** 2024-04-05 23:55 UTC
Labels: bug, help-wanted, os-linux
