### ISSUE TITLE
cjk IME has wrong position after Tooltip isopen on Windows

### ISSUE THREAD

**Issue by peng007ge** [AvaloniaUI/Avalonia#11103] opened 2023-04-23 02:27 UTC
**Describe the bug**
cjk IME position has wrong position after Tooltip isopen.
any popup window has a similar effect.

**To Reproduce**
1. type text in the TextBox
2. The mouse triggers the tooltip
3. type text in another TextBox 

**Expected behavior**
cjk IME has right position.

**Screenshots**
![1](https://user-images.githubusercontent.com/31547137/233815609-ef49edaa-d919-4ccb-9e7f-d9f892d5e8b8.jpg)
![2](https://user-images.githubusercontent.com/31547137/233815615-4bd4ad93-cde3-4722-b965-7863976140e2.jpg)
![3](https://user-images.githubusercontent.com/31547137/233815618-16380762-6016-4773-90b8-d35a39ac9527.jpg)

**Desktop (please complete the following information):**

- OS: Windows10
- Version [0.10.14]-[11.0.0 Preview 4]

**Comment by maxkatz6** [comment] 2023-04-23 02:43
> Version [0.10.14]-[11.0.0 Preview 4]

Can you try latest nightly?

**Comment by maxkatz6** [comment] 2023-04-23 02:43
Probably is a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/8758

**Comment by peng007ge** [comment] 2023-04-24 00:38
> Probably is a duplicate of #8758
@maxkatz6 
11.0.0 Preview6 not fix that bug, maybe the next version,
Use 0.10.x,  I can't open the IME on linux-arm64 only
After upgrading to 11.0.0, I can't open the IME at all on linux(x64 & arm64), EnableIme = true; Souguo IME
Any suggestions please?

**Comment by maxkatz6** [comment] 2023-04-24 22:23
Available with preview7

**Closed by maxkatz6** 2023-04-24 22:23 UTC
Labels: bug
