### ISSUE TITLE
Problems with av_libglesv2.dll

### ISSUE THREAD

**Issue by sekkit** [AvaloniaUI/Avalonia#10441] opened 2023-02-23 06:42 UTC
Use preview-5 with av_libglesv2.dll, together with options set below
ExtendClientAreaToDecorationsHint="True"
ExtendClientAreaChromeHints="NoChrome"  
ExtendClientAreaTitleBarHeightHint="40"  
 will result in no DropShadow window.

**Comment by maxkatz6** [comment] 2023-02-24 02:22
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/9989

**Closed by maxkatz6** 2023-02-24 02:22 UTC
Labels: bug, os-windows
