### ISSUE TITLE
Pixelated Image Rendering in 11 Preview 8

### ISSUE THREAD

**Issue by 3aIno** [AvaloniaUI/Avalonia#11319] opened 2023-05-11 07:25 UTC
**Describe the bug**

When rendering images in Preview 8, they appear pixelated compared to the previous versions where they were smooth.

Preview 8
![image](https://github.com/AvaloniaUI/Avalonia/assets/121347511/78bceb3b-e4c0-4492-ab26-f5bb139eee84)

Preview 7
![image](https://github.com/AvaloniaUI/Avalonia/assets/121347511/17e2b61b-2ec3-4d79-8864-854aac6c57fb)

**To Reproduce**

1. Add an image as an Avalonia Resource.
2. Reference the image as the source of an Image control.

```
<Image Source="../Assets/Logos/avalonia.png"/>
```

**Desktop:**

- Windows
- Version 11 Preview 8

**Comment by tomenscape** [comment] 2023-05-11 07:45
This may be related to #9584. Does adding `RenderOptions.BitmapInterpolationMode="HighQuality"` to your image (or a parent) change rendering?

**Comment by Gillibald** [comment] 2023-05-11 08:53
The default behavior isn't altering the image by default. If you want interpolation you need to enable it explicitly.

**Comment by tomenscape** [comment] 2023-05-11 09:22
If I run my window on a screen with a different DPI from the one the window was designed for, then all images are altered (upscaled) all the time. And they look terrible with the new default scaling.

Luckily it's easy enough to work around this globally by setting the interpolation mode whenever any window opens. But I find it strange that I have to do that.

**Comment by dbriard** [comment] 2023-05-11 19:26
> If I run my window on a screen with a different DPI from the one the window was designed for, then all images are altered (scaled) all the time. And they look terrible with the new default scaling.
> 
> Luckily it's easy enough to work around this globally by setting the interpolation mode whenever any window opens. But I find it strange that I have to do that.

Noticed that too after updating to preview 8. I have images with UI size equal to pixel size and they are now  crappy, as my Windows use 125% dpi. Fixed with interpolation, but basically it always need to be enabled as users have various dpi settings.

**Comment by adirh3** [comment] 2023-05-13 17:08
I agree with the above, not sure why this change was made but I think it should be enabled by default like before.

**Closed** 2023-05-17 06:39 UTC
Labels: bug

**Comment by hhyyrylainen** [comment] 2023-09-04 17:22
Should this fix already be available? I just updated to version 11 and noticed all my icons have this issue. I verified that manually adding that highquality mode fixes it. I have the latest version from nuget (11.0.4).

**Comment by timunie** [comment] 2023-09-04 19:05
Do you have probably the switch overridden somewhere else?

**Comment by hhyyrylainen** [comment] 2023-09-04 19:11
Grepping for the individual words `RenderOptions`, `BitmapInterpolationMode`, and `HighQuality` I only get matches in my built binaries (i.e. I don't use those words at all in my source code). So unless the global option has some other way to set it, I don't have it overwritten.

**Comment by timunie** [comment] 2023-09-05 06:37
Was just an idea. However, you can set it in the root of your visual which will apply to all children afaik. 

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        [...]
        RenderOptions.BitmapInterpolationMode="HighQuality"
        Title="AvaloniaApplication1">
```

**Comment by hhyyrylainen** [comment] 2023-09-05 06:39
That does indeed work if I add that, but doesn't that mean that there's been a regression in Avalonia since this was fixed as the fix is no longer working?

**Comment by timunie** [comment] 2023-09-05 06:43
Not sure if we are talking about the same. But closed issues will not get much attendence. So if you think it's something to be discussed further, please open a new Q&A and provide a very minimal sample to reproduce. At least I didn't notice it on my end but probably my images have a different resultion right away. Thx.

**Comment by hhyyrylainen** [comment] 2023-09-05 08:18
I opened a new issue where I show the issue is easy to trigger when starting from the mvvm template with just a few changes: https://github.com/AvaloniaUI/Avalonia/issues/12786
