### ISSUE TITLE
Program crashes after some time working on MacOS Catalina

### ISSUE THREAD

**Issue by dvygolov** [AvaloniaUI/Avalonia#3200] opened 2019-11-02 17:16 UTC
Hello, guys. I have a naughty bug: the program I've developed works for a minute or two and then crashes. Everything worked well before, but the users updated their OS to MacOS Catalina and now we have this strange behavior. The error message says:
`assertion failure: “_needsGeometryInWindowDidChangeNotificationCount < (1 << 8) - 1” -> %lld`

The program is a simple form with a few inputs and dropdowns, nothing complex.
Do you happen to know any workaround?

**Comment by danwalmsley** [comment] 2019-11-02 20:02
@dvygolov do you have a project you can send me that I can debug or a cut down version to repro?

Any more stack trace info? Are you using the 0.9.0-preview4 version?

**Comment by danwalmsley** [comment] 2019-11-09 19:18
@dvygolov please give feedback on `0.9.0-preview7` release, does the issue persist?

Its not long until we release, and without further information or feedback we are unable to address your issue.


Many thanks Dan

**Comment by MythicLionMan** [comment] 2019-11-29 21:13
This looks like an instance of a bug that I'm researching. Apparently Catalina limits the number of cursor rects. Adding more than ~255 to one view will cause a crash. See here for more details:

https://forums.developer.apple.com/thread/124111

**Comment by kekekeks** [comment] 2019-11-30 16:31
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/3000
Fixed by https://github.com/AvaloniaUI/Avalonia/pull/3007 which removes the usage of cursor rects

**Closed by kekekeks** 2019-11-30 16:31 UTC
Labels: bug, osx
