### ISSUE TITLE
MenuItem command not working on mouse click, but it's working on Enter keydown

### ISSUE THREAD

**Issue by Abbossbek** [AvaloniaUI/Avalonia#9448] opened 2022-11-15 13:59 UTC
**Describe the bug**
MenuItem command not working on mouse click, but it's working on Enter keydown. 

**To Reproduce**

1. Create avalonia app
2. Add menu and menuitems to mainwindow
3. Create mainviewmodel and create a method in it and bind to menuitem
4. Click and see 

**Avalonia libs version:** 11.0.0-preview1
**OS:** Windows 11

**Comment by timunie** [comment] 2022-11-15 18:44
Can you try two things?

1. Update to latest prerelease 11.0 prev 4
2. Provide a minimal sample if the issue is still present 

Thanks

**Comment by StefanKoell** [comment] 2023-10-02 18:14
Unfortunately I still see the same issue with **11.0.4**. When I do a simple binding like this:
```
                        <Menu x:Name="Menu" ItemsSource="{Binding MainMenuViewModel.MenuItems}">
                            <Menu.Styles>
                                <Style Selector="MenuItem" x:DataType="commands:CommandBase">
                                    <Setter Property="Header" Value="{Binding Caption}" />
                                    <Setter Property="ItemsSource" Value="{Binding MenuItems}" />
                                    <Setter Property="Command" Value="{Binding Command}" />
                                </Style>
                            </Menu.Styles>
                        </Menu>
```
My CommandBase is fairly simple:
```
internal abstract partial class CommandBase : ObservableObject
{
    [ObservableProperty] 
    private string _caption = string.Empty;

    [ObservableProperty] 
    private ObservableCollection<CommandBase>? _menuItems;

    public ICommand? Command { get; set; }
}
```

Here's how one of my model looks like:
```
internal sealed class FileNew : CommandBase
{
    public FileNew()
    {
        Caption = "New";
        Command = new RelayCommand(Execute, CanExecute);
    }

    public bool CanExecute()
    {
        return true;
    }

    public void Execute()
    {
        MessageBox.Show("File New");
    }
}
```

The CanExecute is called to determine whether or not to disable the menu item. The Execute method is only called when using the keyboard but never when clicking the menu item using the mouse.

**Comment by timunie** [comment] 2023-10-04 09:17
please attach a minimal sample. The code posted is not enough to know all needed info. Thx.

**Comment by StefanKoell** [comment] 2023-10-04 15:49
After some investigation, it turns out it's probably an issue with the container control (3rd party title bar container). Stand-alone, the menu is working. Having it inside this container, it behaves differently. I'm already working with the vendor to see how this can be resolved.

**Comment by timunie** [comment] 2023-10-05 09:21
@StefanKoell closing this for now as it is out of our scope imo. If you think it is a bug in Avalonia, please come back to me and explain what you think we can do. Thx for your understanding.

**Closed by timunie** 2023-10-05 09:21 UTC
Labels: bug

**Comment by StefanKoell** [comment] 2023-10-05 09:45
According to the 3rd party vendor, the issue will be fixed. I can't really say if the OP still has the issue though.

**Comment by timunie** [comment] 2023-10-05 09:58
@Abbossbek if you still have an issue, you are also welcome to ping me.
