### ISSUE TITLE
custom font failed in 11.1.0-beta1

### ISSUE THREAD

**Issue by ismlsmile** [AvaloniaUI/Avalonia#14923] opened 2024-03-12 06:33 UTC
### Describe the bug

I am using custom font in Desktop project:

```
public static AppBuilder BuildAvaloniaApp()
    => AppBuilder.Configure<App>()
        .UsePlatformDetect()
        //.WithInterFont()
        .With(new FontManagerOptions
        {
            DefaultFamilyName = "微软雅黑",
            FontFallbacks = new FontFallback[1]
            {
                new FontFallback
                {
                    FontFamily = new FontFamily("微软雅黑")
                }
            }
        })
        .LogToTrace()
        .UseReactiveUI();
```
This code works well in 11.0.10, but failed in 11.1.0-beta1, throws this error in MainWindow.axaml.cs:
System.InvalidOperationException:“Could not create glyphTypeface.”

### To Reproduce
```
With(new FontManagerOptions
        {
            DefaultFamilyName = "微软雅黑",
            FontFallbacks = new FontFallback[1]
            {
                new FontFallback
                {
                    FontFamily = new FontFamily("微软雅黑")
                }
            }
        })
```

### Avalonia version

11.1.0-beta1

### OS

Windows

**Comment by Arafath101** [comment] 2024-03-12 07:19
Hahn

**Comment by timunie** [comment] 2024-03-12 07:38
that's unexpected. Where do you load the font from?

**Comment by ismlsmile** [comment] 2024-03-12 07:42
It is a system font., and it is ok in 11.0.x version.

**Comment by ismlsmile** [comment] 2024-03-12 07:46
I think some font handling logic might have changed in "Desktop" Project in 11.1.0-beta1.
I tried this font project: "https://github.com/Quick-AvaloniaFonts/Quick.AvaloniaFonts.SourceHanSansCN", it also failed in Desktop  project(but no error,  just do not take effect), but I tried to add this font to "Browser" project, it works well.

**Comment by timunie** [comment] 2024-03-13 07:35
yeah looks like a duplicate of #13585. Tracking it in the original issue.

**Closed by timunie** 2024-03-13 07:35 UTC
Labels: bug, area-textprocessing

**Comment by Gillibald** [comment] 2024-03-13 14:07
We rely on Skia's font manager and that has a different implementation on each platform. We currently don't use any localized family name and that's why this is failing.
