### ISSUE TITLE
AdornerLayer outside of adorners is not redrawn when an adorner with content outside of the adorned element is moved

### ISSUE THREAD

**Issue by appel1** [AvaloniaUI/Avalonia#13619] opened 2023-11-15 15:28 UTC
## Describe the bug
View is not properly invalidated when an adorner drawing outside of the bounding box of the adorned element is moved. 

## To Reproduce
The following code draws two rectangles on a canvas and animates their positions. Both have adorners with a rectangle with negative margin so that it is drawn partially outside of the adorned element. The first rectangle with ClipToBounds="True" leaves a trail of blue from the adorner while the other does not. 

It does not happen if you set a background on the Canvas. Resizing the Window redraws things. 

```xaml
  <Canvas>
    <Rectangle Name="Target" Canvas.Left="10" Canvas.Top="10" Width="100" Height="100" ClipToBounds="True" StrokeThickness="1.0" Stroke="Black">
      <Rectangle.Styles>
        <Style Selector="Rectangle#Target">
          <Setter Property="(AdornerLayer.Adorner)">
            <Template>
              <Rectangle HorizontalAlignment="Left" VerticalAlignment="Top" Margin="-4 -4 0 0" Height="8" Width="8" Fill="Blue"/>
            </Template>
          </Setter>
          <Style.Animations>
            <Animation Duration="0:0:30">
              <KeyFrame Cue="0%">
                <Setter Property="(Canvas.Left)" Value="10"/>
                <Setter Property="(Canvas.Top)" Value="10"/>
              </KeyFrame>
              <KeyFrame Cue="100%">
                <Setter Property="(Canvas.Left)" Value="1000"/>
                <Setter Property="(Canvas.Top)" Value="1000"/>
              </KeyFrame>
            </Animation>
          </Style.Animations>
        </Style>
      </Rectangle.Styles>
    </Rectangle>
  
    <Rectangle Name="Target2" Canvas.Left="150" Canvas.Top="10" Width="100" Height="100" ClipToBounds="False" StrokeThickness="1.0" Stroke="Black">
      <Rectangle.Styles>
        <Style Selector="Rectangle#Target2">
          <Setter Property="(AdornerLayer.Adorner)">
            <Template>
              <Rectangle HorizontalAlignment="Left" VerticalAlignment="Top" Margin="-4 -4 0 0" Height="8" Width="8" Fill="Blue"/>
            </Template>
          </Setter>
          <Style.Animations>
            <Animation Duration="0:0:30">
              <KeyFrame Cue="0%">
                <Setter Property="(Canvas.Left)" Value="150"/>
                <Setter Property="(Canvas.Top)" Value="10"/>
              </KeyFrame>
              <KeyFrame Cue="100%">
                <Setter Property="(Canvas.Left)" Value="1150"/>
                <Setter Property="(Canvas.Top)" Value="1000"/>
              </KeyFrame>
            </Animation>
          </Style.Animations>
        </Style>
      </Rectangle.Styles>
    </Rectangle>
  </Canvas>
```

## Expected behavior
There should be no traces of the adorner left behind at its previous locations. 

## Screenshots
<img width="279" alt="image" src="https://github.com/AvaloniaUI/Avalonia/assets/973314/2e321d71-e8a6-4b41-af63-bf5669dbd97a">

## Environment

- OS: Windows 11
- Avalonia-Version: 11.0.5

**Comment by MrJul** [comment] 2023-11-15 15:52
Thank you for reporting.
I'm closing this as a duplicate of #10701.

**Closed by MrJul** 2023-11-15 15:52 UTC
Labels: bug
