### ISSUE TITLE
iOS app doesn't work installing on macOS (MacCatalyst)

### ISSUE THREAD

**Issue by Amenti** [AvaloniaUI/Avalonia#15019] opened 2024-03-17 10:06 UTC
### Describe the bug

When deployed to the App Store an iOS app installed on macOS freezes after the first click on a button. 

### To Reproduce

- Create iOS app with 1 button on it
- Deploy iOS app to App Store
- Allow installation on M1 Mac’s in Apple Developer Portal
- Install App via MacOs App Store on macOS with M1 chip
- click on button

### Expected behavior

No freeze. 

### Avalonia version

11.1.0-beta1

### Additional context

This worked before but I don‘t know exactly when it stopped. Possibly related to #15011 .

**Comment by maxkatz6** [comment] 2024-03-18 23:04
Just to confirm, do you mean installing iOS app on macOS, like MacCatalyst?
It's not supported. Primary reason is that we use EGL by default, can be switched to Metal in iOSPlatformOptions.
But SkiaSharp 2.88 has issues with Metal, which should be fixed in 3.0 version (you need to install it manually).

**Comment by Amenti** [comment] 2024-03-19 05:20
Well, I mean [installation like this](https://support.apple.com/en-us/guide/app-store/fird2c7092da/mac) on macOS but I don’t think this „emulation“ of iOS apps on macOS Apple introduced with the M1 uses MacCatalyst at all. 

I published my iOS app on macOS for some time like that when it still used Xamarin.Forms which didn’t support MacCatalyst afaik. 

When I switched to Avalonia the same emulation worked great until 11.1. Even if that never was the intention it just worked and I had some very happy users. 😅

**Comment by maxkatz6** [comment] 2024-03-19 05:50
Xamarin.Forms didn't support a dedicated MacCatalyst target, but a typical iOS app still can run on macOS this way, yes.

**Comment by maxkatz6** [comment] 2024-03-19 05:51
> When I switched to Avalonia the same emulation worked great until 11.1. 

Some logs, from the app and from the console ([diagnostic app](https://support.apple.com/guide/console/welcome/mac)) might help

**Comment by MikeCodesDotNET** [comment] 2024-03-20 06:51
Obviously, if it was working with 11.0, then we want to make it work with 11.1, but I'm curious as to why you wouldn't deploy a Mac version to the app store instead. 

What's the benefit of deploying an iOS app to macOS when you've used Avalonia?

**Comment by Amenti** [comment] 2024-03-20 13:39
> > When I switched to Avalonia the same emulation worked great until 11.1.
> 
> Some logs, from the app and from the console ([diagnostic app](https://support.apple.com/guide/console/welcome/mac)) might help

I did unpublish the app actually because of the angry mails of new users but I'll see what I can do.

I'm actually quite sure that #15011 is the cause of this problem because it behaves remarkably similar (No input possible, buttons stays pressed) and stopped working at the same time.

**Comment by Amenti** [comment] 2024-03-20 13:48
> Obviously, if it was working with 11.0, then we want to make it work with 11.1, but I'm curious as to why you wouldn't deploy a Mac version to the app store instead.
> 
> What's the benefit of deploying an iOS app to macOS when you've used Avalonia?

Well, initially this was a Xamarin.iOS app and I had to realize that Xamarin.MacOS had so many hard to diagnose and fix errors that it was more feasible to "release" the iOS-App for macOS M1 machines because that just worked and at least made users with a newer MacBook happy for now.

After porting the Xamarin.iOS app to Avalonia (which was awesome btw) this decision was reconsidered, and I started working on the MacOS-port. My problem is the time I still need to finish the dedicated MacOS-app since I need to be able to support users of the existing app version in the meantime.

**Comment by MikeCodesDotNET** [comment] 2024-03-20 13:50
Thanks for sharing your use case! Is your app in the iOS app store? I'd love to check it out!

**Comment by Amenti** [comment] 2024-03-20 13:59
> Thanks for sharing your use case! Is your app in the iOS app store? I'd love to check it out!

Of course, [you can find it here](https://itunes.apple.com/de/app/teacherstudio/id1145795564). It helps teachers to manage grades, lessons, schedule, todos. It's only available in Germany and some other European countries though.

**Comment by maxkatz6** [comment] 2024-03-20 21:33
@Amenti Just in case, can you try latest nightly builds? That are start with `11.2.999`. See https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed

Main difference is that Metal is enabled by default. 

Although, I assume, it's also hard to reproduce for you, since app is unlisted for macOS atm.

**Comment by maxkatz6** [comment] 2024-03-20 21:41
Hopefully, this issue will also be fixed by #15061. Will keep it open for now.

**Comment by Amenti** [comment] 2024-03-22 09:13
@maxkatz6 The fix #15061 did indeed fix the problem on macOS. Thanks a lot. :)

**Closed** 2024-03-22 19:18 UTC
Labels: bug, needs-repro, os-macos, os-ios
