### ISSUE TITLE
High CPU usage on macOS?

### ISSUE THREAD

**Issue by foxt** [AvaloniaUI/Avalonia#11070] opened 2023-04-19 20:23 UTC
**Describe the bug**
After creating an app from the `avalonia.app` and running it, I see high CPU usage on my Mac (approx 6-10% on a M1 Max). If I run the same project on Windows, I see very low CPU usage, which is expected from an application idling (0.48% on a 10700k).

Doing actions such as moving the mouse on the window sends the CPU up to 35% CPU, whereas on Windows it uses 8%.

**To Reproduce**

`dotnet new avalonia.app`
`dotnet run`

**Expected behavior**
After the application initialised, the CPU should drop down to a reasonable level.

**Screenshots**
![image](https://user-images.githubusercontent.com/12257112/233190134-28e58080-b95f-41c1-9f85-c3d382cce370.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)] macOS Ventura 13.3 (MacBook Pro, 14-inch, 2021, M1 Max)
- Version [e.g. 0.10.0-rc1 or 0.9.12] 0.10.18

**Additional context**
(Windows numbers were multiplied by x16 from the taskmgr value, as macOS uses per-core CPU values, whereas Windows uses totals)

**Comment by kekekeks** [comment] 2023-04-19 20:36
Note that CPU usage on Windows is measured differently. Windows task manager shows you the the percentage of _all_ cores usage, while macOS (and pretty much every other platform) shows the percentage of singe core usage (i. e. it's possible to have more than  100% usage).

**Comment by foxt** [comment] 2023-04-19 20:38
@kekekeks Yeah, for my numbers in the issue I multiplied all the Windows numbers by 16.

**Comment by GabrielHalvonik** [comment] 2023-08-14 15:23
I am also interested in this one. It does not seem to be expected behaviour. I guess some clock is running on background constantly. Any initiative to fix it?

**Comment by timunie** [comment] 2023-08-14 15:54
@GabrielHalvonik which Avalonia version? Does it also happen in release mode?

**Comment by GabrielHalvonik** [comment] 2023-08-14 16:08
Well for me, I observed this pretty much constantly during last year in all versions I tried on MB Air M1...including latest 11.0.3 one. This is minimal repro I tried, even without rendering any window, cpu idle is constantly hanging somewhere around 7%. With or without window to render.
 
<img width="853" alt="Screenshot 2023-08-14 at 18 03 17" src="https://github.com/AvaloniaUI/Avalonia/assets/60801120/75457a33-4ba5-44b1-afa1-c54ff5fceae5">

(this one is 11.0.3 with .net 8 preview)

**Comment by timunie** [comment] 2023-08-15 06:36
@GabrielHalvonik I think net8 is not officially supported yet. There are some known issues with this preview, see 
- https://github.com/AvaloniaUI/Avalonia/issues/12225
- https://github.com/AvaloniaUI/Avalonia/issues/9503

**Comment by GabrielHalvonik** [comment] 2023-08-15 11:40
It behaves the same way in the previous version.

**Comment by GabrielHalvonik** [comment] 2023-08-30 16:15
Btw did anyone else encountered same issue, or am I only one? Seems to me like big issue to not having any attention, so want to be sure, that problem is not on my side.

**Comment by timunie** [comment] 2023-08-30 19:08
My previous comment is still valid. Net8 still may have some issues. Also do you observe it in release mode without any debugger attached? 

In general .Net apps are kinda known to have high memory usage if there is enough memory available.

**Comment by GabrielHalvonik** [comment] 2023-08-31 00:08
Well it behaves exactly the same in dotnet 7 (currently tested with newest Avalonia 11.0.4 again) with debug/release/deploy mode. Exactly same problem as OP mentioned, but his post was pretty much unanswered for couple months, and my try to revive this issue seems not bring any relevant suggestions also. 
Also note that this issue is about CPU usage, not RAM consumption. I mean when picking up language with GC with excess RAM consumption is probably everyone reconciled, but around 7% cpu usage on idling/minimized application can be dealbreaker. (no matter that windows calculate percentages differently, it is still huge consumption for some minimal-style apps or just keeping app running in background)
I think it may be related to constantly looping of animation clock, even if nothing is subscribed as mentioned in those issues :

[https://github.com/AvaloniaUI/Avalonia/issues/7608](url)
[https://github.com/AvaloniaUI/Avalonia/pull/9554](url)

but they seems to be kind of abandoned (for such a significant issue) 
(also not entirely really sure if it is source of problem in this case)

**Comment by timunie** [comment] 2023-08-31 07:52
@GabrielHalvonik we have many things going on in the background to improve performance. However, this one seems to be not that easy and therefor the mentioned PR was closed. If you have some ideas, you can test them using src/samples/Sandbox and ControlCatalog. (I have no Mac to test on my own). 

- Animations could be an issue, but if no animation is there yet, I doubt it is
- Probably we have software rendering in your configuation? (just a guess)

**Comment by timunie** [comment] 2023-08-31 07:53
Thanks for the details provided btw.

**Comment by RightFS** [comment] 2023-12-29 18:24
The cpu usage of an empty native App is around 0.0%, but an empty avalonia app is 10%, and an empty net8.0-macos app is 0.0% too, avalonia is wasting battery's lifetime.  I gived up using avalonia when I realized that, even though I've written a lot of lines of code. I'm struggling with the stupid xcode and swiftUI now.

**Comment by leandroaphermes** [comment] 2024-05-24 15:22
I have the same high processing consumption on Ubuntu 24.04 with x11.

After locking the screen, the app is consuming high CPU. I have to stop the process to avoid consumption.

**Comment by kpko** [comment] 2024-07-07 14:39
Are there any news on this? I'm new to Avalonia, tried it and an empty "dotnet new avalonia.app" application already pulls >10% cpu usage on my M1 MacBook Pro (.net8 as specified in the latest template + release build).

**Comment by maxkatz6** [comment] 2024-07-08 23:04
I am going to close this issue, for several reasons:
1. The biggest reason - in 11.1 Avalonia we started using CVDisplayLink, it is supposed to lower CPU usage, instead of other timers.
2. This issue was created in 0.10, which was way slower comparing to 11.1 or even 11.0.
3. When I am running an app with couple of text boxes published in release mode, I see 0.5% CPU usage on all threads summed (since my machine has 12 cores, it's essentially 0.5 / 12 = 0.04% of [total CPU](https://discussions.apple.com/thread/6345789). And 2-3% when textbox caret is blinking.

**Closed by maxkatz6** 2024-07-08 23:04 UTC
Labels: bug, os-macos

**Comment by maxkatz6** [comment] 2024-07-08 23:22
Additionally, developers can try experimental support for Metal rendering:
```
.With(new AvaloniaNativePlatformOptions()
{
    RenderingMode = new [] { AvaloniaNativeRenderingMode.Metal, AvaloniaNativeRenderingMode.OpenGL }
})
```

This configuration will prefer Metal over OpenGL, and it might result in better performance for complex apps. Likely won't make any difference on an empty one though.
Note: Metal is already enabled by default in 11.2 nightly builds.

**Comment by hhyyrylainen** [comment] 2024-07-26 12:35
Is there a related issue for Linux? A year ago I saw that the X11 platform implementation of event loop constantly polled even without events (never sleeping). I just got a user reporting they get 25% idle CPU usage (I get around 5% which is probably due to me having more cores). I don't have time right now to check the avalonia code if anything was changed which is why I'm posting this comment, but unless there's an existing report, I can open a new issue later.
