### ISSUE TITLE
Menus are broken

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#2821] opened 2019-08-08 15:52 UTC
On current master (dcf6821ef99d26dad83a30e2e7eb45d5f5e6501d) there are a couple of problems with menus:

- There's no longer a 1px border around the menu
- Clicking on a menu item with a submenu closes the menu instead of opening the submenu

There seem to be 3 separate issues that are causing this:

- [x] When a popup gets closed, pointerover state is not cleared (fix: #2924)
- [ ] Popup is clipping 1 pixel of the top and left edges of its content
- [x] `ContentPresenter` sometimes doesn't set the logical parent of its child control (probably caused by #2825) (fix #2926)

I will open PRs to fix each one separately.

**Comment by mat1jaczyyy** [comment] 2019-08-09 20:23
Noticed this as well

**Comment by danwalmsley** [comment] 2019-08-11 01:33
Also having real difficulty clicking on some menu items.

**Comment by waliarubal** [comment] 2019-08-12 07:24
Menu items no longer show check boxes. This is issue with 0.8.1, 0.8.2 and nightly builds.

```
<MenuItem Header="Navigation Pane">
                <MenuItem.Icon>
                    <CheckBox BorderThickness="0" IsHitTestVisible="False" />
                </MenuItem.Icon>
            </MenuItem>
```

**Comment by wieslawsoltes** [comment] 2019-08-20 16:38
Menu are really broken.

**Comment by HendrikMennen** [comment] 2019-08-21 01:37
Noticed that clicking on the icon part on menus works every time. The other part registers a click only sometimes

**Comment by ahopper** [comment] 2019-09-04 04:17
I wonder if wrong menus closing is caused by the same thing as https://github.com/AvaloniaUI/Avalonia/issues/2921 PopupRoot no longer has a VisualParent

**Closed** 2019-10-01 15:07 UTC
Labels: bug
