### ISSUE TITLE
ArgumentOutOfRangeException during resizing the window

### ISSUE THREAD

**Issue by JakeToWork** [AvaloniaUI/Avalonia#1924] opened 2018-09-27 15:37 UTC
After I resized the window to minimum ( just title bar left ), it throws an ArgumentOutOfRangeException.

![123](https://user-images.githubusercontent.com/28650820/46157400-30957780-c2ae-11e8-978a-0e397854e7d6.gif)

**Comment by jmacato** [comment] 2018-09-28 07:59
Duplicate of #1411

**Closed by jmacato** 2018-09-28 07:59 UTC
