### ISSUE TITLE
NullReferenceException occured in BatchStreamWriter.CommitDataSegment()

### ISSUE THREAD

**Issue by hamster620** [AvaloniaUI/Avalonia#12273] opened 2023-07-21 01:02 UTC
**Describe the bug**
There was a ```NullReferenceException``` thrown in ```BatchStreamWriter.CommitDataSegment()``` but I cannot find how to reproduce. Maybe we can add some check on it.

---

System.NullReferenceException: Object reference not set to an instance of an object.
- at Avalonia.Rendering.Composition.Transport.BatchStreamWriter.CommitDataSegment() in /_/src/Avalonia.Base/Rendering/Composition/Transport/BatchStream.cs:line 81
- at Avalonia.Rendering.Composition.Transport.BatchStreamWriter.Dispose() in /_/src/Avalonia.Base/Rendering/Composition/Transport/BatchStream.cs:line 132
- at Avalonia.Rendering.Composition.Compositor.CommitCore() in /_/src/Avalonia.Base/Rendering/Composition/Compositor.cs:line 173
- at Avalonia.Rendering.Composition.Compositor.Commit() in /_/src/Avalonia.Base/Rendering/Composition/Compositor.cs:line 118
- at Avalonia.Media.MediaContext.CommitCompositor(Compositor compositor) in /_/src/Avalonia.Base/Media/MediaContext.Compositor.cs:line 21
- at Avalonia.Media.MediaContext.SyncCommit(Compositor compositor, Boolean waitFullRender) in /_/src/Avalonia.Base/Media/MediaContext.Compositor.cs:line 110
- at Avalonia.Media.MediaContext.ImmediateRenderRequested(CompositionTarget target) in /_/src/Avalonia.Base/Media/MediaContext.Compositor.cs:line 122
- at Avalonia.Rendering.Composition.CompositingRenderer.Paint(Rect rect) in /_/src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs:line 333
- at Avalonia.Controls.TopLevel.HandlePaint(Rect rect) in /_/src/Avalonia.Controls/TopLevel.cs:line 579
- at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.Paint() in /_/src/Avalonia.Native/WindowImplBase.cs:line 227
- at Avalonia.Native.Interop.Impl.__MicroComIAvnWindowBaseEventsVTable.Paint(Void* this) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4152
- --- End of stack trace from previous location ---
- at Avalonia.Native.DispatcherImpl.RunLoop(CancellationToken token) in /_/src/Avalonia.Native/DispatcherImpl.cs:line 113
- at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl) in /_/src/Avalonia.Base/Threading/DispatcherFrame.cs:line 117
- at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 53
- at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 80
- at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 127
- at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 220
- at CarinaStudio.ULogViewer.App.Main(String[] args)

---

**To Reproduce**
Cannot find reproduct steps.

**Expected behavior**
No exception thrown.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: macOS 13.4.1
- Version 11.0.0

**Comment by timunie** [comment] 2023-07-21 08:26
Without steps to reproduce, we should not touch anything. It may have a complete diffrent root cause and just "ignoring" the NRE may lead to a worth situation. So please try to reproduce the issue. Probably it's happening when executing in an async way?

**Comment by cfnfy** [comment] 2023-08-09 20:10
I have just experience the same issue whilst re-sizing a window in debug. I also can't provide clear re-production steps as this is something that I have done many times before and I can't identify anything that I could have done differently to cause this.

I'm also on OSX 13.4.1 but am using Avalonia V11.0.2.

When re-sizing, rather than the window resizing as it would usually, it instead appeared as though it was an image that was being scaled. This continued until I released the cursor, at which point the error occurred.

I will try to work out the cause of this and follow up with further information if I can, but just wanted to flag also experiencing the issue.

**Comment by timunie** [comment] 2023-08-10 06:23
@cfnfy that may bring us a step further. You may want to try to reproduce it using source/samples/Sandbox or ControlCatalog, so you can see where it crashes in Avalonia source. If you are able to detect the root, probably you are able to file a PR with a fix. 🤞

**Comment by cfnfy** [comment] 2023-11-28 09:45
To follow up, I haven't experienced this issue a single time since using later versions. It appeared to be an issue specific to 11.0.2.

**Comment by timunie** [comment] 2023-11-28 09:47
closing this issue acc. to feedback. If anyone finds this happens in 11.0.5, please let us know how to reproduce and I'll reopen it.

**Closed by timunie** 2023-11-28 09:47 UTC
Labels: bug
