### ISSUE TITLE
ComboBox items cannot be selected on Android

### ISSUE THREAD

**Issue by AArnott** [AvaloniaUI/Avalonia#10440] opened 2023-02-23 04:33 UTC
**Describe the bug**

A ComboBox on a xaml user control displays its items on Windows desktop and Android, but the items cannot be selected on Android (though they can be on desktop).

**To Reproduce**

Unzip this minimal repro solution to see:
[cluebuddy.zip](https://github.com/AvaloniaUI/Avalonia/files/10810258/cluebuddy.zip)

It appears to be as simple as:

```xaml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="400" d:DesignHeight="350"
             x:Class="ClueBuddyAvl.Views.MainView">
    <StackPanel Margin="5" Spacing="5">
        <ComboBox>
            <ComboBoxItem>First</ComboBoxItem>
            <ComboBoxItem>Second</ComboBoxItem>
            <ComboBoxItem>Third</ComboBoxItem>
        </ComboBox>
    </StackPanel>
</UserControl>
```

Although when I created a _new_ solution, I couldn't get it to repro. So instead I whittled my actual solution down to almost nothing, and it still repros.

**Expected behavior**

I expect the combo box items to be selectable in both environments.

**Screenshots**

![2c8d21a2-0db3-4251-a0e9-89bc2a04e96a](https://user-images.githubusercontent.com/3548/220821789-0f22bb0a-e6e5-443b-8a49-969bab8e3787.gif)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version Avalonia 11.0.999-cibuild0029872-beta

**Comment by maxkatz6** [comment] 2023-02-23 04:50
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/10420

**Closed by maxkatz6** 2023-02-23 04:50 UTC
Labels: bug
