### ISSUE TITLE
Alfa channel and opacity on Window 0.9

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#3150] opened 2019-10-23 13:05 UTC
1) opacity don't work in window scope (I dont know it's bug or feature)
2) alfa channel don't work similar in different platforms:
```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="clr-namespace:Wind1.ViewModels;assembly=Wind1"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="Wind1.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"

        Background="#FFFF4040"
        Title="Wind1">

    <TextBlock Text="Hello world"></TextBlock>
</Window>
```
and I change colors
  `Background="#FFFF4040"` -> `Background="#55FF4040"` -> `Background="#00FF4040"`
as background i use Rider
And in os Windows
![image](https://user-images.githubusercontent.com/33497292/67395314-6c346b00-f5ae-11e9-8303-cbebf60446b8.png)
![w2](https://user-images.githubusercontent.com/33497292/67395722-1f9d5f80-f5af-11e9-93bd-46bed71b2221.png)
![w3](https://user-images.githubusercontent.com/33497292/67395789-3c399780-f5af-11e9-8e90-13b585be7a77.png)

bugs work in 0.8.2 too

**Comment by CreateLab** [comment] 2019-10-23 13:10
On Linux (Kubuntu)
![33](https://user-images.githubusercontent.com/33497292/67395979-8458ba00-f5af-11e9-9fd3-ab03e2c5f1cf.png)
![44](https://user-images.githubusercontent.com/33497292/67396028-94709980-f5af-11e9-912c-256024780b4b.png)
![55](https://user-images.githubusercontent.com/33497292/67396076-a5b9a600-f5af-11e9-9ee2-ff1578612062.png)

**Comment by kekekeks** [comment] 2019-10-23 13:24
Opacity is currently only supported on Linux because we got that support basically for free (e. g. no special APIs involved, one needs to just choose an ARGB visual when creating the window).

It's way more complicated on Windows, unfortunately.

**Comment by kekekeks** [comment] 2019-10-23 13:25
Closing as duplicate of #2306 and #987

**Comment by CreateLab** [comment] 2019-10-23 13:30
> Opacity is currently only supported on Linux because we got that support basically for free (e. g. no special APIs involved, one needs to just choose an ARGB visual when creating the window).
> 
> It's way more complicated on Windows, unfortunately.

opacity don't work on linux too(
or I do smth wrong
Will alfa work on windows in some days, or u don't do it in future

**Comment by kekekeks** [comment] 2019-10-23 13:37
You can also try to use https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmextendframeintoclientarea but that won't work on Windows 7 with Aero disabled.

**Closed** 2019-10-23 13:38 UTC
