### ISSUE TITLE
Window ExtendClientArea Broken in 11.1-beta2

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia#15532] opened 2024-04-26 23:05 UTC
### Describe the bug

It seems both `ExtendClientAreaChromeHints` and `ExtendClientAreaToDecorationsHint` have been broken in 11.1 beta2.

 1. The app is not extending into the titlebar at first window load. It does however fix itself when the app is resized
 2. ~The system window buttons (minimize, maximize, close) never appear~ (duplicate of #15522)

![image](https://github.com/AvaloniaUI/Avalonia/assets/17993847/54d3c786-9249-4e9c-ae5f-6bca9e2bc780)

### To Reproduce

```xaml
<Window
    ExtendClientAreaChromeHints="PreferSystemChrome"
    ExtendClientAreaToDecorationsHint="True">
```

### Expected behavior

![image](https://github.com/AvaloniaUI/Avalonia/assets/17993847/6d021931-c241-4dd8-800c-59079bb45145)

### Avalonia version

11.1-beta2

### OS

Windows

### Additional context

There are recent PRs in this area. One of them broke this functionality.

Otherwise, on my end this code has worked fine since 11.0 previews and is unchanged since.

**Comment by jp2masa** [comment] 2024-04-27 00:44
Duplicate of #15522?

**Comment by robloo** [comment] 2024-04-27 00:57
#15522 is a duplicate of point number 2 above (no caption buttons). However, the first one appears to be different.

**Comment by TomEdwardsEnscape** [comment] 2024-04-28 15:34
#14470 is an obvious candidate, but it was included in beta1. Was everything OK in that version?

**Comment by robloo** [comment] 2024-04-28 16:57
> https://github.com/AvaloniaUI/Avalonia/pull/14470 is an obvious candidate, but it was included in beta1. Was everything OK in that version?

@TomEdwardsEnscape Yes, 11.1-beta1 doesn't have these issues.

**Comment by robloo** [comment] 2024-04-28 17:00
Also note that extend into client area does work again if the Window is resized. So another PR just broke the startup path that was applying this property on first load.

(The caption buttons are still broken reguardless)

**Closed** 2024-04-30 01:23 UTC
Labels: bug, regression
