### ISSUE TITLE
The control already has a visual parent exception when opening MenuItem's 

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#2750] opened 2019-07-17 20:51 UTC
Version: 0.8.999-cibuild0003215-beta

Inner exception: `The control already has a visual parent`
```
   at Avalonia.Visual.ValidateVisualChild(IVisual c)
   at Avalonia.Collections.AvaloniaList`1.Add(T item)
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild()
   at Avalonia.Controls.Presenters.ContentPresenter.ApplyTemplate()
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Presenters.ItemVirtualizer.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Presenters.ItemsPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Presenters.ScrollContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass(ILayoutRoot root)
   at Avalonia.Controls.WindowBase.Show()
   at Avalonia.Controls.Primitives.Popup.Open()
   at Avalonia.Controls.Primitives.Popup.IsOpenChanged(AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaObjectExtensions.SubscribeAdapter[TTarget](AvaloniaPropertyChangedEventArgs e, Func`2 handler)
   at Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass8_0`1.<AddClassHandler>b__0(AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaProperty.NotifyChanged(AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.<>c__DisplayClass51_0`1.<SetAndRaiseCore>b__0()
   at Avalonia.Utilities.DeferredSetter`1.<>c__DisplayClass12_0`1.<SetAndNotify>b__0(Action notification)
   at Avalonia.AvaloniaObject.SetAndRaiseCore[T](AvaloniaProperty property, T& field, T value, Action`1 notifyWrapper)
   at Avalonia.AvaloniaObject.<>c__DisplayClass50_0`1.<SetAndRaise>b__0(T val, T& backing, Action`1 notifyWrapper)
   at Avalonia.AvaloniaObject.<>c__DisplayClass49_0`1.<SetAndRaise>b__0(Object update, T& backing, Action`1 notify)
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotify[TValue](AvaloniaProperty property, TValue& backing, SetterDelegate`1 setterCallback, TSetRecord value)
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, SetAndRaiseCallback`1 setterCallback, T value)
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value)
   at Avalonia.Controls.Primitives.Popup.set_IsOpen(Boolean value)
   at Avalonia.Controls.Primitives.Popup.<>c.<.cctor>b__14_4(Popup o, Boolean v)
   at Avalonia.DirectProperty`2.Avalonia.IDirectPropertyAccessor.SetValue(IAvaloniaObject instance, Object value)
   at Avalonia.AvaloniaObject.<>c__DisplayClass54_0.<SetDirectValue>g__Set|0()
   at Avalonia.AvaloniaObject.SetDirectValue(AvaloniaProperty property, Object value)
   at Avalonia.AvaloniaObject.DirectBindingSubscription.OnNext(Object value)
   at Avalonia.Reactive.SingleSubscriberObservableBase`1.PublishNext(T value)
   at Avalonia.Data.TemplateBinding.PublishValue()
   at Avalonia.Data.TemplateBinding.TemplatedParentPropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.PriorityValueChanged(AvaloniaProperty property, Int32 priority, Object oldValue, Object newValue)
   at Avalonia.ValueStore.Changed(AvaloniaProperty property, Int32 priority, Object oldValue, Object newValue)
   at Avalonia.ValueStore.AddValue(AvaloniaProperty property, Object value, Int32 priority)
   at Avalonia.AvaloniaObject.SetStyledValue(AvaloniaProperty property, Object value, BindingPriority priority)
   at Avalonia.AvaloniaObject.SetValue(AvaloniaProperty property, Object value, BindingPriority priority)
   at Avalonia.AvaloniaObject.SetValue[T](AvaloniaProperty`1 property, T value, BindingPriority priority)
   at Avalonia.Controls.MenuItem.set_IsSubMenuOpen(Boolean value)
   at Avalonia.Controls.MenuItem.Open()
   at Avalonia.Controls.Platform.DefaultMenuInteractionHandler.PointerEnter(Object sender, PointerEventArgs e)
```

`Exception has been thrown by the target of an invocation.`
```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Controls.MenuItem.OnPointerEnter(PointerEventArgs e)
   at Avalonia.Input.InputElement.OnPointerEnterCore(PointerEventArgs e)
--- End of stack trace from previous location where exception was thrown ---
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass25_0.<AddClassHandler>b__0(Tuple`2 args)
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.SetPointerOver(IPointerDevice device, UInt64 timestamp, IInputRoot root, IInputElement element, InputModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.SetPointerOver(IPointerDevice device, UInt64 timestamp, IInputRoot root, Point p, InputModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.MouseMove(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties properties, InputModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.DesktopApplicationExtensions.Run(Application app, CancellationToken token)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Draw2D.Desktop.Program.Main(String[] args) in C:\DOWNLOADS\GitHub\Draw2D\src\Draw2D.Desktop\Program.cs:line 16
```

**Comment by wieslawsoltes** [comment] 2019-07-17 22:01
The repro - the `MenuItem`'s in two sub-menus (`Tool` and `Shape`) are using same Static/DynamicResource and this causes the exception:
```XAML
    <Menu Background="Transparent">
        <MenuItem Header="_Tool">
            <MenuItem Header="Pat_h" Icon="{StaticResource PathIcon}">
            </MenuItem>
        </MenuItem>
        <MenuItem Header="_Shape">
            <MenuItem Header="Create Pat_h" Icon="{StaticResource PathIcon}"/>
    </Menu>
```
```XAML
        <DrawingPresenter x:Key="PathIcon" Width="16" Height="16">
            <DrawingGroup>
                <DrawingGroup.Children>
                    <GeometryDrawing Brush="#FFF6F6F6" Geometry="F1M8.7138,-0.000199999999999534L0.000800000000001688,5.4458 0.000800000000001688,6.1648 3.2798,15.9998 15.9998,15.9998 15.9998,14.6388 11.5158,9.2578 15.9998,6.5668 15.9998,5.5318 9.3608,-0.000199999999999534z" />
                    <GeometryDrawing Brush="#FF414141" Geometry="F1M12.8652,14L4.7202,14 2.1982,6.431 8.9162,2.232 13.2782,5.867 9.4852,8.143 8.4842,8.743 9.2312,9.641z M15.0002,6L9.0002,1 1.0002,6 4.0002,15 15.0002,15 10.0002,9z" />
                    <GeometryDrawing Brush="#FFF0EFF1" Geometry="F1M8.916,2.2319L13.278,5.8669 9.485,8.1429 8.484,8.7429 9.231,9.6409 12.865,13.9999 4.721,13.9999 2.198,6.4309z" />
                </DrawingGroup.Children>
            </DrawingGroup>
        </DrawingPresenter>
```

**Comment by kekekeks** [comment] 2019-07-20 08:46
We need `x:Shared` support for using one `Visual` resource in multiple places.
Duplicate of #2735

**Closed by kekekeks** 2019-07-20 08:46 UTC
