### ISSUE TITLE
Textbox failed display with chinese on Linux

### ISSUE THREAD

**Issue by DiceySai** [AvaloniaUI/Avalonia#5828] opened 2021-04-23 10:37 UTC
**Describe the bug**
Textbox with chinese will be garbled on Linux enviroment, it works fine with textblock.

**To Reproduce**
![image](https://user-images.githubusercontent.com/59906289/115859546-ecb57f80-a462-11eb-92ae-b337824df2ff.png)

**Expected behavior**
Textbox can display chinese successfully on linux

**Screenshots**

**Comment by Gillibald** [comment] 2021-04-23 12:09
Duplicate of #4859

**Closed by Gillibald** 2021-04-23 12:09 UTC
Labels: bug

**Comment by kekekeks** [comment] 2021-04-23 16:17
Workaround:
>You need to use a font that has Chinese characters. https://github.com/anthonyfok/fonts-wqy-microhei is a good one
[WenQuanYiMicroHei-01.ttf.zip](https://github.com/AvaloniaUI/Avalonia/files/5703016/WenQuanYiMicroHei-01.ttf.zip)
>
>Place it into Assets, add as AvaloniaResource and add something like
>
>```
><Style Selector="TextBlock">
>    <Setter Property="FontFamily" Value="avares://YourAssemblyName/Assets/Fonts#WenQuanYi Micro Hei" />
></Style>
>```
>to your App.xaml after the theme

**Comment by DiceySai** [comment] 2021-04-25 06:09
> Workaround:
> 
> > You need to use a font that has Chinese characters. https://github.com/anthonyfok/fonts-wqy-microhei is a good one
> > [WenQuanYiMicroHei-01.ttf.zip](https://github.com/AvaloniaUI/Avalonia/files/5703016/WenQuanYiMicroHei-01.ttf.zip)
> > Place it into Assets, add as AvaloniaResource and add something like
> > ```
> > <Style Selector="TextBlock">
> >    <Setter Property="FontFamily" Value="avares://YourAssemblyName/Assets/Fonts#WenQuanYi Micro Hei" />
> > </Style>
> > ```
> > 
> > 
> > to your App.xaml after the theme

Thanks, it works fine.
