### ISSUE TITLE
PointerPressed event won't fire for TreeView Items If ContextMenu Is Open

### ISSUE THREAD

**Issue by Abdallah-Darwish** [AvaloniaUI/Avalonia#3559] opened 2020-02-12 14:41 UTC
As the title says, if I opened the context menu assigned with the tree view then "PointerPressed" event won't fire unless I close the context menu(by "left clicking" any where) then right clicking the item would fire the event only once.

I have included a demo try to right click image "A" then right click on any image multiple times but the event won't fire and the label contents won't change unless you close the menu.

[Demo.zip](https://github.com/AvaloniaUI/Avalonia/files/4192870/Demo.zip)

.Net: .Net core 3.1
Avalonia: 0.9.999-cibuild0005923-beta

**Comment by alexander-miglis** [comment] 2021-05-02 05:45
PointerPressed does also not fire if you click a TreeViewItem, is this related?

**Comment by maxkatz6** [comment] 2021-05-16 23:37
> PointerPressed does also not fire if you click a TreeViewItem, is this related? I tested on the latest 0.10.3 version with .Net Core 5

Because it has transparent background or was already handled somewhere (in this case Tunnel Strategy handling is required).

@Abdallah-Darwish I am able to reproduce it with 0.9 version, but I am not able to do it in 0.10.3.
Closing as fixed, but feel free to ping me if in 0.10.3 it won't work.

**Closed by maxkatz6** 2021-05-16 23:37 UTC

**Comment by alexander-miglis** [comment] 2021-05-17 04:44
> > PointerPressed does also not fire if you click a TreeViewItem, is this related? I tested on the latest 0.10.3 version with .Net Core 5
> 
> Because it has transparent background or was already handled somewhere (in this case Tunnel Strategy handling is required).
> 
> @Abdallah-Darwish I am able to reproduce it with 0.9 version, but I am not able to do it in 0.10.3.
> Closing as fixed, but feel free to ping me if in 0.10.3 it won't work.

I'm pretty sure I don't handle it in between, it's being handled wrongly in the treeview item. I managed to solve it by overriding TreeView class and implement a custom "BeforePointerPressed" event. This is essential to have if you implement drag  & drop in a treeview. Happy to share code if there is interest.

**Comment by maxkatz6** [comment] 2021-05-17 06:07
> it's being handled wrongly in the TreeViewItem

I don't see if it's handled in TreeViewItem, only OnKeyDown. But it's most likely handled in the TreeView for items selection, which is expected to handle, and there is nothing wrong.

> I managed to solve it by overriding TreeView class and implement a custom "BeforePointerPressed" event

It's easier to subscribe on event with Tunnel Strategy. 
See docs: https://docs.avaloniaui.net/docs/input/routed-events
Something similar to https://github.com/AvaloniaUI/Avalonia/issues/5244#issuecomment-753239690

**Comment by alexander-miglis** [comment] 2021-05-18 09:51
Hi again,
Sorry for being persistent, I created a repo with an example. It's ready to run, in the MainWindow.axaml.cs there is an event _tree_PointerPressed. If you click the tree item it will not fire, if you click outside it will.

https://github.com/alexander-miglis/AvaloniaTreeViewExample

If this is a mistake on my side I apologize beforehand
