### ISSUE TITLE
Transparency issue with ComboBox popup on Linux using Fluent theme

### ISSUE THREAD

**Issue by Jackhammer88** [AvaloniaUI/Avalonia#14802] opened 2024-03-03 20:04 UTC
### Description

The ComboBox popup in Avalonia UI applications is displaying with unintended transparency effects on the rounded corners of the popup. This causes the background color of the application window to bleed through the corners. The popup should not be transparent, but it is influenced by the window's background color, which becomes apparent when the background is changed from red to any other color.

### Reproduction Steps

1. Create an Avalonia UI application with Fluent theme.
2. Add a ComboBox control to the application.
3. Run the application on Astra Linux 1.7, 2.12 or Debian 12.
4. Observe the transparency around the rounded corners of the popup when the ComboBox is expanded.

### Expected Behavior

The popup should have solid corners matching the popup's background, without any transparency showing the application window's background color.

### Actual Behavior

The popup corners are transparent, showing the application window's background color.

### Affected Versions

This issue has been observed from Avalonia version 11.0.8 onwards.

### System Information

Operating System: Astra Linux (versions 1.7, 2.12) and Debian 12
Avalonia Version: 11.0.8+
.NET Runtime: dotnet 8.0.2
Theme: Fluent

### Screenshots
![Screenshot_20240303_225204](https://github.com/AvaloniaUI/Avalonia/assets/19895415/982f1b09-6b78-4798-81bc-90f9daec69c9)
![Screenshot_20240303_224315](https://github.com/AvaloniaUI/Avalonia/assets/19895415/58b50890-3962-47b1-9baf-7ccaa9993f91)

### Xaml

```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="using:AvaloniaApplication1.ViewModels"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        Width="300" Height="300"
        WindowStartupLocation="CenterScreen"
        x:Class="AvaloniaApplication1.Views.MainWindow"
        x:DataType="vm:MainWindowViewModel"
        Icon="/Assets/avalonia-logo.ico"
        Title="AvaloniaApplication1">
    <StackPanel Margin="10">
        <ComboBox Width="100" Height="40">
            <ComboBox.Styles>
                <Style Selector="ComboBox">
                    <Setter Property="Template">
                        <ControlTemplate>
                            <DataValidationErrors>
                                <Grid ColumnDefinitions="*,32">
                                    <Border x:Name="Background"
                                            Grid.Column="0"
                                            Grid.ColumnSpan="2"
                                            Background="{TemplateBinding Background}"
                                            BorderBrush="{TemplateBinding BorderBrush}"
                                            BorderThickness="{TemplateBinding BorderThickness}"
                                            CornerRadius="{TemplateBinding CornerRadius}"
                                            MinWidth="{DynamicResource ComboBoxThemeMinWidth}" />
                                    <Border x:Name="HighlightBackground"
                                            Grid.Column="0"
                                            Grid.ColumnSpan="2"
                                            Background="{DynamicResource ComboBoxBackgroundUnfocused}"
                                            BorderBrush="{DynamicResource ComboBoxBackgroundBorderBrushUnfocused}"
                                            BorderThickness="{TemplateBinding BorderThickness}"
                                            CornerRadius="{TemplateBinding CornerRadius}"
                                            IsVisible="False" />
                                    <TextBlock x:Name="PlaceholderTextBlock"
                                               Grid.Column="0"
                                               HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                                               VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
                                               Margin="{TemplateBinding Padding}"
                                               Text="{TemplateBinding PlaceholderText}"
                                               Foreground="{TemplateBinding PlaceholderForeground}"
                                               IsVisible="{TemplateBinding SelectionBoxItem, Converter={x:Static ObjectConverters.IsNull}}" />
                                    <ContentControl x:Name="ContentPresenter"
                                                    Content="{TemplateBinding SelectionBoxItem}"
                                                    ContentTemplate="{TemplateBinding ItemTemplate}"
                                                    Grid.Column="0"
                                                    Margin="{TemplateBinding Padding}"
                                                    HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}"
                                                    VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}" />

                                    <Border x:Name="DropDownOverlay"
                                            Grid.Column="1"
                                            Background="Transparent"
                                            Margin="0,1,1,1"
                                            Width="30"
                                            IsVisible="False"
                                            HorizontalAlignment="Right" />

                                    <PathIcon x:Name="DropDownGlyph"
                                              Grid.Column="1"
                                              UseLayoutRounding="False"
                                              IsHitTestVisible="False"
                                              Height="12"
                                              Width="12"
                                              Margin="0,0,10,0"
                                              HorizontalAlignment="Right"
                                              VerticalAlignment="Center"
                                              Foreground="{DynamicResource ComboBoxDropDownGlyphForeground}"
                                              Data="M1939 486L2029 576L1024 1581L19 576L109 486L1024 1401L1939 486Z" />

                                    <Popup Name="PART_Popup"
                                           WindowManagerAddShadowHint="False"
                                           IsOpen="{TemplateBinding IsDropDownOpen, Mode=TwoWay}"
                                           MinWidth="{Binding Bounds.Width, RelativeSource={RelativeSource TemplatedParent}}"
                                           MaxHeight="{TemplateBinding MaxDropDownHeight}"
                                           PlacementTarget="Background"
                                           IsLightDismissEnabled="True"
                                           InheritsTransform="True">
                                        <Border x:Name="PopupBorder"
                                                Background="{DynamicResource ComboBoxDropDownBackground}"
                                                BorderBrush="{DynamicResource ComboBoxDropDownBorderBrush}"
                                                BorderThickness="{DynamicResource ComboBoxDropdownBorderThickness}"
                                                Padding="{DynamicResource ComboBoxDropdownBorderPadding}"
                                                HorizontalAlignment="Stretch"
                                                CornerRadius="20">
                                            <ScrollViewer
                                                HorizontalScrollBarVisibility="{TemplateBinding ScrollViewer.HorizontalScrollBarVisibility}"
                                                VerticalScrollBarVisibility="{TemplateBinding ScrollViewer.VerticalScrollBarVisibility}"
                                                IsDeferredScrollingEnabled="{TemplateBinding (ScrollViewer.IsDeferredScrollingEnabled)}">
                                                <ItemsPresenter Name="PART_ItemsPresenter"
                                                                Margin="{DynamicResource ComboBoxDropdownContentMargin}"
                                                                ItemsPanel="{TemplateBinding ItemsPanel}" />
                                            </ScrollViewer>
                                        </Border>
                                    </Popup>
                                </Grid>
                            </DataValidationErrors>
                        </ControlTemplate>
                    </Setter>
                </Style>
            </ComboBox.Styles>

            <ComboBoxItem Content="123" />
            <ComboBoxItem Content="234" />
            <ComboBoxItem Content="Abcd" />
        </ComboBox>
        
        <ComboBox Width="100" Height="40">
            <ComboBoxItem Content="123" />
            <ComboBoxItem Content="234" />
            <ComboBoxItem Content="Abcd" />
        </ComboBox>
    </StackPanel>

</Window>
```

The issue is specific to the Linux version of the Fluent theme. I used a custom style with an enlarged border corner radius to better demonstrate the issue. Instead of the popup being transparent, it is the window that appears transparent.

**Comment by jp2masa** [comment] 2024-03-03 23:33
Duplicate of #14568. It will be fixed in the next patch release.

**Comment by timunie** [comment] 2024-03-04 08:10
closing as duplicate

**Closed by timunie** 2024-03-04 08:10 UTC
Labels: bug
