### ISSUE TITLE
In 11.06 TextBlock Control does not implement TextChanged event. 

### ISSUE THREAD

**Issue by KentSwan** [AvaloniaUI/Avalonia#14060] opened 2023-12-29 18:02 UTC
## Describe the bug
While developing an MVVM application, I was using a TextBlock in a ContentControl in a ScrollViewer to log some immediately visible feedback as well as to analyze event handling from some controls I was using.  To test these controls' event generation, I built a Test view which attached various handlers to the controls to see what they did and how they operated. The target controls for this testing were a Button and three different TextBoxes.  Things were cruising along nicely until I noticed that the TextBlock wasn't auto-scrolling when adding text.  The TextChanged events were being generated fine by the handlers for other purposes.  I thought, Okay, let's tap into the TextChanged event handler so that when Text was added, I could call the ScrollToEnd method on the scroll viewer. Was stunned to find that the TextBlock does not have a TextChanged event.  The workaround was to have the ViewModel generate a TextLogChanged event when that TextBlock was updated and have the View subscribe to it to cause the scroll to occur.  This was annoying because the current TextBlock does not behave like a TextBox when the backing field in the ViewModel is updated which means that the workaround tends to violate the separation of View handing from ViewModel data handling.

## To Reproduce

Setup an Avalonia Community Edition.MVVM app at rev 11.06
In Mainview views a ScrollViewer window containing a ContentControl which contains a TextBlock Control with a {Binding TextLog}
In MainViewModel add a public string TextLog property with the [ObservableProperty] attribute.
concatenate messages into the TextLog using  += message;
In MainView, try to set up a subscription to the TextBlocks' TextChanged event an event handler can call the ScrollToEnd method of the ScrollViewer control.  It isn't there

## Expected behavior
I expected a TextChanged event on a TextBlock because I was dynamically updating the content of it.

## Screenshots
If applicable, add screenshots to help explain your problem. (not required)

## Environment 
  Windows 10
  VS2022
  Avalonia 11.06
  CommunityEdition.MVVM
  Fluent Theme

## Additional context
Add any other context about the problem here. Nope. Just annoyed.

**Comment by timunie** [comment] 2023-12-29 18:39
Why do you need or expect that event? TextBox should have it but TextBlock? It's not updated by the user so I normally think you already know the new text in advance? 

Moreover in Avalonia any control has a PropertyChanged event that's also raised after Text changed. Should be enough imo.

**Comment by KentSwan** [comment] 2023-12-29 19:35
Since the TextBlock can be dynamically updated from a backing string observable property then it is effectively a write-only text box and deserves having at least those aspects for event handling without having to write a lot of work-around code and violate mvvm separation of concerns conventions.  To be fair, I'm now exploring the handler implementations using the genearal PropertyChanged and whether it can be used within the View to implement the change sense functionality without the knowledge of the ViewModel.  So far it appears that this might be possible though it also appears that there might be a lot of extcess events that have be filtered out.

**Comment by timunie** [comment] 2023-12-29 19:41
if(e.Property == TextProperty) ...

**Comment by KentSwan** [comment] 2023-12-30 03:37
Thanks, Tim for prodding me to deep dive and giving me a hint of direction.   After researching and then a lot of experimenting I was able to figure out how to attach to the PropertyChange of the view axaml TextBlock "TBLK1" bound to the ViewModel string property "ResultsLog"  so that the ScrollViewer will automatically keep the newest log entries visible.  This solution, shown below, is implemented completely within the View which satisfies the MVVM requirement that the ViewModel not be involved with behavioral aspects of the view.  Again Thanks.  My only comment here is that it would have been far easier and fully consistent had TextChanged been implemented for TextBlock.

View07ViewModel.cs Property is

        [ObservableProperty]
        private string _resultsLog = "No results yet\n";

View07ViewModel.cs method is:

        public void LogText(string? message)
        {
            ResultsLog += message;  // add the message to the text block content
        }

View.axaml fragment

		<ScrollViewer Name="SCRLVWR" Width="350" Height="500">
			<ContentControl BorderBrush="Black" BorderThickness="1" >
				<TextBlock Name="TBLK1"
						   Text="{Binding ResultsLog}"
						   HorizontalAlignment="Stretch"
						   VerticalAlignment="Stretch"
						   Background="BlanchedAlmond" 
						   TextWrapping="Wrap"/>
			</ContentControl>
		</ScrollViewer>

View.axaml.cs edited down

public partial class View07 : UserControl
    {
        private TextBlock resultsLogTextBlock;
        private ScrollViewer resultsLogScrollViewer;

        public View07()
        {
            InitializeComponent();

            View07ViewModel? viewModel = DataContext as View07ViewModel;

            viewModel?.SetView(this);
            resultsLogScrollViewer = this.FindControl<ScrollViewer>("SCRLVWR");

            TextBlock? tblk1 = this.FindControl<TextBlock>("TBLK1");
            tblk1.PropertyChanged += TextBlockPropertyChangedEventHandler;
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }

        private void TextBlockPropertyChangedEventHandler(object? sender, Avalonia.AvaloniaPropertyChangedEventArgs e)
        {
            TextBlock? textBlock = sender as TextBlock;
            if (textBlock != null)
            {
                if (textBlock.Name == "TBLK1")
                {
                    if (e != null)
                    {
                        string val = textBlock.Text;
                        if (resultsLogScrollViewer != null)
                        {
                            resultsLogScrollViewer.ScrollToEnd();
                        }
                    }
                }
            }
        }
}

**Comment by stevemonaco** [comment] 2023-12-30 06:59
Be warned that this approach will perform poorly for any modestly-sized data. Besides allocating larger-and-large strings on each append, you are also recreating the entire text layout from scratch, re-rendering everything, etc.

The better approach is to create an `ObservableCollection<T>` where `T` is either a model or a `string`. Add each entry as a `T`. Coupling with a virtualized collection control will let you scale into many thousands of entries. You could listen to the `CollectionChanged` event of the `ObservableCollection<T>` or use Mvvm Toolkit's Messenger to send a message from the VM to View instead from the `LogText` method.

Lastly, are you using an older version (pre-11) of Avalonia? I noticed that you are manually using `FindControl` to find named controls and have the older explicit definition of `InitializeComponents`. 11 has sourcegen to do those things automatically.

**Comment by KentSwan** [comment] 2023-12-30 07:15
Thanks,  I'm using VS2022 at the current reve level, Avalonia 11.06 with the Fluent Theme.  

I understand the performance issue.  This is a test view to sort out how things work. To that end, I also have a reset button tied to a which uses the [RelayCommand] attribute for binding to the axaml.  Thanks for your suggestions on this kind of functionality in a production environment. 

I'm still looking for a decent explanation and a couple of examples for Messanger. Suggestions?

The explicit definition of InitializeComponents is an accidental artifact because I am using CommunityToolkit.Mvvm code generators.

About the use of FindControl, This code is in the View.axaml.cs.  which is also set up as a partial class. I haven't tripped over the discussion of the new syntactical formats for the equivalent. Can you show or point me?

**Comment by timunie** [comment] 2023-12-30 07:29
If you want a good performing log viewer, I highly suggest to look into a package called AvaloniaEdit. It has virtualization for large texts and even syntax highlights. 

That said I still believe this is not a bug but probably a feature request. However the use case is very rare to me and thus the overhead of the additional event not worth it as we have a working solution also for your case. So I'm closing this for now. Ping me if you disagree. 

One more hint: if you have another question, join us on telegram or use Discussions. Welcome to Avalonia

**Closed by timunie** 2023-12-30 07:29 UTC
Labels: enhancement

**Comment by KentSwan** [comment] 2023-12-30 07:39
Concur. I've been designing hardware and both embedded and application software for a long time so, thinking outside the box, is a natural consequence of that history. If I hadn't been able to solve the problem, the upgrade would be on the needed list but as you said the use case is probably rare for conventional users.  That said, go ahead and close this issue out.

**Comment by stevemonaco** [comment] 2023-12-30 07:45
> I'm still looking for a decent explanation and a couple of examples for Messanger. Suggestions?

`Messenger` has several approaches for autoregistrations that are covered by the [docs](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/messenger). You can't really use autoregistrations because you'll be receiving messages in the View. So an example would be:

1. Create a Message type (I define all of mine as record types in a Messages.cs. They usually have parameters, but not in this example):
```cs
public record RenderInvalidatedMessage();
```
2. Send a message in your VM:
```cs
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Messaging;
...
WeakReferenceMessenger.Default.Send(new RenderInvalidatedMessage());
```
3. Register the message type and receive the message in your View:
```cs
using CommunityToolkit.Mvvm.Messaging;
...
WeakReferenceMessenger.Default.Register<RenderInvalidatedMessage>(this, (_, m) => canvas.Invalidate());
```

> About the use of FindControl, This code is in the View.axaml.cs. which is also set up as a partial class. I haven't tripped over the discussion of the new syntactical formats for the equivalent. Can you show or point me?

You don't need to use `FindControl`. Name the control in XAML and the sourcegen adds the name as a local field and finds it in the generated `InitializeComponents` method.
