### ISSUE TITLE
[XAML Compiler] XAML definition without public constructor

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#2991] opened 2019-09-13 16:54 UTC
It used to be possible to have XAML objects without a public default constructor, but now it's not. I believe that constructor is only needed when instantiating an object (e.g. `<MyObject />`). I'd like to know if this is supposed to work.

## Example

```cs
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace My.Namespace
{
    public class MyWindow : Window
    {
        private readonly int _x;

        public MyWindow(int x)
        {
            InitializeComponent();

            _x = x;
        }

        private void InitializeComponent() => AvaloniaXamlLoader.Load(this);
    }
}
```

```xaml
<Window x:Class="My.Namespace.MyWindow">
    <TextBlock>Test</TextBlock>
</Window>
```

Error:
```
Avalonia error XAMLIL: Unable to find public constructor for type ...
```

**Comment by kekekeks** [comment] 2019-09-13 19:19
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2593

**Closed by kekekeks** 2019-09-13 19:19 UTC
