### ISSUE TITLE
Transparency issue with some buttons in Dialogs

### ISSUE THREAD

**Issue by Krakean** [AvaloniaUI/Avalonia#2328] opened 2019-02-23 18:04 UTC
Hello.
There is problem with Open/Save/SelectFolder dialogs: https://i.imgur.com/X1GSGR0.png

There is no such issue, for example, in Eto.Wpf: https://i.imgur.com/JlMlrYW.png (though, same issue in Eto.Direct2D and Eto.WinForms), and also no such issue when using Windows Explorer - https://i.imgur.com/7zJFq9z.png

Avalonia version: latest master (bebb53cb3436eafef562a065a556fb792577773f)

**Comment by kekekeks** [comment] 2019-02-23 19:30
You seem to be using some highly customized windows theme which might not have proper support for all versions of file dialog API. 

We are using Vista+ file dialogs https://docs.microsoft.com/en-us/windows/desktop/api/shobjidl_core/nn-shobjidl_core-ifiledialog

Please, check if your windows theme supports these properly. Since Eto.WinForms has the same issue, I suspect that regular winforms have it too.

**Comment by Krakean** [comment] 2019-02-23 20:02
@kekekeks 
This is my theme: https://www.deviantart.com/niivu/art/ARC-X-Windows-10-Theme-772549960 (specifically this one - https://i.imgur.com/lrAMR6M.png)
Not really highly customized, just all colors changed :)

>We are using Vista+ file dialogs https://docs.microsoft.com/en-us/windows/desktop/api/shobjidl_core/nn-shobjidl_core-ifiledialog
Well, as I said  there is no such problem in Windows Explorer, and no such problem in case of Eto.Wpf (though, Eto.WinForms and Eto.Direct2D have this problem). 
Also I cannot see such problem in open dialog of mine media player - https://i.imgur.com/93yHmG0.png (written in Delphi, but I dont think it matters, because I use there also standard Windows file dialog). And there is no such problem in Visual Studio file dialog.

**Comment by kekekeks** [comment] 2019-02-23 20:20
According to https://github.com/picoe/Eto/blob/develop/src/Eto.WinForms/Forms/SaveFileDialog.cs eto uses `System.Windows.Forms.SaveFileDialogHandler`. If that doesn't work for you properly, then there is an issue with the theme.

**Comment by Krakean** [comment] 2019-02-23 22:23
@kekekeks 
>If that doesn't work for you properly, then there is an issue with the theme.

May be. But it works fine in others Windows applications that also have open/save dialogs, as I showed you on screenshots.

**Comment by kekekeks** [comment] 2019-02-24 17:49
Windows have several different versions of file dialogs. If *some* of them work, it doesn't mean that *all* of them work.

**Comment by timunie** [comment] 2023-11-06 14:05
@Krakean I think this issue is pretty outdated now. I was not able to reproduce it using 11.0. So for now, I'm gonna close this issue. 

If you still have this issue in latest Avalonia, a minimal sample would be helpful.

**Closed by timunie** 2023-11-06 14:05 UTC
Labels: needs-repro, bug-in-dependency
