### ISSUE TITLE
Confusing error message if a view attempts to use [LibraryImport]

### ISSUE THREAD

**Issue by jyrkive** [AvaloniaUI/Avalonia#12369] opened 2023-07-28 14:46 UTC
**Describe the bug**

If a view tries to import a native method with [LibraryImport], building the project will fail with this rather unclear error message:

> E:\Temp\AvaloniaTest\MainWindow.axaml : Avalonia error AVLN:0004: Object reference not set to an instance of an object.

After upgrading a project of mine to Avalonia 11, it took me quite a while to find out that using [LibraryImport] in a view is what caused the error.

**To Reproduce**

1. Add this method into any view class (it doesn't need to be called anywhere):

```cs
[LibraryImport("user32.dll")]
[return: MarshalAs(UnmanagedType.Bool)]
private static partial bool SetForegroundWindow(IntPtr hWnd);
```

2. Try to build the project.

**Expected behavior**
Either that the project builds successfully, or an error message that informs the developer that [LibraryImport] isn't allowed in views.

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/1665617/0d561f8e-3d11-4eec-bed9-2c18098e4511)

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]: Windows 11
- Version [e.g. 0.10.0-rc1 or 0.9.12]: 11.0.1

**Comment by maxkatz6** [comment] 2023-07-29 05:53
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/10046

**Closed by maxkatz6** 2023-07-29 05:53 UTC
Labels: bug
