### ISSUE TITLE
Avalonia is unable to pass pointer events to NativeControlHost control

### ISSUE THREAD

**Issue by Synirrr** [AvaloniaUI/Avalonia#8104] opened 2022-05-09 13:01 UTC
**Describe the bug**
When placing the pointer over the NativeControlHost pointer events are not propagated to the control even though the control supports InputElement. 

**To Reproduce**

1. Create a NativeControlHost view
2. Hit F12 to show developer tools
3. Place pointer over the NativeControlHost and see that PointerOver field does not display the NativeControlHost control not the embedded window.

**Expected behavior**
NativeControlHost window is recognised by Avalonia for pointer/mouse events so these controls can be passed to the control.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 64-bit
- Version 10.0.19043 Build 19043

**Additional context**
Created any form of embedded windows will need their own control mechanism that can interfere with other Avalonia key inputs rather than unifying all controls under Avalonia.

**Comment by maxkatz6** [comment] 2022-05-09 17:23
I am not sure what's actually expected behavior here. Native controls are not part of avalonia tree and can't receive any events from it. Or is it a question specifically about the "host"? So "host" should see pointer events, but not the content?

**Comment by Synirrr** [comment] 2022-05-10 02:51
Sorry for the confusion. Let me try and explain it better.

Other controls within Avalonia that implement InputElement support pointer events and focus based key input events but NativeControlHost control cannot receive these same events. I understand the actual embedded window controls should not be passed in from Avalonia but the NativeControlHost control should still respond to pointer events and key input events if it implements InputElement since it is attached to the visual tree within the Avalonia application.

**Comment by maxkatz6** [comment] 2022-05-10 05:19
Oh, I see what you mean.
There was an issue about this https://github.com/AvaloniaUI/Avalonia/issues/5256
Shortly - these events are intercepted by native control.
But I wonder if it's only Windows specific behavior, or does mac implementation works in the same way.

**Comment by Synirrr** [comment] 2022-05-10 13:23
Ah that makes sense so the native control and its embedded window consume the inputs so Avalonia has no way of knowing if they occur. That is unfortunate. I wonder if it is possible to add an overlay over the NativeControlHost to allow for at least some aspect of control via Avalonia. If not completely fair and I will implement WndProc message handling to process the inputs.

**Comment by maxkatz6** [comment] 2022-10-24 05:34
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/5256

**Closed by maxkatz6** 2022-10-24 05:34 UTC
Labels: bug
