### ISSUE TITLE
Blur and AcrylicBlur are not working on windows 11 after 0.10.11 release

### ISSUE THREAD

**Issue by Abdesol** [AvaloniaUI/Avalonia#8497] opened 2022-07-13 06:44 UTC
**Describe the bug**
The blur and arcylicblur effect is not working on the recent releases except for the 0.10.11 on windows 11

**To Reproduce**

1. Create an avalonia program with the template
2. Set UseWindowsUIComposition to True
```
public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .With(new Win32PlatformOptions
                {
                    UseWindowsUIComposition = true
                })
                .LogToTrace()
                .UseReactiveUI();
```
3. Set ArcylicBlur or Blur on the window

**Screenshots**
On 0.10.11
![image](https://user-images.githubusercontent.com/69455299/178667701-3641d2e0-9c4f-441e-a566-5d9679a11a45.png)

On 0.10.16
![image](https://user-images.githubusercontent.com/69455299/178667748-1b860d5c-269f-4fff-8bb2-3d723c025526.png)

**Desktop:**

- OS: Windows 11
- Version: 22H2
- Build: 22622.290

**Comment by maxkatz6** [comment] 2022-07-13 07:00
Works fine for me on 25151.1010 and 0.10.16

![image](https://user-images.githubusercontent.com/3163374/178670777-680f8640-d1cf-4875-8d2c-4a1a87c6c38f.png)

**Comment by maxkatz6** [comment] 2022-07-13 07:00
When I do the opposite - set UseWindowsUIComposition to false - it stops working, and background is black.

**Comment by maxkatz6** [comment] 2022-07-24 19:49
Might be a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/6028

@Abdesol can you test build with "win7-x64"?

**Closed** 2022-07-26 15:50 UTC
Labels: bug, needs-repro
