### ISSUE TITLE
ListBox overlaps items under some conditions

### ISSUE THREAD

**Issue by agnauck** [AvaloniaUI/Avalonia#10585] opened 2023-03-07 16:39 UTC
**Describe the bug**
When I bind reactive collections (ReactiveUI and DynamicData) to a ListBox that has filters to slice and dice the data then ListItems sometimes start to overlap. It looks like 2 items are getting drawn at the same position.
Once this happens it does not resolve when I scroll the affected items out of the view and then back in. Most of the time the issue remains until the application gets restarted.
Often it starts with 1 item and then the same problems happens with more items over time.

**To Reproduce**
Its a very strange problem and its very hard to reproduce with a sample app. But it happens once in a while like you can see in the screen below. Try to filter by typing numbers in the Textbox and switch the fllter for showing even items. After a while you may be able to reproduce.
In my real app it happens quite often. But I wasn't able yet to narrow down the root cause yet.  I am sorry that I cannot supply a better sample where its easy to reproduce.

I have added a sample project here to reproduce:
https://github.com/agnauck/AvaloniaListBoxBug3/tree/main

**Expected behavior**
ListItems should be drawn correctly and not overlap

**Screenshots**
![list-bug](https://user-images.githubusercontent.com/1344950/223485807-03526646-9a96-4783-904d-2f8ed816df18.gif)

**Desktop (please complete the following information):**

- OS: Windows
- Version latest nightly build 11.0.999-cibuild0031645-beta

**Additional context**
This may be a threading issue coming form ReaviveUI and DynamicData. Its very hard to reproduce with a basic sample app. I am happy to write a more complex sample to reproduce when I can find a pattern or someone can give me some hints why this happens.

**Comment by timunie** [comment] 2023-03-08 11:30
does it reproduce for you if you add `.ObserveOn(RxApp.MainThreadScheduler)` to the source cache? 

```cs
            _items
                .Connect()                
                .Filter(itemsSearchTextFilter)
                .Filter(evenItemsSearchFilter)
                .ObserveOn(RxApp.MainThreadScheduler)
                .Sort(
                    SortExpressionComparer<Item>
                        .Ascending(i => i.Id)
                )
                .Bind(out _filteredItemsObservable)
                .Subscribe();
```

I can't reproduce either way, but I think it's saver to add this line. Can you add it and try again? 

https://www.reactiveui.net/docs/guidelines/framework/ui-thread-and-schedulers

**Comment by agnauck** [comment] 2023-03-08 11:56
the `ObserveOn(RxApp.MainThreadSchedulr)` makes no difference. In my "real" application I use it on all collections.

Here is a screen of my application where I use the ListBox to display debug messages.

There you can see it happens to a ListItem above the current selection.
This ListItem should not be displayed in the current view. Items are sorted by timestamp and according to the time (11:43:55) this Item should not make it to the current view and it should be invisible.
![image](https://user-images.githubusercontent.com/1344950/223705748-9492f1f1-0280-4af3-8e12-98a7a812bf44.png)

**Comment by timunie** [comment] 2023-03-08 12:01
Does the real App use the same Avalonia version?

**Comment by agnauck** [comment] 2023-03-08 12:03
> Does the real App use the same Avalonia version?

11.0.999-cibuild0031494-beta currently. I try to update to latest nightly every couple of days when I work on code.

**Comment by agnauck** [comment] 2023-03-21 13:40
And I think is also happens more often when I **focus** and **select** ListItems. So it may be related to this issue as well:
https://github.com/AvaloniaUI/Avalonia/issues/10367

**Comment by grokys** [comment] 2023-03-24 22:49
Yeah, I think this is a duplicate of #10367 .

**Closed by grokys** 2023-03-24 22:49 UTC
Labels: bug
