### ISSUE TITLE
Setting Transitions in Button style causes memory leak

### ISSUE THREAD

**Issue by wmchuang** [AvaloniaUI/Avalonia#11664] opened 2023-06-06 01:23 UTC
**Describe the bug**
Setting Transitions in Button style causes memory leak

**To Reproduce**

1.  https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src/Avalonia.Samples/Routing/BasicViewLocatorSample    
    Use this project. upgrade to 11.0.0-rc1.1

2. Add code.
![image](https://github.com/AvaloniaUI/Avalonia/assets/25163291/49e966a0-7cc5-4eda-b416-7fa30cd795c8)

3. run it
4. keep clicking on next back button

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/25163291/a14532c1-b489-48db-a5bd-52e21b87741a)

![image](https://github.com/AvaloniaUI/Avalonia/assets/25163291/566dd7f7-4371-46eb-9060-af6aee12f36a)

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.0-preview6 11.0.0-rc1.1 

**Additional context**

**Comment by wmchuang** [comment] 2023-06-06 01:24
https://github.com/AvaloniaUI/Avalonia/pull/10173  
 Has it been fixed ?

**Comment by timunie** [comment] 2023-06-06 06:19
@wmchuang after the PR you have linked is already merged, please try your sample again but this time using latest master. See https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed for instructions. 

PS: I cannot reproduce it on my machine at least.

**Comment by rabbitism** [comment] 2023-06-06 06:22
@timunie that pr was merged 4 month ago, It's already in rc.

**Closed** 2023-07-28 02:20 UTC
Labels: bug, area-animations

**Comment by dotNET-anykey** [comment] 2023-08-10 21:40
Tryied this on 11.0.3 and the problem is still present.

Commented transitions - no memory leak. Uncommented transitions - memory leak.

**Comment by timunie** [comment] 2023-08-11 06:32
@dotNET-anykey please open a new issue and attach a minimal sample. It may be a similar issue but a bit different.

**Comment by dotNET-anykey** [comment] 2023-08-13 19:02
> @dotNET-anykey please open a new issue and attach a minimal sample. It may be a similar issue but a bit different.

Idk, it's just identical :D
