### ISSUE TITLE
Transitions flat out not working

### ISSUE THREAD

**Issue by Azyyyyyy** [AvaloniaUI/Avalonia#2846] opened 2019-08-14 12:44 UTC
# Issue
Like I just said in https://github.com/AvaloniaUI/Avalonia/issues/2467, using Transitions on Height/Width properties seem to be broken.

Using http://avaloniaui.net/docs/animations/transitions as a example of the code (after changing ``<Setter Property="Background" Value="Red"/>`` to ``<Setter Property="Fill" Value="Red"/>`` and closing off Window) you will see that to Opacity Transition works as it should but changing it to Width/Height and giving it a new value doesn't effect it but instead messes up the control altogether

### Example:

![image](https://user-images.githubusercontent.com/21204235/63021763-36ca1d80-be99-11e9-9beb-c8d6a548bd29.png)
![image](https://user-images.githubusercontent.com/21204235/63021776-3e89c200-be99-11e9-8f1c-3e3f96b69789.png)

### Example 2:

![image](https://user-images.githubusercontent.com/21204235/63021850-69741600-be99-11e9-98b9-b55dc4d16e3f.png)
![image](https://user-images.githubusercontent.com/21204235/63021855-6bd67000-be99-11e9-821a-8d3bf76d2c80.png)
 
Note that the animation doesn't happen at all, it loads up like this
Edit: Also note that the animation doesn't happen on pointerover

**Comment by kekekeks** [comment] 2019-08-14 13:09
@jmacato

**Comment by kekekeks** [comment] 2019-08-14 13:34
Regardless of this bug, you should probably animate render transformations instead of Width/Height directly since changing Width/Height will trigger a layout pass which is kinda expensive performance-wise.

**Comment by AzyIsCool** [comment] 2019-08-14 13:50
Ok, what would the xaml/c# code be for that because I don't use that much (combine with me not knowing the api that well yet)

**Comment by noughtmare** [comment] 2020-05-14 15:10
I think my issue #3927 is a duplicate of this issue. 

> ~~Ok, what would the xaml/c# code be for that because I don't use that much (combine with me not knowing the api that well yet)~~ No worries I got it now

Can you please explain it a bit more for other people (like me) that also have the same problem? (This is starting to feel like https://xkcd.com/979/ :P)

**Closed** 2022-11-24 05:17 UTC
Labels: bug
