### ISSUE TITLE
RemoteDemo, black window

### ISSUE THREAD

**Issue by Kortexito** [AvaloniaUI/Avalonia#13025] opened 2023-09-26 04:56 UTC
When running RemoteDemo a window with black content appears. No controls displayed. 

![image](https://github.com/AvaloniaUI/Avalonia/assets/5676844/c46fa13e-2583-4e31-8cd6-cf1fbd2f056d)

**To Reproduce**
- Clone repository and follow instructions for VS2022.
- Set RemoteDemo as startup project
- Click Start in VS in Debug Configuration

**Comment by timunie** [comment] 2023-09-26 05:59
@Kortexito please fill the issue template. Add a minimal sample and steps to reproduce.

**Comment by Kortexito** [comment] 2023-09-26 07:11
Sorry, added reproduce info to the issue text

**Comment by timunie** [comment] 2023-09-26 07:56
Am I blind? I still see no repo link?

**Comment by Kortexito** [comment] 2023-09-26 08:11
Yes. Sorry once again. It is my first issue report on GitHub. Yes, it is Avalonia source code.

**Comment by timunie** [comment] 2023-09-26 08:34
Actually I've seen the RemoteDemo first time 😆 . I usually start ControlCatalog, Sanbox or RenderDemo. I even don't know what RemoteDemo should show tbh. From the code, it looks like there is nothing more to show than a Window.

**Comment by timunie** [comment] 2023-09-26 08:39
I asked our team: 

> you can do vnc via headless I think
> I used that in codespacess for testing

I think that this means that particular sample is not made to provide any useful content for you. So I'm closing this issue as not planned for now. 

Welcome to Avalonia ❤️

**Closed by timunie** 2023-09-26 08:39 UTC
Labels: bug, needs-repro
