### ISSUE TITLE
Advanced Avalonia+ReactiveUI+Routing example

### ISSUE THREAD

**Issue by cheprogrammer** [AvaloniaUI/Avalonia#3605] opened 2020-02-24 08:17 UTC
Hello,

I want to say that I'm excited to work with Avalonia, this is a fantastic experience to write cross-platform applications which actually works the same on Windows and Linux!

However, to write some advanced applications which uses the full power of chain Avalonia+ReactiveUI+Routing+Asyncs we definitely need some advanced example of code which can show us how to use all these things properly. Also, the current docs about integration with ReactiveUI shows us the very simple use-cases and docs for ReactiveUI do not cover enough to be sure that you are writing the leaks-free code in proper style.

Long story short, so, I have started this issue because I want to understand the following concepts.

### VM Reactive Commands and Routing
- Where the `ReactiveCommand` should be created - in VM constructor or in `WhenActivated` block? And why?
- What is the best way to create the async commands with `async/await` logic? Or may be they should be created in other way?
- How to properly lock the view (aka make it ReadOnly) when the command is executing?
- How to properly setup and use Routing - for example if I have a command which performs some async operation (like request to some REST API) how should I handle properly:
    - The making UI readonly during the request (related to previous point)
    - Return errors to UI textblock
    - Navigate somewhere using `Router.Navigate` (call it in subscription/call it in `async/await` source method/in other way)

### Binding VMs to Views
- What is the best way of binding - via XAML or via `WhenActivated` in view with `DisposeWith` call? And how I should decide which way should be chosen?
- How to avoid memory leaks on bindings?

### Observable examples
- Good use-cases with observing `SourceCache<TModel, TKey>` from singleton service via `Connect` with covering the following topics:
    - How to use `Connect`?
    - How to `Bind` connected SourceCache to `ObservableCollectionExtended`
    - How it should be disposed?
- Advanced example of Oaph usage - assign from multiple sources, etc. (And how to properly dispose them/Do we need to dispose them?)
- Cover most common use cases with `Subscription` and proper disposing of them
- Example of `this.WhenAnyValue` usage and proper disposing of it (or when and how it should be disposed?)

I'm not sure what is the best way how to communicate about it. Ideally, I want to write some example (and possibly exemplary application) after understanding all described concepts. Hope that this future sample application can be used as reference to get started and include it into samples in Avalonia (or as reference here https://github.com/AvaloniaCommunity/awesome-avalonia).

In best case I want to help to extend the Avalonia documentation with all these info.

Hope that you will be able to answer on my questions or provide some links to samples which covers all described cases.

Thanks!

**Comment by worldbeater** [comment] 2020-02-24 09:19
Generally most of the design patterns folks tend to use in WPF are also applicable to Avalonia. There is an online [ReactiveUI Handbook](https://reactiveui.net/docs/handbook/) which covers almost every aspect of the use cases of the reactive framework, including [commanding](https://reactiveui.net/docs/handbook/commands/), [routing](https://reactiveui.net/docs/handbook/routing/), [activation and memory management](https://reactiveui.net/docs/handbook/when-activated/). There is also [a book by Kent Boogaart](https://kent-boogaart.com/you-i-and-reactiveui/) a lot of `ReactiveUI` and `System.Reactive` usage examples. There is also [a bunch of open-source samples](https://reactiveui.net/docs/resources/samples) for various platforms.

### VM Reactive Commands and Routing
On every platform ReactiveUI supports folks usually create the commands in the constructor, and asynchronous logic is usually extracted into separate services which are injected into the view model via the constructor. The button bound to the command will be locked automatically, and to lock the whole view you could declare an [OAPH](https://reactiveui.net/docs/handbook/observable-as-property-helper/) bind to its `IsEnabled` property in XAML.

### Binding VMs to Views
AFAIK, the code-behind bindings were developed to allow the bindings to be compile-time-checked, and aren't necessarily needed in Avalonia, because its XAML markup is [compiled](https://github.com/kekekeks/XamlIl). The memory won't leak as well.

### Observable examples
A rule of thumb is, that subscriptions to everything that outlives the view (e.g. injected services or `public static` instances) should be placed into the `WhenActivated` block and disposed when the view model gets deactivated.

**Comment by cheprogrammer** [comment] 2020-02-24 13:41
Hi @worldbeater!

Thank you very much for such a detailed explanation, I do appreciate it - it gave me a lot of information to refine. 
However, the Routing subject is still not clear for me, I am still having the memory leak and I do not understand what is wrong. Let me show you some code!

I have a MainWindowVM with routing:

```
    public class MainWindowViewModel : ReactiveObject, IActivatableViewModel, IScreen
    {
        public ViewModelActivator Activator { get; } = new ViewModelActivator();

        public RoutingState Router { get; } = new RoutingState();

        public MainWindowViewModel()
        {
            var loginViewModel = new LoginViewModel(this);
            Router.Navigate.Execute(loginViewModel);

            this.WhenActivated((CompositeDisposable disposables) =>
            {
                
            });
        }
    }
```

Is is quite simple - on creating it performs the navigation to login vm:
```
    public class LoginViewModel : ViewModelBase, IRoutableViewModel
    {
        private IApplicationInfo _applicationInfo;
        private ILoginService _loginService;
        private ISettingsProvider<AppSettings> _settingsProvider;

        public IScreen HostScreen { get; }

        public string UrlPathSegment { get; } = nameof(LoginViewModel );

        [Reactive] public string Username { get; set; }

        [Reactive] public string Password { get; set; }

        [Reactive] public ClientMode ClientMode { get; set; }

        [Reactive] public string ErrorMessage { get; set; }

        public ReactiveCommand<Unit, Unit> Login { get; }

        public LoginViewModel(IScreen screen) : 
            this(screen, 
                Locator.Current.GetService<ILoginService>(),
                Locator.Current.GetService<IApplicationInfo>(),
                Locator.Current.GetService<ISettingsProvider<AppSettings>>())
        {

        }

        public LoginViewModel(IScreen screen, ILoginService loginService, IApplicationInfo applicationInfo, ISettingsProvider<AppSettings> settingsProvider)
        {
            HostScreen = screen;
            _loginService = loginService;
            _applicationInfo = applicationInfo;
            _settingsProvider = settingsProvider;

            ClientMode = _settingsProvider.Settings.ClientMode;

            var canLogin = this.WhenAnyValue(vm => vm.Username, vm => vm.Password,
                (userName, password) =>
                    !string.IsNullOrEmpty(userName) &&
                    !string.IsNullOrEmpty(password));

            Login = ReactiveCommand.CreateFromTask(LoginAsync, canLogin);

            Login.IsExecuting.ToProperty(this, x => x.IsBusy, out isBusy);

            this.WhenActivated((CompositeDisposable disposables) =>
            {
                // Added here just for testing
                GC.Collect();
            });
        }

        public async Task LoginAsync()
        {
            var result = await _loginService.LoginAsync(ClientMode, Username, Password);

            if(!result.Succeeded)
            {
                ErrorMessage = result.Errors.First().Message;
                return;
            }

            // Navigation here!
            await HostScreen.Router.NavigateAndReset.Execute(new WorkspaceViewModel(HostScreen, result.Data));
        }
    }
```

Workspace VM - its like a hub for the whole application. Now it simply navigates to EmployeesVM within its own `RoutedViewHost` on the corresponding view

```
    public class WorkspaceViewModel : ViewModelBase, IScreen, IRoutableViewModel
    {
        public string UrlPathSegment => nameof(WorkspaceViewModel);

        public IScreen HostScreen { get; }

        public RoutingState Router { get; } = new RoutingState();

        public UserInformationModel UserInformation { get; }

        [Reactive] public ReactiveCommand<Unit, Unit> Logout { get; set; }

        public WorkspaceViewModel(IScreen screen, UserInformationModel userInformation)
        {
            HostScreen = screen;
            UserInformation = userInformation;

            Logout = ReactiveCommand.Create(() => { HostScreen.Router.NavigateAndReset.Execute(new LoginViewModel(HostScreen)); });
            Router.Navigate.Execute(new EmployeesViewModel(this));
        }
    }
```

So, what is the EmployeesViewModel?

```
    public class EmployeesViewModel : ReactiveObject, IActivatableViewModel, IRoutableViewModel
    {
        public ViewModelActivator Activator { get; } = new ViewModelActivator();

        public string UrlPathSegment { get; } = nameof(EmployeesViewModel);

        public IScreen HostScreen { get; }

        // This is added just for understanding does this EmployeesViewModel is removed from memory or not
        private byte[] Temp = new byte[1024 * 1024 * 20];

        private ReadOnlyObservableCollection<EmployeeModel> _items;
        public ReadOnlyObservableCollection<EmployeeModel> Items => _items;

        [Reactive] public EmployeeModel SelectedEmployee { get; set; }

        private readonly IEmployeesService _employeesService;

        public ReactiveCommand<Unit, Unit> AddEmployee { get; }

        public ReactiveCommand<Unit, Unit> EditEmployee { get; }

        public EmployeesViewModel(IScreen hostScreen) :
            this(hostScreen, Locator.Current.GetService<IEmployeesService>())
        {

        }

        public EmployeesViewModel(IScreen hostScreen, IEmployeesService employeesService)
        {
            HostScreen = hostScreen;
            _employeesService = employeesService;

            AddEmployee = ReactiveCommand.Create(() => { HostScreen.Router.Navigate.Execute(new AddEmployeeViewModel(HostScreen, new EmployeeModel(), _employeesService)); });

            EditEmployee = ReactiveCommand.Create(() => { HostScreen.Router.Navigate.Execute(new EditEmployeeViewModel(HostScreen, SelectedEmployee, _employeesService)); });

            this.WhenActivated((CompositeDisposable disposables) =>
            {
                _employeesService
                    .Connect()
                    .ObserveOn(RxApp.MainThreadScheduler)
                    .Bind(out _items)
                    .Subscribe()
                    .DisposeWith(disposables);
            });
        }
    }
```

Here is the code for AddEmployeeViewModel:
```
    public class AddEmployeeViewModel : ViewModelBase<EmployeeModel>, IRoutableViewModel
    {
        private readonly IEmployeesService _employeesService;

        public string UrlPathSegment => nameof(AddEmployeeViewModel);

        public IScreen HostScreen { get; }

        private byte[] Temp = new byte[1024 * 1024 * 20];

        public ReactiveCommand<Unit, Unit> Add { get; }

        public ReactiveCommand<Unit, Unit> Cancel { get;}

        [Reactive] public string UsernameValidation { get; set; }

        [Reactive] public string PasswordValidation { get; set; }

        public AddEmployeeViewModel(IScreen hostScreen, EmployeeModel model, IEmployeesService employeesService) : base(model)
        {
            HostScreen = hostScreen;
            _employeesService = employeesService;

            Add = ReactiveCommand.CreateFromTask(AddImpl, this.IsValid());
            Cancel = HostScreen.Router.NavigateBack;

            this.ValidationRule(vm => vm.Model.Username, name => !string.IsNullOrEmpty(name), "Username is required");
            this.ValidationRule(vm => vm.Model.Username, name => _employeesService.UsernameIsFree(name), "Username is occupied by another user");

            this.ValidationRule(vm => vm.Model.Password, password => !string.IsNullOrEmpty(password), "Password is required");
            this.ValidationRule(vm => vm.Model.BirthDate, birthdate => birthdate.HasValue ? birthdate.Value.Date <= DateTime.Now.Date : true, "Birtday should be less or equal to the current date");

            Add.IsExecuting.ToProperty(this, x => x.IsBusy, out isBusy);

            this.WhenActivated((CompositeDisposable disposables) =>
            {

            });
        }

        public async Task AddImpl()
        {
            var result = await _employeesService.AddAsync(Model);

            if(result.Succeeded)
                HostScreen.Router.NavigateBack.Execute();
        }
    }
```

And code for EditEmployeeViewModel:
```
    public class EditEmployeeViewModel : ViewModelBase<EmployeeModel>, IRoutableViewModel
    {
        public string UrlPathSegment => nameof(EditEmployeeViewModel);

        public IScreen HostScreen { get; }

        private readonly IEmployeesService _employeesService;

        private byte[] Temp = new byte[1024 * 1024 * 20];

        [Reactive] public ReactiveCommand<Unit, Unit> Save { get; set; }

        [Reactive] public ReactiveCommand<Unit, Unit> Cancel { get; set; }

        private readonly string _originalUserName;

        public EditEmployeeViewModel(IScreen hostScreen, EmployeeModel model, IEmployeesService service) : base(model)
        {
            HostScreen = hostScreen;
            _employeesService = service;

            _originalUserName = model.Username;

            this.ValidationRule(vm => vm.Model.Username, name => !string.IsNullOrEmpty(name), "Username is required");
            this.ValidationRule(vm => vm.Model.Username, name => name == _originalUserName || Model.IsRegisteredOnThePortal || _employeesService.UsernameIsFree(name), "Username is occupied by another user");

            this.ValidationRule(vm => vm.Model.Password, password => !string.IsNullOrEmpty(password), "Password is required");
            this.ValidationRule(vm => vm.Model.BirthDate, birthdate => birthdate.HasValue ? birthdate.Value.Date <= DateTime.Now.Date : true, "Birtday should be less or equal to the current date");

            Save = ReactiveCommand.CreateFromTask(SaveImplementation, this.IsValid());
            Cancel = HostScreen.Router.NavigateBack;

            Save.IsExecuting.ToProperty(this, x => x.IsBusy, out isBusy);

            this.WhenActivated((CompositeDisposable disposables) =>
            {

            });
        }

        public async Task SaveImplementation()
        {
            var result = await _employeesService.UpdateAsync(Model);
        }
    }
```

Here are the use cases:

1. Start application -> Login -> Logout
2. Start application -> Login -> Click Add Employee -> Click Cancel
3. Start application -> Login -> Click Edit Employee -> Click Cancel -> Logout
4. Start application -> Login -> Click Edit Employee -> Logout

With 1 and 2 everything is fine. But 3 and 4 leads to the huge memory leakage (of course, due to temp bytearrays, but them just for testing and to see the whole picture)

Also, it is important to mention that I'm using DataGrid for displaying `EmployeesViewModel.Items`.

Here is the part of code of DataGrid templated column for EditCommand.
```
<DataGridTemplateColumn Width="*">
	<DataGridTemplateColumn.CellTemplate>
		<DataTemplate>
			<WrapPanel Orientation="Horizontal" HorizontalAlignment="Right">
				<StackPanel Orientation="Horizontal">
					<Button Content="Edit" Command="{Binding $parent[DataGrid].DataContext.EditEmployee}" />
				</StackPanel>
			</WrapPanel>
		</DataTemplate>
	</DataGridTemplateColumn.CellTemplate>
</DataGridTemplateColumn>
```

What I'm doing wrong? It seems that I'm following all guides from Handbook, but it is something weird here.

Thanks in advance!

**Comment by worldbeater** [comment] 2020-02-24 14:45
@cheprogrammer could you please upload a repro into a separate repo, so one could browse the whole code, `git clone` and then debug and profile it? From what I see from your message, the issue can be with memory traffic rather than with a memory leak (although not sure). Anyway, the best way to investigate is to check if there are objects holding references to the view models, using the Visual Studio profiler etc.

**Comment by cheprogrammer** [comment] 2020-02-24 17:51
Hi @worldbeater !

Here is the link to repo with sample project: https://github.com/cheprogrammer/SampleAvaloniaApplication

Please, let me know how it goes!

**Comment by cheprogrammer** [comment] 2020-02-25 15:39
Hi @worldbeater !

Did you have a chance to loot at my repo? It seems that after entering the EditViewModel it is started to hang in memory forever.

Maybe the problem is [here]? (I'm passing the SelectedEmployee to the new View Model)(https://github.com/cheprogrammer/SampleAvaloniaApplication/blob/001d741a15af7284b0960f51bb910b1c580cc8e0/Client/SampleAvaloniaApplication.Client.Core/ViewModels/Employees/EmployeesViewModel.cs#L56)

Anyway, I do not have any idea why it is leading to memory leak. Hope that you will be able to help me.

Thanks in advance!

**Comment by cheprogrammer** [comment] 2020-02-27 04:31
Hi! 

Any updates on reported memory leak? I still do not have any idea why it is happening.

**Comment by worldbeater** [comment] 2020-03-02 12:32
@cheprogrammer didn't have time to do a full profiling session, but probably the issue is in here https://github.com/cheprogrammer/SampleAvaloniaApplication/blob/001d741a15af7284b0960f51bb910b1c580cc8e0/Client/SampleAvaloniaApplication.Client.Core/Models/EmployeeModel.cs All the properties of the view model are marked as `[Reactive]`. Then, those properties are observed in the `EditEmployeeViewModel` and never unsubscribed, because the referenced model is kept inside the `EmployeesService`. Try using `NavigateAndReset` instead of `Navigate` here, because otherwise the view model is left in the navigation stack as well https://github.com/cheprogrammer/SampleAvaloniaApplication/blob/001d741a15af7284b0960f51bb910b1c580cc8e0/Client/SampleAvaloniaApplication.Client.Core/ViewModels/Employees/EmployeesViewModel.cs#L56 But still worth doing a profiling session, probably will have time this weekend.

**Comment by cheprogrammer** [comment] 2020-03-03 04:30
Hi @worldbeater !

Thank you very much for your suggestions, I will rework entire application!

**Closed** 2020-07-28 04:10 UTC
