### ISSUE TITLE
DataGridCheckBoxColumn has fundamentally flawed behaviour

### ISSUE THREAD

**Issue by Sayayaya** [AvaloniaUI/Avalonia#15511] opened 2024-04-25 11:01 UTC
### Describe the bug

Once a row becomes focused, it is impossible to toggle the checkbox, leading the user to think the control is broken.

The only way to toggle the checkbox again is to click somewhere else on the UI so that the control loses focus.

### To Reproduce

Make a datagrid with a checkbox column bound to a bool in a viewmodel.

### Expected behavior

The checkbox changes state when clicked, as the user would expect.

### Avalonia version

11.0.10

### OS

Windows 10

### Additional context

DataGrid 11.0.10

**Comment by timunie** [comment] 2024-04-25 12:57
1. try 11.1 beta please
3. Mind that DataGridCheckBoxColumn requires the cell to be editable by design. If you want single click solution consider a TemplateColumn instead

Seems to be a duplicate of #14715

**Closed by timunie** 2024-04-25 12:57 UTC
Labels: bug
