### ISSUE TITLE
Custom Font throws exception on macOS

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#8726] opened 2022-08-11 13:46 UTC
**Describe the bug**
Custom Font in Avalonia throws Exceptions on the macOS platform. But on the windows, the font displays as expected.
```
Unhandled exception. System.InvalidOperationException: Could not create glyph typeface for: Minecraft Ten.
   at Avalonia.Skia.FontManagerImpl.CreateGlyphTypeface(Typeface typeface) in /_/src/Skia/Avalonia.Skia/FontManagerImpl.cs:line 146
   at Avalonia.Media.FontManager.GetOrAddGlyphTypeface(Typeface typeface) in /_/src/Avalonia.Visuals/Media/FontManager.cs:line 94
   at Avalonia.Media.TextFormatting.TextCharacters.TryGetRunProperties(ReadOnlySlice`1 text, Typeface typeface, Typeface defaultTypeface, Int32& count) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 129
   at Avalonia.Media.TextFormatting.TextCharacters.CreateShapeableRun(ReadOnlySlice`1 text, TextRunProperties defaultProperties) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 62
   at Avalonia.Media.TextFormatting.TextCharacters.GetShapeableCharacters() in /_/src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs:line 40
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FetchTextRuns(ITextSource textSource, Int32 firstTextSourceIndex, TextLineBreak previousLineBreak, TextLineBreak& nextLineBreak) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs:line 280
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak) in /_/src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs:line 39
   at Avalonia.Media.TextFormatting.TextLayout.UpdateLayout() in /_/src/Avalonia.Visuals/Media/TextFormatting/TextLayout.cs:line 223
   at Avalonia.Controls.TextBlock.CreateTextLayout(Size constraint, String text) in /_/src/Avalonia.Controls/TextBlock.cs:line 475
   at Avalonia.Controls.TextBlock.get_TextLayout() in /_/src/Avalonia.Controls/TextBlock.cs:line 166
   at Avalonia.Controls.TextBlock.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/TextBlock.cs:line 512
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 549
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 386
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/StackPanel.cs:line 207
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 549
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 386
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint) in /_/src/Avalonia.Controls/Grid.cs:line 230
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 549
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 386
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 46
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Border.cs:line 187
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 549
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 386
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 46
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 366
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 549
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 386
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 625
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 549
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 386
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV) in /_/src/Avalonia.Controls/Grid.cs:line 1108
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged) in /_/src/Avalonia.Controls/Grid.cs:line 1005
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint) in /_/src/Avalonia.Controls/Grid.cs:line 489
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 549
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 386
   at Avalonia.Layout.FlowLayoutAlgorithm.MeasureElement(ILayoutable element, Int32 index, Size availableSize, VirtualizingLayoutContext context) in /_/src/Avalonia.Layout/FlowLayoutAlgorithm.cs:line 153
   at Avalonia.Layout.StackLayout.GetAverageElementSize(Size availableSize, VirtualizingLayoutContext context, StackLayoutState stackLayoutState) in /_/src/Avalonia.Layout/StackLayout.cs:line 349
   at Avalonia.Layout.StackLayout.GetAnchorForRealizationRect(Size availableSize, VirtualizingLayoutContext context) in /_/src/Avalonia.Layout/StackLayout.cs:line 240
   at Avalonia.Layout.StackLayout.Avalonia.Layout.IFlowLayoutAlgorithmDelegates.Algorithm_GetAnchorForRealizationRect(Size availableSize, VirtualizingLayoutContext context) in /_/src/Avalonia.Layout/StackLayout.cs:line 166
   at Avalonia.Layout.FlowLayoutAlgorithm.GetAnchorIndex(Size availableSize, Boolean isWrapping, Double minItemSpacing, String layoutId) in /_/src/Avalonia.Layout/FlowLayoutAlgorithm.cs:line 238
   at Avalonia.Layout.FlowLayoutAlgorithm.Measure(Size availableSize, VirtualizingLayoutContext context, Boolean isWrapping, Double minItemSpacing, Double lineSpacing, Int32 maxItemsPerLine, ScrollOrientation orientation, Boolean disableVirtualization, String layoutId) in /_/src/Avalonia.Layout/FlowLayoutAlgorithm.cs:line 102
   at Avalonia.Layout.StackLayout.MeasureOverride(VirtualizingLayoutContext context, Size availableSize) in /_/src/Avalonia.Layout/StackLayout.cs:line 290
   at Avalonia.Layout.AttachedLayout.Measure(LayoutContext context, Size availableSize) in /_/src/Avalonia.Layout/AttachedLayout.cs:line 130
   at Avalonia.Controls.ItemsRepeater.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Repeater/ItemsRepeater.cs:line 321
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 549
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 386
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 285
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 261
   at Avalonia.Layout.LayoutManager.InnerLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 243
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 145
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4336
```

**To Reproduce**

1. Add a custom font to the project
2. Set its build operation to "Avalonia Resource"
3. Create a new TextBlock with following XAML:
```xaml
<TextBlock FontFamily="/Assets/Font/MinecraftTen-VGORe.ttf#Minecraft Ten">
    TEXT
</TextBlock>
```
4. Compile the project target to OSX-X64
5. Run this program on the macOS
6. Error shows

**Expected behavior**
A TextBlock control with custom font should appear on the window

**Screenshots**
<img width="271" alt="image" src="https://user-images.githubusercontent.com/25716486/184147473-217a3388-8273-4927-b962-8fb96f0d9364.png">

**Desktop (please complete the following information):**

- OS: macOS
- Version: 12.5 Monterey

**Comment by timunie** [comment] 2022-08-11 19:32
@laolarou726 can you send the Avalonia Version you used? 

Also it would be really great if you can test it with latest master (not your working App) to verify if the issue is gone already in the upcoming version.

**Comment by laolarou726** [comment] 2022-08-11 20:17
@timunie I'm using the 0.10.17 right now for my working project. Are there any breaking changes in the current master branch? Btw, when will version 0.11 be released?

**Comment by laolarou726** [comment] 2022-08-11 23:27
@timunie I tried to build macOS binary with latest master branch. However, it pops an error show that:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/25716486/184258813-591289c2-2a31-4357-8a88-1209631bb45c.png">

```
CSC : error AXN0002: XamlX.XamlParseException: Unable to resolve type SimpleTheme from namespace clr-namespace:Avalonia.Themes.Default;assembly=Avalonia.Themes.Default
```

But I can debug the code on the Windows OS. Is this another bug?

Avalonia Version I'm using: Avalonia-0.10.999-cibuild0022654-beta

**Comment by maxkatz6** [comment] 2022-08-11 23:34
@laolarou726 there are a lot of breaking changes in 11.0 branch, you can find a list in the repository's wiki. 

I used custom fonts on my project with stable branch on macos, works as expected. Maybe something specific about your font file? Can you attach it with minimal project?

@Gillibald might also know if it's a known issue with fonts resolving and if it was solved in the master.

**Comment by laolarou726** [comment] 2022-08-11 23:38
@maxkatz6 Here is the test repo with the font file: https://github.com/laolarou726/AcrylicTest

**Comment by timunie** [comment] 2022-08-12 04:48
@laolarou726 as @maxkatz6 said there are many breaking changes. I think the themes are now in their own nuget packages atm. 

However, if I need to test a certain issue, I use the Sandbox project in the source code.

**Comment by maxkatz6** [comment] 2022-08-12 21:52
@laolarou726 it seems SkiaSharp's SKTypeface.FromStream returns typeface with "Minecraft" name on macOS. So when I change
`FontFamily="/MinecraftTen-VGORe.ttf#Minecraft Ten"` to `FontFamily="/MinecraftTen-VGORe.ttf#Minecraft"` it works fine.

![Screen Shot 2022-08-12 at 5 50 34 PM](https://user-images.githubusercontent.com/3163374/184449416-a61e6be9-29e6-4385-a81f-661ec1f42296.png)

I don't think it's a bug in Avalonia, as SkiaSharp returns a wrong result. Or native Skia implementation most likely.
CC @Gillibald

**Comment by laolarou726** [comment] 2022-08-12 21:54
@maxkatz6 Is there any temporary solution for this? Also, do I need to open another issue on SkiaSharp's repo?

**Comment by maxkatz6** [comment] 2022-08-12 22:08
> Also, do I need to open another issue on SkiaSharp's repo?

You can, but I don't know if that's an issue in SkiaSharp, or in Skia or in macOS native apis.

> Is there any temporary solution for this

I would try on of these:
1. Use "Minecraft" font name, if it also works on windows.
2. Edit ttf font directly with third party font editor
3. Or create font family from the code with this condition:
```csharp
public static FontFamily MinecraftFont = OperatingSystem.IsMacOS()
    ? new FontFamily("avares://AcrylicTest/MinecraftTen-VGORe.ttf#Minecraft")
    : new FontFamily("avares://AcrylicTest/MinecraftTen-VGORe.ttf#Minecraft Ten");
```
later can be used with `{x:Static}` markup extension

**Comment by maxkatz6** [comment] 2022-08-12 22:10
What I see in font metadata. `sk_typeface_get_family_name` returns `Z_TYPOGRAPHICFAMILY 1` on macos, when Avalonia expects `Z_FONTFAMILYNAME 1`.

![Screen Shot 2022-08-12 at 6 09 07 PM](https://user-images.githubusercontent.com/3163374/184451021-725e42ad-798a-4a5c-bd24-b6f2b5539f77.png)

**Comment by laolarou726** [comment] 2022-08-12 22:31
> > Also, do I need to open another issue on SkiaSharp's repo?
> 
> You can, but I don't know if that's an issue in SkiaSharp, or in Skia or in macOS native apis.
> 
> > Is there any temporary solution for this
> 
> I would try on of these:
> 
> 1. Use "Minecraft" font name, if it also works on windows.
> 2. Edit ttf font directly with third party font editor
> 3. Or create font family from the code with this condition:
> 
> ```cs
> public static FontFamily MinecraftFont = OperatingSystem.IsMacOS()
>     ? new FontFamily("avares://AcrylicTest/MinecraftTen-VGORe.ttf#Minecraft")
>     : new FontFamily("avares://AcrylicTest/MinecraftTen-VGORe.ttf#Minecraft Ten");
> ```
> 
> later can be used with `{x:Static}` markup extension

Thanks, using the name "Minecraft" works both on Windows and macOS!

**Comment by Gillibald** [comment] 2022-08-13 07:05
Avalonia loads a font when just some part of the font name matches that is returned by Skia. That's why "Minecraft" works on both systems. Skia itself relies on CoreText to get the system font.

**Closed** 2022-08-13 07:13 UTC
Labels: bug-in-dependency
