### ISSUE TITLE
Unable to bind to Window.Position

### ISSUE THREAD

**Issue by mikejashton** [AvaloniaUI/Avalonia#3494] opened 2020-01-31 13:09 UTC
It is not currently possible to bind to the Position element of Window. The compiler returns the following error:

  MainWindow.xaml(7, 9): [XAMLIL] Unable to find suitable setter or adder for property Position of type Avalonia.Controls:Avalonia.Controls.Window for argument Avalonia.Markup:Avalonia.Data.Binding, available setter parameter lists are:
Avalonia.PixelPoint (line 7 position 9) Line 7, position 9.

It looks like the Position is treated differently to Width and Height. Is it possible to allow binding to this property?

**Comment by Schafwolle** [comment] 2021-01-14 14:32
I guess this issue is not yet merged. 
I am running into the same error with (Avalonia Version 0.10.0-rc1)

**Comment by mysteryx93** [comment] 2021-12-17 01:10
Having the same issue in 0.10.10

**Comment by maxkatz6** [comment] 2021-12-17 01:15
This probably should be closed as "by design" due https://github.com/AvaloniaUI/Avalonia/pull/3521#issuecomment-582243868

**Comment by maxkatz6** [comment] 2021-12-17 01:18
Assuming it's expected to have writeable property with two-way bindings support.
Readonly avalonia-property with separated set method might be correct one, but will introduce a breaking change without much sense https://github.com/AvaloniaUI/Avalonia/pull/3521#issuecomment-585179130

**Comment by mysteryx93** [comment] 2021-12-17 01:29
Binding doesn't work; but does that also mean that if I need to display an overlay window, I won't be able to position it at all?

**Comment by maxkatz6** [comment] 2021-12-17 01:49
Why not? There is a Window.PositionChanged event. 
The problem with having a binding (https://github.com/AvaloniaUI/Avalonia/pull/3521#issuecomment-582243868) it that on some platforms there might be a delay between setting new position and having updated value of this property

**Comment by mysteryx93** [comment] 2021-12-17 02:13
ah ok, I can read with PositionChanged and write with Position from code-behind. It's just that these 2 methods aren't MVVM-friendly. If I don't mind that delay, I wonder if I can get a binding job done with an attached property?

**Comment by maxkatz6** [comment] 2021-12-17 02:29
> I wonder if I can get a binding job done with an attached property or would I run into issues?

You can. Possible issues are exactly the same as it would be done out of the box: https://github.com/AvaloniaUI/Avalonia/pull/3521#issuecomment-582243868 https://github.com/AvaloniaUI/Avalonia/pull/3521#issuecomment-585179130

It might not be an issue in your code, but in framework code this behavior might be confusing for some.

**Comment by mysteryx93** [comment] 2021-12-17 15:40
For creating an extension property; where would I hook into the PositionChanged event?

```
public class PositionExtension : AvaloniaObject
{
    static PositionExtension()
    {
        PositionProperty.Changed.Subscribe(OnPositionChanged);
    }
    
    // Position (Window.Position doesn't support binding by default) 
    public static readonly AttachedProperty<PixelPoint> PositionProperty =
        AvaloniaProperty.RegisterAttached<PositionExtension, Window, PixelPoint>("Position"); 
    public static PixelPoint GetPosition(AvaloniaObject d) => d.CheckNotNull(nameof(d)).GetValue(PositionProperty);
    public static void SetPosition(AvaloniaObject d, PixelPoint value) => d.CheckNotNull(nameof(d)).SetValue(PositionProperty, value);
    private static void OnPositionChanged(AvaloniaPropertyChangedEventArgs<PixelPoint> e)
    {
        if (e.Sender is Window p)
        {
            p.Position = e.NewValue.Value;
        }
    }
}
```

**Closed** 2023-07-03 09:04 UTC
Labels: by-design
