### ISSUE TITLE
Grid: star-sized children overlaps

### ISSUE THREAD

**Issue by zii-dmg** [AvaloniaUI/Avalonia#11965] opened 2023-06-29 20:40 UTC
**Describe the bug**
Using star-size for `Grid` columns leads to strange behavior - children with some MinWidth overlaps and moves in neighbor cell bounds. I don't know is it bug or expected. WPF clips cells.

**Code (also in videos)**
```
<Grid Background="LightGray" VerticalAlignment="Center" Margin="30">
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="Auto" />
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="8*" />
    </Grid.ColumnDefinitions>

    <TextBlock VerticalAlignment="Center">Hello world</TextBlock>
    <TextBox Grid.Column="1" Margin="3" MinWidth="64">123</TextBox>
    <TextBox Grid.Column="2" Margin="3" MinWidth="64">456</TextBox>
</Grid>
```

**Avalonia**
https://github.com/AvaloniaUI/Avalonia/assets/2846896/cbbe7a52-eff2-4b2f-a19d-f24f3594205b

**WPF**
https://github.com/AvaloniaUI/Avalonia/assets/2846896/470d6299-c0b7-493f-b729-f3ee61d5feb2

- OS: Windows 10
- Version: 11.0.0-rc1.1

**Comment by maxkatz6** [comment] 2023-06-29 21:09
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/11320

**Closed by maxkatz6** 2023-06-29 21:09 UTC
Labels: bug
