### ISSUE TITLE
[BUG] TrayIcon crashes application on closing (Windows)

### ISSUE THREAD

**Issue by XanatosX** [AvaloniaUI/Avalonia#7588] opened 2022-02-12 10:02 UTC
**Describe the bug**
Application crashed on Windows if you exit and there is a tray icon on the main window

**To Reproduce**
Not sure if this happens on other operation systems as well only tested it on Windows

1. Create a new mvvm application
2. Set it up as a [fluent design application][FluentDesignApplication]
3. Add a tray icon to the application (See additional context)
4. Start the application via Debug/Release
5. Close the application with the close button
6. Crash on `program.cs` -> `System.NullReferenceException: 'Object reference not set to an instance of an object.'`

**Expected behavior**
The application closes successfully

**Desktop (please complete the following information):**

- OS Windows 10
- Avalonia Version 0.10.12

**Additional context**
Tray icon code
```xml
<TrayIcon.Icons>
     <TrayIcons>
          <TrayIcon Icon="/Assets/avalonia-logo.ico" Command="{Binding ShowApplicationCommand}" ToolTipText="Modular tool manager">
               <TrayIcon.Menu>
		     <NativeMenu>
		          <NativeMenuItem Header="Testing" Command="{Binding ExitApplicationCommand}"/>
		     </NativeMenu>
		</TrayIcon.Menu>
	    </TrayIcon>
	</TrayIcons>
</TrayIcon.Icons>
```

Stacktrace
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Avalonia.Controls
  StackTrace:
   at Avalonia.Controls.TrayIcon.RemoveIcons(IEnumerable`1 icons) in /_/src/Avalonia.Controls/TrayIcon.cs:line 204
   at Avalonia.Controls.TrayIcon.Lifetime_Exit(Object sender, ControlledApplicationLifetimeExitEventArgs e) in /_/src/Avalonia.Controls/TrayIcon.cs:line 195
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.DoShutdown(ShutdownRequestedEventArgs e, Boolean force, Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 173
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.TryShutdown(Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 91
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.HandleWindowClosed(Window window) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 82
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.WindowClosedEvent(Object sender, RoutedEventArgs e) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 33
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass23_0.<AddClassHandler>b__0(ValueTuple`2 args) in /_/src/Avalonia.Interactivity/RoutedEvent.cs:line 94
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 36
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 147
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 148
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 87
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 122
   at Avalonia.Controls.Window.HandleClosed() in /_/src/Avalonia.Controls/Window.cs:line 942
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 86
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 30

```

[FluentDesignApplication]: https://docs.avaloniaui.net/tutorials/music-store-app/creating-a-modern-looking-window

**Comment by maxkatz6** [comment] 2022-02-13 16:22
This was fixed in master

**Comment by XanatosX** [comment] 2022-02-13 16:24
So it will be fixed with one of the next versions?

**Comment by maxkatz6** [comment] 2022-02-15 08:21
It seems [this PR](https://github.com/AvaloniaUI/Avalonia/pull/7477) won't be backported to the 0.10.x branch, so fix will be available only with next major version.
CC @grokys

**Comment by scottdoingwork** [comment] 2022-02-24 02:47
Same problem happen on linux with Avalonia 0.10.12.

**Comment by nlogozzo** [comment] 2022-03-03 02:39
Is this fix present in 0.10.13? @maxkatz6

**Comment by PhantomGamers** [comment] 2022-04-13 22:56
I'm getting this error on the latest nightly build of Avalonia as well (currently 0.10.999-cibuild0019887-beta)

Also it occurs on Linux as well so it's not Windows specific.

**Comment by tsuckow** [comment] 2022-05-20 04:30
Persists in 0.10.14

**Comment by tsuckow** [comment] 2022-05-20 04:41
@maxkatz6 That PR wouldn't fix it anyway as the exception is happening at https://github.com/AvaloniaUI/Avalonia/blob/8bd9cb17f8312efee26eb8fcd3e0359293c900d0/src/Avalonia.Controls/TrayIcon.cs#L203 because the object being inspected to have relevant icons, doesn't.

**Comment by tsuckow** [comment] 2022-05-20 04:57
I present you the workaround. Why it doesn't register itself I don't know.

```c#
public override void OnFrameworkInitializationCompleted()
{
    if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
    {
        desktop.MainWindow = new MainWindow();

        var trayIcon = new TrayIcon();
        trayIcon.Icon = desktop.MainWindow.Icon;
        trayIcon.ToolTipText = "Test";

        // Workaround for https://github.com/AvaloniaUI/Avalonia/issues/7588
        var icons = new TrayIcons();
        icons.Add(trayIcon);
        TrayIcon.SetIcons(Application.Current!, icons);
    }

    base.OnFrameworkInitializationCompleted();
}
```

**Comment by PhantomGamers** [comment] 2022-05-20 05:28
I can confirm that the workaround works! Thanks so much for posting your findings!!!

**Comment by maxkatz6** [comment] 2022-07-20 03:50
Done https://github.com/AvaloniaUI/Avalonia/pull/8478

**Closed by maxkatz6** 2022-07-20 03:51 UTC
Labels: bug

**Comment by tsuckow** [comment] 2022-07-20 04:16
The workaround is likely still needed as icons would not get removed on app exit.

**Comment by maxkatz6** [comment] 2022-07-20 04:52
@tsuckow it is getting removed, unless app crashed.

#8478 specifically problem was related to the fact, that we subscribe to the application exit in trayicon static ctor, even if icon has never actually been added to the application.

**Comment by tsuckow** [comment] 2022-07-20 04:55
So then is the workaround above something we should have been doing this entire time to add the icon to the application? I don't believe there is any documentation showing we should be calling Trayicons.seticons

**Comment by maxkatz6** [comment] 2022-07-20 05:00
@tsuckow I haven't said it.

`TrayIcon.SetIcons(Application.Current!, new TrayIcons());` is the equivalent of
```xaml
<Application>
   <TrayIcon.Icons>
       <TrayIcons/>
   </TrayIcon.Icons>
</Application>
```

**Comment by maxkatz6** [comment] 2022-07-20 05:15
Okay, I think I see what's your actual problems is...
You shouldn't set TrayIcons on a Window. It should be set on an Application instance.

**Comment by tsuckow** [comment] 2022-07-20 05:37
Ok, I think I understand now what is happening behind the scenes with the first three levels of

```xaml
<Application>
  <TrayIcon.Icons>
      <TrayIcons>
          <TrayIcon Icon="/Assets/icon_blue.png" ToolTipText="Avalonia Tray Icon ToolTip">
            <TrayIcon.Menu>
	        <NativeMenu>
                    <NativeMenuItem Header="Quit" />
	        </NativeMenu>
            </TrayIcon.Menu>
          </TrayIcon>
      </TrayIcons>
  </TrayIcon.Icons>
</Application>
```

And that the workaround I posted above isn't a workaround, we should have been doing that all along when we don't use axaml (Though others may have malformed axaml as you point out where a TrayIcon needs to be in Application->TrayIcon.Icons->TrayIcons).

Equivalent without axaml:

```c#
public override void OnFrameworkInitializationCompleted()
{
    if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
    {
        desktop.ShutdownMode = ShutdownMode.OnExplicitShutdown;

        var assets = AvaloniaLocator.Current.GetService<IAssetLoader>();
        var bitmap = new Bitmap(assets!.Open(new Uri($"avares://{Assembly.GetExecutingAssembly().FullName}/Assets/icon_blue.png")));
        var icon = new WindowIcon(bitmap);
        var trayIcon = new TrayIcon();
        trayIcon.Icon = icon;
        trayIcon.ToolTipText = "Avalonia Tray Icon ToolTip";
        var menu = new NativeMenu();
        var item = new NativeMenuItem("Quit");

        // Register tray icons to be removed on application shutdown
        var icons = new TrayIcons();
        icons.Add(trayIcon);
        TrayIcon.SetIcons(Application.Current!, icons);
    }

    base.OnFrameworkInitializationCompleted();
}
```
