### ISSUE TITLE
Converter doesn't work in DataTemplate

### ISSUE THREAD

**Issue by amis92** [AvaloniaUI/Avalonia#1464] opened 2018-03-26 22:25 UTC
I have a problem, namely any usage of Converter within DataTemplate results in an invisible control with no content.

Repro repo:
https://github.com/amis92/Avalonia.ErrorRepro.ConverterInDataTemplate

Are they supposed not to be working? Or am I doing something wrong.

PS I really appreciate all the work, Avalonia is awesome! :)

**Comment by danwalmsley** [comment] 2018-03-26 23:53
Looks like your binding statements are simply missing a closing}.

**Comment by danwalmsley** [comment] 2018-03-26 23:54
@grokys hmm iv come across this a few times, when syntax error exists inside a template like this, no exception is thrown, just no controls displayed. Is that by design?

**Comment by amis92** [comment] 2018-03-27 07:17
@danwalmsley please tell me where exactly. I might be going blind, but I can't spot the missing one...?

**Comment by danwalmsley** [comment] 2018-03-27 08:31
hmm maybe its me thats going blind! sorry about that

**Comment by danwalmsley** [comment] 2018-03-27 08:32
im looking into it now

**Comment by danwalmsley** [comment] 2018-03-27 08:40
ok I get this:

![image](https://user-images.githubusercontent.com/4672627/37956255-b3e8b108-31a2-11e8-9331-b9fda11c9e6d.png)

Is that working now?

only changed one line for content control...

```
<TextBlock>Template binding, with converter:</TextBlock>
    <ContentControl Content="{Binding Custom2, Converter={StaticResource CustomConv}}"/>
```

**Comment by danwalmsley** [comment] 2018-03-27 08:40
If you are seeing something different paste a screenshot here

**Comment by amis92** [comment] 2018-03-27 09:00
Well, without changing anything I get 

![image](https://user-images.githubusercontent.com/2671396/37956824-adb58cd4-31ac-11e8-8586-62e37a20ad54.png)

Which obviously misses the last TextBox.

You've simply added the converter into Content binding, so that now the DataTempate isn't used at all. What I'm actually trying to achieve is, get the DataTemplate rendered (in my application the template is used in ListBox, and it contains more than just one line of text). Final effect should look like that:

![image](https://user-images.githubusercontent.com/2671396/37957254-c726d690-31ad-11e8-8344-bdc2a448d0d9.png)

So the problem is, the Converter in binding in a DataTemplate causes the control (TextBox) to disappear. :<

**Comment by danwalmsley** [comment] 2018-03-27 09:34
I see what you mean, this definately looks like a bug! prob best to get @grokys to have a look.

**Comment by ReeJK** [comment] 2018-04-12 21:25
This is the problem with getting resources inside DataTemplate:
StaticResource and DynamicResource inside the DataTemplate does not find a resources from the parent Window.Resources.

[Another Sample](https://gist.github.com/ReeJK/5964207259a9345b98ccaf155df8bbf1)

**Comment by amis92** [comment] 2018-04-18 16:28
It's interesting, because the bindings only seem to fail as a part of Binding. When doing straight StaticResource like I did with string (3rd box) all is good. So it's not a problem for simple binding, but rather for the late binding that happens with Binding extension. I'm trying to find the bug /problem on my own, but it's quite complicated with Templates and Bindings.

**Closed** 2018-05-04 19:43 UTC
