### ISSUE TITLE
AutoCompleteBox hints dropdownbox doesn't "follow" the TextBox movement.

### ISSUE THREAD

**Issue by Nemirtingas** [AvaloniaUI/Avalonia#5890] opened 2021-05-09 10:48 UTC
**Describe the bug**
When using async populator, the hints popup doesn't follow the search field.

**To Reproduce**

Run the Avalonia Control Catalog, type some text in the async control and move the window, the popup will show at the old position.

**Expected behavior**
I think the popup should follow the TextBox.

**Screenshots**
![image](https://user-images.githubusercontent.com/9432037/117568802-c3cbf600-b0c2-11eb-84cb-b4f43a7ed693.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 0.10.3

**Comment by maxkatz6** [comment] 2021-05-12 03:19
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/4225 https://github.com/AvaloniaUI/Avalonia/issues/4630

**Comment by simonhaines** [comment] 2021-11-05 02:11
If this issue (or any of its duplicates) is up for grabs, I'd like to take this on. A good reason for a dive into positioning and placement handling.

**Comment by maxkatz6** [comment] 2021-11-05 02:18
@simonhaines help is always welcomed, but not sure if this issue is easy for starters. As it seems Windows popups implementation specific (works on other OSs from what I remember). Basically popup is hosted in child window which position is not following parent. Though I haven't dive too deep and probably it's not that hard to fix.

**Comment by maxkatz6** [comment] 2021-11-05 02:20
For instance, if OverlayPopups are enabled (which means all popups will be hosted in the same parent window, just in top layer), then this issue is not reproducible on window move.

**Comment by simonhaines** [comment] 2021-11-05 02:40
Agreed, an immediate workaround is to use overlay popups. I am working on a fix that subscribes to `WindowPositionChanged` events in [this conditional branch](https://github.com/AvaloniaUI/Avalonia/blob/f6b94385c5965ae6cce9d640e3808d2f80eadf4c/src/Avalonia.Controls/Primitives/Popup.cs#L421) and routes them to the `HandlePositionChange` [method](https://github.com/AvaloniaUI/Avalonia/blob/f6b94385c5965ae6cce9d640e3808d2f80eadf4c/src/Avalonia.Controls/Primitives/Popup.cs#L528), and this seems to work, but I need to check the consequences of this change more thoroughly to ensure it doesn't break existing behaviour.

**Comment by simonhaines** [comment] 2021-11-19 05:20
This issue is still being worked on. Fixing the overlay positioning on window resize/move is straightforward. Ensuring the correct behaviour for second- and third-level submenus, not so much.

**Closed** 2021-12-06 01:06 UTC
Labels: bug, up-for-grabs
