### ISSUE TITLE
System.InvalidOperationException: The control already has a visual parent.

### ISSUE THREAD

**Issue by mrj001** [AvaloniaUI/Avalonia#4839] opened 2020-10-11 02:57 UTC
Steps:
1. Run the Controls Catalog
2. Choose ComboBox
3. Select an item in the first combo box.
4. Change themes.  I switched to Simple - Light.
5. Try to open the first combo box again & it crashes.

here is the stack trace

> Unhandled exception. System.InvalidOperationException: The control already has a visual parent.
>    at Avalonia.Visual.ValidateVisualChild(IVisual c) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Visuals/Visual.cs:line 555
>    at Avalonia.Visual.<>c.<.ctor>b__16_0(IVisual visual) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Visuals/Visual.cs:line 122
>    at Avalonia.Collections.AvaloniaList`1.InsertRange(Int32 index, IEnumerable`1 items) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/Collections/AvaloniaList.cs:line 369
>    at Avalonia.Controls.Panel.ChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Panel.cs:line 112
>    at Avalonia.Controls.VirtualizingStackPanel.ChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/VirtualizingStackPanel.cs:line 108
>    at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/Collections/AvaloniaList.cs:line 662
>    at Avalonia.Collections.AvaloniaList`1.Add(T item) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/Collections/AvaloniaList.cs:line 187
>    at Avalonia.Controls.Presenters.ItemVirtualizerNone.AddContainers(Int32 index, IEnumerable items) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Presenters/ItemVirtualizerNone.cs:line 96
>    at Avalonia.Controls.Presenters.ItemVirtualizerNone..ctor(ItemsPresenter owner) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Presenters/ItemVirtualizerNone.cs:line 21
>    at Avalonia.Controls.Presenters.ItemVirtualizer.Create(ItemsPresenter owner) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Presenters/ItemVirtualizer.cs:line 203
>    at Avalonia.Controls.Presenters.ItemsPresenter.PanelCreated(IPanel panel) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Presenters/ItemsPresenter.cs:line 151
>    at Avalonia.Controls.Presenters.ItemsPresenterBase.CreatePanel() in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Presenters/ItemsPresenterBase.cs:line 231
>    at Avalonia.Controls.Presenters.ItemsPresenterBase.ApplyTemplate() in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Presenters/ItemsPresenterBase.cs:line 137
>    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 554
>    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 364
>    at Avalonia.Controls.Presenters.ScrollContentPresenter.MeasureOverride(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs:line 243
>    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 559
>    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 364
>    at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Grid.cs:line 1149
>    at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Grid.cs:line 1004
>    at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Grid.cs:line 968
>    at Avalonia.Controls.Grid.MeasureOverride(Size constraint) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Grid.cs:line 489
>    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 559
>    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 364
>    at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 625
>    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 559
>    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 364
>    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/LayoutHelper.cs:line 40
>    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/LayoutHelper.cs:line 33
>    at Avalonia.Controls.Border.MeasureOverride(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Border.cs:line 121
>    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 559
>    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 364
>    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/LayoutHelper.cs:line 40
>    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/LayoutHelper.cs:line 33
>    at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 339
>    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 559
>    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 364
>    at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/LayoutHelper.cs:line 40
>    at Avalonia.Controls.Decorator.MeasureOverride(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Decorator.cs:line 54
>    at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Primitives/VisualLayerManager.cs:line 136
>    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 559
>    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 364
>    at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 625
>    at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 559
>    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 364
>    at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 625
>    at Avalonia.Controls.Primitives.PopupRoot.MeasureOverride(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Primitives/PopupRoot.cs:line 137
>    at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/WindowBase.cs:line 246
>    at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/Layoutable.cs:line 364
>    at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/LayoutManager.cs:line 287
>    at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass() in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Layout/LayoutManager.cs:line 174
>    at Avalonia.Controls.WindowBase.Show() in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/WindowBase.cs:line 162
>    at Avalonia.Controls.Primitives.Popup.Open() in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Primitives/Popup.cs:line 473
>    at Avalonia.Controls.Primitives.Popup.IsOpenChanged(AvaloniaPropertyChangedEventArgs`1 e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Primitives/Popup.cs:line 541
>    at Avalonia.Controls.Primitives.Popup.<>c.<.cctor>b__22_1(Popup x, AvaloniaPropertyChangedEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Primitives/Popup.cs:line 144
>    at Avalonia.AvaloniaObjectExtensions.<>c__DisplayClass23_0`1.<AddClassHandler>b__0(AvaloniaPropertyChangedEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObjectExtensions.cs:line 583
>    at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 148
>    at Avalonia.AvaloniaProperty`1.NotifyChanged(AvaloniaPropertyChangedEventArgs`1 e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaProperty`1.cs:line 80
>    at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 719
>    at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 632
>    at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 662
>    at Avalonia.Controls.Primitives.Popup.set_IsOpen(Boolean value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Primitives/Popup.cs:line 206
>    at Avalonia.Controls.Primitives.Popup.<>c.<.cctor>b__22_3(Popup o, Boolean v) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Primitives/Popup.cs:line 38
>    at Avalonia.DirectProperty`2.InvokeSetter(IAvaloniaObject instance, BindingValue`1 value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/DirectProperty.cs:line 172
>    at Avalonia.AvaloniaObject.SetDirectValueUnchecked[T](DirectPropertyBase`1 property, BindingValue`1 value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 797
>    at Avalonia.AvaloniaObject.DirectBindingSubscription`1.OnNext(BindingValue`1 value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 888
>    at Avalonia.Reactive.SingleSubscriberObservableBase`1.PublishNext(T value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/Reactive/SingleSubscriberObservableBase.cs:line 49
>    at Avalonia.Reactive.TypedBindingAdapter`1.OnNext(BindingValue`1 value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/Reactive/TypedBindingAdapter.cs:line 31
>    at Avalonia.Reactive.SingleSubscriberObservableBase`1.PublishNext(T value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/Reactive/SingleSubscriberObservableBase.cs:line 49
>    at Avalonia.Reactive.BindingValueAdapter`1.OnNext(T value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/Reactive/BindingValueAdapter.cs:line 18
>    at Avalonia.Reactive.SingleSubscriberObservableBase`1.PublishNext(T value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/Reactive/SingleSubscriberObservableBase.cs:line 49
>    at Avalonia.Data.TemplateBinding.PublishValue() in /Users/mj/Documents/develop/avalonia/Avalonia/src/Markup/Avalonia.Markup/Data/TemplateBinding.cs:line 145
>    at Avalonia.Data.TemplateBinding.TemplatedParentPropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Markup/Avalonia.Markup/Data/TemplateBinding.cs:line 183
>    at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 720
>    at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 632
>    at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 662
>    at Avalonia.Controls.ComboBox.set_IsDropDownOpen(Boolean value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/ComboBox.cs:line 101
>    at Avalonia.Controls.ComboBox.<>c.<.cctor>b__13_4(ComboBox o, Boolean v) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/ComboBox.cs:line 35
>    at Avalonia.DirectProperty`2.InvokeSetter(IAvaloniaObject instance, BindingValue`1 value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/DirectProperty.cs:line 172
>    at Avalonia.AvaloniaObject.SetDirectValueUnchecked[T](DirectPropertyBase`1 property, T value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 764
>    at Avalonia.AvaloniaObject.SetValue[T](DirectPropertyBase`1 property, T value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 367
>    at Avalonia.DirectPropertyBase`1.RouteSetValue(IAvaloniaObject o, Object value, BindingPriority priority) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/DirectPropertyBase.cs:line 158
>    at Avalonia.AvaloniaObjectExtensions.SetValue(IAvaloniaObject target, AvaloniaProperty property, Object value, BindingPriority priority) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObjectExtensions.cs:line 529
>    at Avalonia.Data.TemplateBinding.System.IObserver<System.Object>.OnNext(Object value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Markup/Avalonia.Markup/Data/TemplateBinding.cs:line 109
>    at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 138
>    at Avalonia.Reactive.AvaloniaPropertyObservable`1.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/Reactive/AvaloniaPropertyObservable.cs:line 61
>    at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 720
>    at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 632
>    at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/AvaloniaObject.cs:line 662
>    at Avalonia.Controls.Primitives.ToggleButton.set_IsChecked(Nullable`1 value) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Primitives/ToggleButton.cs:line 96
>    at Avalonia.Controls.Primitives.ToggleButton.Toggle() in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Primitives/ToggleButton.cs:line 136
>    at Avalonia.Controls.Primitives.ToggleButton.OnClick() in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Primitives/ToggleButton.cs:line 112
>    at Avalonia.Controls.Button.OnPointerPressed(PointerPressedEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/Button.cs:line 290
>    at Avalonia.Input.InputElement.<>c.<.cctor>b__26_8(InputElement x, PointerPressedEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Input/InputElement.cs:line 182
>    at Avalonia.Interactivity.RoutedEvent`1.<>c__DisplayClass2_0`1.<AddClassHandler>g__Adapter|0(Object sender, RoutedEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Interactivity/RoutedEvent.cs:line 143
>    at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass23_0.<AddClassHandler>b__0(ValueTuple`2 args) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Interactivity/RoutedEvent.cs:line 92
>    at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 148
>    at Avalonia.Interactivity.RoutedEvent.InvokeRaised(Object sender, RoutedEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Interactivity/RoutedEvent.cs:line 99
>    at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Interactivity/EventRoute.cs:line 148
>    at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Interactivity/EventRoute.cs:line 101
>    at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Interactivity/Interactive.cs:line 120
>    at Avalonia.Input.MouseDevice.MouseDown(IMouseDevice device, UInt64 timestamp, IInputElement root, Point p, PointerPointProperties properties, KeyModifiers inputModifiers) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Input/MouseDevice.cs:line 242
>    at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Input/MouseDevice.cs:line 151
>    at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Input/MouseDevice.cs:line 84
>    at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Input/InputManager.cs:line 35
>    at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/TopLevel.cs:line 473
>    at Avalonia.Native.WindowBaseImpl.RawMouseEvent(AvnRawMouseEventType type, UInt32 timeStamp, AvnInputModifiers modifiers, AvnPoint point, AvnVector delta) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Native/WindowImplBase.cs:line 294
>    at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.RawMouseEvent(AvnRawMouseEventType type, UInt32 timeStamp, AvnInputModifiers modifiers, AvnPoint point, AvnVector delta) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Native/WindowImplBase.cs:line 192
>    at Avalonia.Native.Interop.IAvnWindowBaseEventsShadow.IAvnWindowBaseEventsVtbl.RawMouseEvent(IntPtr thisObject, Int32 param0, UInt32 param1, Int32 param2, AvnPoint param3, AvnVector param4) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Native/Generated/Interfaces.cs:line 2834
> --- End of stack trace from previous location where exception was thrown ---
>    at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Native/PlatformThreadingInterface.cs:line 91
>    at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
>    at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /Users/mj/Documents/develop/avalonia/Avalonia/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
>    at ControlCatalog.NetCore.Program.Main(String[] args) in /Users/mj/Documents/develop/avalonia/Avalonia/samples/ControlCatalog.NetCore/Program.cs:line 102
> 

This is the output of "dotnet --info"

> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.401
>  Commit:    39d17847db
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.15
>  OS Platform: Darwin
>  RID:         osx.10.15-x64
>  Base Path:   /usr/local/share/dotnet/sdk/3.1.401/
> 
> Host (useful for support):
>   Version: 3.1.8
>   Commit:  9c1330dedd
> 
> .NET Core SDKs installed:
>   3.1.201 [/usr/local/share/dotnet/sdk]
>   3.1.302 [/usr/local/share/dotnet/sdk]
>   3.1.401 [/usr/local/share/dotnet/sdk]
>   3.1.402 [/usr/local/share/dotnet/sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download
> 

version: HEAD is at 129dfdadd

**Comment by FoggyFinder** [comment] 2020-10-11 06:46
Probably duplicate of #4265

**Comment by mrj001** [comment] 2020-10-11 17:22
I saw that one, but I didn't think it would be a duplicate because the stack traces are different, and this one is a ComboBox instead of a ListBox.

**Comment by FoggyFinder** [comment] 2020-10-12 10:33
Yeah, that's why I wrote "possible"

**Comment by HendrikMennen** [comment] 2020-10-27 13:31
I have a similar error with ContextMenu's sometimes

**Comment by grokys** [comment] 2023-05-20 18:34
Should be long fixed by now ;)

**Closed by grokys** 2023-05-20 18:34 UTC

**Comment by Jurashikku** [comment] 2024-09-13 17:11
> Should be long fixed by now ;)

No, I just test with ComboBox. 

If we replace style with 
`App.Current.Styles.Clear();
 App.Current.Styles.Add(style);
 App.Current.RequestedThemeVariant = variant;`
 Or add style to window.
 
 And there no options to update ColorPallet for fluent in realtime. 

And try combobox 
System.InvalidOperationException: The control ItemsPresenter (Name = PART ItemsPresenter) already has a visual parent ScrollContentPresenter (Name = PART_ContentPresenter) while trying to add it as a child of ScrollContentPresenter (Name = PART_ContentPresenter, Host = ScrollViewer).

The exception throw when changed Style for some think new from code (realtime)

Avalonia 11.1.0 - error 
Avalonia 11.1.3 - ?
