### ISSUE TITLE
Not working shared size scope, Shared size scrope is converting * to Auto

### ISSUE THREAD

**Issue by YohDeadfall** [AvaloniaUI/Avalonia#6455] opened 2021-08-23 14:12 UTC
Tried to make a list of tasks running in background which has a style similar to what `MenuItem` has, but found that shared size doesn't work at all, but applies when and only when it is reset. Here's a gif showing how it behaves:

![shared_size](https://user-images.githubusercontent.com/10694013/130461825-c2a764bc-bd6b-4a47-a7c1-495f18290175.gif)

To make a minimal repro use the following XAML (cut off of the original):

```xml
<ScrollViewer>
  <ItemsRepeater
    x:Name="AllOperations"
    Grid.IsSharedSizeScope="True"
    Items="{Binding Operations}"
    KeyboardNavigation.TabNavigation="Continue">

    <ItemsRepeater.Layout>
      <StackLayout Orientation="Vertical" Spacing="8" />
    </ItemsRepeater.Layout>

    <ItemsRepeater.ItemTemplate>
      <DataTemplate DataType="status:Operation">
        <Button Height="{StaticResource StatusBarHeight}">

          <Grid>

            <Grid.ColumnDefinitions>
              <ColumnDefinition Width="*" SharedSizeGroup="OperationName" />
              <ColumnDefinition Width="{StaticResource StatusBarIconWidth}" />
              <ColumnDefinition Width="{StaticResource StatusBarProgressWidth}" />
              <ColumnDefinition Width="{StaticResource StatusBarIconWidth}" />
            </Grid.ColumnDefinitions>

            <TextBlock
              Grid.Column="0"
              Grid.ColumnSpan="2"
              Margin="4,0"
              Text="{Binding Name}"
              TextTrimming="CharacterEllipsis" />

            <controls:ProgressBar
              Grid.Column="2"
              Margin="4,0"
              HorizontalAlignment="Stretch"
              Maximum="1"
              Value="{Binding Progress}" />

            <TextBlock
              Grid.Column="3"
              Margin="4,0"
              IsVisible="{Binding !#PART_OperationStatus.IsVisible}"
              Text="{Binding Progress, StringFormat=\{0:P0\}}"
              TextAlignment="Center" />

            <Border
              x:Name="PART_OperationStatus"
              Grid.Column="3" />

          </Grid>

        </Button>
      </DataTemplate>
    </ItemsRepeater.ItemTemplate>

  </ItemsRepeater>
</ScrollViewer>
```

```
private class Operation
{
    public string Name { get; set; }

    public double? Progress { get; set; }
}
```

**Comment by grokys** [comment] 2021-08-23 14:15
@jmacato any idea why this might be happening?

**Comment by grokys** [comment] 2021-08-23 14:47
@YohDeadfall your repro doesn't compile as-is, and I tried to make it work but just ended up with this

![image](https://user-images.githubusercontent.com/1775141/130467895-fa34c070-8710-4b38-aada-2e8804813d97.png)

Could you update your repro to something that demonstrates the problem without changes?

**Comment by YohDeadfall** [comment] 2021-08-23 14:49
It will take a bit more time, but sure.

**Comment by wieslawsoltes** [comment] 2021-08-23 14:57
Shared size scrop is converting `*` to  `Auto`

Same as in WPF https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.grid.issharedsizescope?view=net-5.0#remarks

`
Columns and rows participating in size sharing do not respect Star sizing. In this scenario, Star sizing is treated as Auto.
`

**Comment by grokys** [comment] 2021-08-23 15:47
Ah yes, that looks like it @wieslawsoltes. Should we close this issue then as it looks to be working as designed?

**Comment by YohDeadfall** [comment] 2021-08-23 15:49
If `*` is treated as `Auto` shouldn't it provide the same width for all columns anyway?

**Comment by Gillibald** [comment] 2021-08-23 18:28
Yes it should still provide the same width for all shared size columns

**Comment by dfkeenan** [comment] 2022-10-01 14:10
I seem to have been bitten by this today. I am trying to create a TreeView like control where the child items within each item line-up.  The ColumnDefinition in question is using  `auto` not `*`. The repository is public but not a minimal example. I am still currently using v0.10.14.

**Comment by timunie** [comment] 2022-10-01 19:42
Try to not set SharedGridSizeGroup to a column with size *. Then it works for me.

**Closed** 2024-03-15 01:15 UTC
Labels: bug, by-design
