### ISSUE TITLE
Question: How to access TranslateTransform, LineSegment etc, from code behind using name? 

### ISSUE THREAD

**Issue by JTrotta** [AvaloniaUI/Avalonia#3628] opened 2020-03-02 10:26 UTC
In WPF I can set the name of any component like:
` <TranslateTransform  X="35" Y="0" Name="_markerTranslation"/>`

in Avalonia  I got the error:
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve suitable regular or attached property Name on type Avalonia.Visuals:Avalonia.Media.TranslateTransform (line 27 position 12) Line 27, position 12.	AvaloniaMVVM`

XAML code is :
`    <Ellipse Name="_pointerCircle" Width="20" Height="20" Stroke="Gainsboro" StrokeThickness="0" ZIndex="99">
      <Ellipse.RenderTransform>
        <TransformGroup>
          <TranslateTransform  X="35" Y="0"/>
        </TransformGroup>
      </Ellipse.RenderTransform>
      <Ellipse.Fill>
        <LinearGradientBrush EndPoint="0.5,0" StartPoint="0.5,1">
          <GradientStop Color="Red" Offset="0"/>
          <GradientStop Color="DarkRed" Offset="1.0"/>
        </LinearGradientBrush>
      </Ellipse.Fill>
    </Ellipse>`

And I want to change TranslateTransform  X and Y at runtime.

The same happens for many other.

**Comment by kekekeks** [comment] 2020-03-02 12:42
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/2998

**Closed** 2020-03-02 12:42 UTC

**Comment by RomanSoloweow** [comment] 2020-08-30 21:44
You can do it like:

get translate transform
```C#
   var  translateTransform = this.RenderTransform as TranslateTransform;
``` 
get path, figure e.t.c.
``` C#
  var PathConnect = this.FindControlWithExeption<Path>("PathConnect");
  var PathGeometryConnect = PathConnect.Data as PathGeometry;
  var PathFigureConnect = PathGeometryConnect.Figures.First();
  var BezierSegmentConnect = PathFigureConnect.Segments.First() as BezierSegment;
```
