### ISSUE TITLE
Can't set `BoxShadow` value `0` in `DevTools`

### ISSUE THREAD

**Issue by Coloryr** [AvaloniaUI/Avalonia#12908] opened 2023-09-15 15:08 UTC
**Describe the bug**
Can't set `BoxShadow` value `0` in `DevTools`.

**To Reproduce**

1. Open the DevTools
2. select `Border`
3. Set `BoxShadow` , like `5 5 10 0 DarkGray`
4. Zero value gone, become `5 5 10 DarkGray`

**Expected behavior**

**Screenshots**
![GIF](https://github.com/AvaloniaUI/Avalonia/assets/26276037/98bedc31-618d-4d84-bafd-3e5b462eabb9)

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.4

**Additional context**

**Comment by rabbitism** [comment] 2023-10-01 12:35
![image](https://github.com/AvaloniaUI/Avalonia/assets/14807942/d69e8903-19d8-454e-ad1b-aa4344afcab7)
This is by design.

**Comment by timunie** [comment] 2023-10-01 17:57
Yeah 0 can be omitted it does add no additional info. 

So closing this as intended.

**Closed** 2023-10-01 17:58 UTC
Labels: by-design
