### ISSUE TITLE
WindowNotificationManager: can't show 2 notifications with the same content

### ISSUE THREAD

**Issue by fgsfds** [AvaloniaUI/Avalonia#16986] opened 2024-09-11 07:01 UTC
### Describe the bug

Getting `System.ArgumentException: 'An item with the same key has already been added. Key: TEST'` when trying to show 2 notifications with the same content.

### To Reproduce

The code is as follows:

```
var notificationManager = new WindowNotificationManager()
{
    MaxItems = 3,
    Position = NotificationPosition.TopRight,
};

notificationManager.Show("TEST", NotificationType.Information);
notificationManager.Show("TEST", NotificationType.Information);
```

### Expected behavior

Both notifications with "TEST" message are shown

### Avalonia version

11.2.0-beta1

### OS

Windows

**Comment by maxkatz6** [comment] 2024-09-11 07:46
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/15766

**Closed by maxkatz6** 2024-09-11 07:46 UTC
Labels: bug
