### ISSUE TITLE
Child ContextMenuItems disappear when I move the mouse over them, and eventually it crashes to desktop.

### ISSUE THREAD

**Issue by SparkyTD** [AvaloniaUI/Avalonia#5320] opened 2021-01-19 14:59 UTC
**Describe the bug**
Consider the following ContextMenu:
```
ContextMenu
|-- Item1
\-- Item2
    |-- SubItem1
    \-- SubItem2
```
On the root level (Item1 and Item2), everything works as expected. But if I try to click on any of the SubItems, they disappear as soon as my mouse leaves Item2's area and enters the next level of menu items. This makes it really difficult to click on the SubItems. Sometimes when I move my mouse left and right for a bit, the SubItems will reappear and I will be able to click them, but this doesn't seem  to be consistent.

I've noticed that this happens a lot more often in the "Simple" theme. If I switch to the "Fluent" theme, it still happens, but there's a higher chance that eventually I can click the sub items.

**To Reproduce**
1. Clone master (dc8c6eba6) or 0.10.0-rc1
2. Build and run ControlCatalog.NetCore
3. Make sure that the "Simple" theme is selected
4. Select the ContextMenu page
5. Right click on a blue rectangle.
6. Move mouse over "Menu with submenu" or "Recent"
7. Try to click on the sub menu items.

**Expected behavior**
When I move my mouse over a MenuItem that has children, I expect a second context menu to open with the sub items, right next to the first one. When I move my mouse from the first menu over to the new menu with the sub items, I expect both menus to remain open, so I can click on any of the now visible items.

**Video**

https://user-images.githubusercontent.com/45818400/105051104-1c757580-5a77-11eb-97db-986411629dd8.mp4

In this video it even crashes after I try to access the sub items on the first menu. [Here](https://pastebin.com/raw/YF4e70yE) is the full exception log of the crash.

**Desktop:**
 - OS: Manjaro Linux, Xorg, KDE Plasma, kernel 5.9
 - Version: both 0.10.0-rc1 and the current master (dc8c6eba6)

**Comment by Deadpikle** [comment] 2021-01-19 23:31
I think the submenu not working might be a duplicate of #4729, although the crash isn't reported there.

**Closed** 2021-01-20 13:48 UTC
Labels: bug, linux
