### ISSUE TITLE
Unexpected behavior with the latest Avalonia Render

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#9975] opened 2023-01-13 23:27 UTC
**Describe the bug**

The new render failed to display elements with size changes when using animation. It will cause elements to disappear on the screen.
Also, the control elements seem failed to deal with size change, and the elements that should stay on the screen will be removed after the animation is ended.

**To Reproduce**

1. Create a basic UI element with text and some size change animations.
2. Run the application

**Expected behavior**

All the elements should show correctly.

**Screenshots**

![record1](https://user-images.githubusercontent.com/25716486/212436448-69e236c9-b915-4842-9118-567a442a49b9.gif)

As you can see, the purple region should stay on the screen. However, it has been removed after the animation ended.

![record1](https://user-images.githubusercontent.com/25716486/212436583-fd5a8394-87c0-48b3-8987-02f8e4ec6680.gif)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 22H2

**Comment by maxkatz6** [comment] 2023-01-13 23:33
Is it the latest nightly? Can you provide a minimal sample project?

**Comment by laolarou726** [comment] 2023-01-14 00:10
> Is it the latest nightly? Can you provide a minimal sample project?

Just created a repro: [Github Repo](https://github.com/laolarou726/RenderBug)

**Comment by lukaszossowski** [comment] 2023-01-14 08:38
This seems to be happening all across the board when resizing Window for example. Text flickers, disappears, reappears. I am on Preview 4. Upper image shows the state after resizing the Window and lower after reloading the page.

![moved](https://user-images.githubusercontent.com/112421929/212463802-54c5c1eb-0732-47d5-95af-827070d6ed21.JPG)
![proper](https://user-images.githubusercontent.com/112421929/212463795-46c5f6a5-186f-4009-b826-8d796e7edcce.JPG)

**Comment by Numpsy** [comment] 2023-01-15 14:38
fwiw, I was having a go at building Avalonia.FuncUI with the nightly builds to get up to date with the latest changes, and I noticed that their control catalog app has these sort of issues when resizing the window horizontally (resizing vertically seems ok).
It seems ok with the Preview4 build.

**Comment by robloo** [comment] 2023-01-16 13:17
I've now seen this issue in the Expander control in ControlCatalog. Sometimes the expander, when it opens, will not show any expanded content. That might be a good place to find the root cause.

**Comment by danielmayost** [comment] 2023-01-17 05:49
In fact, the problem can be reproduced in a simple way:
in ControlCatalog change the theme to `FluentDark` and then click somewhere within the window.

it's happens also when i change `FlowDirection`.

**Comment by mhmd-azeez** [comment] 2023-01-18 11:14
Hi, I have hit the same issue when using `FlowDirection=RightToLeft`. 

https://user-images.githubusercontent.com/16880059/213157314-94a016dd-f7c7-4e6e-be46-34c514885184.mp4
[AvaloniaApplication2.zip](https://github.com/AvaloniaUI/Avalonia/files/10445276/AvaloniaApplication2.zip)

Please see the attached video and the minimal repro

**Comment by danielmayost** [comment] 2023-01-18 11:35
yes, but it's not issue with FlowDirection but the new renderer.

**Comment by mhmd-azeez** [comment] 2023-01-18 13:19
@danielmayost is this a known bug or should I file a new issue for it?

**Comment by danielmayost** [comment] 2023-01-18 17:48
this is the bug reported in current issue, i no think you need open new issue.

**Comment by danielmayost** [comment] 2023-01-22 12:25
i can't reproduce with latest master, seems the my problem are solved, @laolarou726 can you check it?

**Comment by maxkatz6** [comment] 2023-01-22 22:09
Yes, text rendering issue was fixed with https://github.com/AvaloniaUI/Avalonia/pull/10015

**Comment by laolarou726** [comment] 2023-01-23 00:15
Yes. The issue was fixed! Thank you guys so much!

**Closed** 2023-01-23 00:18 UTC
Labels: bug, area-composition
