### ISSUE TITLE
Hit testing elements with CornerRadius > 0 incorrectly uses rectangular bounds

### ISSUE THREAD

**Issue by billhenn** [AvaloniaUI/Avalonia#13784] opened 2023-11-30 14:13 UTC
## Describe the bug

Many UI elements in Avalonia use rounded corners via controls like `Border` and `ContentPresenter` with a `CornerRadius` greater than zero.  We've found that when moving the mouse over the area outside of rounded corners but still within the rectangular bounds of these controls, hit testing is matching, even though it should not be.

This is very evident and problematic when making a circular `Button`.  The bug makes things like pointer-over state, tooltips, and mouse cursors all change when the mouse is clearly outside the visual circle of the `Button` but still within its overall rectangular bounds.  We should be able to click through to controls underneath this area, but that is currently not possible.

![HitTestingIssue](https://github.com/AvaloniaUI/Avalonia/assets/5760058/fe2b159a-cbdd-4cb1-8a2c-32e2eee45dbf)

The animation above shows three different ways of making a `Button` template.  The first two use `ContentPresenter` and `Border` respectively, and both show the issue.  The third works properly and uses an `Ellipse` shape.

After debugging Avalonia source, we found that these controls with `CornerRadius` all end up invoking `DrawingContext.DrawRectangleCore` which does pass in the `RoundedRect`.  That `RoundedRect` eventually finds its way into `RenderDataRectangleNode`, which is the class deep down that does hit-testing.  It's [HitTest](https://github.com/AvaloniaUI/Avalonia/blob/d22048707323b5c49d3a0e51df2ecd115eb37dad/src/Avalonia.Base/Rendering/Composition/Drawing/Nodes/RenderDataRectangleNode.cs#L11) method is:

```
public override bool HitTest(Point p)
{
    if (ServerBrush != null) // it's safe to check for null
    {
        var rect = Rect.Rect.Inflate((ClientPen?.Thickness / 2) ?? 0);
        return rect.ContainsExclusive(p);
    }
    else
    {
        var borderRect = Rect.Rect.Inflate((ClientPen?.Thickness / 2) ?? 0);
        var emptyRect = Rect.Rect.Deflate((ClientPen?.Thickness / 2) ?? 0);
        return borderRect.ContainsExclusive(p) && !emptyRect.ContainsExclusive(p);
    }
}
```

You can see there that the hit-testing logic ignore the corners completely and purely does rectangular hit-testing.  This logic needs to be refactored to only do the above if `RoundedRect.IsRounded` is `false`.  When `true`, more complicated logic needs to be added to handle hit testing the rounded corners properly.

## To Reproduce

This XAML will reproduce the UI in the animation above:

```
<StackPanel Orientation="Horizontal" Spacing="10">
	<Button Width="100" Height="100" Content="Bad" ToolTip.Tip="Button template contains a ContentPresenter.">
		<Button.Theme>
			<ControlTheme TargetType="Button">
				<Setter Property="Background" Value="#f0e0e0" />
				<Setter Property="BorderThickness" Value="0" />
				<Setter Property="CornerRadius" Value="50" />
				<Setter Property="Cursor" Value="Hand" />
				<Setter Property="HorizontalContentAlignment" Value="Center" />
				<Setter Property="VerticalContentAlignment" Value="Center" />
						
				<Setter Property="Template">
					<ControlTemplate>

						<ContentPresenter
							x:Name="PART_ContentPresenter"
							Background="{TemplateBinding Background}"
							BorderBrush="{TemplateBinding BorderBrush}"
							BorderThickness="{TemplateBinding BorderThickness}"
							Content="{TemplateBinding Content}"
							ContentTemplate="{TemplateBinding ContentTemplate}"
							CornerRadius="{TemplateBinding CornerRadius}"
							Foreground="{TemplateBinding Foreground}"
							HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}"
							Padding="{TemplateBinding Padding}"
							RecognizesAccessKey="True"
							VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}"
							/>

					</ControlTemplate>
				</Setter>
					
				<Style Selector="^:pointerover /template/ ContentPresenter#PART_ContentPresenter">
					<Setter Property="Background" Value="#e0e0f0" />
				</Style>
			</ControlTheme>
		</Button.Theme>
	</Button>
				
	<Button Width="100" Height="100" Content="Bad" ToolTip.Tip="Button template only contains a Border.">
		<Button.Theme>
			<ControlTheme TargetType="Button">
				<Setter Property="Background" Value="#f0e0e0" />
				<Setter Property="BorderThickness" Value="0" />
				<Setter Property="CornerRadius" Value="50" />
				<Setter Property="Cursor" Value="Hand" />
				<Setter Property="HorizontalContentAlignment" Value="Center" />
				<Setter Property="VerticalContentAlignment" Value="Center" />
						
				<Setter Property="Template">
					<ControlTemplate>

						<Border Background="{TemplateBinding Background}" CornerRadius="{TemplateBinding CornerRadius}">
							<ContentPresenter Content="{TemplateBinding Content}"
								HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}" VerticalAlignment="{TemplateBinding VerticalContentAlignment}" />
						</Border>

					</ControlTemplate>
				</Setter>
					
				<Style Selector="^:pointerover /template/ Border">
					<Setter Property="Background" Value="#e0e0f0" />
				</Style>
			</ControlTheme>
		</Button.Theme>
	</Button>

	<Button Width="100" Height="100" Content="Good" ToolTip.Tip="Button template only contains an Ellipse.">
		<Button.Theme>
			<ControlTheme TargetType="Button">
				<Setter Property="Background" Value="#e0f0e0" />
				<Setter Property="Cursor" Value="Hand" />
				<Setter Property="HorizontalContentAlignment" Value="Center" />
				<Setter Property="VerticalContentAlignment" Value="Center" />
						
				<Setter Property="Template">
					<ControlTemplate>

						<Panel>
							<Ellipse Fill="{TemplateBinding Background}" />
							<ContentPresenter Content="{TemplateBinding Content}"
								HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}" VerticalAlignment="{TemplateBinding VerticalContentAlignment}" />
						</Panel>

					</ControlTemplate>
				</Setter>
					
				<Style Selector="^:pointerover /template/ Ellipse">
					<Setter Property="Fill" Value="#e0e0f0" />
				</Style>
			</ControlTheme>
		</Button.Theme>
	</Button>
				
</StackPanel>
```

Simply move the mouse around and see how hit testing is incorrectly matching when outside the circles in the first two buttons.

## Expected behavior

Hit testing any element with `CornerRadius` > 0 should properly ignore anything outside the rounded corner.

## Environment 

- OS: Windows 11
- Avalonia-Version: 11.0.5

**Comment by stevemonaco** [comment] 2023-12-01 06:25
Until this is addressed, a simpler workaround may be to use a clipping geometry. Hit testing will respect that. Not sure how to handle size changes however.

Unfortunately, there doesn't seem to be a `RoundedRectGeometry`, so one may need to create a `PathGeometry` from scratch. Which isn't very straightforward if you're unfamiliar with vector graphics, but it does work with careful sizing. Luckily, the special case of a circular button is more straightforward as `EllipseGeometry` can be used. The following uses a square-shaped `Rect` that's 100x100 and creates a circular clip when fit to an ellipse. It's not possible to use this approach for rounded rectangles as ellipses do not have straight lines.

```xml
<Button Width="100" Height="100"
    HorizontalContentAlignment="Center"
    VerticalContentAlignment="Center"
    Background="#f0e0e0"
    BorderThickness="0"
    Content="Clipped"
    CornerRadius="50"
    Cursor="Hand"
    ToolTip.Tip="Button is only clipped">
    <Button.Clip>
        <EllipseGeometry Rect="0,0,100,100" />
    </Button.Clip>
    <Button.Styles>
        <Style Selector="Button:pointerover /template/ ContentPresenter#PART_ContentPresenter">
            <Setter Property="Background" Value="#e0e0f0" />
        </Style>
    </Button.Styles>
</Button>
```

**Comment by timunie** [comment] 2023-12-01 08:04
looks like a duplicate of #8550 and #7626 🤔

**Comment by timunie** [comment] 2023-12-01 09:02
> You can see there that the hit-testing logic ignore the corners completely and purely does rectangular hit-testing. This logic needs to be refactored to only do the above if RoundedRect.IsRounded is false. When true, more complicated logic needs to be added to handle hit testing the rounded corners properly.

Yeah, that would be a valid fix imo.

**Comment by billhenn** [comment] 2023-12-01 12:36
I spent most of yesterday writing up some code that I think resolves the hit testing for rounded cornered objects and matches how rendering of those objects works on Windows at least.  I'll make a PR this morning.

Tim, I think it's a bit of a different issue than those linked ones though since this particular issue is specifically when the mouse is outside the rounded corner of things like a `Border` but still in the overall rectangular bounds.

**Comment by timunie** [comment] 2023-12-01 13:12
worth to check these issues once the PR is there. Maybe it is covered, but not 100 % sure either.

**Closed** 2023-12-06 04:15 UTC
Labels: bug
