### ISSUE TITLE
Button animation breaks click on edges

### ISSUE THREAD

**Issue by Stannieman** [AvaloniaUI/Avalonia#8550] opened 2022-07-20 15:55 UTC
**Describe the bug**
When clicking a button on the every edge, especially a very wide one, the click is not registered.
This is likely due to the animations.
When the mouse is pressed the button is animated to become narrower. If the button is wide and the pointer is at the edge of the button then the button animates away from the pointer. When the mouse button is released the pointer is not over the button anymore and thus not registered. This is only a problem when ClickMode is Release.

**To Reproduce**

1. Create a very wide button, like Width="1000", with ClickMode="Release".
2. Press the mouse over the button on the outer left or right edge and within about 5mm from the side.
3. The button animates and shrinks so it is not underneath the pointer anymore.
4. Release the mouse button.
5. The click event did not fire.

**Expected behavior**
When at the time of mouse release the pointer is still over the area where the button originally was before the animation started the click event should still be fired.

- OS: Windows 11
- Version 22000.795

**Comment by maxkatz6** [comment] 2022-07-23 06:16
I assume it might be a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/7626, seems to be the same issue.

**Comment by timunie** [comment] 2022-07-23 07:17
Maybe we need some kind of transparent background which doesn't get animated. 🤔

**Comment by Stannieman** [comment] 2022-07-25 14:41
> Maybe we need some kind of transparent background which doesn't get animated. 🤔

That sounds like a good idea yes.

**Closed** 2023-06-15 21:56 UTC
Labels: bug
