### ISSUE TITLE
Trimming exception from build 11.0.999-cibuild0026358-beta

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#9533] opened 2022-11-24 11:08 UTC
**Describe the bug**
Publishing trimmed now throws an exception on publish from build 11.0.999-cibuild0026358-beta onwards

**To Reproduce**
This repro will publish on earlier versions
[AvaloniaTrimTest.zip](https://github.com/AvaloniaUI/Avalonia/files/10083845/AvaloniaTrimTest.zip)

publish.ps1 has the publish command in it

**Expected behavior**
no exception

**Screenshots**

```
AvaloniaTrimTest -> C:\Users\alan\OneDrive\scratch\AvaloniaTrimTest\AvaloniaTrimTest\bin\Release\net7.0\win7-x64\Aval
  oniaTrimTest.dll
  Optimizing assemblies for size. This process might take a while.
ILLink : error IL1012: IL Trimmer has encountered an unexpected error. Please report the issue at https://github.com/do
tnet/linker/issues [C:\Users\alan\OneDrive\scratch\AvaloniaTrimTest\AvaloniaTrimTest\AvaloniaTrimTest.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'document')
     at Mono.Cecil.Cil.SequencePoint..ctor(Int32 offset, Document document)
     at Mono.Cecil.SignatureReader.ReadSequencePoints(Document document)
     at Mono.Cecil.MetadataReader.ReadSequencePoints(MethodDefinition method)
     at Mono.Cecil.Cil.PortablePdbReader.ReadSequencePoints(MethodDebugInformation method_info)
     at Mono.Cecil.Cil.PortablePdbReader.Read(MethodDefinition method)
     at Mono.Cecil.Cil.EmbeddedPortablePdbReader.Read(MethodDefinition method)
     at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
     at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
     at Mono.Cecil.MetadataReader.ReadMethodBody(MethodDefinition method)
     at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
     at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
     at Mono.Cecil.MethodDefinition.get_Body()
     at Mono.Linker.Dataflow.CompilerGeneratedState.<GetCompilerGeneratedStateForType>g__ProcessMethod|11_0(MethodDefin
  ition method, <>c__DisplayClass11_0&)
     at Mono.Linker.Dataflow.CompilerGeneratedState.GetCompilerGeneratedStateForType(TypeDefinition type)
     at Mono.Linker.Dataflow.CompilerGeneratedState.TryGetCompilerGeneratedCalleesForUserMethod(MethodDefinition method
  , List`1& callees)
     at Mono.Linker.Steps.MarkStep.MarkReflectionLikeDependencies(MethodBody body, Boolean requiresReflectionMethodBody
  Scanner)
     at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason, MessageOrigin& origin
  )
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets(86,5): error NET
SDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to
false. [C:\Users\alan\OneDrive\scratch\AvaloniaTrimTest\AvaloniaTrimTest\AvaloniaTrimTest.csproj]
```

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version 11.0.999-cibuild0026358-beta 

**Additional context**

**Comment by maxkatz6** [comment] 2022-11-24 19:13
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/9533

**Closed by maxkatz6** 2022-11-24 19:13 UTC
Labels: bug
