### ISSUE TITLE
DataGrid Scrolling cause some cells to Disappear 

### ISSUE THREAD

**Issue by Shadow4walker** [AvaloniaUI/Avalonia#3456] opened 2020-01-21 16:58 UTC
when using ComboBox in DataGridTemplateColumn.CellTemplate and do scrolling some cells Disappear 
for example using the this code will cause the cells to Disappear When scrolling

`<DataGridTemplateColumn Header="UseFilter">
                            <DataGridTemplateColumn.CellTemplate>
                                <DataTemplate>
                                    <StackPanel Orientation="Horizontal" Spacing="5">
                                        <CheckBox IsChecked="{Binding UseFilter,Mode=TwoWay}"/>
                                        <ComboBox IsEnabled="{Binding UseFilter,Mode=OneWay}" Items="{Binding GroupsFilter,Mode=OneWay}" SelectedItem="{Binding SelectedFilter,Mode=TwoWay}">
                                            <ComboBox.ItemTemplate>
                                                <DataTemplate>
                                                    <TextBlock Text="{Binding GroupIdentity}"/>
                                                </DataTemplate>
                                            </ComboBox.ItemTemplate>
                                        </ComboBox>
                                    </StackPanel>
                                </DataTemplate>
                            </DataGridTemplateColumn.CellTemplate>
                        </DataGridTemplateColumn>`

**Comment by Shadow4walker** [comment] 2020-01-28 01:44
any work around for this?

**Comment by sdoroff** [comment] 2020-04-30 03:05
Are you still experiencing this issue? I was not able to reproduce it using the xaml above.

**Comment by Denny09310** [comment] 2021-07-02 12:46
@sdoroff, I've the same issue when using DataTemplateColumns and as DataTemplate a ComboBox. When I scroll Up or Down at some point this ComboBox values are deleted

` <DataGridTemplateColumn Header="Transfer">
          <DataGridTemplateColumn.CellTemplate>
            <DataTemplate>
              <ComboBox MinWidth="220" VerticalAlignment="Stretch"
                        Items="{Binding $parent[UserControl].DataContext.TypesOfTransfer}"
                        SelectedItem="{Binding Transfer}" />
            </DataTemplate>
          </DataGridTemplateColumn.CellTemplate>
        </DataGridTemplateColumn>`
I don't know if there is a fix for this but this is my datatemplate

**Comment by maxkatz6** [comment] 2021-07-03 01:01
@Denny09310 created feature request for DataGridComboBoxColumn https://github.com/AvaloniaUI/Avalonia/issues/6177

**Closed** 2023-11-25 23:47 UTC
Labels: bug, needs-repro, area-datagrid
