### ISSUE TITLE
New project from template draws fully transparent main window (on Windows ARM64)

### ISSUE THREAD

**Issue by AArnott** [AvaloniaUI/Avalonia#12210] opened 2023-07-15 15:48 UTC
**Describe the bug**

The main window frame is the only thing visible. Its entire client area is fully transparent.
This is on a brand new Avalonia project from the template.

**To Reproduce**

```
dotnet new install Avalonia.Templates
dotnet new avalonia.app -o QRCode.Generator.App
cd  QRCode.Generator.App
dotnet run
```

**Expected behavior**

A main window appears with a white background and a label as found in the template xaml.

**Screenshots**

![image](https://github.com/AvaloniaUI/Avalonia/assets/3548/c5109bb0-fa55-437f-beea-2fa9f13a3dfb)

**Desktop (please complete the following information):**

- OS: Windows 11 on arm64

**Additional context**

[repro.zip](https://github.com/AvaloniaUI/Avalonia/files/12062019/repro.zip)

**Comment by maxkatz6** [comment] 2023-07-15 18:55
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/10405

**Closed by maxkatz6** 2023-07-15 18:55 UTC
Labels: bug
