### ISSUE TITLE
Avalonia.Utilities.WeakEvent: null reference exception

### ISSUE THREAD

**Issue by DmitryZhelnin** [AvaloniaUI/Avalonia#10240] opened 2023-02-06 11:55 UTC
**Describe the bug**
Sometimes I get `NullReferenceException` when using Avalonia with `ReactiveUI`.
Stacktraces:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Utilities.WeakEvent`2.Subscription.OnEvent(Object sender, TEventArgs eventArgs) in /_/src/Avalonia.Base/Utilities/WeakEvent.cs:line 162
   at Avalonia.Utilities.WeakEvents.<>c__DisplayClass5_1.<.cctor>b__7(Object _, PropertyChangedEventArgs e) in /_/src/Avalonia.Base/Utilities/WeakEvents.cs:line 29
   at ReactiveUI.ReactiveObject.ReactiveUI.IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs args) in /_/src/ReactiveUI/ReactiveObject/ReactiveObject.cs:line 96
```
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Utilities.WeakHashList`1.GetAlive(Func`1 factory) in /_/src/Avalonia.Base/Utilities/WeakHashList.cs:line 210
   at Avalonia.Utilities.WeakEvent`2.Subscription.OnEvent(Object sender, TEventArgs eventArgs) in /_/src/Avalonia.Base/Utilities/WeakEvent.cs:line 157
   at Avalonia.Utilities.WeakEvents.<>c__DisplayClass5_1.<.cctor>b__7(Object _, PropertyChangedEventArgs e) in /_/src/Avalonia.Base/Utilities/WeakEvents.cs:line 29
   at ReactiveUI.ReactiveObject.ReactiveUI.IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs args) in /_/src/ReactiveUI/ReactiveObject/ReactiveObject.cs:line 96
```
<details>
  <summary>Full stacktrace</summary>
   
  ```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Utilities.WeakHashList`1.GetAlive(Func`1 factory) in /_/src/Avalonia.Base/Utilities/WeakHashList.cs:line 210
   at Avalonia.Utilities.WeakEvent`2.Subscription.OnEvent(Object sender, TEventArgs eventArgs) in /_/src/Avalonia.Base/Utilities/WeakEvent.cs:line 157
   at Avalonia.Utilities.WeakEvents.<>c__DisplayClass5_1.<.cctor>b__7(Object _, PropertyChangedEventArgs e) in /_/src/Avalonia.Base/Utilities/WeakEvents.cs:line 29
   at ReactiveUI.ReactiveObject.ReactiveUI.IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs args) in /_/src/ReactiveUI/ReactiveObject/ReactiveObject.cs:line 96
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1375
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs:line 827
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 238
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Where.cs:line 54
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 147
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.RaisePropertyChanged(String propertyName) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 390
   at ReactiveUI.IReactiveObjectExtensions.RaisingPropertyChanged[TSender](TSender reactiveObject, String propertyName) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 245
   at ReactiveUI.IReactiveObjectExtensions.RaiseAndSetIfChanged[TObj,TRet](TObj reactiveObject, TRet& backingField, TRet newValue, String propertyName) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 131
   at Avalonia.NETCoreMVVMApp2.ViewModels.TreeViewModel.set_IsLoading(Boolean value) in C:\Users\mitya\RiderProjects\Avalonia.NETCoreMVVMApp2\Avalonia.NETCoreMVVMApp2\ViewModels\MainWindowViewModel.cs:line 51
   at Avalonia.NETCoreMVVMApp2.ViewModels.TreeViewModel.Populate(String arg) in C:\Users\mitya\RiderProjects\Avalonia.NETCoreMVVMApp2\Avalonia.NETCoreMVVMApp2\ViewModels\MainWindowViewModel.cs:line 64
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
   at System.Reactive.ExceptionHelpers.Throw(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 62
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 553
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 507
   at System.Reactive.ObserveOnObserverNew`1.<>c.<.cctor>b__17_0(IScheduler scheduler, ObserveOnObserverNew`1 self) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 497
   at Avalonia.ReactiveUI.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in /_/src/Avalonia.ReactiveUI/AvaloniaScheduler.cs:line 48
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 193
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 257
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 204
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 212
   at Avalonia.NETCoreMVVMApp2.Program.Main(String[] args) in C:\Users\mitya\RiderProjects\Avalonia.NETCoreMVVMApp2\Avalonia.NETCoreMVVMApp2\Program.cs:line 17
  ```
  
</details>

I have two `TreeView` controls with following viewmodels. After `Task.Delay` in `Populate` method is finished and `IsLoading` is set to `false` exception is thrown

```cs
public class TreeViewModel : ReactiveObject
{
    public TreeViewModel()
    {
        this.WhenAnyValue(x => x.Filter)
            .Throttle(TimeSpan.FromMilliseconds(800))
            .Select(text => text.Trim())
            .DistinctUntilChanged()
            .SelectMany(Populate)
            .ObserveOn(RxApp.MainThreadScheduler)
            .Subscribe();
    }

    public ObservableCollection<NodeViewModel> Items { get; } = new();

    [Reactive] public bool IsLoading { get; set; }

    [Reactive] public string Filter { get; set; } = string.Empty;

    private async Task<Unit> Populate(string arg)
    {
        try
        {
            IsLoading = true;
            await Task.Delay(2000);
        }
        finally
        {
            IsLoading = false;
        }

        return Unit.Default;
    }

}
```

```xaml
<TextBlock Text="Loading..." IsVisible="{Binding Tree1.IsLoading}" />
<TreeView Items="{Binding Tree1.Items}" >
  <TreeView.Styles>
    <Style Selector="TreeViewItem" x:DataType="viewModels:NodeViewModel">
      <Setter Property="IsExpanded" Value="{Binding IsExpanded, Mode=TwoWay}" />
      <Setter Property="IsSelected" Value="{Binding IsSelected, Mode=TwoWay}" />
    </Style>
  </TreeView.Styles>
  <TreeView.DataTemplates>
    <TreeDataTemplate DataType="viewModels:NodeViewModel" ItemsSource="{Binding Children}">
      <TextBlock Text="{Binding Value}" />
    </TreeDataTemplate>
  </TreeView.DataTemplates>
</TreeView>
```
**To Reproduce**

1. Run attached repro project
2. See the error (maybe you have to launch it several times)

**Expected behavior**
No exception is thrown

**Desktop (please complete the following information):**

- OS: [Windows]
- Version [11-preview4, 11-preview5, .net6, .net7]

**Additional context**
Version 0.10.18 worked without errors.

Repro
[Avalonia.NETCoreMVVMApp2.zip](https://github.com/AvaloniaUI/Avalonia/files/10662686/Avalonia.NETCoreMVVMApp2.zip)

**Comment by danielmayost** [comment] 2023-02-06 12:39
I also get this error sometimes, also when using ReactiveUI. i thought it was my problem, thanks for reproduced it.

**Comment by DmitryZhelnin** [comment] 2023-02-06 12:46
If I remove `ObserveOn(RxApp.MainThreadScheduler)` the exception is not thrown but one of the textblocks remains visible.

**Comment by maxkatz6** [comment] 2023-02-06 22:27
Not sure where is the problem exactly.
But in your code ObserveOn is definitely used too late. I.e. SelectMany might be processed on the another thread, as Throttle does.
Ideally, it should be something like this:
```
        this.WhenAnyValue(x => x.Filter)
            .Throttle(TimeSpan.FromMilliseconds(800))
            .ObserveOn(RxApp.MainThreadScheduler)
            .Select(text => text.Trim())
            .DistinctUntilChanged()
            .SelectMany(Populate)
            .Subscribe();
```

**Comment by DmitryZhelnin** [comment] 2023-02-06 22:33
But that's the point to have `SelectMany` running tasks on another thread to keep UI responsive

**Comment by Symbai** [comment] 2023-02-06 22:37
I'm having the same problem when calling `this.RaisePropertyChanged(nameof(...))` but only rarely, call stack:

 ```
  at Avalonia.Utilities.WeakHashList`1.GetAlive(Func`1 factory)
   at Avalonia.Utilities.WeakEvent`2.Subscription.OnEvent(Object sender, TEventArgs eventArgs)
   at Avalonia.Utilities.WeakEvents.<>c__DisplayClass5_1.<.cctor>b__7(Object _, PropertyChangedEventArgs e)
   at ReactiveUI.ReactiveObject.ReactiveUI.IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs args)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing value)
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value)
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.RaisePropertyChanged(String propertyName)
   at ReactiveUI.IReactiveObjectExtensions.RaisingPropertyChanged[TSender](TSender reactiveObject, String propertyName)
   at ReactiveUI.IReactiveObjectExtensions.RaisePropertyChanged[TSender](TSender reactiveObject, String propertyName)
```
I just got it again and googled for it and found this issue, lol.

**Comment by maxkatz6** [comment] 2023-02-06 22:47
> But that's the point to have SelectMany running tasks on another thread to keep UI responsive

By itself, SelectMany doesn't run on another thread. It all depends on the scheduler.
Also, in your code, Populate is expected to be run on the UI thread, as you update UI bound properties.

**Comment by maxkatz6** [comment] 2023-02-06 22:47
> I'm having the same problem when calling this.RaisePropertyChanged(nameof(...)) but only rarely, call stack:

Just to be sure, RaisePropertyChanged is called from the UI thread, right?

**Comment by DmitryZhelnin** [comment] 2023-02-06 22:49
> > But that's the point to have SelectMany running tasks on another thread to keep UI responsive
> 
> 
> 
> By itself, SelectMany doesn't run on another thread. It all depends on the scheduler.
> 
> Also, in your code, Populate is expected to be run on the UI thread, as you update UI bound properties.

Doesn't `PropertyChanged` automatically dispatched to UI thread, like in WPF?

**Comment by maxkatz6** [comment] 2023-02-06 22:52
It might, and I think it was broken and then fixed in preview5.
But still this code doesn't look good to me, as it assumes that framework would do that, when in my opinion it should throw "invalid thread exception".

**Comment by maxkatz6** [comment] 2023-02-06 22:52
In general it looks like a duplicate of this issue https://github.com/AvaloniaUI/Avalonia/issues/8810
With more details from @grokys .

**Comment by Symbai** [comment] 2023-02-07 01:15
> RaisePropertyChanged is called from the UI thread

Good question, stupid me. It wasn't 🤦‍♂️😂Weird that it still worked in 90% of all cases. When doing the same on Winforms for example it immediately and always throws (with a more clear error description). But cant really blame Avalonia as I still shouldn't do UI stuff in non UI threads.

**Comment by maxkatz6** [comment] 2023-02-07 14:40
Closing as a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/8810

**Closed by maxkatz6** 2023-02-07 14:40 UTC
Labels: bug
