### ISSUE TITLE
DesignSurface User interface design

### ISSUE THREAD

**Issue by mansai** [AvaloniaUI/Avalonia#14352] opened 2024-01-25 08:57 UTC
1.DesignSurface
reference url https://github.com/icsharpcode/WpfDesigner
2.Or develop a WPF solution convert to AvaloniaUI Tool

![image](https://github.com/AvaloniaUI/Avalonia/assets/3213405/0a378e16-0d21-44b6-8cc8-653a42476502)

**Comment by thevortexcloud** [comment] 2024-01-25 10:08
I am not sure why you would want a designer? For something like a XML language it's a lot of work to make and almost always results in subpar generated layouts. It kind of made sense for Winforms because making winforms code by hand was very painful, but XAML takes away most of the pain.

**Comment by timunie** [comment] 2024-01-26 09:14
duplicate of https://github.com/AvaloniaUI/Avalonia/issues/4361

**Closed by timunie** 2024-01-26 09:14 UTC
Labels: enhancement, area-dev-tools
